### ISSUE TITLE
下一版本升级计划

### ISSUE THREAD

**Issue by Sayi** [Sayi/poi-tl#1]
1.  更多的表格处理、表格样式

**Comment by costtian** [comment]
哥们 等你发大招哈

**Comment by AlexZds** [comment]
请问一下,不能动态插入表格吗?必须是现在word文档里创建table 然后再替换吗?

**Comment by Sayi** [comment]
@AlexZds 动态插入表格建议用poi原生语法

**Comment by cc22868** [comment]
哥，我建议能有XWPFTemplate.compile(XWPFDocument)功能；

**Comment by cc22868** [comment]
这样我就可以动态修改模板，再调用你的方法　（＾。。＾）

**Comment by Sayi** [comment]
@cc22868  谢谢建议这个功能，最近我也考虑过。
