### ISSUE TITLE
是否考虑支持if elseif else判断

### ISSUE THREAD

**Issue by wade-bigdata** [Sayi/poi-tl#1001]
区块对虽然能支持if判断，但不支持if elseif else逻辑判断。需要在代码层去控制，不是很方便，是否考虑后续版本支持。

**Comment by Sayi** [comment]
不需要在代码层控制吧，两个if else就能解决这个问题。

if elseif else这个逻辑会更复杂，简单才好用。

**Comment by fwt11** [comment]
我的文档里有个地方是电价，它可能是单一价格，就一个数字，也可能是阶梯价格，是个表格，需要根据输入数据的类型做判断。这种情况下，在模板里应该怎么用标签。如果没有if/else的情况，好像很难办？
