### ISSUE TITLE
垃圾库,好多bug

### ISSUE THREAD

**Issue by wan766405890** [Sayi/poi-tl#1002]
垃圾库,好多bug,建议从github上消失

**Comment by LXang723** [comment]
就不承认是自己的问题

**Comment by yuexiaying** [comment]
不至于这样诋毁吧？那您能推荐一个好用的处理word的框架吗

**Comment by wan766405890** [comment]
> 不至于这样诋毁吧？那您能推荐一个好用的处理word的框架吗

根本用不了,巨坑,还不如不开源呢,浪费时间

**Comment by CarterCL** [comment]
> > 不至于这样诋毁吧？那您能推荐一个好用的处理word的框架吗
> 
> 根本用不了,巨坑,还不如不开源呢,浪费时间

提示：Github的Issues是**提问题**的地方，不是**输出情绪**的地方。如果还不会用Github，推荐学习一下官方写的[教程](https://docs.github.com/zh/get-started)。

**Comment by wan766405890** [comment]
> > > 不至于这样诋毁吧？那您能推荐一个好用的处理word的框架吗
> > 
> > 
> > 根本用不了,巨坑,还不如不开源呢,浪费时间
> 
> 提示：Github的Issues是**提问题**的地方，不是**输出情绪**的地方。如果还不会用Github，推荐学习一下官方写的[教程](https://docs.github.com/zh/get-started)。

项目烂还不让人说了

**Comment by polarlights** [comment]
如果觉得有问题，请提PR；抱怨不会解决问题，不会让这个世界变得更好。

**Comment by cuitz** [comment]
真有你的

**Comment by vk-f** [comment]
> 垃圾库,好多bug,建议从github上消失

连描述一个自己遇到的bug的能力都没有吗
