### ISSUE TITLE
是否支持导出二级X轴

### ISSUE THREAD

**Issue by p410342078** [Sayi/poi-tl#1006]
### Issue description
![image](https://github.com/Sayi/poi-tl/assets/49271307/62bac074-e377-4ba9-a2e2-7963e44c92de)
1.图表支持二级X轴吗，如图这种的？
2.文本是否支持导出上标、下标，如：SO₂、PM₁₀
### Minimal test code to reproduce the issue

```java

```

**Comment by Sayi** [comment]
目前不支持。
