### ISSUE TITLE
插入svg图片报错

### ISSUE THREAD

**Issue by 759427794** [Sayi/poi-tl#1008]
制作了一个word模板，插入svg图片，设置标签为{{svg}}

如图所示：
![image](https://github.com/Sayi/poi-tl/assets/39944452/a1c9e256-f45a-4472-87c8-3bb2c567a88b)

代码分别使用如下四种方式替换，均报错
![image](https://github.com/Sayi/poi-tl/assets/39944452/c42db96d-a853-4348-97d6-21fbcbac7f2f)

错误日志如下：

[err.log](https://github.com/Sayi/poi-tl/files/11907174/err.log)

**Comment by fwk1010** [comment]
一个思路，先转为普通图片？png等

**Comment by 759427794** [comment]
> 一个思路，先转为普通图片？png等

不是很契合业务场景，图片是专门部署的node服务生成的，主要是看官网支持svg想尝试用svg渲染

**Comment by fwk1010** [comment]
不好意思，没留到代码。图片标签以@开始：{{@var}}
http://deepoove.com/poi-tl/#_%E5%9B%BE%E7%89%87

**Comment by Sayi** [comment]
引用标签不支持svg，图片标签支持svg，可以尝试修改下源码，并贡献出来哦。
