### ISSUE TITLE
如果在渲染表格的时候，固定行数后新建一个表格并添加换页符

### ISSUE THREAD

**Issue by polarlights** [Sayi/poi-tl#1010]
RT. 目前渲染使用 DynamicTableRenderPolicy 实现，但是在渲染过程中，达到一定行数后，分割出来若干新的表格，并换页。

目前对于在当前框架下实现完全没有思路，不知道其它人是否有遇到此类场景，是否有一些思路。

**Comment by fwk1010** [comment]
使用动态模板方式，追加内容，如不同的表格。
http://deepoove.com/poi-tl/#_%E6%A8%A1%E6%9D%BF%E7%94%9F%E6%88%90%E6%A8%A1%E6%9D%BF

**Comment by polarlights** [comment]
> 使用动态模板方式，追加内容，如不同的表格。 http://deepoove.com/poi-tl/#_%E6%A8%A1%E6%9D%BF%E7%94%9F%E6%88%90%E6%A8%A1%E6%9D%BF

嗯。谢谢。有查看过技术文档。文档中的场景是针对相同表格作扩展定制；我的场景里面多了1个表格拆分。

**Comment by fwk1010** [comment]
可以拼接不同的表格的，甚至是段落等。本质是doc的一部分，详细参见Documents.DocumentBuilder。我们这边用到的场景根据json配置文件动态生成一部分文档

**Comment by cuitz** [comment]
我使用的AbstractRenderPolicy，完全自己控制生成表格和样式，不过我的场景是生成多个表格，每个表格中间插入一个空行。

**Comment by polarlights** [comment]
@fwk1010 @cuitz 谢谢。我分别看下相关实现。

**Comment by polarlights** [comment]
https://stackoverflow.com/questions/46337263/apache-poi-word-best-way-to-add-text-after-table

**Comment by polarlights** [comment]
/

**Comment by polarlights** [comment]
there's another way that render the whole table and then copy and edit the tables.
https://stackoverflow.com/questions/58014683/copy-table-from-templates-with-fixed-place-using-apache-poi
