### ISSUE TITLE
条形图排序问题

### ISSUE THREAD

**Issue by wan766405890** [Sayi/poi-tl#1014]
条形图排序 series默认是从右到左读？
![image](https://github.com/Sayi/poi-tl/assets/31981203/8e804942-04d7-45fa-b45c-bd916e5ecd0c)

**Comment by wan766405890** [comment]
![image](https://github.com/Sayi/poi-tl/assets/31981203/852c65b3-ae1b-413d-be0e-fc5b5f259f14)

**Comment by cuitz** [comment]
你这种横置的图是这样的，如果你改成竖置的你会发现是正常的，不知道是poi-tl的问题还是本该如此。我是靠代码解决的，把数据源反转一下。
