### ISSUE TITLE
请问我想设置柱状图最大值，如：超出最大值250，则为最大值250，该怎么设置

### ISSUE THREAD

**Issue by chenxiaopeng-com** [Sayi/poi-tl#1015]
目前柱状图代码部分
 ChartMultiSeriesRenderData ccChart = Charts
                    .ofMultiSeries("",areaList.toArray(new String[areaList.size()]))
                    .addSeries("计划", planlitionIntegerList.toArray(new Number[planlitionIntegerList.size()]))
                    .addSeries("1-"+month+"月拆除量",completeDemolitionIntegerList.toArray(new Number[completeDemolitionIntegerList.size()]))
                    .addSeries("完成率",rateDemolitionList.toArray(new Number[rateDemolitionList.size()]))
                    .create();

            export.put("ccChart",ccChart);

**Comment by Sayi** [comment]
数据源着手。
