### ISSUE TITLE
带有目录的模板 代码块输出错误

### ISSUE THREAD

**Issue by youwu210** [Sayi/poi-tl#1017]
### Issue description
带有目录的模板代码块模板出错
### poi-tl version
1.12.0
### Minimal test code to reproduce the issue

data.put("bidInfoList", bidInfoList);//评审项

这个是没有目录的模板文件的日志
21:25:30.474 [main] INFO  c.deepoove.poi.render.DefaultRender - Render template start...
21:25:30.509 [main] INFO  c.d.p.render.processor.LogProcessor - ${?bidInfoList}
21:25:30.509 [main] INFO  c.d.p.render.processor.LogProcessor -   ${review}
21:25:30.510 [main] INFO  c.d.p.render.processor.LogProcessor -   ${standard}
21:25:30.510 [main] INFO  c.d.p.render.processor.LogProcessor -   ${remark}
21:25:30.510 [main] INFO  c.d.p.render.processor.LogProcessor - ${/bidInfoList}
21:25:30.512 [main] INFO  c.d.p.r.processor.IterableProcessor - Process iterableTemplate:${?bidInfoList}${review} ${standard} ${remark} ${/bidInfoList}
21:25:30.571 [main] DEBUG c.d.poi.resolver.RunningRunBody - ${ review }
21:25:30.571 [main] DEBUG c.d.poi.resolver.RunningRunBody - [Start]:The run position of ${ review } is 0, Offset in run is 0
21:25:30.571 [main] DEBUG c.d.poi.resolver.RunningRunBody - [End]:The run position of ${ review } is 0, Offset in run is 10
21:25:30.572 [main] DEBUG c.d.poi.resolver.TemplateResolver - Resolve where text: ${ review }, and create RunTemplate for XWPFRun
21:25:30.572 [main] DEBUG c.d.poi.resolver.RunningRunBody - ${ standard }
21:25:30.572 [main] DEBUG c.d.poi.resolver.RunningRunBody - [Start]:The run position of ${ standard } is 0, Offset in run is 0
21:25:30.572 [main] DEBUG c.d.poi.resolver.RunningRunBody - [End]:The run position of ${ standard } is 0, Offset in run is 12
21:25:30.576 [main] DEBUG c.d.poi.resolver.TemplateResolver - Resolve where text: ${ standard }, and create RunTemplate for XWPFRun
**21:25:30.576 [main] DEBUG c.d.poi.resolver.RunningRunBody - ${ remark }
21:25:30.576 [main] DEBUG c.d.poi.resolver.RunningRunBody - [Start]:The run position of ${ remark } is 0, Offset in run is 0
21:25:30.576 [main] DEBUG c.d.poi.resolver.RunningRunBody - [End]:The run position of ${ remark } is 0, Offset in run is 10**
21:25:30.576 [main] DEBUG c.d.poi.resolver.TemplateResolver - Resolve where text: ${ remark }, and create RunTemplate for XWPFRun
21:25:30.703 [main] INFO  c.d.p.r.processor.DelegatePolicy - Start render Template ${review}, Sign:

这个是有目录的模板文件的日志
21:22:54.348 [main] INFO  c.deepoove.poi.render.DefaultRender - Render template start...
21:22:54.364 [main] INFO  c.d.p.render.processor.LogProcessor - ${?bidInfoList}
21:22:54.364 [main] INFO  c.d.p.render.processor.LogProcessor -   ${review}
21:22:54.364 [main] INFO  c.d.p.render.processor.LogProcessor -   ${standard}
21:22:54.364 [main] INFO  c.d.p.render.processor.LogProcessor -   ${remark}
21:22:54.364 [main] INFO  c.d.p.render.processor.LogProcessor - ${/bidInfoList}
21:22:54.375 [main] INFO  c.d.p.r.processor.IterableProcessor - Process iterableTemplate:${?bidInfoList}${review} ${standard} ${remark} ${/bidInfoList}
21:22:54.506 [main] DEBUG c.d.poi.resolver.RunningRunBody - ${ review }
21:22:54.506 [main] DEBUG c.d.poi.resolver.RunningRunBody - [Start]:The run position of ${ review } is 0, Offset in run is 0
21:22:54.506 [main] DEBUG c.d.poi.resolver.RunningRunBody - [End]:The run position of ${ review } is 0, Offset in run is 10
21:22:54.506 [main] DEBUG c.d.poi.resolver.TemplateResolver - Resolve where text: ${ review }, and create RunTemplate for XWPFRun
21:22:54.506 [main] DEBUG c.d.poi.resolver.RunningRunBody - ${ standard }
21:22:54.506 [main] DEBUG c.d.poi.resolver.RunningRunBody - [Start]:The run position of ${ standard } is 0, Offset in run is 0
21:22:54.506 [main] DEBUG c.d.poi.resolver.RunningRunBody - [End]:The run position of ${ standard } is 0, Offset in run is 12
21:22:54.506 [main] DEBUG c.d.poi.resolver.TemplateResolver - Resolve where text: ${ standard }, and create RunTemplate for XWPFRun
**21:22:54.506 [main] DEBUG c.d.poi.resolver.RunningRunBody - ${ review }
21:22:54.506 [main] DEBUG c.d.poi.resolver.RunningRunBody - [Start]:The run position of ${ review } is 0, Offset in run is 0
21:22:54.506 [main] DEBUG c.d.poi.resolver.RunningRunBody - [End]:The run position of ${ review } is 0, Offset in run is 10**
21:22:54.506 [main] DEBUG c.d.poi.resolver.TemplateResolver - Resolve where text: ${ review }, and create RunTemplate for XWPFRun
21:22:54.559 [main] INFO  c.d.p.r.processor.DelegatePolicy - Start render Template ${review}, Sign:
### Minimal Docx template file

[标书响应文件主模板2-out - 正常.docx](https://github.com/Sayi/poi-tl/files/12081120/2-out.-.docx)
[标书响应文件主模板2-out-错误.docx](https://github.com/Sayi/poi-tl/files/12081123/2-out-.docx)

**Comment by Sayi** [comment]
```java
   @Test
    public void test() throws IOException {
        XWPFTemplate.compile("src/test/resources/issue/1017-1.docx", Configure.builder().buildGramer("${", "}").useSpringEL().build())
            .render(new HashMap<String, Object>() {
                {
                    put("bidInfoList", new ArrayList<Object>() {
                        {
                            add(new HashMap<String, Object>() {{
                                put("review", "zs");
                                put("standard", "zs");
                                put("remark", "zs");
                            }});
                        }
                    });
                }
            }).writeToFile("target/out_1017-1.docx");
    }
```

无法重现。
