### ISSUE TITLE
官网打不开了

### ISSUE THREAD

**Issue by zmk940918** [Sayi/poi-tl#1018]
http://deepoove.com/poi-tl/
这个网址打不开了

**Comment by zmk940918** [comment]
你能打开这个官网文档地址吗？

**Comment by zmk940918** [comment]
> > http://deepoove.com/poi-tl/ 这个网址打不开了
> 
> 可以的,我想问一下,现在需求要我生成很多复杂的文本样式,但是poi-tl很多都设置不了,有没有什么办法

你的浏览器能打开这个文档地址吗？

**Comment by zmk940918** [comment]
> 打不开

想看个文档都找不到地方

**Comment by yunmengmeng** [comment]
> > > http://deepoove.com/poi-tl/ 这个网址打不开了
> > 
> > 
> > 可以的,我想问一下,现在需求要我生成很多复杂的文本样式,但是poi-tl很多都设置不了,有没有什么办法
> 
> 你的浏览器能打开这个文档地址吗？

打不开了

**Comment by Sayi** [comment]
官方文档由于域名问题，暂时无法解析访问，将尽快解决。

**Comment by Sayi** [comment]
[poi-tl文档.pdf](https://github.com/Sayi/poi-tl/files/12096748/poi-tl.pdf)

**Comment by zxw75192** [comment]
> [poi-tl文档.pdf](https://github.com/Sayi/poi-tl/files/12096748/poi-tl.pdf)

感谢大佬

**Comment by chunjie95** [comment]
> [poi-tl文档.pdf](https://github.com/Sayi/poi-tl/files/12096748/poi-tl.pdf)

感谢大佬

**Comment by chengliangHuang** [comment]
今天看文档官网没的了，感谢大佬的离线文档

**Comment by tuablove** [comment]
> [poi-tl文档.pdf](https://github.com/Sayi/poi-tl/files/12096748/poi-tl.pdf)

赶紧把，官网再不正常，世界都不和平了

**Comment by coder-chun** [comment]
官网打不开，还以为不维护了
