### ISSUE TITLE
解决文档更新域之后，弹窗问题

### ISSUE THREAD

**Issue by zlp8013** [Sayi/poi-tl#1025]
我在代码中更新域之后，生成的目标文件在打开的时候，会显示弹窗：
![image](https://github.com/Sayi/poi-tl/assets/101457266/9e06b07b-c361-4c83-abe4-7037ef53ff4b)
![image](https://github.com/Sayi/poi-tl/assets/101457266/acc9d5ee-35e3-40b6-aa84-47b6432739c8)
有没有什么办法可以解决？或者说有没有方法帮用户去快速点击，反正目的就是为了让用户感知不到这两个弹窗

**Comment by HYliangkai** [comment]
> 我在代码中更新域之后，生成的目标文件在打开的时候，会显示弹窗： ![image](https://user-images.githubusercontent.com/101457266/255500105-9e06b07b-c361-4c83-abe4-7037ef53ff4b.png) ![image](https://user-images.githubusercontent.com/101457266/255500127-acc9d5ee-35e3-40b6-aa84-47b6432739c8.png) 有没有什么办法可以解决？或者说有没有方法帮用户去快速点击，反正目的就是为了让用户感知不到这两个弹窗

使用spire.doc可以解决目录更新的问题(有免费版)
