### ISSUE TITLE
在使用文档模板{{+var}}时，如果put进去的list数据越多，导出word的时间越久

### ISSUE THREAD

**Issue by RowanJie** [Sayi/poi-tl#1026]
`List<SegmentData> segments = new ArrayList<SegmentData>();
SegmentData s1 = new SegmentData();
s1.setTitle("经常抱怨的自己");
s1.setContent("每个人生活得都不容易，经常向别人抱怨的人，说白了就是把对方当做“垃圾场”，你一股脑地将自己的埋怨与不满倒给别人，自己倒是爽了，你有考虑过对方的感受吗？对方的脸上可能一笑了之，但是心里可能有一万只草泥马奔腾而过。");
segments.add(s1);

SegmentData s2 = new SegmentData();
s2.setTitle("拖拖拉拉的自己");
s2.setContent("能够今天做完的事情，不要拖到明天，你的事情没有任何人有义务去帮你做；不要做“宅男”、不要当“宅女”，放假的日子约上三五好友出去转转；经常动手做家务，既能分担伴侣的负担，又有一个干净舒适的环境何乐而不为呢？");
segments.add(s2);

put("docx_word", new DocxRenderData(new File("~/segment.docx"), segments));  `

已上诉官方代码为例，当segments大于200条数据时候，导出时间超过7-8s，不使用文档模板{{+var}}直接使用原生poi动态添加时时间只要1s，望楼主可以看看这个加载子模板速率太慢的性能问题，本人使用的是poi-tl 的1.6.0版本

**Comment by Sayi** [comment]
区块对的性能更佳。嵌套文档模版在数据量很大的时候的确会慢。
