### ISSUE TITLE
模板导出支持控制跳过某行不导出吗？

### ISSUE THREAD

**Issue by dyilong** [Sayi/poi-tl#1027]
模板导出“表格列循环”时，支持控制跳过某行时间不导出吗？

**Comment by fwk1010** [comment]
从数据源入手

**Comment by dyilong** [comment]
![image](https://github.com/Sayi/poi-tl/assets/13959274/1417d29a-4e6b-4257-8c68-5afad4dce305)

比如该示例，我想控制货物或折扣 整行不输出。是否支持该功能呢

**Comment by dyilong** [comment]
> 从数据源入手

![image](https://github.com/Sayi/poi-tl/assets/13959274/d41663bc-4dd2-41f7-a479-dd4d98083593)
比如该示例，我想控制货物或折扣 整行不输出。是否支持该功能呢

**Comment by fwk1010** [comment]
这种基于写死模板的方式不行，只能是自定义动态表格或动态模板的方式

**Comment by dyilong** [comment]
> 这种基于写死模板的方式不行，只能是自定义动态表格或动态模板的方式

有相关示例吗？参考一下 谢谢

**Comment by fwk1010** [comment]
参考 https://github.com/Sayi/poi-tl/issues/1010

**Comment by Sayi** [comment]
在模版中如何呈现这个功能？没有找到很好的方式，有什么好的建议？

**Comment by Sayi** [comment]
表格中至少满足两个功能：
- if 隐藏显示单行列或者多行列
- 循环单行列或者多行列

如果模版制作起来简单易懂，这个特性是很不错的。

**Comment by dyilong** [comment]
![image](https://github.com/Sayi/poi-tl/assets/13959274/be4abd1c-36f0-4091-b053-1af7a1f9002e)
图中是一个隐藏边框的表格输出模板。我希望的特性是  我想通过生成模板时传入一个参数。根据参数来控制 [teamName]是否输出。
ps: 目前我是在Java中通过数据控制的，但是会生成一个空白的行占位，我想要的效果是整行都不显示

**Comment by dyilong** [comment]
> 继承表格循环插件，覆盖`afterloop`方法，使用XWPFTable删除不想要的行。

多谢指导
