### ISSUE TITLE
一个文档里面如何渲染一个图片列表？

### ISSUE THREAD

**Issue by Revin-zk** [Sayi/poi-tl#103]
您好，根据您的api文档，貌似文档里面只能传入格式已定的图片。我有多张图片（1-n）n未知，这里如何去渲染

**Comment by Sayi** [comment]
这些图片是横排，还是竖排，图片样式很难统一，可以自己写个插件。 

 [插件机制](http://deepoove.com/poi-tl/#_%E6%8F%92%E4%BB%B6%E6%9C%BA%E5%88%B6plugin_mechanism)
