### ISSUE TITLE
标签没有值的时候，还会留下空间占位置

### ISSUE THREAD

**Issue by zlp8013** [Sayi/poi-tl#1032]
如果一个标签没有值，那么就不显示，但是在word中，还是会占位置，如果一行只有一个标签的话，那么就会留下一个空行，有没有什么方法可以解决？
如果去遍历所有的段落判断是否为空的话，那么有些我想留下的空行也会被删除

**Comment by Sayi** [comment]
我本地无法复现，默认NULL标签的段落没有额外文字会删除该行的。

**Comment by zlp8013** [comment]
如果只是普通的文本标签{{}} ,没有包裹在循环里面的话，那么如果该标签没有put行为的话，会自动删除该行，但是如果有put行为，只不过我put了一个空，也就是“” ，那么就不会删除该行，就会出现空行。
如果文本标签{{}}，被包裹在了循环里面：
![image](https://github.com/Sayi/poi-tl/assets/101457266/39ebef4b-3231-470e-a937-20ae22abeb4c)
那么即使我没有put行为：
![image](https://github.com/Sayi/poi-tl/assets/101457266/b41f5531-034e-4f68-b36f-7f19d20c0753)
对应空行不会删除，依然存在：
![image](https://github.com/Sayi/poi-tl/assets/101457266/6f718e07-07f9-42e2-aedd-9f23993fa2e1)
（当然，如果是put一个空值“”，也是一样，不会删除）

**Comment by Sayi** [comment]
我试了下无论是否在循环里面，只要是NULL值都会清空该行。用的都是文本策略，处理方式是一致的。

**Comment by zlp8013** [comment]
> 我试了下无论是否在循环里面，只要是NULL值都会清空该行。用的都是文本策略，处理方式是一致的。

那这就有点奇怪，我上面那个示例也很简单，name和sex之间有空行。
@Test
  void test04() throws IOException {
    Map<String, Object> data = new HashMap<>();
    List<Object> list = new ArrayList<>();
    for (int i = 0; i < 2; i++) {
      HashMap<String, Object> map = new HashMap<>();
      map.put("name", "zs");
      map.put("sex", "男");
      list.add(map);
    }
    data.put("a", list);
    XWPFTemplate.compile("D:\\poi-tl\\test.docx")
        .render(data)
        .writeToFile("D:\\poi-tl\\testTarget.docx");
  }

**Comment by Sayi** [comment]
是因为你age前面有很多空格吧，有空格该行是不会被删除的。

**Comment by zlp8013** [comment]
> 是因为你age前面有很多空格吧，有空格该行是不会被删除的。

确实，只不过不是空格，是一个手动换行符，不过道理应该是一样的，会占位置
