### ISSUE TITLE
表格自定义合并策略中  再  为字段自定义策略

### ISSUE THREAD

**Issue by zlp8013** [Sayi/poi-tl#1038]
需求:
一个表格中的某些单元格可能会被放入富文本，比如<b> </b>，那么在表格中就要显示加粗效果，比如下面的age：
![image](https://github.com/Sayi/poi-tl/assets/101457266/2a662d88-c9fb-4242-ad68-704e572317d0)
如果没有写合并策略的话，也就是用默认的行循环策略，那么是可以显示加粗效果的。
![image](https://github.com/Sayi/poi-tl/assets/101457266/8e049e9d-615e-4eb0-b9fe-583b2ad5147d)
但现在问题就是，我需要对表格进行合并，这时候，age对应的HtmlRenderPolicy就失效了：
![image](https://github.com/Sayi/poi-tl/assets/101457266/5853c95c-d959-47be-978a-3a843a2b949b)
我不知道是我操作有问题，还是poi-tl不支持

**Comment by zlp8013** [comment]
即使在我的自定义策略中没有去合并单元格，仅仅是遍历渲染数据，HtmlRenderPolicy还是会失效

**Comment by Sayi** [comment]
没理解。。。

**Comment by zlp8013** [comment]
> 没理解。。。

其实需求很简单，就是一个表格，然后我自定义 了一个合并策略，然后这个表格中的一个字段（比如上面图片中的age），它的内容是富文本数据，也就是HTML片段。
问题就是，如果我给上面的tab绑定了我自定义的策略，那么下面给age绑定的HTML策略就会失效，比如就会显示：<b>XXX</b>，富文本数据没有得到解析

**Comment by Sayi** [comment]
给个demo吧，我好复现下

**Comment by zlp8013** [comment]
> 给个demo吧，我好复现下

模板：
![image](https://github.com/Sayi/poi-tl/assets/101457266/91a3c746-8dd9-4629-9189-4fa2ea88f66a)

代码：

@Test
  void test01() throws IOException {
    Map<String, Object> map = new HashMap<>();
    List<Map<String, Object>> list = new LinkedList<>();
    for (int i = 0; i < 2; i++) {
      Map<String, Object> m = new HashMap<>();
      m.put("name", "zs");
      m.put("age", "<b>20</b>");
      list.add(m);
    }
    map.put("tab", list);
    Configure configure =
        Configure.builder()
            .bind("tab", new Table1Policy())
            .bind("age", new HtmlRenderPolicy())
            .build();
    XWPFTemplate.compile("D:\\poi-tl\\project\\html.docx", configure)
        .render(map)
        .writeToFile("D:\\poi-tl\\project\\htmlTarget.docx");
  }
  
  表格策略：
  
  public class Table1Policy extends DynamicTableRenderPolicy {
  @Override
  public void render(XWPFTable table, Object data) throws Exception {
    int startRow = 1;
    List<Map<String, Object>> jsonData = (List<Map<String, Object>>) data;
    List<RowRenderData> renderDataList = new LinkedList<>();
    for (Map<String, Object> d : jsonData) {
      String name = (String) d.get("name");
      String age = (String) d.get("age");
      renderDataList.add(Rows.of(name, age).create());
    }
    table.removeRow(startRow);
    for (int i = 1; i <= renderDataList.size(); i++) {
      // 插入行
      XWPFTableRow row = table.insertNewTableRow(i);
      // 插入列
      for (int j = 0; j < 2; j++) {
        row.createCell();
      }
      // 渲染数据
      TableRenderPolicy.Helper.renderRow(table.getRow(i), renderDataList.get(i - 1));
    }
  }
  }

效果：
![image](https://github.com/Sayi/poi-tl/assets/101457266/a9074437-05a4-4dde-ad15-1181ddd15eb8)

**Comment by zlp8013** [comment]
> 给个demo吧，我好复现下

![image](https://github.com/Sayi/poi-tl/assets/101457266/c33144e6-7422-4ee4-9030-477094fd93c3)

这里的age20，被浏览器自动解析了

![image](https://github.com/Sayi/poi-tl/assets/101457266/a72c294a-1ac2-4e29-b449-28becae8dce6)

**Comment by Sayi** [comment]
age不是合法的标签，用法错了。

```
TableRenderPolicy.Helper.renderRow(table.getRow(i), renderDataList.get(i - 1));
```
这行代码并不会渲染html,需要通过html插件去渲染.

**Comment by zlp8013** [comment]
> 

那需要如何做，是修改这行代码吗，还是说要从数据源入手，策略中的data
![image](https://github.com/Sayi/poi-tl/assets/101457266/ca54ebe8-81ee-4b56-8e05-3a023710ea92)

**Comment by Sayi** [comment]
1. 调用htmlrenderpolicy中相关渲染方法
2. 不能用自定义插件,需要通过标准方法绑定age到htmlrenderpolicy
