### ISSUE TITLE
请问如何使用区块对循环生成表格

### ISSUE THREAD

**Issue by yunmengmeng** [Sayi/poi-tl#1039]
当我使用下面的区块对
{{?sections}}
节点：{{hostname}}
{{#inst_info}}
{{/sections}}
想要生成一个动态表格时，发现表格没有生成，请问应该怎么写代码？
![image](https://github.com/Sayi/poi-tl/assets/46476040/6f8833ec-0ad5-40e9-979b-22d9ff56897c)

**Comment by zlp8013** [comment]
sectionsList里面放inst_infoMap

**Comment by yunmengmeng** [comment]
> sectionsList里面放inst_infoMap

好吧，我发现了，是sections标签下面的那一行解析不出来，真神奇

**Comment by yunmengmeng** [comment]
> sectionsList里面放inst_infoMap

我擦，之前用的是1.12.0，我用1.12.1就可以解析出来了，看来是上个版本的bug
