### ISSUE TITLE
表格位置是否能够右移

### ISSUE THREAD

**Issue by Lone5267** [Sayi/poi-tl#104]
我在模板里使用的表格替换符，在生成的word中表格位置总是在最左边顶到头，无论我使用空格还是tab都不能让这个表格往右移动。我想问问是不是我的操作方式有问题。还是需要进行一些什么操作才能让这个表格位置往右移动呢。。。 poi-tl 版本 1.2.0

**Comment by Sayi** [comment]
word 默认表格都是最左边顶到头：即超出左页边距些许尺寸。

希望不希望左边顶出头的话，可以设置一个宽度，让表格整体居中。
参见1.3.1版本的测试用例：[MiniTableRenderTest.java](https://github.com/Sayi/poi-tl/blob/master/src/test/java/com/deepoove/poi/tl/policy/MiniTableRenderTest.java)
