### ISSUE TITLE
XWPFTemplate.compile(sourceFile).render(data).writeAndClose(os)生成的word文档有换行效果但是没换行符

### ISSUE THREAD

**Issue by codeBoy01** [Sayi/poi-tl#1043]
### Minimal test code to reproduce the issue

```java

```
### Minimal Docx template file
图片如下
<img width="854" alt="image" src="https://github.com/Sayi/poi-tl/assets/55353017/30a5b908-4637-4a0f-9e5e-dee520b86d20">
复制出来的内容为
<img width="657" alt="image" src="https://github.com/Sayi/poi-tl/assets/55353017/bdbec610-74cc-4b96-b747-1f82d9eaa9de">
请问一下怎么处理呢，因为做了word预览，没换行符，内容都连成一片了。

**Comment by Sayi** [comment]
手动的换行其实是多个段落，你需要用段落来代替换行。

**Comment by Sayi** [comment]
参考DocumentRenderPolicy和ParagraphRenderPolicy

**Comment by Sayi** [comment]
#890

**Comment by codeBoy01** [comment]
> 

不太会呢，我是要重新定义一个插件吗

**Comment by codeBoy01** [comment]
> 参考DocumentRenderPolicy和ParagraphRenderPolicy

大佬，能给我一份示例代码吗，非常感谢

**Comment by codeBoy01** [comment]
我的word模版是固定的怎么办

**Comment by codeBoy01** [comment]
> ParagraphRenderPolicy

谢谢大佬指导，已经解决了，有中文文档说明就是好用
