### ISSUE TITLE
表格进行合并后,打开word,手工挪动列宽,发现已合并的列又分开

### ISSUE THREAD

**Issue by FengTian2** [Sayi/poi-tl#105]
我是 直接在 PaymentExample 这例子操作， 
      1  付款通知书.docx 里删除掉所有有内容，新建一个4*4表，其中第一行第一列格子填写{{detail_table}}
      2 更改 DetailTablePolicy.java的render 如下： 
    @Override
    public void render(XWPFTable table, Object data) {
    	for(int i =0;i < 8;i ++)
		 {			 
				   XWPFTableRow tableRowThree = table.createRow();
				   tableRowThree.getCell(0).setText("col one, row three");
				   tableRowThree.getCell(1).setText("col two, row three");
				   tableRowThree.getCell(2).setText("col three, row three");				 						 
		 }	
		 NiceXWPFDocument.mergeCellsVertically(table, 0, 4 , 9 );
         }

其他都不变，
生成的WORD表格，打开看是正常，但是如果改变列宽，就发现已可并的列，又分开
请问是否还有其他要操作或设置？

**Comment by Sayi** [comment]
@FengTian2  因为在第4到第9行的第一列你都设置值了，当垂直合并这些行时，无法确定合并后的值。
把这行代码注释掉`tableRowThree.getCell(0).setText("col one, row three");`应该就不会出现你的问题。

针对这个问题后续我会考虑优化，**目前建议先做单元格合并操作，再给单元格设置文字**
