### ISSUE TITLE
请问，关于表格列循环插件，能否限制列数，超过限制则往下一行增加

### ISSUE THREAD

**Issue by zsrey** [Sayi/poi-tl#1053]
poi-tl version 1.12.1

![20230905111405](https://github.com/Sayi/poi-tl/assets/55772098/be7c0b63-a63e-452b-b7ed-74b2921294ec)

如图，当我有5条数据时，使用表格列循环插件，能否在限制当前行插入3条数据，往下一行插入2条数据

**Comment by zlp8013** [comment]
自定义表格策略
