### ISSUE TITLE
表格列合并问题

### ISSUE THREAD

**Issue by dydaiyang** [Sayi/poi-tl#1055]
我需要类似这样的表头
![image](https://github.com/Sayi/poi-tl/assets/30311441/fdde0656-685a-4858-bb3d-5202bfe71738)
我的代码是这样实现的
![image](https://github.com/Sayi/poi-tl/assets/30311441/67e12dbc-7125-4f57-a79b-431e3c0e6c85)
但最终的效果是这样的
![image](https://github.com/Sayi/poi-tl/assets/30311441/af328aa4-c46a-474e-b2c3-626c3e08e532)
调试了很多次还是没有调试出来

**Comment by Ayerchi** [comment]
第三条规则有问题吧

**Comment by Sayi** [comment]
总共5列。
