### ISSUE TITLE
请问如何在表格里实现0-100进度条的效果

### ISSUE THREAD

**Issue by xiaokaRepo** [Sayi/poi-tl#1056]
有没有办法在表格里根据数值生成进度条样式，目前的方案啥根据█和░来实现，有没有比较优雅的方式来实现
<img width="683" alt="image" src="https://github.com/Sayi/poi-tl/assets/141160532/5f3bcaff-1f2e-48fe-b7cc-5e9d0104bb31">

**Comment by fwk1010** [comment]
我的理解是word本身是怎么做到，就可以怎么做

**Comment by xiaokaRepo** [comment]
> 我的理解是word本身是怎么做到，就可以怎么做

因为特殊字符的高度不一致感觉不够美观，无法做到高度自定义，目前另外一种方式通过SVGGraphics2D来根据比例绘制svg矢量图片，插入图片可以实现需求。但是却遇到一个图片精度问题，看作者源码，svg默认是转为png进行插入，估计是转换失真导致，我将生成的svg直接插入文档效果显示非常好。下一步就是看图片格式转换问题如何解决。
<img width="1080" alt="image" src="https://github.com/Sayi/poi-tl/assets/141160532/b0cd8d05-73b2-4697-af1d-f70add6cf1c7">
