### ISSUE TITLE
代码高亮的示例代码报错

### ISSUE THREAD

**Issue by JadeDust** [Sayi/poi-tl#1060]
Connected to the target VM, address: '127.0.0.1:63789', transport: 'socket'
16:08:31.166 [main] INFO com.deepoove.poi.resolver.TemplateResolver - Resolve the document start...
16:08:31.175 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {{
16:08:31.175 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - code
16:08:31.175 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - }}
16:08:31.175 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [Start]:The run position of {{code}} is 0, Offset in run is 0
16:08:31.175 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [End]:The run position of {{code}} is 2, Offset in run is 1
16:08:31.177 [main] DEBUG com.deepoove.poi.resolver.TemplateResolver - Resolve where text: {{code}}, and create RunTemplate for XWPFRun
16:08:31.183 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {
16:08:31.184 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {
16:08:31.184 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - code
16:08:31.184 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - }}
16:08:31.184 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [Start]:The run position of {{code}} is 0, Offset in run is 0
16:08:31.184 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [End]:The run position of {{code}} is 3, Offset in run is 1
16:08:31.184 [main] DEBUG com.deepoove.poi.resolver.TemplateResolver - Resolve where text: {{code}}, and create RunTemplate for XWPFRun
16:08:31.185 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {{code}}
16:08:31.185 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [Start]:The run position of {{code}} is 0, Offset in run is 0
16:08:31.185 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [End]:The run position of {{code}} is 0, Offset in run is 7
16:08:31.185 [main] DEBUG com.deepoove.poi.resolver.TemplateResolver - Resolve where text: {{code}}, and create RunTemplate for XWPFRun
16:08:31.185 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {
16:08:31.185 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {code}}
16:08:31.185 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [Start]:The run position of {{code}} is 0, Offset in run is 0
16:08:31.185 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [End]:The run position of {{code}} is 1, Offset in run is 6
16:08:31.186 [main] DEBUG com.deepoove.poi.resolver.TemplateResolver - Resolve where text: {{code}}, and create RunTemplate for XWPFRun
16:08:31.186 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {
16:08:31.186 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {?themes
16:08:31.186 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - }}
16:08:31.186 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [Start]:The run position of {{?themes}} is 0, Offset in run is 0
16:08:31.186 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [End]:The run position of {{?themes}} is 2, Offset in run is 1
16:08:31.186 [main] DEBUG com.deepoove.poi.resolver.TemplateResolver - Resolve where text: {{?themes}}, and create RunTemplate for XWPFRun
16:08:31.187 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {
16:08:31.187 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {_index}}
16:08:31.187 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - . 
16:08:31.188 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {
16:08:31.188 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {
16:08:31.188 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - theme
16:08:31.188 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - }}
16:08:31.188 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [Start]:The run position of {{_index}} is 0, Offset in run is 0
16:08:31.188 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [End]:The run position of {{_index}} is 1, Offset in run is 8
16:08:31.188 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [Start]:The run position of {{theme}} is 3, Offset in run is 0
16:08:31.188 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [End]:The run position of {{theme}} is 6, Offset in run is 1
16:08:31.188 [main] DEBUG com.deepoove.poi.resolver.TemplateResolver - Resolve where text: {{_index}}, and create RunTemplate for XWPFRun
16:08:31.188 [main] DEBUG com.deepoove.poi.resolver.TemplateResolver - Resolve where text: {{theme}}, and create RunTemplate for XWPFRun
16:08:31.189 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {
16:08:31.189 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {
16:08:31.189 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - code
16:08:31.189 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - }}
16:08:31.189 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [Start]:The run position of {{code}} is 0, Offset in run is 0
16:08:31.189 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [End]:The run position of {{code}} is 3, Offset in run is 1
16:08:31.189 [main] DEBUG com.deepoove.poi.resolver.TemplateResolver - Resolve where text: {{code}}, and create RunTemplate for XWPFRun
16:08:31.189 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {
16:08:31.189 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - {/themes}}
16:08:31.189 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [Start]:The run position of {{/themes}} is 0, Offset in run is 0
16:08:31.189 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [End]:The run position of {{/themes}} is 1, Offset in run is 9
16:08:31.189 [main] DEBUG com.deepoove.poi.resolver.TemplateResolver - Resolve where text: {{/themes}}, and create RunTemplate for XWPFRun
16:08:31.196 [main] INFO com.deepoove.poi.resolver.TemplateResolver - Resolve the document end, resolve and create 5 MetaTemplates.
16:08:31.196 [main] INFO com.deepoove.poi.render.DefaultRender - Render template start...
16:08:31.200 [main] INFO com.deepoove.poi.render.processor.LogProcessor - {{code}}
16:08:31.200 [main] INFO com.deepoove.poi.render.processor.LogProcessor - {{code}}
16:08:31.200 [main] INFO com.deepoove.poi.render.processor.LogProcessor - {{code}}
16:08:31.200 [main] INFO com.deepoove.poi.render.processor.LogProcessor - {{code}}
16:08:31.200 [main] INFO com.deepoove.poi.render.processor.LogProcessor - {{?themes}}
16:08:31.200 [main] INFO com.deepoove.poi.render.processor.LogProcessor -   {{_index}}
16:08:31.200 [main] INFO com.deepoove.poi.render.processor.LogProcessor -   {{theme}}
16:08:31.200 [main] INFO com.deepoove.poi.render.processor.LogProcessor -   {{code}}
16:08:31.200 [main] INFO com.deepoove.poi.render.processor.LogProcessor - {{/themes}}
16:08:31.203 [main] INFO com.deepoove.poi.render.processor.DelegatePolicy - Start render Template {{code}}, Sign: , policy:HighlightRenderPolicy
Exception in thread "main" com.deepoove.poi.exception.RenderException: Unable to render template {{code}}
	at com.deepoove.poi.policy.AbstractRenderPolicy.reThrowException(AbstractRenderPolicy.java:87)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:69)
	at com.deepoove.poi.render.processor.DelegatePolicy.invoke(DelegatePolicy.java:45)
	at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:65)
	at com.deepoove.poi.render.processor.ElementProcessor.visit(ElementProcessor.java:59)
	at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
	at com.deepoove.poi.render.processor.DocumentProcessor.visit(DocumentProcessor.java:95)
	at com.deepoove.poi.template.run.RunTemplate.accept(RunTemplate.java:64)
	at com.deepoove.poi.render.processor.DocumentProcessor.lambda$process$0(DocumentProcessor.java:59)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.deepoove.poi.render.processor.DocumentProcessor.process(DocumentProcessor.java:59)
	at com.deepoove.poi.render.DefaultRender.renderTemplate(DefaultRender.java:82)
	at com.deepoove.poi.render.DefaultRender.render(DefaultRender.java:64)
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:223)
	at com.ruoyi.system.util.tes.testHightlight(tes.java:84)
	at com.ruoyi.system.util.tes.main(tes.java:20)
Caused by: java.lang.IndexOutOfBoundsException
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTRPrImpl.getRStyleArray(CTRPrImpl.java:160)
	at org.apache.poi.xwpf.usermodel.XWPFRun.getStyle(XWPFRun.java:1256)
	at com.deepoove.poi.util.StyleUtils.styleRun(StyleUtils.java:157)
	at com.deepoove.poi.policy.DocumentRenderPolicy$Helper.renderDocument(DocumentRenderPolicy.java:63)
	at com.deepoove.poi.policy.AbstractDocumentConverterRenderPolicy.doRender(AbstractDocumentConverterRenderPolicy.java:46)
	at com.deepoove.poi.policy.AbstractRenderPolicy.render(AbstractRenderPolicy.java:66)
	... 14 more
![2023-09-15_161142](https://github.com/Sayi/poi-tl/assets/57691291/e484201d-807e-4afe-8164-555eae83c809)

使用版本：poi-tl 1.10.5   poi相关依赖都是5.0.0
使用的示例代码地址：https://github.com/Sayi/poi-tl/blob/dev-1.10.x/poi-tl-plugin-highlight/src/test/java/com/deepoove/poi/plugin/highlight/HighlightRenderPolicyTest.java

**Comment by Sayi** [comment]
版本搞错了，1.10.5支持4.1.2，建议你用最新版本试试哦。
