### ISSUE TITLE
怎么设置表格的粗边框

### ISSUE THREAD

**Issue by loyy77** [Sayi/poi-tl#1062]
### Issue description
需要设置表格样式如下：
外边框比单元格粗，而不是单元格边框和整个表格边框一样粗
![image](https://github.com/Sayi/poi-tl/assets/958019/2a3e6279-8611-4321-800c-e735cd06bcc2)
### poi-tl version
1.21.1
### Minimal test code to reproduce the issue

```java
   val table = Tables.of(row0)
            .border(BorderStyle.DEFAULT)
            .center()

```

**Comment by loyy77** [comment]
@Sayi

**Comment by Sayi** [comment]
use poi api.
