### ISSUE TITLE
插件使用 builder.customPolicy("report", new MyRenderPolicy());标签未被替换

### ISSUE THREAD

**Issue by yaoshanli** [Sayi/poi-tl#107]
ConfigureBuilder builder = Configure.newBuilder();
builder.customPolicy("content1", new PercentRenderPolicy());
builder.customPolicy("content2", new PercentRenderPolicy());
builder.customPolicy("content3", new PercentRenderPolicy());
builder.customPolicy("content4", new PercentRenderPolicy());
String temp_url =getRequest().getSession().getServletContext()
				.getRealPath("/WEB-INF/jsp/template/doc_kjcg_template.docx");
XWPFTemplate template = XWPFTemplate.compile(temp_url, builder.build()).render(dataMap);   这个插件方法使用时，{{content1}}、{{content2}}、{{content3}}、{{content4}}标签后边累加了内容，而不是替换。
如：“{{content1}}1、研究设计内容
1、研究设计内容（1）高标号、高性能、耐久性箱梁混凝土配合比研制；”

**Comment by yaoshanli** [comment]
可以了，把获取到的run至为空 run.setText("", 0);   //清空标签

**Comment by Sayi** [comment]
恩，如果是替换文本的话，可以直接run.setText("需要替换的文本", 0);
