### ISSUE TITLE
WPS怎么设置图片的引用标签，没找到替换文字设置。

### ISSUE THREAD

**Issue by 1140989174** [Sayi/poi-tl#1071]

**Comment by xiying77** [comment]
可以去示例的模板文件里面找，选中图表设置后右边栏 属性->文本选项->可选文字->标题

**Comment by lg-hanyunfei** [comment]
> 可以去示例的模板文件里面找，选中图表设置后右边栏 属性->文本选项->可选文字->标题

你好，可以详细说明下吗?我并没有在wps中找到属性中包含文本选项

**Comment by xiying77** [comment]
> > 可以去示例的模板文件里面找，选中图表设置后右边栏 属性->文本选项->可选文字->标题
> 
> 你好，可以详细说明下吗?我并没有在wps中找到属性中包含文本选项

![Uploading 1701245506581.jpg…]()

**Comment by 1140989174** [comment]
最后没找到，用Office Tool Plus，下载了个office，地址：https://www.coolhub.top/archives/42
