### ISSUE TITLE
在通过程序动态创建表格对象时，创建的单元格的首行缩进无法消除

### ISSUE THREAD

**Issue by ncman** [Sayi/poi-tl#1079]
### Issue description
在通过程序动态创建表格对象时，其中单元格中创建的内容虽然通过withIndentFirstLineChars 或 setIndentFirstLineChars设置任何值（包括负值、0和正值），其首行缩进都是维持不变的，也消除不了。
### poi-tl version
1.12.1
### Minimal test code to reproduce the issue

```java
/**
*  创建单元格
* */
private CellRenderData createCellRenderData(String data, Boolean isBold) {
        Style.StyleBuilder styleBuilder = Style.builder();
        styleBuilder.buildFontSize(10).buildFontFamily("宋体");
        if (isBold) {
            styleBuilder.buildBold();
        }
        Style style = styleBuilder.build();

        TextRenderData textRenderData = new TextRenderData(data);
        textRenderData.setStyle(style);

        BorderStyle.Builder borderStyleBuilder = BorderStyle.builder();
        BorderStyle borderStyle = borderStyleBuilder
                .withSpace(0)
                .build();

        ParagraphRenderData graph = new ParagraphRenderData();
        ParagraphStyle.Builder paragraphStyleBuilder = ParagraphStyle.builder();
        ParagraphStyle paragraphStyle = paragraphStyleBuilder
                .withSpacingBeforeLines(0.0).withSpacingAfterLines(0.0)
                .withSpacingBefore(0.0).withSpacingAfter(0.0)
                .withIndentHangingChars(0.0)
                // 缩进-首行
//                .withIndentFirstLineChars(-0.01D)
                // 缩进-左侧
                .withIndentLeftChars(-0.2)
                .withIndentRightChars(0.0)
                .withAlign(ParagraphAlignment.LEFT)
                .build();
        paragraphStyle.setIndentFirstLineChars(-0.01D);
        graph.setParagraphStyle(paragraphStyle);
        graph.addText(textRenderData);

        CellRenderData rtn = Cells.of().addParagraph(graph).horizontalCenter().create();

        return rtn;
    }

/**
* 创建行单元
* */
private RowRenderData createRowRenderData(String bgColor, Boolean isFirstBold, Boolean isOtherBold, String str) {
        int index = 0;
        Rows.RowBuilder rowBuilder = Rows.of();
        rowBuilder.textColor("000000").bgColor(bgColor).center();

        CellRenderData cellRenderData = createCellRenderData(str, true);
        rowBuilder.addCell(cellRenderData);

        RowRenderData rtn = rowBuilder.create();

        return rtn;
    }

/**
* 创建表格对象
* */
private TableRenderData getTable() {
   .....
   Tables.TableBuilder tableBuilder = Tables.of(head1, head2).percentWidth("100%", cellWidthArray);
   ......
   RowRenderData rowBottom = createAllBoldRowRenderData("d7f9ed", "总计", "123456", "100.00", "123458", "100.00", "5566", "100.00");
        tableBuilder.addRow(rowBottom);

        TableRenderData rtn = tableBuilder.create();

      return rtn;
}

public void mian(){
   // 此处调用getTable()函数获得表格对象
}
```

**Comment by ncman** [comment]
经过这两天验证，发现只有把创建ParagraphRenderData实例的写法改一下，就能生效了。具体原理没有分析。见如下：
private CellRenderData createCellRenderData(String data, Boolean isBold) {
        Style.StyleBuilder styleBuilder = Style.builder();
        styleBuilder.buildFontSize(10).buildFontFamily("宋体");
        if (isBold) {
            styleBuilder.buildBold();
        }
        Style style = styleBuilder.build();

        TextRenderData textRenderData = new TextRenderData(data);
        textRenderData.setStyle(style);

        ParagraphStyle.Builder paragraphStyleBuilder = ParagraphStyle.builder();
        ParagraphStyle paragraphStyle = paragraphStyleBuilder
                // 缩进-首行
                .withIndentFirstLineChars(-0.01f)
                // 缩进-左侧
                .withIndentLeftChars(0f)
                .withAlign(ParagraphAlignment.LEFT)
                .build();
//        paragraphStyle.setBackgroundColor("0000ff");

       //  注意重要不同点在这里，使用Paragraphs类的of方法，然后通过create方法获得，上面的写法是new了一个ParagraphRenderData，这是区别之处。其二发现withIndentFirstLineChars和withIndentHangingChars不能同时使用，否则也无法解决去除首行缩进问题。其三注意：首行缩进值只能是-0.01f合适，多了或少了都呈现不正确。
        ParagraphRenderData graph = Paragraphs.of()
                .addText(textRenderData)
                .paraStyle(paragraphStyle)
                .create();

        CellRenderData rtn = Cells.of().addParagraph(graph)
//                .horizontalCenter()
                .create();

        return rtn;
    }

**Comment by modyuan** [comment]
遇到了一样的问题，后来发现把全局样式里，正文的段落属性中，首行缩进取消掉就好了。
![1712458720831](https://github.com/Sayi/poi-tl/assets/18202493/30fcdf9c-28f3-47ac-8409-bd479d44c73b)
