### ISSUE TITLE
数据为多个对象嵌套

### ISSUE THREAD

**Issue by txy1996** [Sayi/poi-tl#108]
当数据为多重list嵌套的时候如何进行遍历,现在我只能取到第一层list集合的数据

数据格式如下:
[{
	"stage": "阶段一名称",
	"info": "阶段一介绍",
	"shops": [{
		"sid": 1,
		"sname": "小龙坎",
		"stel": "商务联系人，李先生：138888888888",
		"products": [{
			"pid": 1,
			"pname": "蛋糕",
			"pnum": 2
		}, {
			"pid": 2,
			"pname": "汽水",
			"pnum": 3
		}]
	}, {
		"sid": 1,
		"sname": "小龙坎1",
		"stel": "商务联系人，李先生：138888888888",
		"products": [{
			"pid": 1,
			"pname": "蛋糕",
			"pnum": 2
		}, {
			"pid": 2,
			"pname": "汽水",
			"pnum": 3
		}]
	}]
}, {
	"stage": "阶段2名称",
	"info": "阶段2介绍"
}]

**Comment by Sayi** [comment]
目前只能放到第一层。

#101  有个pull-Request是针对这种情况的遍历。

下个版本会给个最终方案。

**Comment by txy1996** [comment]
嗯,好的,谢谢!

**Comment by Sayi** [comment]
数据循环渲染使用{{+var}}语法。

**Comment by txy1996** [comment]
谢谢
