### ISSUE TITLE
如何跳过不想被解析的标签

### ISSUE THREAD

**Issue by lilileleo** [Sayi/poi-tl#1084]
### {{?paragraphList}}
{{headerInfo}}
{{isPageBreak}}
{{levelChart}}
{{levelChartTitle}}
{{isPageBreak}}
{{devCmpTableTitle}}
{{#devCmpTable}}
{{/paragraphList}}
{{testTag}}

比如说我最后一个标签不想被解析就当普通文本
现在直接运行会报错
![1698309049822](https://github.com/Sayi/poi-tl/assets/55476458/0cd4c89c-7909-4cc7-8615-bd29d143ffb4)

**Comment by lilileleo** [comment]
我有个备用方法就是替换标签前后缀，但想问问还有什么别的方法

**Comment by Sayi** [comment]
https://deepoove.com/poi-tl/#_%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86
