### ISSUE TITLE
关于MultipleRowTableRenderPolicy在获取行数量时的问题

### ISSUE THREAD

**Issue by 2624621001** [Sayi/poi-tl#1087]
在MultipleRowTableRenderPolicy的getAllTemplateRow函数里
`String text = ((XWPFTableRow)rows.get(startIndex)).getCell(0).getText();
        Matcher matcher = Pattern.compile("\\$\\([0-9]+\\)").matcher(text);`
有这么一段代码用于获取行配置，但真实用户使用中可能是并不是从0开始的cell 建议构建MultipleRowTableRenderPolicy对象时传入一个cellnumber 要么就在{{}}中去识别

**Comment by Sayi** [comment]
welcome pr.
