### ISSUE TITLE
poi-tl错误

### ISSUE THREAD

**Issue by g2plus** [Sayi/poi-tl#1088]
### Issue description
java.lang.NoSuchMethodError: org.apache.poi.xwpf.usermodel.XWPFDocument.getDocComments()Lorg/apache/poi/xwpf/usermodel/XWPFComments;
### poi-tl version
1.12.1
### Minimal test code to reproduce the issue

```java
1.8——201
```

**Comment by Sayi** [comment]
check dependency.
