### ISSUE TITLE
junit 例子 storyexample中 追加了个表格展示异常

### ISSUE THREAD

**Issue by lilianbiao** [Sayi/poi-tl#109]
我在segment.docx新增{{table}}之后，展示异常如下图：
![image](https://user-images.githubusercontent.com/25141719/44456061-373b2a00-a632-11e8-9f71-343e1b9af223.png)
但是我复制 table.docx 然后 替换segment.docx,然后修改 模板内容增加{{content}}就正常了。
如下图：
![image](https://user-images.githubusercontent.com/25141719/44456112-589c1600-a632-11e8-8769-4dd3b99054c5.png)
然后我新建了个word 使用的是segment.docx模板，发现展示也是问题，请问是什么原因？

**Comment by Sayi** [comment]
直接给个单元测试吧

**Comment by lilianbiao** [comment]
谢谢大佬啦。
[story.docx](https://github.com/Sayi/poi-tl/files/2322214/story.docx)
[segment.docx](https://github.com/Sayi/poi-tl/files/2322215/segment.docx)

[issue109 .zip](https://github.com/Sayi/poi-tl/files/2322219/issue109.zip)
[out_story.docx](https://github.com/Sayi/poi-tl/files/2322221/out_story.docx)

**Comment by Sayi** [comment]
segment.docx里面应用了表格的样式~换个样式就好了
