### ISSUE TITLE
柱状图如何设置动态颜色添加基准线

### ISSUE THREAD

**Issue by sinosofti** [Sayi/poi-tl#1090]
### Issue description
如图 怎么设置这种动态颜色的柱状图 还有图中的基准线是否能实现
![image](https://github.com/Sayi/poi-tl/assets/38282416/77757424-2203-4d5e-a5ab-696ec451c7c3)

### poi-tl version
依赖为1.10.x版本
### Minimal test code to reproduce the issue

```java
jdk1.8
```

**Comment by Sayi** [comment]
auto closed.
