### ISSUE TITLE
使用区块对后总是会有空白段落，导致表格连接不起来

### ISSUE THREAD

**Issue by maguoliang888** [Sayi/poi-tl#1092]
### Issue description
使用区块对后总是会有空白段落，导致表格连接不起来。图1为模板出错地方。图2为实际出错样式

### poi-tl version
1.10.5

### Minimal test code to reproduce the issue

```java

```
### Minimal Docx template file

![image](https://github.com/Sayi/poi-tl/assets/67767897/41b096c3-4e7c-48f6-93c5-aace9e84e75f)
![image](https://github.com/Sayi/poi-tl/assets/67767897/1e6c4c37-6cd4-4857-8e45-ed94305bbf64)

**Comment by sinosofti** [comment]
这不是word问题吗 加个换行跳过段落试试

**Comment by cuitz** [comment]
#928 当bool区块对跨页时有此问题。
