### ISSUE TITLE
你好我遇到一个列循环的问题,代码用的就是你LoopColumnTableRenderPolicyTest中的代码

### ISSUE THREAD

**Issue by fredeason** [Sayi/poi-tl#1093]
![image](https://github.com/Sayi/poi-tl/assets/19574910/c9727c9d-74d0-4271-8c73-b74f4f551926)
以上是我的模板我需要列循环的是中间的两行,但是运行老是报错:
com.deepoove.poi.exception.RenderException: HackLoopTable for {{goods2}}error: null
但是问题是我如果删除1和4行他就能正常列循环,实在搞不懂是哪里的问题了,能否给我解答下
下面是主要的代码,组装数据用的是源码中的没改动
![image](https://github.com/Sayi/poi-tl/assets/19574910/2468f2ba-2aa7-4e85-bc0b-4252b13d8746)

难道要进行列循环的上下不能有已经进行过分列的行吗,,我把1和4行合并了单元格变成单行之后也是可以的,就是最终循环列了之后1和4行也会被等分列,但是这不是我需要的

**Comment by Sayi** [comment]
auto closed.
