### ISSUE TITLE
按照版本poi-tl 1.10.0 实现的自定义解析器，但是发现解析出来的数据 表格是连在一起的，然后文字是在最下面，想做到的效果就是一个文本框一个表格

### ISSUE THREAD

**Issue by JionDack** [Sayi/poi-tl#1096]
## 按照版本poi-tl 1.10.0 实现的自定义解析器，但是发现解析出来的数据 表格是连在一起的，然后文字是在最下面，想做到的效果就是一个文本框一个表格
package com.nine.rivers.jydd.houtai.modular.report.render;

import cn.hutool.core.util.StrUtil;
import com.deepoove.poi.XWPFTemplate;
import com.deepoove.poi.config.Configure;
import com.deepoove.poi.data.ChartMultiSeriesRenderData;
import com.deepoove.poi.data.TableRenderData;
import com.deepoove.poi.policy.RenderPolicy;
import com.deepoove.poi.policy.TableRenderPolicy;
import com.deepoove.poi.policy.TextRenderPolicy;
import com.deepoove.poi.policy.reference.MultiSeriesChartTemplateRenderPolicy;
import com.deepoove.poi.resolver.DefaultElementTemplateFactory;
import com.deepoove.poi.template.ElementTemplate;
import com.deepoove.poi.template.run.RunTemplate;
import com.deepoove.poi.util.StyleUtils;
import com.deepoove.poi.xwpf.NiceXWPFDocument;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.xwpf.usermodel.BreakType;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.apache.poi.xwpf.usermodel.XWPFTable;

import java.util.Iterator;
import java.util.List;

/**
 * 自定义渲染器
 *
 * @author 
 * @date 2023/12/4 14:24
 */
@Slf4j
public class ListDataRenderPolicy implements RenderPolicy {

    /**
     * 文字解析器
     */
    private final TextRenderPolicy textRenderPolicy = new TextRenderPolicy();

    /**
     * table渲染器
     */
    private final TableRenderPolicy tableRenderPolicy = new TableRenderPolicy();

    /**
     * 图表解析器（有问题）
     */
    private final MultiSeriesChartTemplateRenderPolicy multiSeriesChartTemplateRenderPolicy = new MultiSeriesChartTemplateRenderPolicy();

    /**
     *
     */
    private final DefaultElementTemplateFactory defaultElementTemplateFactory = new DefaultElementTemplateFactory();

    @SuppressWarnings("unchecked")
    @Override
    public void render(ElementTemplate eleTemplate, Object dataList, XWPFTemplate template) {
        // 拿到需要的RunTemplate
        RunTemplate runTemplate = (RunTemplate) eleTemplate;
        // 获取执行器
        XWPFRun run = runTemplate.getRun();
        // 判断是否是迭代器
        if (!(dataList instanceof Iterable)) {
            log.warn("Error render {}, should be Iterable:{}", runTemplate.getTagName(), dataList.getClass());
            return;
        }
        // 强制转换
        Iterable<Object> list = (Iterable<Object>) dataList;

        Iterator<Object> iterator = list.iterator();
        RenderPolicy policy = null;
        while (iterator.hasNext()) {
            Object next = iterator.next();
            policy = this.getPolicy(next);

            if (null == policy) {
                log.warn("cannot find render policy: [" + runTemplate.getTagName() + "]");
                return;
            }

            XWPFRun insertNewRun = ((XWPFParagraph) run.getParent()).insertNewRun(runTemplate.getRunPos());

            StyleUtils.styleRun(insertNewRun, run);

            RunTemplate createRunTemplate = defaultElementTemplateFactory.createRunTemplate(
                    Configure.createDefault(), StrUtil.uuid() + runTemplate.getTagName(),
                    insertNewRun);

            policy.render(createRunTemplate, next, template);

            // 使用poi api,需要自己处理数据之间的格式
            NiceXWPFDocument xwpfDocument = template.getXWPFDocument();

            List<XWPFTable> allTables = xwpfDocument.getAllTables();

            insertNewRun.addBreak(BreakType.PAGE);// 数据之间换行
            insertNewRun.addBreak();// 数据之间换行
            insertNewRun.addBreak();// 数据之间换行
            insertNewRun.addBreak();// 数据之间换行
            insertNewRun.addBreak();// 数据之间换行

        }
        run.setText("", 0);
    }

    /**
     * 获取对应的解析器
     *
     * @param data 数据类型
     * @return RenderPolicy
     */
    private RenderPolicy getPolicy(Object data) {
        if (data instanceof TableRenderData) {
            return tableRenderPolicy;
        } else if (data instanceof ChartMultiSeriesRenderData) {
            return multiSeriesChartTemplateRenderPolicy;
        } else if (data instanceof Iterable) {
            return new ListDataRenderPolicy();
        } else {
            return textRenderPolicy;
        }
    }
}

**Comment by JionDack** [comment]
![1701745653239](https://github.com/Sayi/poi-tl/assets/86410861/72287de7-fd19-460e-9ec9-0ad632ae3edb)
这个是输出的样式图

**Comment by Sayi** [comment]
需要自己调整插入顺序
