### ISSUE TITLE
数据集合循环生成一个word文档

### ISSUE THREAD

**Issue by wpcfree** [Sayi/poi-tl#11]
现在我有5个数据的集合，定义好一个模板，利用循环能够将五个数据生成到一个word文件里边不？

**Comment by Sayi** [comment]
@wpcfree 

抱歉，暂时不支持一个模板替换成组合数据集。在下一版本考虑直接支持此特性。

> 在我们系统中，有些复杂不通用的逻辑是通过自定义策略实现的。
> 通过自定义模板，注册到自定义的数据处理策略，在策略中，对数据集进行替换遍历操作，替换模板。


如何自定义策略：
[自定义模板和数据策略](https://github.com/Sayi/poi-tl/wiki/1.%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AD%96%E7%95%A5renderpolicy)

参见代码示例：
[%语法插件](https://github.com/Sayi/poi-tl/wiki/3.%25%E8%AF%AD%E6%B3%95%E6%8F%92%E4%BB%B6%E4%B9%8B%E6%9C%89%E8%B6%A3%E7%9A%84%E6%95%B0%E5%AD%A6%E8%A1%A8%E8%BE%BE%E5%BC%8F)

**Comment by wpcfree** [comment]
希望尽快添加对集合的支持！
按你所说，如果通过自定义模板处理的话，貌似只能处理某一标签对应的数据，如何带上我建的word模板的样式呀？

**Comment by wpcfree** [comment]
我需要一个模板嵌套

**Comment by Sayi** [comment]
@wpcfree 
场景是希望有一套自带样式的组合模板对应一套组合数据集合吗？比如：
```
<start>
{{text1}}
{{@image}}
{{text2}}
<end>
```
对应到数据集合：
```
[
  {
  "text1 str",
  new PictureRenderData(),
  "text2 str"
  },
  {
  "text1 str",
  new PictureRenderData(),
  "text2 str"
  }
]
```

**Comment by wpcfree** [comment]
对的，就是这个意思，这是我自定义的模板策略，合理不？
`public class MyRenderPolicy implements RenderPolicy {

    @Override
    public void render(ElementTemplate elementTemplate, Object renderData, XWPFTemplate xwpfTemplate) {
        RunTemplate runTemplate = (RunTemplate) elementTemplate;
        XWPFRun run = runTemplate.getRun();

        if (null != renderData && renderData instanceof List) {
            XWPFTemplate doc = XWPFTemplate.compile("src/test/resources/title.docx");
            List<Object> titles = (List<Object>) renderData;
            for (Object title : titles) {
                if (title instanceof Map) {
                    doc.render((Map<String, Object>) title);
                }
            }
            run.setText(doc.);
        }
    }

}`

**Comment by SnailFighter** [comment]
`我最后是这么做的，把那些集合中的数据，作为整体，添加到word中的{{*name}}，把集合中的数据按照自己想展现的位置，顺序写入到NumbericRenderData中。`
 /**
     *
     * @param data  要包装的参数,元素个数总是偶素存在
     *              key为整形数字，要显示的内容有显示顺序，key越小，位置越靠前，value为字符串数组，
     *              包含第一个值中文翻译，第二个值为具体的数据值,以此类推
     *              如果想把某些数据写入同一行，可以把这些数据按顺序写在字符串数组中
     * @param style 字体设置
     * @return
     */
    public static NumbericRenderData wapData(Style style,List<Map<Integer,String[]>> data){
        if(null == data){
            return null;
        }
        List<TextRenderData> textRenderDataList = new ArrayList<TextRenderData>();
        Map<Integer,String[]> content = new TreeMap<Integer,String[]>(new Comparator<Integer>() {
            @Override
            public int compare(Integer o1, Integer o2) {
                return o1.compareTo(o2);
            }
        });
        content.putAll((Map<? extends Integer, ? extends String[]>) data);
        int dataSize = content.size();
        for(int i=0;i<dataSize;i++){
            String[] params = content.get(i);
            int arrLength = params.length;
            StringBuilder sb = new StringBuilder();
           for(int j=0;j<arrLength;j++) {
               if(j>0&&j%2==0){
                   sb.append("    ").append(params[j]);
               }else {
                   sb.append(params[j]);
               }
           }

            TextRenderData textRenderData = new TextRenderData();
            textRenderData.setStyle(style);
            textRenderData.setText(sb.toString());
            textRenderDataList.add(textRenderData);
        }
        return new NumbericRenderData(Pair.of(STNumberFormat.LOWER_ROMAN, ""),textRenderDataList);
    }

**Comment by Sayi** [comment]
@wpcfree 这样自定义策略是错误的，不能再生成XWPFTemplate对象。

目前版本需要代码处理每个数据的插入，通过NiceXWPFDocument的api插入文字、图片、表格等。
```java
NiceXWPFDocument xwpfDocument = xwpfTemplate.getXWPFDocument().
```

**Comment by Sayi** [comment]
@SnailFighter  你的模板数据是字符串列表，所以你处理的方式是可行的。

**Comment by Sayi** [comment]
#### 下面代码自定义的模板策略，可以将一个模板标签替换成List数据集合。
#### 可以基于这个类进行修改，自定义处理数据之间的样式，通过TextRenderData设置文本样式等。
```java
package com.deepoove.poi.tl.mypolicy;

import java.util.Iterator;

import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

import com.deepoove.poi.XWPFTemplate;
import com.deepoove.poi.data.PictureRenderData;
import com.deepoove.poi.policy.PictureRenderPolicy;
import com.deepoove.poi.policy.RenderPolicy;
import com.deepoove.poi.policy.TextRenderPolicy;
import com.deepoove.poi.resolver.TemplateFactory;
import com.deepoove.poi.template.ElementTemplate;
import com.deepoove.poi.template.run.RunTemplate;
import com.deepoove.poi.util.StyleUtils;

public class ListDataRenderPolicy implements RenderPolicy {
    
    final PictureRenderPolicy  pictureRenderPolicy = new PictureRenderPolicy();
    final TextRenderPolicy  textRenderPolicy = new TextRenderPolicy();

    @SuppressWarnings({ "unchecked" })
    @Override
    public void render(ElementTemplate eleTemplate, Object dataList, XWPFTemplate template) {
        RunTemplate runTemplate = (RunTemplate) eleTemplate;
        XWPFRun run = runTemplate.getRun();

        if (dataList == null || !(dataList instanceof Iterable)) {
            logger.warn("Error render {}, should be Iterable:{}", runTemplate.getTagName(),
                    dataList.getClass());
            return;
        }

        Iterable<Object> list = (Iterable<Object>) dataList;
        Iterator<Object> iterator = list.iterator();
        RenderPolicy policy = null;
        while (iterator.hasNext()) {
            Object next = iterator.next();
            policy = getPolicy(next);
            if (null == policy) {
                logger.warn("cannot find render policy: [" + runTemplate.getTagName() + "]");
                return;
            }
            XWPFRun insertNewRun = ((XWPFParagraph) run.getParent()).insertNewRun(runTemplate.getRunPos());
            StyleUtils.styleRun(insertNewRun, run);
            RunTemplate createRunTemplate = TemplateFactory.createRunTemplate(
                    runTemplate.getSign() + runTemplate.getTagName(),
                    template.getConfig().getGramerChars(), insertNewRun);
            
            policy.render(createRunTemplate, next, template);

            // 使用poi api,需要自己处理数据之间的格式
            // NiceXWPFDocument xwpfDocument = template.getXWPFDocument();
             insertNewRun.addBreak();//数据之间换行
        }
        run.setText("", 0);
    }

    private RenderPolicy getPolicy(Object data) {
        if (data instanceof PictureRenderData) {
            return pictureRenderPolicy;
        } else if (data instanceof Iterable){
            return new ListDataRenderPolicy();
        }else{
            return textRenderPolicy;
        }
    }

}

```

#### Testcase，模板数据支持List和List\<List\>
```java
@Test
public void testListData() throws Exception {
    
    Map<String, Object> datas = new HashMap<String, Object>(){{
        
        final List<Object> list = new ArrayList<Object>(){{
            add("ver 0.0.3");
            add(new PictureRenderData(100, 120, "src/test/resources/logo.png"));
            add(new TextRenderData("9d55b8", "Deeply in love with the things you love, just deepoove."));
            add("ver 0.0.4");
            add(new PictureRenderData(100, 120, "src/test/resources/logo.png"));
        }};
        List<Object> list2 = new ArrayList<Object>(){{
            add(list);
            add(list);
        }};
        
        put("website", list2);
    }};
    
    
    XWPFTemplate template = XWPFTemplate.compile("src/test/resources/PB.docx");
    /指定标签-策略
    template.registerPolicy("website", new ListDataRenderPolicy());
    
    template.render(datas);

    FileOutputStream out = new FileOutputStream("out_PB.docx");
    template.write(out);
    out.flush();
    out.close();
    template.close();
}
```

**Comment by wpcfree** [comment]
@Sayi 上边代码利用递归list也能够解决我的问题，但是我想让list里的不同数据需要有不同的样式，看看还有什么还方法推荐吗？我想的是在内层list不需要递归了，去读取另一个模板的样式去渲染好数据再写回到外层模板中？这样的思想可行吗？

**Comment by wpcfree** [comment]
@Sayi 如果能设置类似于下边的模板即可满足我的需求了
```
<start>
{{paper}}
<list>
{{title}}
</list>
<end>
```
不知道是否能满足？
还有一种思路就是首先外层是一个paper的模板word，可以设置试卷的样式，内层还有一个试题的集合，需要一个title模板word，获取了title的模板填充数据后写到paper的模板里去。

**Comment by Sayi** [comment]
1. 这样的模板目前不支持，嵌套循环组合模板，其实还需要开发一套标签库(Tag Library)支持
2. 我看你的需求好像是文字样式，POI提供了通过代码设置样式的方法，可以满足大部分文字样式的需求
[参见Style.java](https://github.com/Sayi/poi-tl/blob/master/src/main/java/com/deepoove/poi/data/style/Style.java)
[如何设置word字体](https://github.com/Sayi/poi-tl/wiki/7.Java%E5%8A%A0%E8%BD%BD%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91%E5%AD%97%E4%BD%93)
3. 模板样式是继承模板标签的，你说的内层模板写到外层模板就无法继承，还是需要通过上面的方法通过代码设置样式的。

目前你可以试试方法2能不能满足。

**Comment by Sayi** [comment]
1.3.0 版本已支持。
