### ISSUE TITLE
想在模板中增加js脚本

### ISSUE THREAD

**Issue by liugangfeng** [Sayi/poi-tl#1100]
### Issue description
你好：{{%add(hello)}}  TemplateResolver 解析不了，导致 RenderPolicy调用不到。
### poi-tl version
1.12.0
### Minimal test code to reproduce the issue

```java

```

**Comment by Sayi** [comment]
you can try to parse the tag and then customize the rendering plugin, the following points may be useful:
- Configure.elementTemplateFactory
- Configure.grammerRegex
- Define render policy plugin

[Configure.grammerRegex](https://deepoove.com/poi-tl/#_%E6%A0%87%E7%AD%BE%E6%AD%A3%E5%88%99)
