### ISSUE TITLE
插入自定义附件无法打开

### ISSUE THREAD

**Issue by gudeying** [Sayi/poi-tl#1106]
com.deepoove.poi.policy.AttachmentRenderPolicy内置了xlsx和docx的支持，参考该类插入其他附件，word内无法打开附件，
提示“不能启动此对象的源应用程序”。转为xml格式和手动添加附件对比，发现 <pkg:binaryData>里面的内容不一样，将手动添加的内容复制替换到poi-tl渲染的文件中，附件可以正常打开
![image](https://github.com/Sayi/poi-tl/assets/35475134/03238a47-d785-4858-ba94-ce3c0483f4f4)
请问NiceXWPFDocument#addEmbeddData(byte[], java.lang.String, java.lang.String) 中embeddData有什么特殊处理吗，比如是否要添加文件格式信息。多谢。

**Comment by Sayi** [comment]
auto closed.
