### ISSUE TITLE
根据条件动态删除表格行

### ISSUE THREAD

**Issue by fredeason** [Sayi/poi-tl#1108]
![image](https://github.com/Sayi/poi-tl/assets/19574910/098bd5bd-e18c-47bd-ba9e-fb4a8c14b4f7)

我的模板中就是这样的取值,这个roughlyDesc有值的情况下一切正常,但是我想这个值如果为null空的情况下这一行就不显示了,但是没给实现,我模板中写的是{{roughlyDesc}}

**Comment by hmycl0820** [comment]
区块对应该可以实现

**Comment by catlvsuger** [comment]
自定义个删除行的策略就行了
/**
 * 表格中，是否要删除当前行 isRemove true 删除，
 * @author catlvsuger
 * @version 
 */
@Slf4j
public class RemoveTableRowPolicy implements RenderPolicy {

    private boolean isRemove;

    public RemoveTableRowPolicy() {
        this(false);
    }

    public RemoveTableRowPolicy(boolean isRemove) {
        this.isRemove = isRemove;
    }

    @Override
    public void render(ElementTemplate eleTemplate, Object data, XWPFTemplate xwpfTemplate) {
        RunTemplate runTemplate = (RunTemplate)eleTemplate;
        XWPFRun run = runTemplate.getRun();
        if(!this.isRemove) {
            TextRenderPolicy.Helper.renderTextRun(run, data);
//            clearPlaceholder(run);
        }else if (!TableTools.isInsideTable(run)) {
            throw new IllegalStateException("The template tag " + runTemplate.getSource() + " must be inside a table");
        } else {
            XWPFTableCell tagCell = (XWPFTableCell)((XWPFParagraph)run.getParent()).getBody();
            XWPFTableRow tableRow = tagCell.getTableRow();
            XWPFTable table = tableRow.getTable();
            int templateRowIndex = TableUtil.getRowIndex(table, tableRow);
            table.removeRow(templateRowIndex);
        }
    }
}   

 /**
     * 获取单元格所在行下标
     *
     * @param table
     * @param row
     * @return
     */
    public static int getRowIndex(XWPFTable table, XWPFTableRow row) {
        List<XWPFTableRow> rows = table.getRows();
        return rows.indexOf(row);
    }
