### ISSUE TITLE
填充带有括号的标签，填充不上。

### ISSUE THREAD

**Issue by doublez-ten** [Sayi/poi-tl#1110]
### Issue description
填充带有括号的标签，填充不上。例如{{填充测试（括号文本）}}，这种形式填充不了数据。
### poi-tl version
1.12.0

**Comment by 955-955** [comment]
![image](https://github.com/Sayi/poi-tl/assets/103930937/dc5f8b54-7b4c-4a29-b9fc-29b814103d43)
![image](https://github.com/Sayi/poi-tl/assets/103930937/3554db41-f2d6-44c1-ae19-f5bf0c781efe)

应该是你代码的问题，亲测可以正常导出{{内容(内容)}}这种格式的文本

**Comment by doublez-ten** [comment]
> ![image](https://private-user-images.githubusercontent.com/103930937/295488100-dc5f8b54-7b4c-4a29-b9fc-29b814103d43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Mzc1OTAsIm5iZiI6MTcwNDkzNzI5MCwicGF0aCI6Ii8xMDM5MzA5MzcvMjk1NDg4MTAwLWRjNWY4YjU0LTdiNGMtNGEyOS1iOWZjLTI5YjgxNDEwM2Q0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwMTQxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NGJjOWYwNjBiYjAxZTA2MjkyNzI3M2M4NjVkNzk2YTlmNzc5YWMwZDFiNDU2YzMyY2E1Zjc3ZWEyNjRkNTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3eeeriwzKaDeWqu2sa0TqCZ7dWvjxQZj4foWBpQcRh4) ![image](https://private-user-images.githubusercontent.com/103930937/295488382-3554db41-f2d6-44c1-ae19-f5bf0c781efe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5Mzc1OTAsIm5iZiI6MTcwNDkzNzI5MCwicGF0aCI6Ii8xMDM5MzA5MzcvMjk1NDg4MzgyLTM1NTRkYjQxLWYyZDYtNDRjMS1hZTE5LWY1YmYwYzc4MWVmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwMTQxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGM2MDgyODlhZjZkNDc4Mzc2YTRmMTkwNmQ5NTkzMzQxZDdiYmE3YjQyNTNiNzM4ZGVlNzk5NmUwYjE2YzQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RjdjtmQ3XldxaBNIaVMdAYe1QtHYDoCG0tmaiZTLQMo)
> 
> 应该是你代码的问题，亲测可以正常导出{{内容(内容)}}这种格式的文本

是键中带有括号，不是值带有括号。
https://github.com/Sayi/poi-tl/issues/1110#issuecomment-1884340558

**Comment by hmycl0820** [comment]
键可以自定义，不带括号就好了呀

**Comment by Sayi** [comment]
https://deepoove.com/poi-tl/#_%E6%A0%87%E7%AD%BE%E6%AD%A3%E5%88%99

**Comment by qqilin1213** [comment]
文本中有包含其他符号，也是改不来的
key为xxx-xx，识别不了

**Comment by qqilin1213** [comment]
> https://deepoove.com/poi-tl/#_%E6%A0%87%E7%AD%BE%E6%AD%A3%E5%88%99

想问一下。替换文本的key只能是纯字或者中午吗，有一些需要一些参数，key为"xxx-aa-bb"用'-'来区分名称和参数，我试了1.12.2版本的是识别不了的

**Comment by doublez-ten** [comment]
> > https://deepoove.com/poi-tl/#_%E6%A0%87%E7%AD%BE%E6%AD%A3%E5%88%99
> 
> 想问一下。替换文本的key只能是纯字或者中文吗，有一些需要一些参数，key为"xxx-aa-bb"用'-'来区分名称和参数，我试了1.12.2版本的是识别不了的

替换文本有部分字符会被过滤，‘-’被过滤了，识别不了。

**Comment by doublez-ten** [comment]
> > https://deepoove.com/poi-tl/#_%E6%A0%87%E7%AD%BE%E6%AD%A3%E5%88%99
> 
> 想问一下。替换文本的key只能是纯字或者中文吗，有一些需要一些参数，key为"xxx-aa-bb"用'-'来区分名称和参数，我试了1.12.2版本的是识别不了的

允许任意字符：
```java
ConfigureBuilder builder = Configure.builder();
builder.buildGrammerRegex(RegexUtils.createGeneral("{{", "}}"));
```
