### ISSUE TITLE
LoopRowTableRenderPolicy插件中SpringEL的使用问题

### ISSUE THREAD

**Issue by Bingo330** [Sayi/poi-tl#1115]
使用LoopRowTableRenderPolicy进行表格循环的时候。使用SpringEL对时间格式进行格式化。
[{new java.text.SimpleDateFormat('MMM dd, yyyy', new java.util.Locale("en")).format(createTime)}]
数据可以正常导出但导出结果。左右两边带有[].

**Comment by cactuer** [comment]
我也遇到这个问题了，期待作者回复😂

**Comment by cactuer** [comment]
@Bingo330 我遇到的问题已经解决了，我觉得主要有2个注意点：
1.要开启springEl表达式builder().useSpringEL(true)
2.要注意缓存

这是我使用的表达式，仅供参考
[new java.text.SimpleDateFormat('yyyy-MM-dd HH:mm:ss').format(endTime)]

**Comment by chengda1992** [comment]
确实是可以的，但是出现个问题，应该怎么解决，模板是这个样子的，
![image](https://github.com/Sayi/poi-tl/assets/42691983/65174e12-ad73-4c0e-825a-c3f579798c15)
生成后是这个样子的
![image](https://github.com/Sayi/poi-tl/assets/42691983/e53ce3d7-b903-454d-8004-a778d5e32bf1)

**Comment by cactuer** [comment]
套进去就可以了
[new java.text.SimpleDateFormat('yyyy-MM-dd HH:mm:ss').format(transactionDate)] 

@chengda1992 你试一下

**Comment by chengda1992** [comment]
@cactuer 这个出来了，但是列宽怎么调整

**Comment by cactuer** [comment]
@chengda1992 列宽直接在原有模版上调整就行了

**Comment by Sayi** [comment]
正解：列宽直接在原有模版上调整。
