### ISSUE TITLE
请问如何实现表格多行循环

### ISSUE THREAD

**Issue by Strong-Gavin** [Sayi/poi-tl#1118]
我有一个需求，是每个数据占用2行表格，第一行显示图片，第二行显示描述；目前表格循环都是单行，是否能支持任意多行循环。类似图中这种，每2行渲染一个数据
![image](https://github.com/Sayi/poi-tl/assets/17334234/367b6b48-112b-4e72-8861-2285a459d246)

**Comment by Sayi** [comment]
#784
