### ISSUE TITLE
Markdown tag inside block pairs is not working

### ISSUE THREAD

**Issue by raccarva** [Sayi/poi-tl#1119]
I am trying to expand a markdown tag inside block pairs but the tag is being expanded to the name of the MarkdownRenderData object.
In the example below, I expand a regular text tag (map item contains tag name / string text) and then a markdown tag (map item contains tag name / MarkdownRenderData object).
The original code is a bit complex so I avoid pasting it here. In case we need it, I will create a small test program to demonstrate the issue.
Regards.

### poi-tl version
    implementation group: 'com.deepoove', name: 'poi-tl', version: '1.12.1'
    implementation group: 'com.deepoove', name:'poi-tl-plugin-markdown', version: '1.0.3'

### Minimal test code to reproduce the issue

```java


```
### Minimal Docx template file
{{?Tasks}}
{{tskTitle}}
{{tkdDescr}}
{{/Tasks}}

Output of test for a list of two items:

FLIGHT CONTROL MECHANICAL CHARACTERISTICS
com.deepoove.poi.plugin.markdown.MarkdownRenderData@72f4d746
BLABLABLA
com.deepoove.poi.plugin.markdown.MarkdownRenderData@1321f113

**Comment by Sayi** [comment]
[poi-tl#plugin-markdown](https://deepoove.com/poi-tl/#plugin-markdown)

Should bind Plugin:
```java
Configure config = Configure.builder().bind("md", new MarkdownRenderPolicy()).build();
```

**Comment by raccarva** [comment]
Never mind. It was my mistake since I did not call ConfigureBuilder.bind to the labels which are inside the block pairs. I changed that and now the markdown code is being correctly expanded within the block pairs.
