### ISSUE TITLE
如何渲染模板中的公式

### ISSUE THREAD

**Issue by tonggege001** [Sayi/poi-tl#1128]
### 假设模板长这样：
这是一个文章标题
测试替换普通文本： {{text}}
测试替换公式： {{equation}}

text可以直接传入String就能替换，但是equation公式该怎么实现？目前想法是传入Latex（或者markdown）的公式格式，比如传入 \sum_{i = 1}^{n} a_i ，就能渲染成对应的word格式的公式 $\sum^{n}_{i = 1} a_i$ 。

问一下题主大大，有没有这种功能呀？

**Comment by Sayi** [comment]
请参考[官方文档：常见问题](https://deepoove.com/poi-tl/#_vip%E4%B8%93%E5%B1%9E%E6%9C%8D%E5%8A%A1)
