### ISSUE TITLE
怎么在同一个文档内重复插入很多表格哇

### ISSUE THREAD

**Issue by huwqGalaxy** [Sayi/poi-tl#113]
怎么在同一个文档内重复插入很多表格哇

**Comment by hustxq** [comment]
多写几个#标签就行吧，例如#table1,#table2...

**Comment by hustxq** [comment]
@huwqGalaxy  多写几个#标签就行吧，例如#table1,#table2...

**Comment by huwqGalaxy** [comment]
现在就是这么解决的😂
还想了先动态生成模版多条标签再读取这个标签不过感觉还是不够

**Comment by Sayi** [comment]
[文档模板试试](http://deepoove.com/poi-tl/#_%E6%96%87%E6%A1%A3%E6%A8%A1%E6%9D%BFvar)

**Comment by funyule** [comment]
@Sayi 

![image](https://user-images.githubusercontent.com/12372048/48118746-2c467c00-e2a8-11e8-8b78-adad1c033579.png)
 子模板里这么玩，貌似进不去

PS:UP主弄个QQ群交流下撒
