### ISSUE TITLE
1.10版本在结构体中渲染时出现问题

### ISSUE THREAD

**Issue by 66pi** [Sayi/poi-tl#1132]
版本号: 1.10
在结构体中渲染list数据时出现问题
{{?projInfos}}
  {{projNum}} {{projName}}
  //下方是表格,这里就不作过多描述

{{/projInfos}}
上面是模版word中出问题的部分, (结构体大致内容)
其中projInfos是个list, 元素是map, 遍历时第一个map中的{{projNum}} {{projName}}没有遍历出来,但是除了第一个其它的都遍历了一遍第一个map的{{projNum}} {{projName}}的内容

//大概的遍历结果如下
--结构体头

  //正常这一行应该是projNum1 projName1,但是现在没有,下面的表格内容是正常的
  表格内容
   
  projNum1 projName1 //这里正常情况下,不应该有projNum1 projName1, 下方内容都正常
  projNum2 projName2
  表格内容

  projNum1 projName1//这里正常情况下,不应该有projNum1 projName1  下方内容都正常
  projNum3 projName3
  表格内容

  projNum1 projName1//这里正常情况下,不应该有projNum1 projName1 下方内容都正常
  projNum4 projName4
  表格内容

--结构体尾部

希望可以帮忙看一下是不是bug,现在项目中出现了问题,看了源码也没看出来什么

**Comment by 66pi** [comment]
这是模版,出问题的地方是projInfos
[fundExport.docx](https://github.com/Sayi/poi-tl/files/14471464/fundExport.docx)

**Comment by 66pi** [comment]
这是渲染结果的图片,第一张是第一行没有渲染出projNum和projName
![iwEdAqNwbmcDAQTRBgYF0QLlBrAZ054YqQtlMgXSJ5p1MeICB9ImP2XWCAAJomltCgAL0gAA2fU png_720x720q90](https://github.com/Sayi/poi-tl/assets/40259436/18f01be6-969d-44fa-966d-f5537ae6c54c)
第二张是渲染第二个和第三个时把第一个的projNum和projName也渲染了一遍
![iwEeAqNwbmcDAQTRAvwF0QLABrAwN35wBl2WvgXSJ5p1MeIAB9ImP2XWCAAJomltCgAL0XD1 png_720x720q90](https://github.com/Sayi/poi-tl/assets/40259436/671553ef-08f1-4d24-bfc0-50d5467448cc)

**Comment by 66pi** [comment]
第一张是渲染第一个元素时没有渲染出projNum projName,第二张是在渲染除第一行外把第一行的projNum projName都渲染了一遍
![iwEeAqNwbmcDAQTRAvwF0QLABrAwN35wBl2WvgXSJ5p1MeIAB9ImP2XWCAAJomltCgAL0XD1 png_720x720q90](https://github.com/Sayi/poi-tl/assets/40259436/0c61a6e6-d388-4d13-ba91-49020815f008)
![iwEdAqNwbmcDAQTRBgYF0QLlBrAZ054YqQtlMgXSJ5p1MeICB9ImP2XWCAAJomltCgAL0gAA2fU png_720x720q90](https://github.com/Sayi/poi-tl/assets/40259436/7b2b703c-ec1a-40d6-9e24-7430a13f56ec)

**Comment by 66pi** [comment]
第一张是渲染第一个元素时没有渲染出projNum projName,第二张是在渲染除第一行外把第一行的projNum projName都渲染了一遍
![43571cbbf3549dff9c4a60484b51be0f503d55c7a8a8efd9825e7fca6f091c82QzpcVXNlcnNcdXNlclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcNjQxNjg5MDQ2X3YyXEltYWdlRmlsZXNcMTcwOTQzMzYzNDQxNV85QjAyMkIzMi03NjdCLTQ2MTctQkQ1MS1DMzgyREYwQUZCNEQucG5n](https://github.com/Sayi/poi-tl/assets/40259436/9815ecde-7817-451e-812f-0bae8cf1172c)
![78e35eb8612506a7d266e6e73863738b71f3d12ab9e951c07a743d47ed993b8fQzpcVXNlcnNcdXNlclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcNjQxNjg5MDQ2X3YyXEltYWdlRmlsZXNcMTcwOTQzMzY0OTU2NF80MDVEQzhCNS1FRjBELTRlNzMtQkU1Qy1ENkI4MzMyOTAyODcucG5n](https://github.com/Sayi/poi-tl/assets/40259436/fcdb1193-29fe-480c-ba46-a723499fabe0)

**Comment by 66pi** [comment]
第一张是遍历第一个元素时没有projNum和projName,第二张是遍历其它元素时都多遍历了第一个元素中的proNum和projName
![iwEcAqNwbmcDAQTRAs8F0QK0BrBg9GhUfYCVugXSKwQy094AB9ImP2XWCAAJomltCgAL0gAAhDg png_720x720q90](https://github.com/Sayi/poi-tl/assets/40259436/37fa7515-042a-4ace-8def-77ea31de25e3)
![iwEeAqNwbmcDAQTRBdEF0QLmBrDdMxUjTS0sMAXSKwQy094BB9ImP2XWCAAJomltCgAL0gABF4k png_720x720q90](https://github.com/Sayi/poi-tl/assets/40259436/a282e88a-f1ae-4947-ab11-878939015c16)

**Comment by 66pi** [comment]
这是模版,出问题的地方是projInfos
[Uploading fundExport.docx…]()

**Comment by 66pi** [comment]
[fundExport.docx](https://github.com/Sayi/poi-tl/files/14471504/fundExport.docx)
这是模版,出问题的地方是projInfos

**Comment by Sayi** [comment]
我这边无法复现，我使用的是1.10.6版本。
```java
XWPFTemplate.compile("fundExport.docx")
            .render(new HashMap<String, Object>() {
                {

                    put("projInfos", new ArrayList<Map<String, Object>>() {{
                        add(new HashMap<String, Object>() {{
                            put("projNum", "projNum1");
                            put("projName", "projName1");
                        }});
                        add(new HashMap<String, Object>() {{
                            put("projNum", "projNum2");
                            put("projName", "projName2");
                        }});
                    }});


                }
            }).writeToFile("out.docx");
```

![image](https://github.com/Sayi/poi-tl/assets/1394854/4cdcd339-11a6-42e6-9cb7-12ca57b0fe68)

**Comment by 66pi** [comment]
1.10.0-beta版本确实有这个问题, 我换了1.10.6就没有了
