### ISSUE TITLE
Problem with hidden text in Word templates

### ISSUE THREAD

**Issue by Bigdatha** [Sayi/poi-tl#1137]
Hi,

i have some Word templates that contain hidden text with text tags. After rendering the template the inserted values (and sometimes parts of the neighboring text in more complex templates) appear as visible text.

Am I doing something wrong or is this actually a bug ?

Here an example to illustrate this:
- [Demo.java.txt](https://github.com/Sayi/poi-tl/files/14585404/Demo.java.txt) (using OpenJDK 1.8.0_322 and poi-tl v1.12.2)
- [Template.docx](https://github.com/Sayi/poi-tl/files/14585344/Template.docx)
- [Result.docx](https://github.com/Sayi/poi-tl/files/14585345/Result.docx)

Thank you very much in advance !

**Comment by Sayi** [comment]
Hi, use `1.12.3-beta1` 😄

**Comment by Bigdatha** [comment]
Hi Sayi,
thank you very much for the quick response, poi-tl v1.12.3-beta1 works perfect !
