### ISSUE TITLE
怎样在word中增加一个超链接呢？

### ISSUE THREAD

**Issue by beamofsoul** [Sayi/poi-tl#115]
RT!
是否支持在word中通过模板增加一个超链接呢？
如果可以的话，怎么样操作呢？
使用普通的TextRenderData就可以实现嘛？

1. 外部链接 - 比如, http://github.com
2. 内部锚点 - 比如, 点击跳转到指定(锚点)位置

**Comment by Sayi** [comment]
暂时没有自带，可以通过插件机制去扩展这个功能。

**Comment by Sayi** [comment]
其余功能已实现，内部锚点涉及到书签Bookmark的配合，稍微复杂目前不去实现。
