### ISSUE TITLE
列表形式的数据，可否去掉前面的序号

### ISSUE THREAD

**Issue by m5j** [Sayi/poi-tl#116]
`dataMap.put("dataList", new NumbericRenderData(dataList));`
此构造方法默认使用了FMT_BULLET的格式
```
public NumbericRenderData(List<TextRenderData> numbers) {
        this(FMT_BULLET, numbers);
    }
```
能否不要前面的●或者1. 或者1)等

**Comment by Sayi** [comment]
列表就应该前面有序号的吧，如果不需要序号，可以用普通文本，换行使用\n。

**Comment by m5j** [comment]
谢谢作者，刚才试了我的需求可以使用换行符实现
