### ISSUE TITLE
不能继承XWPFTemplate类

### ISSUE THREAD

**Issue by m5j** [Sayi/poi-tl#118]
作者大大您好
该类的无参构造是私有的
private XWPFTemplate() {}

我的需求是把得到的XWPFTemplate对象，转成字节数组然后保存在另一台文件服务器上，
但是发现这个类没有实现序列化接口，也发现不能继承该类，可以给我提供一个解决办法吗谢谢啦

**Comment by Sayi** [comment]
可以把XWPFTemplate里面的流持久化啊。
```java
ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
template.write(byteArrayOutputStream);
template.close();
```
输出流可以转化为输入流，重新初始化XWPFTemplate
```java
new ByteArrayInputStream(byteArrayOutputStream.toByteArray())
```
