### ISSUE TITLE
word列表编号的样式可以改变颜色么？

### ISSUE THREAD

**Issue by openmartin** [Sayi/poi-tl#12]
看文档说明，word列表编号的样式可以改变字符，但是颜色可以改变么？

**Comment by Sayi** [comment]
@openmartin 
这个版本没有，下一个版本加上这个功能。
下一个小版本最快这周发。

**Comment by openmartin** [comment]
非常感谢

**Comment by openmartin** [comment]
我摸索到了怎么设置列表编号的颜色，字体，缩进，希望能有点帮助

cTLvl.addNewRPr().addNewColor().setVal("640000");  // 颜色
cTLvl.addNewRPr().addNewRFonts().setAscii("Verdana");  // 字体
cTLvl.addNewRPr().addNewRFonts().setHAnsi("Verdana"); // 字体
cTLvl.addNewRPr().addNewSz().setVal(BigInteger.valueOf(16)); // 字体大小

// 列表编号后面接的文字的缩进
CTInd cTInd = cTLvl.addNewPPr().addNewInd();
cTInd.setHanging(BigInteger.valueOf(420));
cTInd.setLeft(BigInteger.valueOf(420));

**Comment by Sayi** [comment]
@openmartin 
考虑个更通用的场景：
> 是希望改变所有的编号的颜色、字体，还是改变指定某一个编号的颜色、字体？

比如1、2、3、4只想改变2的颜色字体，有这个场景吗？

**Comment by openmartin** [comment]
我目前应用的场景没有这种情况，我目前的需求是把所有的编号都变成红色方块

**Comment by Sayi** [comment]
1.1.0版本已发布。
```xml
<dependency>
  <groupId>com.deepoove</groupId>
  <artifactId>poi-tl</artifactId>
  <version>1.1.0</version>
</dependency>
```
具体设置编号样式代码示例：
```java
Style fmtStyle = new Style("f44336");
put("custom_style", new NumbericRenderData(Pair.of(STNumberFormat.BULLET, "■"), fmtStyle, new ArrayList<TextRenderData>() {
    {
        add(new TextRenderData("df2d4f", "Deeply in love with the things you love, just deepoove."));
        add(new TextRenderData("Deeply in love with the things you love, just deepoove."));
        add(new TextRenderData("5285c5", "Deeply in love with the things you love, just deepoove."));
    }
}));
```

设置编号样式的源码参见[StyleUtils.styleRpr](https://github.com/Sayi/poi-tl/blob/eb7d1ddbedd26088d63bc00c601a1b4834471005/src/main/java/com/deepoove/poi/util/StyleUtils.java#L85)

**Comment by openmartin** [comment]
非常感谢
