### ISSUE TITLE
多次调用render方法

### ISSUE THREAD

**Issue by LinYueshan** [Sayi/poi-tl#120]
问题描述：我需要批量处理文档内容替换，所以将渲染后的XWPFTemplate放进缓存中，但是服务器启动后，只有第一次可以替换成功，其余都是失败的，报的异常是XmlValueDisconnectedException，在org.apache.xmlbeans.impl.values.XmlObjectBase类里。
作者大大可以帮忙解决下吗

**Comment by LinYueshan** [comment]
将XWPFTemplate.compile(inputStream, config)后 得到的XWPFTemplate放进LoadingCache<Integer, XWPFTemplate> documentCache里，然后就可以根据id获取XWPFTemplate了。

**Comment by Sayi** [comment]
是不是XWPFTemplate模板使用了{{+docx}}这样的语法？

**Comment by Sayi** [comment]
是多次调用同一个XWPFTemplate对象的render方法？

**Comment by LinYueshan** [comment]
没有，只有替换字符。
是的，多次调用同一个XWPFTemplate对象的render方法

**Comment by Sayi** [comment]
没能重现出你的错误，但是目前不支持多次render。

这个错误大多数的原因是文档结构变了，但是XWPFTemplate没有及时更新自身文档导致的。

**Comment by LinYueshan** [comment]
好的，非常感谢

**Comment by LinYueshan** [comment]
确实是，不放缓存，直接循环多次render()就会报异常：org.apache.xmlbeans.impl.values.XmlValueDisconnectedException
