### ISSUE TITLE
word标题样式嵌套生成

### ISSUE THREAD

**Issue by PinLinMoMo** [Sayi/poi-tl#122]
![46064346-bbd51700-c1a1-11e8-82bb-2fd3c55756fb](https://user-images.githubusercontent.com/24206061/47139233-dce6de80-d2ed-11e8-8544-91f53f5a2b63.png)

作者您好，问题实例图如上。具体请问下关于生成word时的如何生成多个子标题的问题，谢谢您了。

**Comment by Sayi** [comment]
采用文档模板{{+var}}，子标题放到待合并的文档里面不行吗？

**Comment by PinLinMoMo** [comment]
抱歉，我目前生成word的方式是基本word文档中嵌套{{+var}}文档模板进行循环，但需求中需要相同标题的循环内容合并为一个子标题，并且内容中相同循环内容数量不确定。

**Comment by Sayi** [comment]
可能是你循环方式有问题，我理解你这里应该有两处循环了。
首先3.1 3.1.1 3.1.2 这是一类循环，比如还有3.2节，3.3节，然后3.1.1 3.1.2这也是一类循环，比如还有3.1.3节。

所以模板可能是这样的：
* 主模板包含大的章节：
{{+segment}}
* 次模板定义大章节里面的内容（其中title对应3.1，样式为标题一，subSegment对应多个子节3.1.1 3.1.2）：
{{title}}
{{+subSegment}}
* 子模板定义小节的内容（其中title对应3.1.1，样式为标题二，content对应内容）：
{{title}}
{{content}}


**poi-tl是针对模板的引擎，所以实现你这个标题样式稍微饶了点，如果标题样式要求很高的话，建议使用POI生成整个文档**

**Comment by PinLinMoMo** [comment]
谢谢你，国庆还能回复我的请求。国庆快乐。是的双重循环无法渲染，最近想自定义模板也没想好。
如果按照
主模板包含大的章节：
{{+segment}}
次模板定义大章节里面的内容（其中title对应3.1，样式为标题一，subSegment对应多个子节3.1.1 3.1.2）：
{{title}}
{{+subSegment}}
子模板定义小节的内容（其中title对应3.1.1，样式为标题二，content对应内容）：
{{title}}
{{content}}

这样写法曾经尝试过，可惜第二层之后就没有渲染出来。
现在考虑在DocxRenderPolicy.getMergedDocxs 进行重写。但没有头绪。

**Comment by issac21** [comment]
哈哈，楼主，我们是同行啊~
我是自定义一个渗透测试结果的渲染类（主标题），然后在这个类里循环渲染漏洞信息（子标题）

**Comment by Sayi** [comment]
v1.7.1 版本支持模板内循环，类似issue的需求应该很容易实现。
