### ISSUE TITLE
【问题】模仿“一篇文章”的代码报错

### ISSUE THREAD

**Issue by l328958741** [Sayi/poi-tl#123]
* 系统：win10，maven项目，poi-tl版本为1.3.1
* 模板为两个docx文件：template.docx, segment.docx
```java
    private void story(String no) throws IOException{
        RenderDataDto data = new RenderDataDto();

        List<RenderDto> segments = new ArrayList<RenderDto>();
        RenderDto s1 = new RenderDto();
        s1.setNo("经常抱怨的自己");
        s1.setDetailNo("每个人生活得都不容易，经常向别人抱怨的人，说白了就是把对方当做“垃圾场”，你一股脑地将自己的埋怨与不满倒给别人，自己倒是爽了，你有考虑过对方的感受吗？对方的脸上可能一笑了之，但是心里可能有一万只草泥马奔腾而过。");
        s1.setQrcodeImg(new PictureRenderData(510, 402, "C:\\web\\yun\\Img\\1.jpg"));
        segments.add(s1);

        RenderDto s2 = new RenderDto();
        s2.setNo("拖拖拉拉的自己");
        s2.setDetailNo("能够今天做完的事情，不要拖到明天，你的事情没有任何人有义务去帮你做；不要做“宅男”、不要当“宅女”，放假的日子约上三五好友出去转转；经常动手做家务，既能分担伴侣的负担，又有一个干净舒适的环境何乐而不为呢？");
        s2.setQrcodeImg(new PictureRenderData(510, 510, "C:\\web\\yun\\Img\\2.jpg"));
        segments.add(s2);

        RenderDto s3 = new RendeDto();
        s3.setNo("斤斤计较的自己");
        s3.setDetailNo("人生在世，真的没必要斤斤计较：和亲人计较，即使赢了也会伤了感情；和朋友计较，可能你们的友谊到此就结束了；和陌生人计较，别人会记着你一辈子。少了斤斤计较，你的生活也会豁然开朗。");
        s3.setQrcodeImg(new PictureRenderData(510, 384, "C:\\web\\yun\\Img\\1.jpg"));
        segments.add(s3);
        File segmentFile = new File(new File(atsProperties.getSegmentFilePath()).getCanonicalPath());
        DocxRenderData segment = new DocxRenderData(segmentFile, segments );
        data.setSegment(segment);

        String filePath = new File(atsProperties.getTemplateFilePath()).getCanonicalPath();
        File templateFile = new File(filePath);
        XWPFTemplate template = XWPFTemplate.compile(templateFile).render(data);

        FileUtil.mkDirBySlash(atsProperties.getExportFilePath());
        String outputFilePath = FileUtil.mixPath(atsProperties.getExportFilePath(), no + TypeEunm.word_docx);
        outputFilePath = outputFilePath.substring(0, outputFilePath.lastIndexOf("/"));
        FileOutputStream out = new FileOutputStream(outputFilePath);
        template.write(out);
        out.flush();
        out.close();
        template.close();
    }
```

> 报错信息：<code>org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.deepoove.poi.NiceXWPFDocument.getRelationId(Lorg/apache/poi/POIXMLDocumentPart;)Ljava/lang/String;
 
> Caused by: java.lang.NoSuchMethodError: com.deepoove.poi.NiceXWPFDocument.getRelationId(Lorg/apache/poi/POIXMLDocumentPart;)Ljava/lang/String;
	at com.deepoove.poi.NiceXWPFDocument.mergePicture(NiceXWPFDocument.java:520)
	at com.deepoove.poi.NiceXWPFDocument.extractMergePart(NiceXWPFDocument.java:474)
	at com.deepoove.poi.NiceXWPFDocument.merge(NiceXWPFDocument.java:428)
	at com.deepoove.poi.policy.DocxRenderPolicy.render(DocxRenderPolicy.java:53)
	at com.deepoove.poi.render.RenderAPI.render(RenderAPI.java:139)
	at com.deepoove.poi.render.RenderAPI.render(RenderAPI.java:151)
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:159)
	at com.wkeye.ats.modular.product.service.impl.BatchServiceImpl.story(BatchServiceImpl.java:285)</code>

在代码跑到<code>XWPFTemplate template = XWPFTemplate.compile(templateFile).render(data);</code>时报错，走到源码里是在NiceXWPFDocument.class 的第520行代码<code>String relationId = docMerge.getRelationId(xwpfPictureData);</code>报错。但是我看您给的[例子](https://github.com/Sayi/poi-tl/blob/master/src/test/java/com/deepoove/poi/tl/example/StoryExample.java)是可以成功的，找了很久的原因，找不到原因，特来请教，怎么解决这个问题，感谢！！！

**Comment by Sayi** [comment]
你项目中是不是引用了其它poi的版本，poi的版本需要3.16+

**Comment by l328958741** [comment]
![image](https://user-images.githubusercontent.com/21151878/46137007-6705cf00-c27b-11e8-8afd-750b804aef24.png)

![image](https://user-images.githubusercontent.com/21151878/46137122-a03e3f00-c27b-11e8-9d19-cf3ea177edcd.png)
这是我引用的poi，版本是3.16的

**Comment by l328958741** [comment]
找到原因了，版本不一致导致的问题，poi全部换成3.16就可以了
