### ISSUE TITLE
合并任意一行最后几个格子会出现数组越界错误

### ISSUE THREAD

**Issue by samluby** [Sayi/poi-tl#124]
只要包括最后一个格子就会出现此错误。

**Comment by Sayi** [comment]
麻烦给个单元测试，谢谢。

**Comment by samluby** [comment]
`package com.deepoove.poi.tl.example;

import java.util.List;

import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;

import com.deepoove.poi.NiceXWPFDocument;
import com.deepoove.poi.data.RowRenderData;
import com.deepoove.poi.policy.DynamicTableRenderPolicy;
import com.deepoove.poi.policy.MiniTableRenderPolicy;

/**
 * 付款通知书 明细表格的自定义渲染策略<br/>
 * 1. 填充货品数据 <br/>
 * 2. 填充人工费数据 <br/>
 * @author Sayi
 * @version 
 */
public class DetailTablePolicy extends DynamicTableRenderPolicy {

    // 货品填充数据所在行数
    int goodsStartRow = 2;
    // 人工费填充数据所在行数
    int laborsStartRow = 5;

    @Override
    public void render(XWPFTable table, Object data) {
        if (null == data) return;
        DetailData detailData = (DetailData) data;

        List<RowRenderData> labors = detailData.getLabors();
        if (null != labors) {
            table.removeRow(laborsStartRow);
            // 循环插入行
            for (int i = 0; i < labors.size(); i++) {
                XWPFTableRow insertNewTableRow = table.insertNewTableRow(laborsStartRow);
                for (int j = 0; j < 7; j++) insertNewTableRow.createCell();

                // 合并单元格
                NiceXWPFDocument.mergeCellsHorizonal(table, laborsStartRow, 4, 6);
                MiniTableRenderPolicy.renderRow(table, laborsStartRow, labors.get(i));
            }
        }

        List<RowRenderData> goods = detailData.getGoods();
        if (null != goods) {
            table.removeRow(goodsStartRow);
            for (int i = 0; i < goods.size(); i++) {
                XWPFTableRow insertNewTableRow = table.insertNewTableRow(goodsStartRow);
                for (int j = 0; j < 7; j++) insertNewTableRow.createCell();
                MiniTableRenderPolicy.renderRow(table, goodsStartRow, goods.get(i));
            }
        }
    }

}`

`package com.deepoove.poi.tl.example;

import java.io.FileOutputStream;
import java.util.Arrays;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.STJc;

import com.deepoove.poi.XWPFTemplate;
import com.deepoove.poi.config.Configure;
import com.deepoove.poi.data.MiniTableRenderData;
import com.deepoove.poi.data.RowRenderData;
import com.deepoove.poi.data.TextRenderData;
import com.deepoove.poi.data.style.Style;
import com.deepoove.poi.data.style.TableStyle;

/**
 * 付款通知书：表格操作示例
 * @author Sayi
 * @version 
 */
public class PaymentExample {
    
    PaymentData datas = new PaymentData();
    
    Style headTextStyle = new Style();
    TableStyle headStyle = new TableStyle();
    TableStyle rowStyle = new TableStyle();
    
    @Before
    public void init(){
        headTextStyle.setFontFamily("Hei");
        headTextStyle.setFontSize(9);
        headTextStyle.setColor("7F7F7F");
        
        headStyle.setBackgroundColor("F2F2F2");
        headStyle.setAlign(STJc.CENTER);
        
        rowStyle = new TableStyle();
        rowStyle.setAlign(STJc.CENTER);
        
        
        
        datas.setNO("KB.6890451");
        datas.setID("ZHANG_SAN_091");
        datas.setTaitou("深圳XX家装有限公司");
        datas.setConsignee("丙丁");
        
        datas.setSubtotal("8000");
        datas.setTax("600");
        datas.setTransform("120");
        datas.setOther("250");
        datas.setUnpay("6600");
        datas.setTotal("总共：7200");

        
        RowRenderData header = RowRenderData.build(new TextRenderData("日期", headTextStyle),
                new TextRenderData("订单编号", headTextStyle), new TextRenderData("销售代表", headTextStyle),
                new TextRenderData("离岸价", headTextStyle), new TextRenderData("发货方式", headTextStyle),
                new TextRenderData("条款", headTextStyle), new TextRenderData("税号", headTextStyle));
        header.setStyle(headStyle);
        
        RowRenderData row = RowRenderData.build("2018-06-12", "SN18090", "李四", "5000元", "快递", "附录A", "T11090");
        row.setStyle(rowStyle);
        MiniTableRenderData  miniTableRenderData = new MiniTableRenderData(header, Arrays.asList(row), MiniTableRenderData.WIDTH_A4_MEDIUM_FULL);
        miniTableRenderData.setStyle(headStyle);
        datas.setOrder(miniTableRenderData);
        
        DetailData detailTable = new DetailData();
        RowRenderData good = RowRenderData.build("4", "墙纸", "书房+卧室", "1500", "/", "400", "1600");
        good.setStyle(rowStyle);
        List<RowRenderData> goods = Arrays.asList(good, good, good);
        RowRenderData  labor = RowRenderData.build("油漆工", "2", "200", "400");
        labor.setStyle(rowStyle);
        List<RowRenderData> labors = Arrays.asList(labor, labor, labor, labor);
        detailTable.setGoods(goods);
        detailTable.setLabors(labors);
        datas.setDetailTable(detailTable);
    }

    @Test
    public void testResumeExample() throws Exception {
        Configure config = Configure.newBuilder().customPolicy("detail_table", new DetailTablePolicy()).build();
        XWPFTemplate template = XWPFTemplate.compile("src/test/resources/付款通知书.docx", config).render(datas);
        FileOutputStream out = new FileOutputStream("C:/Users/Administrator/Desktop/out_付款通知书.docx");
        template.write(out);
        out.flush();
        out.close();
        template.close();
    }

}
`

只是把DetailTablePolicy中41行的参数 0 3 改为了 4 6即合并最后3个单元格，其他都是源码example 中付款单的代码，  这样会出现IndexOutOfBoundsException的异常

**Comment by Sayi** [comment]
0-3是四个数据，4-6是三个元素，你多传了一列元素进去了。
```java
RowRenderData  labor = RowRenderData.build("油漆工", "2", "200", "400");
```
这行代码是要显示四列的，你去掉400应该就可以了。

**Comment by samluby** [comment]
多谢了。

**Comment by funyule** [comment]
确实存在这个BUG，生成的最后一个单元格有问题，最后一个单元格永远不能和整个表格对齐

**Comment by funyule** [comment]
请问下这个的 NiceXWPFDocument 中间的跨列合并单元格 是什么含义呢：
` /**
     * 合并列单元格
     * @param table
     * @param col
     * @param fromRow
     * @param toRow
     */
    public static void mergeCellsVertically(XWPFTable table, int col, int fromRow,
            int toRow) {

        for (int rowIndex = fromRow; rowIndex <= toRow; rowIndex++) {

            _XWPFTableCell cell = table.getRow(rowIndex).getCell(col);_
            CTTcPr tcPr = cell.getCTTc().getTcPr();
            if (null == tcPr)
                tcPr = cell.getCTTc().addNewTcPr();
            CTVMerge vMerge = tcPr.addNewVMerge();
            if (rowIndex == fromRow) {
                // The first merged cell is set with RESTART merge value
                vMerge.setVal(STMerge.RESTART);
            } else {
                // Cells which join (merge) the first one, are set with CONTINUE
                vMerge.setVal(STMerge.CONTINUE);
            }
        }
    }`


这里获取单元格 根据 列序号作为行是反着来么？ XWPFTableCell cell = table.getRow(rowIndex).getCell(col);

**Comment by Sayi** [comment]
@funyule 合并一列上的单元格，不是合并列

**Comment by funyule** [comment]
看错了。重新试了一下，对比行合并的写法NiceXWPFDocument  这个类中下面方法：

/**
     * 合并行单元格
     * @param table
     * @param row
     * @param fromCol
     * @param toCol
     */
    public static void mergeCellsHorizonal(XWPFTable table, int row, int fromCol,
            int toCol) {
        if (toCol <= fromCol) return;
        XWPFTableCell cell = table.getRow(row).getCell(fromCol);
        CTTcPr tcPr = cell.getCTTc().getTcPr();
        if (null == tcPr)
            tcPr = cell.getCTTc().addNewTcPr();
        XWPFTableRow rowTable = table.getRow(row);
        for (int colIndex = fromCol + 1; colIndex <= toCol; colIndex++) {
            rowTable.getCtRow().removeTc(colIndex);
            rowTable.removeCell(colIndex);
        }
        spanCellsAcrossRow(table, row, fromCol, toCol - fromCol + 1);
    }

问题出在这里：当删除一个cell后，整个行里的cell数量会-1，所以这样子写会导致最后出现数组越界
for (int colIndex = fromCol + 1; colIndex <= toCol; colIndex++) {
            rowTable.getCtRow().removeTc(colIndex);
            rowTable.removeCell(colIndex);
        }

尝试修改了一下，计算需要向右合并单元格的数量 toCol-from，循环删除这几个即可，最后就不会出现数组越界

**Comment by funyule** [comment]
,因为引用的jar，就自己重写了父类的方法，单元测试就用example的那个
![image](https://user-images.githubusercontent.com/12372048/47011120-a84f1780-d173-11e8-9baf-9d1f3e81547b.png)

**Comment by yaosing** [comment]
@funyule 

请问这个bug修复了吗？ 什么时候能修复！

**Comment by Edison-Tian** [comment]
修复后的版本是哪一个？
