### ISSUE TITLE
预览文本多出了删除线

### ISSUE THREAD

**Issue by m5j** [Sayi/poi-tl#125]
生成出来的demo.docx，调用第三方的预览接口转换，预览的效果会在**某些** 动态生成的内容 加上删除线
如图：
![image](https://user-images.githubusercontent.com/13043066/46795094-d7cce100-cd7b-11e8-8a7c-cf92228a0b77.png)
 如果用word编辑一下保存，再调用预览接口，预览的效果就是正常的
--------------------------------------------------------------------------------
生成出来的demo.doc:
[生成的测试word.docx](https://github.com/Sayi/poi-tl/files/2468313/word.docx)

第三方预览的地址：http://dcs.yozosoft.com/examples.html

使用高清预览功能，如图
![image](https://user-images.githubusercontent.com/13043066/46795411-b6202980-cd7c-11e8-99f8-4229e59882e1.png)

**Comment by m5j** [comment]
如有需要可提供模板和单元测试代码，跪求作者大大抽空看一下啊，我请喝咖啡

**Comment by Sayi** [comment]
代码里面用到了Style这个类吧，Style类设置了删除线为false，但是预览里面似乎对这个false解析不兼容，你尝试不要设置false？不设置或者设置为null

**Comment by Sayi** [comment]
过期关闭issue
