### ISSUE TITLE
图片重复问题

### ISSUE THREAD

**Issue by sin60-cos30** [Sayi/poi-tl#129]
一个word模板有多张图片，多个模板合并后图片错乱、重复，只有我有遇到这个问题吗？困扰了好多天了，求大神指点
![tim 20181023111434](https://user-images.githubusercontent.com/27758845/47333298-f6ed3c00-d6b4-11e8-87d0-13e8e378cdf9.png)

**Comment by Sayi** [comment]
能给个单元测试看看吗？

**Comment by sin60-cos30** [comment]
> 能给个单元测试看看吗？

@RequestMapping(value = "test")
	public void test(HttpServletRequest request, HttpServletResponse response) throws Exception {
   	List<Map<String, Object>> datalist =Lists.newArrayList();
   	//用于获取测试数据的id
   	String ids[]={"a7104f4436734c4190c6b4c8c116e774","467fd859d3c24fe0b74a088aad8aa95d"};
   	//设置基础信息
   	String userfilesBaseDir =Global.getUserfilesBaseDir();
   	
   	for(String id:ids){
   		Attachment attachment = new Attachment();
   		attachment.setRecNo(id);
   		List<Attachment> attachments = attachmentService.findList(attachment);//获取相关附件

   	   	for(int i=0;i<attachments.size();i++){
   	   		Map<String, Object> dataMap=new HashMap<String, Object>();	
   	   		Attachment a = attachments.get(i);
   	   		PictureRenderData pic=new PictureRenderData(265, 180, userfilesBaseDir + a.getPath());
   	   		dataMap.put("xcpgt"+i, pic);
   	   		dataMap.put("xcpgtmx"+i, a.getRemarks());
   	   		datalist.add(dataMap);
   	   	}
   	}
   	
		String myFileName = "测试"+DateUtils.formatDate(new Date(), "yyyyMMddHHmmss")+".docx";
   	
		try {
			
	    	String segmentPath = ServletContextFactory.getServletContext().getRealPath("/")+"wordTemplate/test.docx";
	    	String templatePath = ServletContextFactory.getServletContext().getRealPath("/")+"wordTemplate/testAll.docx";
	    	DocxRenderData segment = new DocxRenderData(new File(segmentPath), datalist );
	    	Map<String, Object> datafor=new HashMap<String, Object>();
	    	datafor.put("segment", segment);
	        XWPFTemplate template = XWPFTemplate.compile(templatePath).render(datafor);
	        
	        response.reset();
	  	  	response.setContentType("application/x-msdownloadoctet-stream;charset=utf-8");
	  	  	response.setHeader("Content-Disposition","attachment;filename=\"" + URLEncoder.encode(myFileName, "UTF-8"));
	  	  	OutputStream output = response.getOutputStream();
	  	  	template.write(output);
	  	  
	  	  	output.flush();  
	  	  	output.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
![tim 20181023112714](https://user-images.githubusercontent.com/27758845/47333761-b2fb3680-d6b6-11e8-835e-0644488f0602.png)
![tim 20181023112656](https://user-images.githubusercontent.com/27758845/47333762-b2fb3680-d6b6-11e8-92d1-be2c5d9ba241.png)

**Comment by sin60-cos30** [comment]
@Sayi 大神能给个解释吗，谢谢了

**Comment by Sayi** [comment]
```java
for(int i=0;i<attachments.size();i++){
    Map<String, Object> dataMap=new HashMap<String, Object>();  
    Attachment a = attachments.get(i);
    PictureRenderData pic=new PictureRenderData(265, 180, userfilesBaseDir + a.getPath());
    dataMap.put("xcpgt"+i, pic);
    dataMap.put("xcpgtmx"+i, a.getRemarks());
    datalist.add(dataMap);
}
```

这段代码创建那么多Map干啥？
`    datalist.add(dataMap);`这段代码提到for循环外呢？我看你想要做的的是把表格的所有数据填充好，所以这些数据应该是在一个dataMap里面。

**Comment by sin60-cos30** [comment]
@Sayi 不好意思，上面代码是临时整出来的，有点错。实际代码是：
`   	for(String id:ids){
   		Attachment attachment = new Attachment();
   		attachment.setRecNo(id);
   		List<Attachment> attachments = attachmentService.findList(attachment);//获取相关附件

   		Map<String, Object> dataMap=new HashMap<String, Object>();	
   	   	for(int i=0;i<attachments.size();i++){
   	   		Attachment a = attachments.get(i);
   	   		PictureRenderData pic=new PictureRenderData(265, 180, userfilesBaseDir + a.getPath());
   	   		dataMap.put("xcpgt"+i, pic);
   	   		dataMap.put("xcpgtmx"+i, a.getRemarks());
   	   	}
   	   	datalist.add(dataMap);
   	}`
思路是先把一个模板的数据放在一个Map里面，再把所有模板数据的Map放在List，然后导出

**Comment by Sayi** [comment]
@sin60-cos30 我这边按照你这样试了下，能正常显示。 并没有理解到你说的图片错乱重复是什么现象？

**Comment by sin60-cos30** [comment]
@Sayi 我找找其他原因。谢谢了大神

**Comment by sin60-cos30** [comment]
@Sayi 不好意思又打扰了。我排查了好久，还是认为是插件问题。
代码：
`
@RequestMapping(value = "test")
	public void test(HttpServletRequest request, HttpServletResponse response) throws Exception {
   		List<Map<String, Object>> datalist =Lists.newArrayList();
   	
   		String ids[]={"1","2"};
   	
	   	for(String id:ids){
	   		Map<String, Object> dataMap=new HashMap<String, Object>();	
	   	   	for(int i=0;i<9;i++){
	   	   		
				PictureRenderData pic=new PictureRenderData(65, 80, "d:\\test\\"+id+"\\"+i+".jpg");
				dataMap.put("xcpgt"+i, pic);//插入图片
	   	   		dataMap.put("xcpgtmx"+i, i);//插入描述
	   	   	}
	   	   	datalist.add(dataMap);
	   	}
			
    	String segmentPath = ServletContextFactory.getServletContext().getRealPath("/")+"wordTemplate/test.docx";
    	String templatePath = ServletContextFactory.getServletContext().getRealPath("/")+"wordTemplate/testAll.docx";
    	DocxRenderData segment = new DocxRenderData(new File(segmentPath), datalist );
    	Map<String, Object> dataTemplate=new HashMap<String, Object>();
    	dataTemplate.put("segment", segment);
        XWPFTemplate template = XWPFTemplate.compile(templatePath).render(dataTemplate);
        
        response.reset();
  	  	response.setContentType("application/x-msdownloadoctet-stream;charset=utf-8");
  	  	response.setHeader("Content-Disposition","attachment;filename=\"" + URLEncoder.encode("测试"+DateUtils.formatDate(new Date(), "yyyyMMddHHmmss")+".docx", "UTF-8"));
  	  	OutputStream output = response.getOutputStream();
  	  	template.write(output);  
  	  	output.flush();  
  	  	output.close();
	}`
测试数据图片：
![2](https://user-images.githubusercontent.com/27758845/47349741-da69f780-d6e6-11e8-8418-8418073d4cc9.png)
![1](https://user-images.githubusercontent.com/27758845/47349923-3e8cbb80-d6e7-11e8-8919-a211cdee6406.png)
导出结果：
![default](https://user-images.githubusercontent.com/27758845/47350053-890e3800-d6e7-11e8-81cc-52159985b495.png)

**Comment by Sayi** [comment]
@sin60-cos30 你能给出一个一个完整可运行的junit测试，把图片，模板docx都以附件形式发过来吗？这样方便我这边重现一下，现在给的代码是servlet的，给个输出结果到本地的示例。

**Comment by sin60-cos30** [comment]
@Sayi 
`public class test {
	@Test
	public void testExport() {
		System.out.println("begin");
		List<Map<String, Object>> datalist =new ArrayList<Map<String, Object>>();
	   	
   		String ids[]={"1","2"};
   	
	   	for(String id:ids){
	   		Map<String, Object> dataMap=new HashMap<String, Object>();	
	   	   	for(int i=0;i<9;i++){
	   	   		
				PictureRenderData pic=new PictureRenderData(65, 80, "D:\\图片重复文件\\测试图片\\test\\"+id+"\\"+i+".jpg");
				dataMap.put("xcpgt"+i, pic);//插入图片
	   	   		dataMap.put("xcpgtmx"+i, i);//插入描述
	   	   	}
	   	   	datalist.add(dataMap);
	   	}
			
    	String segmentPath = "D:\\图片重复文件\\导出模板\\test.docx";
    	String templatePath = "D:\\图片重复文件\\导出模板\\testAll.docx";
    	DocxRenderData segment = new DocxRenderData(new File(segmentPath), datalist );
    	
    	Map<String, Object> dataTemplate=new HashMap<String, Object>();
    	dataTemplate.put("segment", segment);
        XWPFTemplate template = XWPFTemplate.compile(templatePath).render(dataTemplate);
        
  	  	OutputStream output;
		try {
			output = new FileOutputStream("D:\\图片重复文件\\导出结果\\测试.docx");
			template.write(output);  
	  	  	output.flush();  
	  	  	output.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
		System.out.println("over");
	}
}`
源码附件里面也有。辛苦了！
[图片重复文件.zip](https://github.com/Sayi/poi-tl/files/2508791/default.zip)

**Comment by Sayi** [comment]
图片过多导致的一个BUG，下一版本近期发布，我会修复它。

谢谢提交ISSUE

**Comment by sin60-cos30** [comment]
### 辛苦了！
