### ISSUE TITLE
是否有考虑过实现目录这个功能呢，这个功能有点头疼

### ISSUE THREAD

**Issue by kealina** [Sayi/poi-tl#13]
现在本人需要从一个带有目录的word中读取出内容，再把这个目录的内容格式化生成另一个文件
问题
1.在读取时如何更好的读取，因为有分一级目录，二级目录等，因为一级目录与二级目录所要的样式不同。
2.读取后格式化到另一个word时里面的目录如何实现（ctrl+点击）直接到达那个目录下的内容
楼主有什么好的建议么？打扰了...

**Comment by Sayi** [comment]
是从一个word中拷贝目录到另一个word中吗？如果是简单拷贝的话，`apache poi`默认应该有这些功能。

场景可以说的再具体点。

**Comment by kealina** [comment]
不是简单的拷贝哦！我是要对它进行改格式，我只能读取它的文本内容，然后写一个template对它进行格式化。

假如有一份已经有目录的文件，可是它的样式和排版都不是我想要的，所以我就读取里面的内容然后对它进行再次格式化，而且它有多少级的目录是我不能确定的，但是我要求他的第一级目录要求四号宋体，如果有第二级目录就要求四号小黑体，如果有第三级目录又是另外一种样式。大概就是这样一个意思。

**Comment by Sayi** [comment]
@kealina
我觉得可以这样来：
 
1. 读取原word的目录
2. 写入目录到另一个word，**并且针对不同级的目录设置自己想要的样式**

读取目录的具体代码参考POI的API：
```java
CTP ctp = xwpfParagraph.getCTP();
List<CTBookmark> bookmarkStartList = ctp.getBookmarkStartList();
...
```
关于ctr+点击要跳转这个问题有个前提：
1.需要设置跳转处锚点
2.如果目录有页码，可能随着文档字体变化页码要更新

**Comment by kealina** [comment]
好的，感谢回答，我去试试
