### ISSUE TITLE
设置多级标题

### ISSUE THREAD

**Issue by ucstone** [Sayi/poi-tl#134]
你好，poi-现在支持设置多级标题吗？
现在我看到文章里面支持设置标题，只能设置为1级标题，能否继续设置二级、三级标题呢

**Comment by Sayi** [comment]
你好，poi-tl目前只能再已有标题样式时替换部分文本，不支持设置多种标题样式。可以自行考虑使用Poi去扩展。

**Comment by ucstone** [comment]
> 你好，poi-tl目前只能再已有标题样式时替换部分文本，不支持设置多种标题样式。可以自行考虑使用Poi去扩展。

好的，多谢~
