### ISSUE TITLE
报classCastException

### ISSUE THREAD

**Issue by wangkof** [Sayi/poi-tl#135]
XWPFTemplate template = XWPFTemplate.compile("E:/template.docx").render(new HashMap<String, Object>(){{  
		        put("helloWorld", word.getName());
		}});
		File file = new File("E:/out_template.docx");
		FileOutputStream out;
		try {
			out = new FileOutputStream(file);
			template.write(out); 
			out.flush();
			out.close();
			template.close();
			return Ret.ok("msg", "");
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return Ret.fail("msg", "");
		}

报了这个错：
java.lang.ClassCastException: org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.DocumentDocumentImpl cannot be cast to org.openxmlformats.schemas.wordprocessingml.x2006.main.DocumentDocument

**Comment by Sayi** [comment]
[参见文档中常见问题第二条哦](http://deepoove.com/poi-tl/#_%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)

**Comment by wangkof** [comment]
<dependency>
		    <groupId>com.deepoove</groupId>
		    <artifactId>poi-tl</artifactId>
		    <version>1.4.0</version>
		</dependency>
		<dependency>
		    <groupId>org.apache.poi</groupId>
		    <artifactId>poi</artifactId>
		    <version>3.17</version>
		</dependency>
