### ISSUE TITLE
【咨询】DocxRenderData中含有DynamicTableRenderPolicy（可能有多个时），最终要如何实现对整个文档的渲染

### ISSUE THREAD

**Issue by onlylivi** [Sayi/poi-tl#136]
总的模板文档中定义文档模板{{+docxTemplate}}
文档模板可能有多个，因此在DocxRenderData中定义了List<docxTemplateData>进行循环渲染。
我的问题是：如果docxTemplateData中包含有一个或者多个DynamicTableRenderPolicy表时，最终要如何实现整个文档的渲染呢？
感谢作者，期待您的解答:)

**Comment by Sayi** [comment]
没有什么特别的，正常使用就行了啊。
```java
ConfigureBuilder builder = Configure.newBuilder();
builder.customPolicy("report1", new OneRenderPolicy());
builder.customPolicy("report2", new TwoRenderPolicy());
builder.customPolicy("report3", new ThreeRenderPolicy());
XWPFTemplate.compile("~/template.docx", builder.buid());
```
其中report是你任何一个文档里面的标签名称。

**Comment by onlylivi** [comment]
> 没有什么特别的，正常使用就行了啊。
> 
> ```java
> ConfigureBuilder builder = Configure.newBuilder();
> builder.customPolicy("report1", new OneRenderPolicy());
> builder.customPolicy("report2", new TwoRenderPolicy());
> builder.customPolicy("report3", new ThreeRenderPolicy());
> XWPFTemplate.compile("~/template.docx", builder.buid());
> ```
> 
> 其中report是你任何一个文档里面的标签名称。

好的，谢谢

**Comment by funyule** [comment]
@onlylivi 请问你实现了么

我在字幕版里定义 表格，貌似进不去
