### ISSUE TITLE
为什么不调render方法

### ISSUE THREAD

**Issue by wangkof** [Sayi/poi-tl#138]
HashMap<String,Object> datas = new HashMap<String, Object>();
		
		List<HashMap<String,Object>> jhr = new ArrayList<HashMap<String,Object>>(); 
		HashMap<String,Object> jhrHash0 = new HashMap<String, Object>(); 
		HashMap<String,Object> jhrHash1 = new HashMap<String, Object>(); 
		jhrHash0.put("jhrName", "张峰");
		jhrHash1.put("jhrName", "王重阳");
		jhr.add(jhrHash0);
		jhr.add(jhrHash1);
		datas.put("jhr", jhr);
		datas.put("name", "123");
		
		
		Configure config = Configure.newBuilder().
				customPolicy("detail_table", new DetailTablePolicy(jhr)).
				build();
        XWPFTemplate template = XWPFTemplate.compile("E:/template.docx", config).render(datas);
		
		FileOutputStream out = new FileOutputStream("E:/out_template.docx");
		template.write(out); 
		out.flush();
		out.close();
		template.close();

package ishug.service.common;

import java.util.HashMap;
import java.util.List;

import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;

import com.deepoove.poi.data.RowRenderData;
import com.deepoove.poi.policy.DynamicTableRenderPolicy;
import com.deepoove.poi.policy.MiniTableRenderPolicy;
import com.deepoove.poi.util.TableTools;

public class DetailTablePolicy extends DynamicTableRenderPolicy {

	  // 人工费填充数据所在行数
	  int laborsStartRow = 8;
	private List<HashMap<String, Object>> jhr;
	  
	  public DetailTablePolicy(List<HashMap<String,Object>> jhr) {
			super();
			this.jhr = jhr;
		}

	  @Override
	  public void render(XWPFTable table, Object data) {
	    if (null == data) return;

	    HashMap<String,Object> detailData = (HashMap<String,Object>)data;
	      for (int i = 0; i < jhr.size(); i++) {
	        XWPFTableRow insertNewTableRow = table.insertNewTableRow(laborsStartRow);
	        XWPFTableRow insertNewTableRow1 = table.insertNewTableRow(laborsStartRow);
	        for (int j = 0; j < 6; j++) {
	        	insertNewTableRow.createCell();
	        	insertNewTableRow1.createCell();
	        }
	        
	        TableTools.mergeCellsHorizonal(table, laborsStartRow + 2, 1, 2);
	        TableTools.mergeCellsHorizonal(table, laborsStartRow + 2, 4, 5);

	        RowRenderData row0 = RowRenderData.build("姓名", (String)jhr.get(0).get("jhrName"),"关系","","联系电话");
	        RowRenderData row1 = RowRenderData.build("联系地址", "","工作单位","");
	        // 渲染单行人工费数据
	        MiniTableRenderPolicy.renderRow(table, laborsStartRow, row0);
	        MiniTableRenderPolicy.renderRow(table, laborsStartRow, row1);
	      }

      }

	    
	}

**Comment by wangkof** [comment]
不调用DetailTablePolicy 里面的render方法

**Comment by Sayi** [comment]
数据源放到data里面去：
```java
datas.put("detail_table", jhr);
```
