### ISSUE TITLE
关于表格的疑问

### ISSUE THREAD

**Issue by Ewasong** [Sayi/poi-tl#14]
1. 请问  TableRenderData width参数的单位是什么? 
2. 请问 可以处理table有两个头的情况么？
![image](https://user-images.githubusercontent.com/8654292/31328071-9d2b2cd8-ad05-11e7-8380-896ee5f3e68e.png)

**Comment by Sayi** [comment]
@Ewasong 
1. 单位是1440分之一个英寸。官方解释:
> dxa - Specifies that the value is in twentieths of a point (1/1440 of an inch).

这个单位有点复杂，是一个点的二十分之一，或者是1440分之一英寸。
首先1英寸=2.54厘米，A4纸大小为21cm*29.7cm。
如果这个width设置成5670，则表示这个表格的宽度是10cm：
```
5670inch/1440inch*2.54cm/inch=10cm
```

2. 是支持自定义表格处理的。  
因为表格布局每个开发者的需求都不一样，处理两个头需要自己来处理。可以把两个头的处理需求说的更详细点

**Comment by Ewasong** [comment]
@Sayi 
感谢

**Comment by Ewasong** [comment]
@Sayi 
非常抱歉,又来打扰你。

还想请教一个问题, 自己查了半天没有查到 可能自己方法有问题, 就是换行的问题。
我在单元格或段落中如何换行？
我看table的代码中 用的 
`XWPFRun.setText(String value)`
查询并琢磨了一下午还是不知道该如何换行。

尝试过 \r\n
\n
\r
(char)11
等

**Comment by Sayi** [comment]
@Ewasong  
由于公司历史上线版本使用的是\\\n作为换行标记，所以目前针对普通段落可以这样使用：
```java
"Deeply in love with \\n the things you love,\\n just deepoove."
```
下一版本将支持\n的方式。

很遗憾，表格内换行目前尚未支持，下一版本也将此特性加入，支持表格内通过\n换行。

非常感谢反馈问题，这周内会为这个迭代一个小版本。

**Comment by Sayi** [comment]
从1.2.0开始，换行支持\n，表格内文本也可以通过\n换行
```xml
<dependency>
    <groupId>com.deepoove</groupId>
    <artifactId>poi-tl</artifactId>
    <version>1.2.0</version>
</dependency>

```

**Comment by cc22868** [comment]
有没有将XWPFTable直接作为参数传进去的功能？？（相当于复制的功能）

**Comment by Sayi** [comment]
@cc22868 

既然你已经有了XWPFTable对象，你可以自定义策略，参考com/deepoove/poi/policy/SimpleTableRenderPolicy.java
直接插入这个表格。

**Comment by cc22868** [comment]
大神，有没有什么方法可以获取XWPFTableCell的宽高啊? （^。。 ^)

**Comment by Sayi** [comment]
@cc22868 

你可以google下poi的API
