### ISSUE TITLE
关于文档模板的建议

### ISSUE THREAD

**Issue by funyule** [Sayi/poi-tl#142]
文档模板生成的时候
DocxRenderPolicy
![image](https://user-images.githubusercontent.com/12372048/48120881-5b5fec00-e2ae-11e8-9d66-7696d8b751ba.png)
 这里限制了默认的policy，是不是可以把这个方法去掉私有，允许重写这一个方法呢，比如，文档里我们自己传一个策略进去

**Comment by Sayi** [comment]
你看的代码是旧的，最新版本是1.4.0  允许通过Configure来设置策略。

**Comment by funyule** [comment]
我去，搞这个搞了一天，结果....
