### ISSUE TITLE
向页眉添加图片，图片显示失败

### ISSUE THREAD

**Issue by xiaobrid** [Sayi/poi-tl#143]
使用默认标签“@”向页眉添加图片时，生成的word文件中页眉图片无法显示，提示“当前无法显示此图”

**Comment by Sayi** [comment]
@xiaobrid 你可以写个Junit单元测试附上来，我判断可能是图片数据的问题

**Comment by xiaobrid** [comment]
使用同一张图片，在word正文中可以正确显示，只是在页眉、页脚显示有问题

**Comment by Sayi** [comment]
这应该是个bug，如果不急的话，我会下个版本修复。

**Comment by xiaobrid** [comment]
poi方法（支持页眉、页脚、文档内容中添加图片）
XWPFRun.addPicture(java.io.InputStream pictureData,
                              int pictureType,
                              java.lang.String filename,
                              int width,
                              int height)
Parameters:
pictureData - The raw picture data
pictureType - The type of the picture, eg Document.PICTURE_TYPE_JPEG
width - width in EMUs. To convert to / from points use Units
height - height in EMUs. To convert to / from points use Units

**Comment by hackmagic** [comment]
今天使用遇到一样的问题了，找了半天不知怎么解决~~

**Comment by Sayi** [comment]
@xiaobrid @hackmagic 最初基于poi的3.10版本有问题，所以图片处理是重写的。

1.4.2版本已修复这个问题。

```xml
<dependency>
    <groupId>com.deepoove</groupId>
    <artifactId>poi-tl</artifactId>
    <version>1.4.2</version>
</dependency>
```
