### ISSUE TITLE
关于循环的问题

### ISSUE THREAD

**Issue by hugolubingshen** [Sayi/poi-tl#145]
我看了demo一篇文章的例子，我现在的需求是只要那个循环的内容，不要头尾，就是不需要将两个模板合并，如何一个模板实现循环的效果呢？

**Comment by Sayi** [comment]
你是想要一个模板被多套数据渲染后 直接合并，而不要合并到一个主模板是吧？

这样的话其实就是末尾处直接合并word文档就行了，不需要在特定位置合并。

**Comment by hugolubingshen** [comment]
不是很懂你的意思，能给个例子或者链接参考下吗

**Comment by Sayi** [comment]
一个模板无法实现循环

**Comment by hugolubingshen** [comment]
我懂了，我昨天也是用了两个模板搞，只是好奇能不能单个模板弄出循环，谢谢回答
