### ISSUE TITLE
添加横线

### ISSUE THREAD

**Issue by hugolubingshen** [Sayi/poi-tl#146]
可以用代码在word里面加横线吗？

**Comment by Sayi** [comment]
代码能表示的字符 应该都可以写入到word里面去，除非代码表示不了。

**Comment by hugolubingshen** [comment]
因为我有个需求，循环生成数据，需要某些地方加条横线，某些地方不要，所以不能写在模板呢

**Comment by Sayi** [comment]
代码里面字符串使用横线？应该可以的吧，比如这样： "姓名：__________"

**Comment by hugolubingshen** [comment]
😝哈哈哈，跟我想的一样
