### ISSUE TITLE
生成报告后，修改了我原来的表格样式

### ISSUE THREAD

**Issue by AnnaHuangPro** [Sayi/poi-tl#147]
你好~ 我生成报告之后 表格样式变了（封面的框我用的是表格的一个格子表示）
![image](https://user-images.githubusercontent.com/35721313/48308410-23eb8b00-e59f-11e8-9226-b6db47f9f0ed.png)
生成之后变成了下面这张图的样子
![image](https://user-images.githubusercontent.com/35721313/48308419-6319dc00-e59f-11e8-8983-17b011843201.png)
你知道这是什么原因吗？

**Comment by AnnaHuangPro** [comment]
而且修改了我原来模板的所有英文字体样式（ 伤心 大哭 不开心 流泪 桑心）

**Comment by Sayi** [comment]
麻烦你把单独封面 写一个junit单元测试附上来

**Comment by AnnaHuangPro** [comment]
封面没有占位符，封面是写死的，内容有占位符，生成之后封面的样式变了，全部文档的字体样式变了。
刚刚我又用单个封面加一页，一页中有1个占位符，然后生成的报告是正常的，不知道是不是下面的样式影响了它。

**Comment by AnnaHuangPro** [comment]
我大概是知道为什么了 因为两个文档的样式没有统一
