### ISSUE TITLE
你好~文档嵌套时，子模板中的DynamicTableRenderPolicy的渲染问题

### ISSUE THREAD

**Issue by AnnaHuangPro** [Sayi/poi-tl#148]
这是我的文档嵌套：
![image](https://user-images.githubusercontent.com/35721313/48353560-b50b5080-e6ca-11e8-83ec-92f0d681880e.png)
![image](https://user-images.githubusercontent.com/35721313/48353598-cb191100-e6ca-11e8-9c9f-e82841328f25.png)
子模板中有两个DynamicTableRenderPolicy表格；
然后我没有传数据给子模板，如图：
![image](https://user-images.githubusercontent.com/35721313/48353936-83df5000-e6cb-11e8-9d0e-cac93dc747a4.png)
再像下面图中这样把子模板和主模板的DynamicTableRenderPolicy标签渲染
![image](https://user-images.githubusercontent.com/35721313/48354053-bb4dfc80-e6cb-11e8-8b99-e7b745c9b39d.png)
最后的渲染失败了，请问是哪里写错了吗？麻烦你了~~~有点急谢谢你啦

**Comment by Sayi** [comment]
怎么渲染错了哦？

**Comment by AnnaHuangPro** [comment]
啊啊啊 你居然这么快回我了 谢谢你~
就是最后子模板文档的表格框架渲染出来了，还带着标签，数据也没有

**Comment by AnnaHuangPro** [comment]
我的子模板中只有两个待渲染的表格 没有其他占位符，那我是在子模板中渲染好了再合并到主模板的吗？那我应该传什么数据给子模板呢？因为config里写的我相当于是传给主模板的。

**Comment by Sayi** [comment]
主模板只是注册策略，DocRenderData构造器可以传数据的，数据是你自己需要的，好好看看DynamicTableRenderPolicy

**Comment by AnnaHuangPro** [comment]
好的 那我好好看一下 谢谢你啦

**Comment by AnnaHuangPro** [comment]
文档写出来了写出来了 谢谢你啦 太谢谢你啦 我已经语无伦次了 哈哈哈

**Comment by Sayi** [comment]
看这两个例子的源码：
http://deepoove.com/poi-tl/#example-article

http://deepoove.com/poi-tl/#example-table

**Comment by Sayi** [comment]
@AnnaHuangPro 额。。。。。不客气。。

**Comment by AnnaHuangPro** [comment]
最终的结果可以看到，就是不知道为什么打开word时会报错，我的是word2016，我只要信赖它打开内容是完整的，我测了一下，只有在我嵌套子模板，而且子模板中有DynamicTableRenderPolicy会报这个错。
![image](https://user-images.githubusercontent.com/35721313/48391976-17ecfe00-e744-11e8-872f-b271a1625819.png)
虽然可以看到最终结果，就是用户体验不好，不知道怎么去修复一下。

**Comment by Sayi** [comment]
附件发我邮箱

**Comment by AnnaHuangPro** [comment]
就发文档给你吗？

**Comment by Sayi** [comment]
恩

**Comment by AnnaHuangPro** [comment]
已经发给你啦 麻烦你了哟~
