### ISSUE TITLE
new XWPFDocument新建的文档无法用来合并

### ISSUE THREAD

**Issue by bigbencat** [Sayi/poi-tl#149]
函数：
    public NiceXWPFDocument merge(NiceXWPFDocument docMerge)

复现：
先新建一个文档：
NiceXWPFDocument docFirst = new NiceXWPFDocument();
然后 merge 已有文件的时候会报错。

问题可能：
应该是代码 String prefix = srcString.substring(0, srcString.indexOf(">") + 1) 
取的是第一个xml文件头，而里面没有包含第二个文件的schemer。

**Comment by Sayi** [comment]
@bigbencat 
```java
NiceXWPFDocument docFirst = new NiceXWPFDocument();
```
空参数的构造器一般用来创建文档使用，合并文档需要传一个文件参数，不知道你是什么场景需要空文档合并？

**Comment by Sayi** [comment]
代码创建的文档缺少某些元素，不适用于现在的合并方法。

So.....现在合并需要传递一个手动创建的文档。
