### ISSUE TITLE
MiniTableRenderPolicy 数据中存在空值导致后面的数据不渲染

### ISSUE THREAD

**Issue by xpalive** [Sayi/poi-tl#151]
MiniTableRenderPolicy.renderRow 方法在判断cellText时使用break
是否应该使用continue更为合理
![image](https://user-images.githubusercontent.com/4743854/48473360-3e3d9700-e833-11e8-9183-a79dd4793305.png)

**Comment by Sayi** [comment]
👍  master已修改

**Comment by Sayi** [comment]
```xml
<dependency>
    <groupId>com.deepoove</groupId>
    <artifactId>poi-tl</artifactId>
    <version>1.4.2</version>
</dependency>
```
