### ISSUE TITLE
请问一下 这样的表格怎么渲染数据呢

### ISSUE THREAD

**Issue by AnnaHuangPro** [Sayi/poi-tl#152]
![image](https://user-images.githubusercontent.com/35721313/48483154-a5684500-e84d-11e8-8836-2393e496357e.png)
不知道这样的表格怎么渲染数据

**Comment by AnnaHuangPro** [comment]
☺☺☺

**Comment by Sayi** [comment]
简单啊，想怎么渲染就怎么渲染

**Comment by AnnaHuangPro** [comment]
方向盘转角死区  | deg | 50km/h & 0.4g | 数据1 |  --
方向盘转角死区  | deg | 50km/h & 0.4g | 数据1 |  --

**Comment by AnnaHuangPro** [comment]
哭唧唧
我的想法是
按照这样的数据结构渲染吗
方向盘转角死区  | deg | 50km/h & 0.4g | 数据1 |  --
方向盘转角死区  | deg | 50km/h & 0.4g | 数据2 |  --
方向盘转角死区  | deg | 50km/h & 0.4g | 数据3 |  --
方向盘转角死区  | deg | 75km/h & 0.2g | 数据1 |  --
方向盘转角死区  | deg | 75km/h & 0.2g | 数据2 |  --
                       ....  .....
是这样一行一行的渲染吗？

**Comment by Sayi** [comment]
参见这个：http://deepoove.com/poi-tl/#example-table

**Comment by AnnaHuangPro** [comment]
我看了几遍啦☹ 因为这个例子是合并了列，一行一行的渲染只用看一行的单元格是多少个。 我这个表格是合并了行，我的想法是：前面几列进行了行的合并，是不是一行一行的渲染，然后前面已经合并的行只要数据一致就行了，不知道这样想是不是对的☹
