### ISSUE TITLE
MiniTableRenderData生成表格的时候表头和表体的格子一定要一样吗

### ISSUE THREAD

**Issue by AnnaHuangPro** [Sayi/poi-tl#153]
![image](https://user-images.githubusercontent.com/35721313/48534676-bc597680-e8e3-11e8-866e-ee83de9afe78.png)
想动态生成这样的表格结构 可以吗？

**Comment by Sayi** [comment]
怎么又是你。。。 表格样式千奇百怪，很难统一，需要自己实现策略。仔细看文档。

**Comment by AnnaHuangPro** [comment]
没有啦。。。我实现了很多表格样式的，这是这个表格比较简单,看能不能够用简单的方式来实现，好吧 我自己再看看吧
