### ISSUE TITLE
生成的表格有首行缩进问题 请问这个应该怎么处理呢

### ISSUE THREAD

**Issue by AnnaHuangPro** [Sayi/poi-tl#155]
![image](https://user-images.githubusercontent.com/35721313/48720598-f4054d00-ec5a-11e8-8f5f-e842f83a145d.png)
比较第一行和第二行（第二行是生成的）

**Comment by AnnaHuangPro** [comment]
我是继承自：DynamicTableRenderPolicy 完全操控这个表格，用table.getRow(row).getCell(col).setText("example") 来填充数据，
找了很久能够去设置这个表格的样式的API  没有找到~ 请问可以设置这个表格的样式吗？？~

**Comment by Sayi** [comment]
本身你的第二行表格格式是不是有缩进或者两个空格哦？

**Comment by AnnaHuangPro** [comment]
首行缩进这个问题我已经搞定了 主要是修改文档的段落的首行缩进改为空 还要保证多个模板的样式一样
