### ISSUE TITLE
com.deepoove.poi.el.Dot.evalKey 建议

### ISSUE THREAD

**Issue by xpalive** [Sayi/poi-tl#156]
获取对象属性值的时候是否能再加一种方式，通过get方法去读取属性值如下

`
PropertyDescriptor propertyDescriptor = new PropertyDescriptor(String propertyName, Class<?> beanClass);
propertyDescriptor.getReadMethod().invoke(vo);
`

且 get方式取得的值优于 Field.get(Object)的值
因为有时候会通过get方法去加工下数据格式

**Comment by Sayi** [comment]
最初也是按照你这样实现的，后来发现PropertyDescriptor在获取boolean类型数据的时候会因为大家缺乏一个统一命名标准而有问题(is的问题)，所以改成了现在的方式。

JavaBean是强烈不推荐改写get方法的，我觉得你可以考虑写个Utils类对需要改写的字段重新赋值。

**Comment by xpalive** [comment]
好的，受教啦
