### ISSUE TITLE
多个文档模板的问题

### ISSUE THREAD

**Issue by zonghsh** [Sayi/poi-tl#157]
一个文档中需要有多个文档模板时，比如有 {{+students}} 和 {{+teachers}}， 如果 students 为 null 时，生成的文件中  {{+students}} 的部分为空，无论 HashMap 里是否 put 了 teachers,  {{+teachers}} 部分总是不会被渲染。 怎么解决？

**Comment by Sayi** [comment]
给个Junit单元测试

**Comment by zonghsh** [comment]
package com.kedacom.ezview.data;

import com.deepoove.poi.XWPFTemplate;
import com.deepoove.poi.data.DocxRenderData;
import com.deepoove.poi.render.RenderAPI;
import lombok.Data;

import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author Shen Huang Jian
 * @date 2018-11-26
 */

public class GenDocTest2 {

    public static void main(String[] args) throws Exception{

        Map<String, Object> params = new HashMap<>();
        params.put("title", "testTitle");

        /* 不加入这一段， 虽然 {{+teachers}} 设置值了，但是仍然不会渲染
       List<Student> stuList = new ArrayList<>();
        Student p1 = new Student();
        p1.setName("test1");
        stuList.add(p1);

        p1 = new Student();
        p1.setName("test2");
        stuList.add(p1);

        params.put("students", new DocxRenderData(new File("F:/download/docGenTest/test_stu.docx"), stuList));*/

        List<Teacher> teacherList = new ArrayList<>();
        Teacher t1 = new Teacher();
        t1.setName("t1");
        t1.setAge(18);
        teacherList.add(t1);

        t1 = new Teacher();
        t1.setName("t2");
        t1.setAge(36);
        teacherList.add(t1);

        params.put("teachers", new DocxRenderData(new File("F:/download/docGenTest/test_teacher.docx"), teacherList));

        XWPFTemplate doc = XWPFTemplate.compile("F:/download/docGenTest/test_stu_tea.docx");
        RenderAPI.render(doc, params);

        FileOutputStream fos = new FileOutputStream("F:/download/docGenTest/output.docx");
        doc.write(fos);
        fos.flush();
        fos.close();


    }
}

@Data
class Student{
    private String name;

    private int age;
}

@Data
class Teacher{
    private String name;
    private int age;
}


test_stu_tea.docx 中的内容：
{{title}}

{{+students}}

{{+teachers}}

test_stu.docx 中的内容：
学生：{{name}}
年龄：{{age}}

test_teacher.docx 中的内容：
老师：{{name}}
年龄：{{age}}

**Comment by liuyake** [comment]
我现在也是使用文档合并，子文档是一段html，我把html转换为docx保存，再合并到主文档，发现会影响主文档的样式，而我手动把html粘贴到主文档中确没有出现这种情况，请问这是咋回事？可以给个思路吗？

**Comment by Sayi** [comment]
master已修复，我会在下一个版本发布。
