### ISSUE TITLE
模板替换不支持中文参数

### ISSUE THREAD

**Issue by 346673164** [Sayi/poi-tl#159]
TemplateVisitor下的正则不能匹配中文，参数中有中文就不会替换。看是否这部分可以自定义配置？多谢。

**Comment by Sayi** [comment]
#48

**Comment by Sayi** [comment]
什么场景需要中文？

**Comment by 346673164** [comment]
谢谢回复，感谢框架提供的很完善的功能。我的业务场景和#48这种有点类似，模板都是给不懂开发数据结构的人员使用，他们可能更希望能实现中文的替换。当时发现TemplateVisitor构造器私有，发现不能继承TemplateVisitor来达到修改正则的目的。

**Comment by Sayi** [comment]
可以通过修改源码，通过Configure类提供正则可配。
