### ISSUE TITLE
关于.docx文档合并，图片w:pict问题

### ISSUE THREAD

**Issue by h262729** [Sayi/poi-tl#160]
com.deepoove.poi.NiceXWPFDocument  的 merge() 方法

addPart = addPart.replaceAll("r:embed=\"" + relaId + "\"",
                    "r:embed=\"" + placeHolderblipIdsMap.get(relaId) + "\"");

这里有点问题，图片替换我这边检测应该是

addPart = addPart.replaceAll("r:id=\"" + relaId + "\"",
                    "r:id=\"" + blipIdsMap.get(relaId) + "\"");

如果是用 r:embed的话， 多份文档合并后，虽然会合并成功，但是打开后会报错，合并文档图片不显示

**Comment by Sayi** [comment]
可以把你的带图片的文档发给我看看？

**Comment by Sayi** [comment]
你这个图片是怎么插入进去的？具体word里面怎么操作的，我看并不像正常的图片

**Comment by h262729** [comment]
我是直接从文件夹拖进去的。。。

**Comment by Sayi** [comment]
告知一下Word版本号

**Comment by h262729** [comment]
LICENSE DESCRIPTION: Office 15, VOLUME_KMSCLIENT channel

**Comment by h262729** [comment]
![image](https://user-images.githubusercontent.com/35761148/49416236-49da0900-f7b4-11e8-9f19-6d8c84fcc39a.png)

**Comment by zview** [comment]
请教下，  怎么合并多个文档呢
