### ISSUE TITLE
占位符问题

### ISSUE THREAD

**Issue by lrc8000** [Sayi/poi-tl#161]
![e7089c9d0d4c17eaa9f9b86cc4eee65](https://user-images.githubusercontent.com/44364528/49436324-d0faa180-f7f3-11e8-8691-bba37c93d6df.png)
填充后，有些占位符会只剩下左边，而且数据没填充成功。

**Comment by Sayi** [comment]
给个junit单元测试

**Comment by lrc8000** [comment]
第一次提问题表达不好请见谅
下面是我的test

@Test
    public void test88() throws Exception {

//测试数据
        Map<String,String> dataMap = new HashMap<>();
        dataMap.put("projectName","项目名称test");
        dataMap.put("designDeptName","设计单位test");
        dataMap.put("applyUnitName","申请单位test");
        dataMap.put("ownerDeptName","建设单位test");
        dataMap.put("optimizeReason","变更原因test");
        dataMap.put("optimizeChangeName","审查方案test");
        dataMap.put("changeType","变更类型test");
        dataMap.put("moneyChange","变更数test");
        //主路径
        String mainPath = PrintTest.class.getClassLoader().getResource("").getFile();
        //模板
        String templatePath =  mainPath + "test.docx";
        //生成的目标文件
        File f = new File(mainPath  + "newFile.docx");
        XWPFTemplate template = XWPFTemplate.compile(templatePath).render(dataMap);
        OutputStream out = new FileOutputStream(f);
        template.write(out);
        out.flush();
        out.close();
        template.close();

    }


//填充前
![270ed185479de3e23aa690f8d48cfd8](https://user-images.githubusercontent.com/44364528/49439543-45d1d980-f7fc-11e8-958d-693afb91b44c.png)
//模板后
![7081affc8508cdaec0ae0c7ed2ecbba](https://user-images.githubusercontent.com/44364528/49439501-23d85700-f7fc-11e8-8008-50872342a13a.png)

**Comment by Sayi** [comment]
@lrc8000 你好，是因为出现了三个enter键导致的，分别在：
1. (建设单位) +enter键
2. 元。+enter键
3. 材料 + enter键

你把所有enter键换成return键再试试？
![image](https://user-images.githubusercontent.com/1394854/49494405-897b2080-f89a-11e8-9e0e-9d14f6674aea.png)

**Comment by Sayi** [comment]
#111

**Comment by WangShaoYang** [comment]
> @ lrc8000你好，是因为出现了三个输入键导致的，分别在：
> 
> 1. （建设单位）+ enter键
> 2. 元。+ enter键
> 3. 材料+输入键
> 
> 你把所有输入键换成返回键再试试？
> ![图片](https://user-images.githubusercontent.com/1394854/49494405-897b2080-f89a-11e8-9e0e-9d14f6674aea.png)

请问return键是哪个键？键盘上没有找到
