### ISSUE TITLE
merge文档有bug

### ISSUE THREAD

**Issue by jacklincao** [Sayi/poi-tl#163]
使用官方demo来运行，一样会出现这样的错误，请问这是什么导致的？感谢
![4x3d qn1 mal1 mm31lzae3](https://user-images.githubusercontent.com/22211197/49716637-48ff1680-fc8f-11e8-947c-e89637cd2218.jpg)

**Comment by Sayi** [comment]
官方demo是哪个示例？

**Comment by jacklincao** [comment]
文件xml的abstractNumId重复

**Comment by Sayi** [comment]
复用导致的，master已修复。
