### ISSUE TITLE
文档转成xml后 {{+doc}}

### ISSUE THREAD

**Issue by AnnaHuangPro** [Sayi/poi-tl#166]
现在有两个连续的{{+doc}}标签，当只给第二个标签赋值的时候，会报错
![image](https://user-images.githubusercontent.com/35721313/49785128-75339980-fd5a-11e8-9338-10f3c2ce2ea5.png)
转成xml后发现
![image](https://user-images.githubusercontent.com/35721313/49785156-90060e00-fd5a-11e8-85b5-fb2c6f2bf1b4.png)
产生这个报错是因为这个原因吗？
（如果同时给两个标签赋值就不会报错）

**Comment by Sayi** [comment]
你现在问问题的时候 越来越专业了 

报啥错？你试试最新版本1.4.2？

**Comment by AnnaHuangPro** [comment]
哈哈哈哈哈哈 谢谢你
我昨天晚上刚好换成了1.4.2
后台控制台报的是找不到前缀
![image](https://user-images.githubusercontent.com/35721313/49788386-2f7bce80-fd64-11e8-818e-c06261f9ffc3.png)
可以生成文档 但是{{+doc}}内容没有渲染出来
要不然我发个测试用例给你？

**Comment by Sayi** [comment]
好

**Comment by AnnaHuangPro** [comment]
//测试代码

[docxQiantao.zip](https://github.com/Sayi/poi-tl/files/2666859/docxQiantao.zip)

//测试模板
[story.docx](https://github.com/Sayi/poi-tl/files/2666845/story.docx)
[segment.docx](https://github.com/Sayi/poi-tl/files/2666846/segment.docx)
[segmentTwo.docx](https://github.com/Sayi/poi-tl/files/2666848/segmentTwo.docx)

**Comment by Sayi** [comment]
并没有重现你的错误，发现了 #163 这个错误的原因。。。。

**Comment by AnnaHuangPro** [comment]
第一个标签我没有赋值；第二个标签我赋值了；
![image](https://user-images.githubusercontent.com/35721313/49799598-50521d00-fd80-11e8-8bbe-77ee92571673.png)
但是最后的文档是
![image](https://user-images.githubusercontent.com/35721313/49799676-7d9ecb00-fd80-11e8-8033-779494db51a3.png)
标签1没有了（是正常的）；标签2赋值了，但是结果没有渲染（但是这个demo里面没有报错）。
#163 的错误原因是什么？

**Comment by Sayi** [comment]
确定用的1.4.2？我这里和你说的结果不一样

**Comment by AnnaHuangPro** [comment]
我确定用的1.4.2 那我再刷新gradle试试吧
![image](https://user-images.githubusercontent.com/35721313/49810653-9e751980-fd9c-11e8-9316-590a9fe4d353.png)

**Comment by AnnaHuangPro** [comment]
我还是不得行。。。
