### ISSUE TITLE
请问可以支持附件插入否?

### ISSUE THREAD

**Issue by FengTian2** [Sayi/poi-tl#167]
有时希望在WORD的指定位置插入个附件，如TXT，EXCEL等文件，
如果能像文本那样有便捷接口直接插入就好了！

**Comment by Sayi** [comment]
需要自定义插件了

**Comment by LuciferWeidy** [comment]
请问这种插入附件的自定义插件应该怎么写？我项目中正好遇到在word中插入附件的需求。

**Comment by Sayi** [comment]
@LuciferWeidy 可以google下 如何使用Apache poi 插入附件，如果可以的话再利用poi-tl在指定位置插入附件。

**Comment by LuciferWeidy** [comment]
我下午研究了一下，poi好像也不支持 插入附件

**Comment by wikicoo** [comment]
是否可以增加转换pdf功能

**Comment by 2582167435** [comment]
> 我下午研究了一下，poi好像也不支持 插入附件
我现在也需要这个功能，请问有解决办法吗？

**Comment by 2582167435** [comment]
> 我下午研究完了，poi 好像也不支持插入附件

请问您这边最后怎么解决的？ word中插入附件

**Comment by 2582167435** [comment]
> 有时希望在WORD的指定位置插入附件，如TXT、EXCEL等文件， 如果能像文本那样有演示接口直接插入就好了！

请问最后有解决方案吗？

**Comment by tonggangjin** [comment]
我也有这个需求，但是不知道怎么弄

**Comment by Sayi** [comment]
是希望实现什么样的效果？word中插入一个word或者excel附件，word中以图标显示出来？

**Comment by 2582167435** [comment]
> 是希望实现什么样的效果？word中插入一个word或者excel附件，word中以图标显示出来？

是的，最好可以这样。

**Comment by 2582167435** [comment]
是的，最好可以这样。

**Comment by tonggangjin** [comment]
> 是希望实现什么样的效果？word中插入一个word或者excel附件，word中以图标显示出来？

对的，能够插入另外一个excel作为附件就最完美了

**Comment by Sayi** [comment]
![image](https://user-images.githubusercontent.com/1394854/142977403-cea84ef3-859b-428e-9832-98b4e4117c31.png)
类似这样的效果？附件类型有哪些？？？

**Comment by 2582167435** [comment]
> ![image](https://user-images.githubusercontent.com/1394854/142977403-cea84ef3-859b-428e-9832-98b4e4117c31.png) 类似这样的效果？附件类型有哪些？？？
> 
> @tonggangjin @2582167435

对我来说有excel（xlsx）就够了。

**Comment by 2582167435** [comment]
老师 有什么实现思路么？我已经被卡了好几周了。。

**Comment by gudqs7** [comment]
> 老师 有什么实现思路么？我已经被卡了好几周了。。

试试先在模版中插入一个附件, 然后写一个 插件, 插件里获取出这个附件的输入/输出流, 将Excel从 out 流写入, 如果 Excel 是个模版, 可以用 in 流读取后修改了再写入... 甚至可以使用 easyexcel 直接往 out 流写. 参考代码

```java
            XWPFDocument docx = run.getDocument();
            List<PackagePart> embeddedDocs = docx.getAllEmbeddedParts();
            if (embeddedDocs==null || embeddedDocs.isEmpty()) {
                return;
            }
            for (PackagePart pPart : embeddedDocs) {
                String ext = pPart.getPartName().getExtension();
                if (BINARY_EXTENSION.equals(ext) || OPENXML_EXTENSION.equals(ext)) {
                    try (
                            InputStream is = pPart.getInputStream();
                            Workbook workbook = WorkbookFactory.create(is);
                            OutputStream os = pPart.getOutputStream()
                    ) {
                        Sheet sheet = workbook.getSheetAt(SHEET_INDEX);
                        Row headerRow = sheet.getRow(FLAG_ROW_INDEX);

                        int startRow = FLAG_ROW_INDEX + 1;
	                // 这里若有多个附件, 还可以读取指定指定单元格预先设置的标识(行+列) 来区分是哪个附件

                        workbook.write(os);
                    }
                }
            }
```

若是模版中的附件的数量和位置是固定的, 可以试试我的方法, 如果是数量根据具体的数据来的, 则可以等作者大佬更新嵌套文档对 Excel 附件的支持, 见 PR  https://github.com/Sayi/poi-tl/pull/689

**Comment by 2582167435** [comment]
> 入附件了, 但是我对 <v:shape> 和 <o:OLEObject> 这俩个不太熟悉.
> 按理说, 先把附件加到 packagePart 中, 在添加 packagePart 的 relation, 在添加与 document 的 relation(得到 rId), 然后把 rId 绑定到 <o:OLEObject> 的 r:id 上就行了,
> 然后 shape 需要一个图片的附件

第一步附件插入packagePart我就没成功，没有找到对应的类，直接写入xml也没有成功，，你说的这个模板包含附件的我去试一下！感谢

**Comment by gudqs7** [comment]
> 第一步附件插入packagePart我就没成功，没有找到对应的类，直接写入xml也没有成功，，你说的这个模板包含附件的我去试一下！感谢

@2582167435 哈哈哈, 有方法的 参考`org.apache.poi.ooxml.POIXMLDocumentPart#createRelationship(org.apache.poi.ooxml.POIXMLRelation, org.apache.poi.ooxml.POIXMLFactory, int, boolean) `. 
它是先创建出一个 part, 然后通过 out 流写数据进去, 不是根据 in 流创建一个 part !
另外这个方法有个问题就是文件名后缀没发改, 固定就是 xlsx, 需要改造下才行!

这个就交给作者大佬了

**Comment by 2582167435** [comment]
> > 附件插入插件部分我成功了，没有找到对应的类，这个插件直接写入xml也没有成功，你说的插件插件我去试一下！
> 
> @2582167435高，有方法参考`org.apache.poi.ooxml.POIXMLDocumentPart#createRelationship(org.apache.poi.ooxml.POIXMLRelation, org.apache.poi.ooxml.POIXMLFactory, int, boolean) `。 它先创建出一个部分，然后通过流出的流写数据进去，不是根据在流创建部分！ 另一种方法有一个问题就是文件名后缀没有发，固定就是xlsx，需要改造下才行！
> 
> 这就是作者大佬了

请问有没有具体的示例？感谢！

**Comment by gudqs7** [comment]
> 请问有没有具体的示例？感谢！

@2582167435 
#689  参考下我提交的 PR, XmlXWPFDocumentMerge.java 中 mergePackageByRelationType 方法
注意是我提交的内容里找

**Comment by Sayi** [comment]
感谢@gudqs7 的支持，master代码已提交，新增两个特性：
* AttachmentRenderPolicy 插件支持插入附件，附件类型为docx或者xlsx，数据结构为AttachmentRenderData，构造器使用Attachments，单元测试见AttachmentRenderTest
* 支持附件的合并

预计下个版本(1.11.0和1.10.2)发布。

**Comment by luokui-c12** [comment]
我参考AttachmentRenderPolicy写了一个其他文件类型的附件Policy，但是我自定义的附件内容package part没加进去

**Comment by lokinell** [comment]
`public class AttachmentChemRenderPolicy extends AbstractRenderPolicy<AttachmentChemRenderData> {

    private static final String CDX_DOCUMENT_12 = "ChemDraw.Document.6.0";
    private static final String SHAPE_TYPE_ID = "_x0000_t75";
    private static final String SHAPE_TYPE_XML = "<v:shapetype id=\"" + SHAPE_TYPE_ID + "\" coordsize=\"21600,21600\" o:spt=\"75\" o:preferrelative=\"t\" "
                + "                      path=\"m@4@5l@4@11@9@11@9@5xe\" filled=\"f\" stroked=\"f\">\n"
                + "                        <v:stroke joinstyle=\"miter\"/>\n" 
                + "                        <v:formulas>\n"
                + "                            <v:f eqn=\"if lineDrawn pixelLineWidth 0\"/>\n"
                + "                            <v:f eqn=\"sum @0 1 0\"/>\n"
                + "                            <v:f eqn=\"sum 0 0 @1\"/>\n"
                + "                            <v:f eqn=\"prod @2 1 2\"/>\n"
                + "                            <v:f eqn=\"prod @3 21600 pixelWidth\"/>\n"
                + "                            <v:f eqn=\"prod @3 21600 pixelHeight\"/>\n"
                + "                            <v:f eqn=\"sum @0 0 1\"/>\n"
                + "                            <v:f eqn=\"prod @6 1 2\"/>\n"
                + "                            <v:f eqn=\"prod @7 21600 pixelWidth\"/>\n"
                + "                            <v:f eqn=\"sum @8 21600 0\"/>\n"
                + "                            <v:f eqn=\"prod @7 21600 pixelHeight\"/>\n"
                + "                            <v:f eqn=\"sum @10 21600 0\"/>\n"
                + "                        </v:formulas>\n"
                + "                        <v:path o:extrusionok=\"f\" gradientshapeok=\"t\" o:connecttype=\"rect\"/>\n"
                + "                        <o:lock v:ext=\"edit\" aspectratio=\"t\"/>\n"
                + "                    </v:shapetype>\n";
    
    private static final String cdxIcon = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAABXFJREFUeF7tW3tQVFUc/u7dxQU1bPJZoBLQDIWwV0EqnRo0iLKEQEbyQVpjCgnGkDkRwWypNWpOBiNPS0GzUEHy1eAjBcEnfzQp5oROWWg6IiEUk+De25xloL3cu487tevZ7v7+2/O49/d953e/3zlnz2GgcmNowx9qCJ/wvaHxvLP8umcERBoiPdvQwTFGgeMFhmNY6CGAA+DppfEYdtpwusMZJDiFgDBD2IjuuzzHsqyeFwSOIUAZTLAE0KUJ4Aycn5HX6hme5xgGnADTqPopGU2XIUCfow/mGU3viPaOqh7ASCVg5dpSR0BgXqBu8M1hHCMInMAwHCAQoGRkvf4tWOoICMqKGD7Io4eMqt4EtleYQhwBlBoN4HK4yUawWQwEDmAediZYuXf5hPrka7Wabkf5cRco/Ca++jJ5vikLEAJ4sGcc9UKlz/XV+4LVsEq7KWq/76VqFgwE1RLA8GzE3llVZ90EqPUTcEeA+xNwa4BbBKnNAiey6zBEN0SU12dWx/f/nhOUhLlBL9ud99+tz8G5VvEWA9Ui6CaAtghInbZENtwECCg6WmIxFCP8JyNs/CTZ+sKjxRb7URcBAaP8UZW2U+Jwj7EH4e8/YRFI+euboR8bKqr/804XlpSl4lyL5W0/6gggCFYlfICZ3AsSsBsO5mFzfZmkPCr4GaxPWispzz9SgE21n1kVMGcshhSLoE6rw5ncExLHr9++gZj1MyTlX6Zsw2MPPSoqP/tTIxaXpYLnedcjgHhMtCBl2mKJ82sOrMP2U1/1l88Kj0du7HuSdqnlaThx6aTN9EVlBPR53ZBdi6G6oSIQTVcvYG5xcn+Z3OhvaSjHJzWf2gRPGpSmFMFrkHi3jeTyPiPzgJARFjeVpdF4seK/mwcQHSB6MNBW7MhCzfmDSAxPQE5stqi6vasdcXkJaO+6bRcBVIqguecVqV8g6MEgEZi6H48jfVsG5JS/jxy70AOgnoCJ4zhsWSRV8jlF80HC39zqmxuwdOsye7Gb2lFPAHHy46Q1iA6OEgHb1Vhl+gTM7cUNcfi1reX/R8DI+0bg8Ns1VoEVHytFwbdFisCTxjHTn4VWqxX1M1/MKBHAvoc4ZDGUEZ2OV59aKAvwZmcrotbFKAZPOlCdBs0RLX8uE8lT5lkESTThwrUfFJPgEgQEjgpAZdoOq+AIeEKCUnOJT2Db4jKE+IonIycvn8KTAeLF0co9q0HEUYlRnwXkprpXbv2Csvpy5MZJp8DT10bj1h9tdnNANQFjho1BzVv7JWCI2lc27sb2lHKM9h4tSY8kEuw1qglYGW9A7MSZIizX2n/D7II56PyrE4uefg3pUUslWN/Ymo6GZulqUo4UagkgEx8yARpoGw7lYfPx3j0BDavB18uqMPYBX1EzIojzSxbAyBttBgKViyFvL28Q4Rs/fJwIwM+tV0wLHXMjqZGkyIGWf3gjNtV9bpMAKtNgZkwGFkz9Z8nbh8KSyu9O3wn/kf4SsPOKX8H5q01WSaCOgKmPTEFBcr7E6eYbl5C4MUkWzIzQ5/FR4ipJ3aGmI1hescJ1CPDQeKBkYSEmjZ8ocfrN7Zk4drHWIhi5uQJpvHLPh9jVWGmxH1UiaGlLnHhvbWub1D/uHyFLHKnb+91+tPwuv0qkigCbiuWABm4CaPtnyAGDbPWRqo8A6tKgsyPATYATzgkq/mvMmVHgjgB3BDj+qKz7E1D7OcF98dWmY8L9Z4WpOi4f7LOa9dDccZTwCsbu0gOzD1zvJ8D8Raq8MGGL6cD0QN3g+1VyZcYWGeb1qrk0pYQU7h3OzzhIJdfm7CVGVRcn7SXFzxDp6d3TwTGsCq7O2ksKaaeay9NKSHFk278BpaKbbiHMt1QAAAAASUVORK5CYII=";
	private static final String CDX_CONTENTTYPE = "application/vnd.openxmlformats-officedocument.oleObject";

    private static boolean haveShapeType;

    @Override
    protected boolean validate(AttachmentChemRenderData data) {
        return null != data && null != data.getAttachment() && null != data.getFileType();
    }

    @Override
    protected void afterRender(RenderContext<AttachmentChemRenderData> context) {
        super.clearPlaceholder(context, false);
    }

    @Override
    public void doRender(RenderContext<AttachmentChemRenderData> context) throws Exception {
        NiceXWPFDocument doc = context.getXWPFDocument();
        XWPFRun run = context.getRun();
        CTR ctr = run.getCTR();

        // Only one shapetype is needed
        String shapeTypeXml = "";
        if (!haveShapeType) {
            haveShapeType = true;
            shapeTypeXml = SHAPE_TYPE_XML;
        }

        String uuidRandom = UUID.randomUUID().toString().replace("-", "") + ThreadLocalRandom.current().nextInt(1024);
        String shapeId = "_x0000_i1025" + uuidRandom;

        AttachmentChemRenderData data = context.getData();
        AttachmentChemType fileType = data.getFileType();
        byte[] attachment = data.getAttachment();

        String contentType = "";
        String part = "";
        String progId = "";
        if (fileType == AttachmentChemType.CDX) {
            progId = CDX_DOCUMENT_12;
            contentType = CDX_CONTENTTYPE;
            part = "/word/embeddings/ChemDraw" + uuidRandom + ".cdx";
        }
        PictureRenderData icon = data.getIcon();
        if (null == icon) {
            icon = Pictures.ofBase64(cdxIcon, PictureType.PNG)
                    .size(64, 64)
                    .create();
        }
        byte[] image = icon.readPictureData();
        PictureType pictureType = icon.getPictureType();
        if (null == pictureType) {
            pictureType = PictureType.suggestFileType(image);
        }

        PictureStyle style = icon.getPictureStyle();
        if (null == style) {
            style = new PictureStyle();
        }
        double widthPt = Units.pixelToPoints(style.getWidth());
        double heightPt = Units.pixelToPoints(style.getHeight());

        String imageRId = doc.addPictureData(image, pictureType.type());
//        String embeddId = doc.addEmbeddCdxData(attachment);
        String embeddId = doc.addEmbeddCdxData(attachment, contentType, part);

        String wObjectXml = "<w:object xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\""
                + "             xmlns:v=\"urn:schemas-microsoft-com:vml\""
                + "             xmlns:w14=\"http://schemas.microsoft.com/office/word/2010/wordml\""
                + "             xmlns:o=\"urn:schemas-microsoft-com:office:office\""
                + "             xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\""
                + "             w:dxaOrig=\"8662\" w:dyaOrig=\"3067\" w14:anchorId=\"2CD37D77\">\n" + shapeTypeXml
                + "                    <v:shape id=\"" + shapeId + "\" type=\"#" 
                                            + SHAPE_TYPE_ID + "\" alt=\"\" style=\"width:" + widthPt + "pt;height:" + heightPt
                                            + "pt;mso-width-percent:0;mso-height-percent:0;mso-width-percent:0;mso-height-percent:0\" o:ole=\"\">\n"
                + "                        <v:imagedata r:id=\"" + imageRId + "\" o:title=\"\"/>\n"
                + "                    </v:shape>\n"
                + "                    <o:OLEObject Type=\"Embed\" ProgID=\""+ progId + "\" ShapeID=\"" + shapeId
                                            + "\" DrawAspect=\"Content\" ObjectID=\""+shapeId+"\" r:id=\""+ embeddId + "\">\n"
                + "                    </o:OLEObject>"
                + "            </w:object>";

        Document document = DocumentHelper.readDocument(new InputSource(new StringReader(wObjectXml)));
        XmlObject parse = XmlObject.Factory.parse(document.getDocumentElement(), POIXMLTypeLoader.DEFAULT_XML_OPTIONS);
        ctr.set(parse);
    }

}
`
