### ISSUE TITLE
导出表格是动态的，模板多余的{{#var}}如何取消？（我用了自定义渲染策略，没有消除）

### ISSUE THREAD

**Issue by hy529283176** [Sayi/poi-tl#169]
**1.先说一下遇到的坑。**
       公司要到出word，大佬使用了这个开源项目的依赖。经过多次查看源码，才懂得，这个框架对一些表格啊，图片啊都是强转，结果前端传来的json数据，转成Map后，以为就能导出，结果在到表格或图片的policy时不能将数据对象强转成功，然后导出失败。后来得自己把表格数据进行封装成框架定义的实体类对象，才能导成功，还有合并单元格的工具使用也合并不了，貌似是循环里面的起始行问题，多加了1，反正不清楚是不是。百度的合并单元格方法可以用，所以最终用了自定义渲染策略，自己写个policy去实现，用了百度的方法，可以合并了，然后终于导出想要的效果，也灵活一些。这里想建议，在policy的 数据，作者不要直接就强转啊，这个不一定都能成功吧
源码里的代码，MiniTableRenderData tableData = (MiniTableRenderData) data;
       这步的 data，如果是像demo，自己new正确的实体对象，是没问题啊，但如果不是呢？
直接通过data.get(key);来获取值，然后封装也行。其实很多数据的转换很少直接强转，要强转也行，比如net.sf.json包里，json字符串转对象或者集合。这样转换时，实体类型材统一。
List<CADCoverageName> cadCoverageNameList = (List<CADCoverageName>) JSONArray.toCollection(rowDataArray,CADCoverageName.class);
   

**2.现在说一下遇到的问题。**
就是前端页面传来的表格数据对象个数是不固定的，但模板里面的变量{{#var}}我默认设置了6个（当前最多会存在6个），可能是自定义渲染策略吧，比如说，表格对象只有有两个，渲染了，结果剩下的四个{{#var}}变量没消除，图片的渲染是用框架默认的，是可以消除多余的{{@var}}变量。

**所以我想问多余的{{#var}}怎么消除？在自定义的policy里面操作吗？**

**Comment by Sayi** [comment]
谢谢你的建议和打赏。:smile:

**Comment by a1105013796** [comment]
@Sayi 遇到了类似的问题，我使用的是poitl默认的表格渲染，当表格有数据的时候，会生成表格去渲染{{#var}}，是可以正常渲染的，但是当没有数据的时候，map中我赋了null，渲染后模板中的{{#var}}没有被消除
