### ISSUE TITLE
我根据demo示例代码 导出后 显示的空白 word

### ISSUE THREAD

**Issue by tiandimengzhu** [Sayi/poi-tl#170]
String name=fileName+".docx";
        // 下载文件的默认名称
        response.setHeader("Content-Disposition", "attachment;filename=" + URLEncoder.encode(name, "utf-8"));
        File file = ResourceUtils.getFile("classpath:templates/temp.docx");
        XWPFTemplate template = XWPFTemplate.compile(file.getPath()).render(params);
        FileOutputStream out = new FileOutputStream(file.getPath());
        template.write(out);
        out.flush();
        out.close();
        template.close();

**Comment by Sayi** [comment]
过期关闭
