### ISSUE TITLE
word文档合并异常：word中带有图表

### ISSUE THREAD

**Issue by tinet-shenjg** [Sayi/poi-tl#172]
模板生成的多个XWPFDocument进行合并后导出word在office中打开需要修复提示文档内容损坏，wps则可以打开，求解
![image](https://user-images.githubusercontent.com/25969983/50537993-22077680-0ba3-11e9-8227-6d16a09f3f94.png)

**Comment by 0nise** [comment]
同样的问题，在进行文档合并的时候出现，文档损坏。

**Comment by Sayi** [comment]
可以给个单元测试方便定位。

**Comment by ScalletaZ** [comment]
我貌似也有类似问题 合并超过165条就会错误

**Comment by haojw123** [comment]
你好 同样的问题，我定位到问题是因为文档合并和后自定义的样式不会合并，几个文档拼接样式就会复制几遍，最后导致样式太多文档损坏。请问怎么修改一下设置样式的代码能解决这个问题呢？

**Comment by Sayi** [comment]
@haojw123 如果是样式太多的原因，可以判断如果是同一个文档多次合并，样式只合并一次

**Comment by haojw123** [comment]
@Sayi 你好  是不同的文档，比如自定义一个样式（word自带的样式不会有问题）叫投标标题，每个模版里都有投标标题，拼接完样式列表里 就变成投标标题1，投标标题2，投标标题3，投标标题4 …… 。

**Comment by Sayi** [comment]
你总共有多少个模板？

**Comment by haojw123** [comment]
@Sayi 这个不一定 10个左右吧

**Comment by liruilirui** [comment]
XWPFTemplate文档合并怎么实现？

**Comment by haojw123** [comment]
你用的是poi-tl么？ poi-tl 有写好的方法 。NiceXWPFDocument 类里有 merge方法，你可以看一下。

**Comment by liruilirui** [comment]
> 你用的是poi-tl么？ poi-tl 有写好的方法 。NiceXWPFDocument 类里有 merge方法，你可以看一下。

XWPFRun主要作用是什么，感觉用不到呀

**Comment by nywujunhua** [comment]
合并完的文档报样式错误，wps能打开，但是office打不开

**Comment by haojw123** [comment]
@nywujunhua 我之前也遇到过，原因是1.样式太多，2.拼接之前有图表（不是图片也不是表格，是图表），如果有图表拼接之后word也打不开，但是wps可以。

**Comment by nywujunhua** [comment]
有没有处理办法？

**Comment by Sayi** [comment]
poi 4.0.0以后对图表操作有改进，提供了XWPFChart类，目前版本子模板含有图表的确会出现BUG

**Comment by Sayi** [comment]
poi-tl 1.7.x 版本以后如果有图表的话，循环可以使用区块对，就不会存在图表合并的问题了。

**Comment by GuoSakura** [comment]
区块对里如果有图片循环样式全部丢失了
