### ISSUE TITLE
文档嵌套标签{{+var}}

### ISSUE THREAD

**Issue by forgiveForever** [Sayi/poi-tl#175]
有多个连续的文档嵌套标签  前面的嵌套标签值为空，为空的标签模板让它不渲染出来

**Comment by Sayi** [comment]
最新版本这个bug应该解决了，你试下1.4.2

**Comment by forgiveForever** [comment]
可是我就是用的最新版的 1.4.2

**Comment by excepuiohao** [comment]
我也是用的1.4.2 .遇到了同样的问题。

**Comment by excepuiohao** [comment]
我查看了一下你的提交记录，然后将其和maven下载下来的1.4.2的包进行了对比。发现1.4.2的包中的render.java代码是有bug的代码。我已将最新的代码替换。测试解决了这个问题。谢谢

**Comment by Sayi** [comment]
@excepuiohao 可以描述下你出现的问题吗？

**Comment by excepuiohao** [comment]
问题就是：当一个word中存在多个{{+var}}，而为null的{{+var}}数量大于1时，第一个{{+var}会在word中被渲染为空，第二个及其以后的{{+var}}就会直接显示在word中，没有渲染。
这个问题在你的commit中已经解决了，当DocxRenderPolicy为null的时候，continue而不是break。
