### ISSUE TITLE
多种日期format要怎么处理，表达式能不能带参？

### ISSUE THREAD

**Issue by Lroyia** [Sayi/poi-tl#177]
RenderPolicy好像是表达式能直接在数据源中找到数据才执行渲染的，那假如找到的是Date，我希望能够通过传参的方式来设置format格式的话怎么办？又或者要通过传参的方式设置数字的保留位数怎么办？

**Comment by Sayi** [comment]
为什么不考虑先把数据格式化？而要通过传参方式来动态格式化？

**Comment by Lroyia** [comment]
因为同一个数据的格式可能有很多个

**Comment by Lroyia** [comment]
而且有的时候还要对这个时间进行前推或后退处理

**Comment by Sayi** [comment]
可以在造某个标签数据的时候指定呀？提前格式化好。

**Comment by Lroyia** [comment]
问题就是太多，如果我需要一个前推时间，一个后退时间，一个原来时间，再加上5中format，我就得定义15个标签。单说制作模版的情况下，就需要多记14个标签。这样不太靠谱吧。。

**Comment by Sayi** [comment]
可以打个比方说下你希望的标签是什么？然后渲染出的结果是什么吗？

**Comment by Lroyia** [comment]
{{订单日期}}
结果：yyyy-MM-dd HH:mm:ss 前推1小时
yyyy-MM-dd HH:mm:ss 前推7分钟
HH:mm:ss 前推1分钟
mm:ss 后退1分钟
yy/MM

**Comment by Lroyia** [comment]
以上是几种结果的简单举例，还有很多种可能性，所以我希望能接受传参。能动态设置format

**Comment by Sayi** [comment]
既然是一个标签，`订单日期`对应的数据可以直接构造成下面这样，不行吗？
```
yyyy-MM-dd HH:mm:ss 前推1小时
yyyy-MM-dd HH:mm:ss 前推7分钟
HH:mm:ss 前推1分钟
mm:ss 后退1分钟
yy/MM
```

**Comment by Sayi** [comment]
下个版本1.5.0会支持SpEL表达式，支持这种特性，标签写法如下：
```java
{{new java.text.SimpleDateFormat('yyyy-MM-dd HH:mm:ss').format(time)}}
```

或者自定义CustomDate，实现format方法，标签写法如下：
```java
{{time.format('yyyy-MM-dd HH:mm:ss')}}
```
