### ISSUE TITLE
能否设置插入图片的板式，比如嵌入型，紧密环绕型等文字环绕效果

### ISSUE THREAD

**Issue by greentealc** [Sayi/poi-tl#178]
比如我在表格中插入图片，但是默认的嵌入型会显示不了图片，设置文字环绕才有效果

**Comment by EricMo** [comment]
你解决了没？？？我现在也需要这个功能。

**Comment by Sayi** [comment]
使用Apache-POI相关API

**Comment by VeThent** [comment]
有解决的吗..看下代码

**Comment by BigBroB** [comment]
工具能否直接就提供一个设置属性呢？如果是自己去操作的话，需要具体用到哪个api呢？

**Comment by lwx475784** [comment]
我也碰到这个问题，默认插入图片格式是嵌入型，想设置成四周型，没有提供设置方式，求大神看下 @ @ @

**Comment by lwx475784** [comment]
已找到解决方案，关于word中图片布局可以参靠：https://stackoverflow.com/questions/47673133/change-image-layout-or-wrap-in-docx-with-apache-poi，修改内置模板策略PictureRenderPolicy即可
我的修改：`public static void renderPicture(XWPFRun run, PictureRenderData picture) throws Exception {
            int suggestFileType = suggestFileType(picture.getPath());

            InputStream ins = null == picture.getData() ? new FileInputStream(picture.getPath())
                    : new ByteArrayInputStream(picture.getData());

            run.addPicture(ins, suggestFileType, "Generated", picture.getWidth() * EMU,
                    picture.getHeight() * EMU);
            //处理照片布局
            if (Layout.AROUND == picture.getLayout()) {
                CTDrawing drawing = run.getCTR().getDrawingArray(0);
                CTGraphicalObject graphicalobject = drawing.getInlineArray(0).getGraphic();
                CTAnchor anchor = getAnchorWithGraphic(graphicalobject, "test.jpg",
                        Units.toEMU(picture.getWidth()), Units.toEMU(picture.getHeight()),
                        Units.toEMU(40), Units.toEMU(0));
                drawing.setAnchorArray(new CTAnchor[]{anchor});
                drawing.removeInline(0);
            }
        }`

**Comment by Sayi** [comment]
两个方式：
1. 使用poi原生代码，参照PictureRenderPolicy实现自己的图片策略
2. 待发布的版本(1.6.0)支持引用策略ReferenceRenderPolicy，支持将设置好板式布局的图片直接替换
