### ISSUE TITLE
自定义策略

### ISSUE THREAD

**Issue by forgiveForever** [Sayi/poi-tl#179]
这样写Configure.newBuilder().customPolicy("test", new TestPolicy())模板中 {{test}} 
报错：
Connot find the key:lowG from Prefix-Model EL:null

**Comment by forgiveForever** [comment]
已解决，麻烦了

**Comment by DevilTerminator** [comment]
@forgiveForever ,您好，最近有用到
[自定义模板策略](http://deepoove.com/poi-tl/#_%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF%E7%AD%96%E7%95%A5)
[新增语法插件](http://deepoove.com/poi-tl/#_%E6%96%B0%E5%A2%9E%E8%AF%AD%E6%B3%95%E6%8F%92%E4%BB%B6)
请问，builder.customPolicy以及builder.addPlugin的用法，您可以简单的讲解一下吗？
![image](https://user-images.githubusercontent.com/44009699/58940905-49dfb380-87ad-11e9-8f72-85260d8f958f.png)
