### ISSUE TITLE
批量替换表格标签后，新生成的word文档会默认增加一个空行。有办法解决吗？

### ISSUE THREAD

**Issue by caoguopeng** [Sayi/poi-tl#183]
批量替换表格标签后，新生成的word会在表格后面默认加一行多余的空行。请问是我处理的有问题吗

**Comment by Sayi** [comment]
这应该是个问题，后续会考虑处理

**Comment by issac21** [comment]
好像是因为插入表格或者段落的时候，是在模板位置的前面插入的。
例如：
**插入前：**
<{{template}}(模板标记的位置)>
**插入后：**
<插入的内容>
<原来模板标记的位置（但插入之后就变成空行）>

**如果插入两个内容后：**
<插入的内容1>
<插入的内容2>
<原来模板标记的位置（但插入之后就变成空行）>

_因为我们的客户比较严格，多一个空行都不行。。。。_

**我是这样处理的：**

```java
public void render(ElementTemplate eleTemplate, Object data, XWPFTemplate template) {
        //模板对象
        RunTemplate runTemplate = (RunTemplate) eleTemplate;
        //模板的段落的光标位置
        XWPFRun run = runTemplate.getRun();
       //文档对象
        NiceXWPFDocument doc = template.getXWPFDocument();

       // ....省略插入数据的过程

      //删除多余的段落（模板空行）
       //posOfParagraph是段落在文档对象中的List数组中的索引
       int posOfParagraph = doc.getPosOfParagraph(run.getParagraph());
       doc.removeBodyElement(posOfParagraph);
}
```

**Comment by caoguopeng** [comment]
我也是替换后统一删除的。我这边的需求也很麻烦，不能把所有的空行全部删除，客户要求2级标题之间要留有空行，而我替换调的是三级标题下的表格，所以要特殊处理，还要麻烦些

**Comment by issac21** [comment]
我个人觉得：
一，自己定制2级标题，让2级标题后面的行距加宽，或者让2级标题后面自己加一行（我不知道word能不能实现，只是猜）。
二，自己实现生成策略，定制化。我一般都是这种，因为我的内容都要定制的。

**Comment by Sayi** [comment]
@caoguopeng 可以像 @issac21 所说的那样来做。

表格后空行其实是有扩展的，但是考虑欠周到，只有一个XWPFRun类型的参数，目前可以自定义一个策略`MyTableRenderPolicy`实现空行的删除。
```java
public class MyTableRenderPolicy extends MiniTableRenderPolicy{
  
  @Override
  protected void clearPlaceholder(XWPFRun run) {
    // 暂时无法通过移除段落方式，只能用骇客一点的方式
    // int posOfParagraph = doc.getPosOfParagraph(run.getParagraph());
    // doc.removeBodyElement(posOfParagraph);
    IRunBody parent = run.getParent();
    if (parent instanceof XWPFParagraph) {
      // Hack
       ((XWPFParagraph) parent).setSpacingBetween(0,
       LineSpacingRule.AUTO);
    }
  }

}
```
然后渲染前注册这个策略：
```java
Configure config = Configure.newBuilder()
    .addPlugin(GramerSymbol.TABLE.getSymbol(), new MyTableRenderPolicy())
    .build();
XWPFTemplate template = XWPFTemplate.compile("src/test/resources/table.docx", config).render(datas);
```

**Comment by sourcespro** [comment]
@Sayi 你好，请问一下，我用的是文档模板{{+var}}。
文档模板里面只有一个表格，数据有3条，生成的主文档包含3个表格，这三个表格之间的空行应该怎么处理掉。自定义一个策略不起作用。
`public class MyDocxRenderPolicy extends DocxRenderPolicy {
    @Override
    protected void clearPlaceholder(XWPFRun run) {
        IRunBody parent = run.getParent();
        if (parent instanceof XWPFParagraph) {
            ((XWPFParagraph) parent).setSpacingBetween(0, LineSpacingRule.AUTO);
        }
    }
}`

**Comment by Sayi** [comment]
@sourcespro 表格产生的空行，自定义表格策略？
