### ISSUE TITLE
批量替换表格后，如何优雅的控制单元格宽度？

### ISSUE THREAD

**Issue by caoguopeng** [Sayi/poi-tl#188]
![1550730695324](https://user-images.githubusercontent.com/12540775/53148380-74827380-35e5-11e9-9655-dcd696197aa8.jpg)
类似这种复杂表格，宽度的处理很麻烦，如果自适应，那么很多文字就挤在一起，如果固定列宽，那么金额比较大的数据就会换行，不符合要求。有个思路不知道是否可行，在固定列宽的前提下，随着内容的变换改变字号大小，来控制不换行。

**Comment by Sayi** [comment]
字号不一致  那得问问给你提需求的人同不同意了~~~~

**Comment by caoguopeng** [comment]
哈哈，需求倒是认可这样哦。但是实现起来就复杂了。只能通过逻辑来处理了，当发现cell内容有换行，循环减小字号，直到不出现换行。不直到大神有什么好思路没啊

**Comment by Sayi** [comment]
或者找到金额的位数和字号的关系  直接根据位数转换成字号~~~~

**Comment by caoguopeng** [comment]
好的，感谢，我试一下
