### ISSUE TITLE
如何设置日志等级 输出异常的stacktrace信息？出问题调试太麻烦！

### ISSUE THREAD

**Issue by yaosing** [Sayi/poi-tl#189]
如何设置日志等级 输出异常的stacktrace信息？出问题调试太麻烦！

**Comment by Sayi** [comment]
日志和你选用的日志框架有关系，你可以选用log4j、logback等等，将包`com.deepoove.poi`设置成你想要的日志级别。

**Comment by yaosing** [comment]
抱歉， 我描述的不太清楚， 应该是渲染的过程中出错 我没记错的话 代码直接catch异常 然后使用log打出exception的message， 没有打出异常的stacktrace。

**Comment by Sayi** [comment]
相关需要的日志包括渲染应该都打印了栈信息：`LOGGER.error("Render docx error", e);`

其中e会打印整个栈。

**Comment by yaosing** [comment]
发现问题了 是我代码中的logbackLayout中的配置吃掉了这个异常的信息，console中没打出来 日志文件中打出来了。打扰了！
