### ISSUE TITLE
表格合并

### ISSUE THREAD

**Issue by Fvames** [Sayi/poi-tl#19]
1.不知道是否支持去除表格边框及合并单元格?
2.您说的自定义表格处理是指的什么,在wiki上没有看到

**Comment by Fvames** [comment]
![default](https://user-images.githubusercontent.com/14091364/32427808-0edfaa74-c288-11e7-9750-c81776081719.png)

**Comment by Sayi** [comment]
1. 不支持去除边框，合并单元格，参加[NiceXWPFDocument.mergeCellsHorizonal](https://github.com/Sayi/poi-tl/blob/9e32604c4dfd78615396b42b340ee265d92152bd/src/main/java/com/deepoove/poi/NiceXWPFDocument.java#L65)

2. 基本上很多需求的表格都需要自定义的，需要熟悉POI操作table的API。
参见 [DynamicTableRenderPolicy.java](https://github.com/Sayi/poi-tl/blob/9e32604c4dfd78615396b42b340ee265d92152bd/src/main/java/com/deepoove/poi/policy/DynamicTableRenderPolicy.java#L35)

PS： {{#kbgs}} #号是插入表格的语法，如果像替换文本的话，示例图片中应该用{{kbgs}}

**Comment by Fvames** [comment]
谢谢,有个疑问: getTableArray(index)是基于什么样的顺序获取表格呢?
```
// 解析    
XWPFTemplate template = XWPFTemplate.compile("/Users/james/Desktop/models.docx").render(vo);
        
NiceXWPFDocument niceXWPFDocument = template.getXWPFDocument();
// 获取待合并的表格
XWPFTable xwpfTable = niceXWPFDocument.getTableArray(0);
niceXWPFDocument.mergeCellsHorizonal(xwpfTable, 0, 4, 5);
niceXWPFDocument.mergeCellsHorizonal(xwpfTable, 0, 6, 7);

niceXWPFDocument.mergeCellsVertically(xwpfTable, 0, 0, 1);
```

**Comment by Sayi** [comment]
sorry,没用过这个方法。

**Comment by Fvames** [comment]
1.实现 DynamicTableRenderPolicy时,发现如果模板文件的表格变量不定义在表格内会报错
```
ERROR com.deepoove.poi.policy.DynamicTableRenderPolicy.render(DynamicTableRenderPolicy.java:53) dynamic table error:org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.DocumentDocumentImpl cannot be cast to org.openxmlformats.schemas.wordprocessingml.x2006.main.CTTbl
java.lang.ClassCastException: org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.DocumentDocumentImpl cannot be cast to org.openxmlformats.schemas.wordprocessingml.x2006.main.CTTbl
	at com.deepoove.poi.policy.DynamicTableRenderPolicy.render(DynamicTableRenderPolicy.java:50)
```
可以替换 [ComplexRenderTest.java](https://github.com/Sayi/poi-tl/blob/f0a3bae3ef1df19fe000e0ec14e8952af3cdf8b2/src/test/java/com/deepoove/poi/tl/ComplexRenderTest.java)内的模板为 src/test/resources/table.docx 复现

**Comment by Sayi** [comment]
的确要求模板在表格内。
什么场景需要表格外的模板操作表格呢？看看有没有其他处理方案？

**Comment by Fvames** [comment]
1.我期望是,直接用创建的表格替换模板变量,是我之前理解不正确,模板变量需要自行删除.
![image](https://user-images.githubusercontent.com/14091364/32766783-08986c56-c8d6-11e7-8662-4192ba9b2033.png)
2.以下是实现:
```
        @Override
	public void render(XWPFTable table, Object data) {
		TableRenderData tableData = (TableRenderData) data;
		List<Object> datas = tableData.getDatas();
		if (null == datas || datas.isEmpty()) {
			table.getRow(1).getCell(0).removeParagraph(0);
			table.getRow(1).getCell(0).setText(tableData.getNoDatadesc());
		} else {
			// 插入标题
			createHeader(table, ((TableRenderData) data).getHeaders());
			// 插入内容区域
			for (Object obj : datas) {
				XWPFTableRow row = table.insertNewTableRow(2);
				String str = obj.toString();
				String[] split = str.split(";");
				XWPFTableCell cell0 = row.createCell();
				cell0.setText(split[0]);
				XWPFTableCell cell1 = row.createCell();
				cell1.setText(split[1]);
				XWPFTableCell cell2 = row.createCell();
				cell2.setText(split[2]);
			}
		}
		// 删除模板第一行
		table.removeRow(0);
	}
 ```
