### ISSUE TITLE
字号精度问题

### ISSUE THREAD

**Issue by caoguopeng** [Sayi/poi-tl#190]
style.setFontSize(10)这个方法设置字号大小，我这边的要求是word里面为宋体五号，对应的数字应该是10.5 。但我们的方法里只能支持整形，怎么实现对应到10.5这个字号呢？

**Comment by Sayi** [comment]
Apache Poi貌似也不支持浮点型字体大小，参见[http://poi.apache.org/apidocs/dev/org/apache/poi/xwpf/usermodel/XWPFRun.html#setFontSize-int-](http://poi.apache.org/apidocs/dev/org/apache/poi/xwpf/usermodel/XWPFRun.html#setFontSize-int-)

**Comment by gechaoqing** [comment]
可以的，POI的CharacterRun这样定义的 setFontSize(int **halfPoints**)，但是XWPFRun的setFontSize实现是把size*2的，所以只需要我们自己去写一下就可以了
```
BigInteger bint = new BigInteger(String.valueOf((int)(10.5*2)));
CTR ctr = run.getCTR();
 CTRPr pr = ctr.isSetRPr() ? ctr.getRPr() : null;
if (pr == null) {
  pr = ctr.addNewRPr();
}
CTHpsMeasure ctSize = pr.isSetSz() ? pr.getSz() : pr.addNewSz();
ctSize.setVal(bint);
```

**Comment by Sayi** [comment]
> Specifies the font size in half points

**Comment by Sayi** [comment]
https://bz.apache.org/bugzilla/show_bug.cgi?id=64605
