### ISSUE TITLE
可以支持多个config吗？因doc文件里面的表格有多个不同的id

### ISSUE THREAD

**Issue by zhanghenghengheng** [Sayi/poi-tl#192]
XWPFTemplate template2 = XWPFTemplate.compile("D:\\jianchamb4.docx",config1,config2，config0).render(dailyMinistryVo);

**Comment by Sayi** [comment]
没理解为啥你需要多个config....

**Comment by zhanghenghengheng** [comment]
因为 我的文档报告需求是如下的样子
一.今日重要新闻信息
   表格
二.今日品种负面相关信息
 表格
三.今日商品交易量
表格

我在制作模板的时候 就每一个表格给一个{{}} 。在填充数据的时候，compile（）方法就支持一个呀

**Comment by zhanghenghengheng** [comment]
大神，回复我一下，应该怎么处理呀

发自我的 iPhone

**Comment by Sayi** [comment]
没有理解，三个表格是可以都渲染的啊？

**Comment by zhanghenghengheng** [comment]
是呀的  就是三个不同的表格， 怎么操作才能都渲染。compile 那里就支持一个呀，这里有三个表格对应的TablePolicy，在给模板填充的时候，只能给一个config
        Configure config0 = Configure.newBuilder().customPolicy("base_overview", new MinistryTablePolicy()).build();
        Configure config1 = Configure.newBuilder().customPolicy("base_summary", new MinistryTablePolicy()).build()
        Configure config2 = Configure.newBuilder().customPolicy("base_abnormal", new MinistryTablePolicy()).build();
        XWPFTemplate template = XWPFTemplate.compile("D:\\jianchamb4.docx",config1).render(dailyMinistryVo);
        FileOutputStream out = new FileOutputStream("D:\\out_006.docx");

**Comment by Sayi** [comment]
customPolicy方法可以调用多次哈。。。

```java
Configure.newBuilder()
.customPolicy("base_overview", new MinistryTablePolicy())
.customPolicy("base_summary", new MinistryTablePolicy())
.customPolicy("base_abnormal", new MinistryTablePolicy()).build();
```

**Comment by zhanghenghengheng** [comment]
哦哦，好的，谢谢


发自我的 iPhone

**Comment by DoForDream** [comment]
案例中如果在实体类中未使用@Name声明对应的标签是否就无法渲染呢请问

**Comment by zhanghenghengheng** [comment]
那你用name标签


发自我的 iPhone

**Comment by Sayi** [comment]
@DoForDream @name只是个别名，比如文档中名称为user_department_name，那么字段声明可以这样：
```java
priavte String user_department_name;
```
也可以使用注解：
```java
@Name("user_department_name")
priavte String department;
```

**Comment by DoForDream** [comment]
原来如此  感谢@Sayi @zhanghenghengheng
