### ISSUE TITLE
word中的tabel怎样设置一行数据不同cell的水平对齐方式

### ISSUE THREAD

**Issue by xpalive** [Sayi/poi-tl#193]
### 建议
* 在TextRenderData中添加 com.deepoove.poi.data.style.TableStyle 属性这样可以在构造数据时指定其水平对齐方式
* 修改MiniTableRenderPolicy 中的renderRow方法 使其优先使用 TextRenderData中的TableStyle，再使用RowRenderData中的TableStyle

> 不知这个建议是否合适，或有更好的实现方式，望指教一二
先谢谢啦

**Comment by Sayi** [comment]
TextRenderData的对齐方式 需要在单元格或者表格内部生效，单独添加对齐方式似乎意义不大

**Comment by xpalive** [comment]
其实单独对齐的应用还是有的，比如文字左对齐，数字右对齐，这种要求。
我想表达的是
TextRenderData中有com.deepoove.poi.data.style.Style 属性，但是没有com.deepoove.poi.data.style.TableStyle 属性；
然而Style 只能控制垂直样式，我看poi-tl的源码发现TableStyle控制的是水平样式；
有一个疑问是为何不在TextRenderData中支持水平样式呢？

**Comment by Sayi** [comment]
@xpalive hi, 样式继承模板，如果希望左对齐或者右对齐，模板预先设置对齐方式就行了。

TextRenderData中有com.deepoove.poi.data.style.Style其实也是可以增加对齐属性的，这样会增加一种通过代码设置对齐的方式。

**Comment by xpalive** [comment]
@Sayi ok，我明白了。谢谢
