### ISSUE TITLE
生成的doc文档转换html失败 

### ISSUE THREAD

**Issue by jayknoxqu** [Sayi/poi-tl#197]
出现的问题和这个一样 https://github.com/Sayi/poi-tl/issues/95
### 用模版生成的word再用代码转html出现同样的问题

```
compile group: 'com.deepoove', name: 'poi-tl', version: '1.4.2'
compile group: 'fr.opensagres.xdocreport', name: 'fr.opensagres.xdocreport.converter.docx.xwpf', version: '2.0.1'
```

```
Exception in thread "main" fr.opensagres.poi.xwpf.converter.core.XWPFConverterException: java.lang.NumberFormatException: For input string: ""
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:71)
	at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:39)
	at fr.opensagres.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:46)
```

```
    private static void doc2pdf(InputStream is, OutputStream os) throws Exception {
        PdfOptions options = PdfOptions.create();
        PdfConverter.getInstance().convert(new XWPFDocument(is), os, options);
    }


    public static void doc2html(InputStream inputStream, OutputStream outputStream) throws Exception {
        XWPFDocument document = new XWPFDocument(inputStream);
        XHTMLOptions options = XHTMLOptions.create();
        XHTMLConverter.getInstance().convert(document, outputStream, options);
    }
```

**Comment by Sayi** [comment]
可以给个转pdf失败的文档给我吗 ，我本地复现一下

**Comment by jayknoxqu** [comment]
文件已发邮件给你了,请查收

不过我升级了下jar包,改了下你的代码就好了
```
compile group: 'fr.opensagres.xdocreport', name: 'fr.opensagres.xdocreport.converter.docx.xwpf', version: '2.0.2'
```

修改CodeGenUtils类中:
```
if (null == template) throw new POIXMLException("template is null,should be setted first.");
↓↓↓
if (null == template) throw new RuntimeException("template is null,should be setted first.");
```

因为`org.apache.poi:poi-ooxml:4.0.1`中更改了`org.apache.poi.POIXMLException`类为`org.apache.poi.ooxml.POIXMLException`

**Comment by 1521166966** [comment]
我也遇到同样的问题，换了这个包的版本好像也不行啊！是什么原因导致的？？
报错信息如下
org.apache.poi.xwpf.converter.core.XWPFConverterException: java.lang.NumberFormatException: For input string: ""

**Comment by taojunnan** [comment]
> 文件已发邮件给你了,请查收
> 
> 不过我升级了下jar包,改了下你的代码就好了
> 
> ```
> compile group: 'fr.opensagres.xdocreport', name: 'fr.opensagres.xdocreport.converter.docx.xwpf', version: '2.0.2'
> ```
> 
> 修改CodeGenUtils类中:
> 
> ```
> if (null == template) throw new POIXMLException("template is null,should be setted first.");
> ↓↓↓
> if (null == template) throw new RuntimeException("template is null,should be setted first.");
> ```
> 
> 因为`org.apache.poi:poi-ooxml:4.0.1`中更改了`org.apache.poi.POIXMLException`类为`org.apache.poi.ooxml.POIXMLException`

感谢
