### ISSUE TITLE
poi版本的问题

### ISSUE THREAD

**Issue by wyyyy** [Sayi/poi-tl#199]
1.请问这一个项目是基本3.16的版本开发的是吧？
2.现在poi的版本到poi-bin-4.0.1-20181203 然后导入进来就会报错 考虑代码更新不?不考虑的化我就要找老版本的了 谢谢 xfxbnb@163.com

**Comment by Sayi** [comment]
暂时没有精力更新~~

**Comment by Crown017** [comment]
4.0.1有bug

**Comment by Crown017** [comment]
或者是没有更新pom文件
