### ISSUE TITLE
关于云服务器上部署

### ISSUE THREAD

**Issue by kealina** [Sayi/poi-tl#20]
查看了你的说明文档，这个需要有
![image](https://user-images.githubusercontent.com/29566290/32924533-0df9684a-cb78-11e7-995d-9116ed927595.png)
请问下是否可以在Linux系统下搭建，是否在Linux下安装openoffice 与word lib库一样可以用呢

**Comment by xingya771** [comment]
@kealina 文档中写的是 “为了避免：XXX”，并不存在openoffice和word lib的依赖

**Comment by kealina** [comment]
这么说也就是在linux下部署是可以的

**Comment by Sayi** [comment]
恩 可以部署，不需要动态链接库。
