### ISSUE TITLE
页眉页脚中模板渲染网络图片，word中显示图片加载失败（正文中渲染图片是正常的）

### ISSUE THREAD

**Issue by GoodBoy123** [Sayi/poi-tl#204]

**Comment by Sayi** [comment]
没有重现你的问题，`com.deepoove.poi.tl.policy.PictureRenderTest`单元测试我本地跑是OK的。

**Comment by GoodBoy123** [comment]
模板word文件：![image](https://user-images.githubusercontent.com/31762432/55382829-4172be80-5559-11e9-93a2-b6e11b7bc40c.png)
代码：
![image](https://user-images.githubusercontent.com/31762432/55383187-2785ab80-555a-11e9-9c10-f292391a5870.png)
生成的word:
![image](https://user-images.githubusercontent.com/31762432/55383218-39674e80-555a-11e9-9057-92c8b5f39d75.png)

**Comment by Sayi** [comment]
能给个单元测试Junit的代码给我吗？

**Comment by GoodBoy123** [comment]
代码：
![image](https://user-images.githubusercontent.com/31762432/55446548-af1ef900-55f2-11e9-87ca-35073cfa8f2b.png)
word模板：
![image](https://user-images.githubusercontent.com/31762432/55446571-c52cb980-55f2-11e9-8224-0e03c92b087b.png)
输出的word文件：
![image](https://user-images.githubusercontent.com/31762432/55446584-d37ad580-55f2-11e9-9c5c-ca34c96965c3.png)

**Comment by Sayi** [comment]
还是没能重现。。。。。

**Comment by GoodBoy123** [comment]
和我的单元测试代码一模一样么，能给我看看你的单元测试么？我对比一下

2019-04-04 

YXYong4719 



发件人：卅一 <notifications@github.com>
发送时间：2019-04-04 09:34
主题：Re: [Sayi/poi-tl] 页眉页脚中模板渲染网络图片，word中显示图片加载失败（正文中渲染图片是正常的） (#204)
收件人："Sayi/poi-tl"<poi-tl@noreply.github.com>
抄送："GoodBoy123"<YXYong4719@163.com>,"Author"<author@noreply.github.com>

还是没能重现。。。。。

**Comment by Sayi** [comment]
一样的，要不你把你测试代码和模板附件发给我，我再试试吧

**Comment by GoodBoy123** [comment]
有个WordTest.java测试类，以及相关图片和word模板

2019-04-04 

YXYong4719 



发件人：卅一 <notifications@github.com>
发送时间：2019-04-04 09:51
主题：Re: [Sayi/poi-tl] 页眉页脚中模板渲染网络图片，word中显示图片加载失败（正文中渲染图片是正常的） (#204)
收件人："Sayi/poi-tl"<poi-tl@noreply.github.com>
抄送："GoodBoy123"<YXYong4719@163.com>,"Author"<author@noreply.github.com>

一样的，要不你把你测试代码和模板附件发给我，我再试试吧

**Comment by Sayi** [comment]
附件发给我？好像没看到附件？

**Comment by GoodBoy123** [comment]
有的，

2019-04-04 

YXYong4719 



发件人：卅一 <notifications@github.com>
发送时间：2019-04-04 11:08
主题：Re: [Sayi/poi-tl] 页眉页脚中模板渲染网络图片，word中显示图片加载失败（正文中渲染图片是正常的） (#204)
收件人："Sayi/poi-tl"<poi-tl@noreply.github.com>
抄送："GoodBoy123"<YXYong4719@163.com>,"Author"<author@noreply.github.com>

附件发给我？好像没看到附件？

**Comment by Sayi** [comment]
未复现。
