### ISSUE TITLE
功能优化建议

### ISSUE THREAD

**Issue by DaiJieLang** [Sayi/poi-tl#206]
`TableTools.mergeCellsHorizonal(table, tableRow, 1, 7);`
自定义表格模板渲染策略，一行多次合并单元格，需要计算之前合并后的结果，好麻烦啊，一开始还以为不支持多次合并。强烈建议优化一下

**Comment by Sayi** [comment]
你有什么好的优化推荐呢

**Comment by DaiJieLang** [comment]
才疏学浅，不太懂。。另外，表格样式除了背景色和居中居右居左对齐，可以设置上下居中吗，咋设置呀
