### ISSUE TITLE
1.4.2文档中的付款通知书代码不可用，代码也没完整给出

### ISSUE THREAD

**Issue by xinhaiCai** [Sayi/poi-tl#207]
http://deepoove.com/poi-tl/#example-table

找不到DetailData类

**Comment by Sayi** [comment]
所有示例的源码都在github上：https://github.com/Sayi/poi-tl/blob/master/src/test/java/com/deepoove/poi/tl/example/PaymentExample.java

**Comment by xinhaiCai** [comment]
刚发现了，但DetailData 类是找不到的

**Comment by xinhaiCai** [comment]
找到了，原来是你另外定义的，我以为在依赖里应该已经包含了
