### ISSUE TITLE
模板里有回城会导致下一个{{}}异常

### ISSUE THREAD

**Issue by tinybright** [Sayi/poi-tl#208]
content = 666;
回车  title:{{content}}

渲染后->
回车  title:{666content}}

**Comment by Sayi** [comment]
#161  参见这个issue

**Comment by tinybright** [comment]
是否不能用enter @Sayi

**Comment by Sayi** [comment]
嗯 目前的版本无法使用

**Comment by Sayi** [comment]
与161是同一个问题。
