### ISSUE TITLE
希望模板支持过滤器或者表达式

### ISSUE THREAD

**Issue by tinybright** [Sayi/poi-tl#210]

**Comment by Sayi** [comment]
可以说下场景

**Comment by tinybright** [comment]
往往使用的现有的bean。bean里面的字段 不一定是显示的样子。比如说金额，我们的bean都是存的分，在word上一般显示为元 ，万元，或者中文大写。还有有些字段为空时可能要有特殊显示。再有就是现在bean的属性值获取不是调用的getter

**Comment by Sayi** [comment]
一般设计建议是为 每个输出专门提供DTO的Bean。

你可以为Word专门提供一个BeanDTO，这个bean里面的金额是转换好的元，这样也不需要污染bean的getter方法了呀。

现在的做法是把显示逻辑控制放到后端去做，尽量保持模板轻量。

**Comment by tinybright** [comment]
复杂的逻辑放在后端去做可以 ，但是只是格式化这个多频的 感觉还是需要

**Comment by Sayi** [comment]
多频格式化后端其实也就是调用工具类格式化不同字段而已~~
