### ISSUE TITLE
模版表达式会添加对数组的支持吗？

### ISSUE THREAD

**Issue by Gawegor** [Sayi/poi-tl#217]
看了下1.4.2版本的TemplateVisitor的templatePatter默认生成的正则是这样的：`\{\{(|@|#|\*|\+)?\w+(\.\w+)*\}\}`，这个表达式应该不能匹配数组表达式（比如{{person.dog[0].name}}），所以目前应该不支持数组表达式吧？
会在之后版本添加吗？或者现在有没有其他方法实现？（比如插件）。

**Comment by Sayi** [comment]
hi，一个不错的建议，目前版本只能通过map去做。比如模板如下
{{person.dog.name0}{{person.dog.age0}
{{person.dog.name1}{{person.dog.age0}

那么java代码类似这样的循环赋值：
```java
dog = new HashMap<>();
for (int i = 0; i < list.size(); i++) {
  Dog myDog = list.get(i);
  dog.put("name" + i, myDog.getName());
  dog.put("age" + i, myDog.getAge());
}
```

**Comment by Gawegor** [comment]
> hi，一个不错的建议，目前版本只能通过map去做。比如模板如下
> {{person.dog.name0}{{person.dog.age0}
> {{person.dog.name1}{{person.dog.age0}
> 
> 那么java代码类似这样的循环赋值：
> 
> ```java
> dog = new HashMap<>();
> for (int i = 0; i < list.size(); i++) {
>   Dog myDog = list.get(i);
>   dog.put("name" + i, myDog.getName());
>   dog.put("age" + i, myDog.getAge());
> }
> ```

**Comment by Gawegor** [comment]
感谢，这个思路对我有用。因为我已经有部分POJO了，所以不希望完全使用Map。我对你的思路改动了一下：
模版Model结构大概这样：
```
class Person{
    ...
    Map<String, Dog> dogs;
    ...
}
```
装填Model代码：
```
Map<String, Dog> dogMap = new HashMap<>();
int seq = 1;
for(Dog d : dogs){   // 这里假设我有一个100只狗的列表
    dogMap.put(String.valueOf(seq), dog);
    seq++;
}
```
那么我就可以在模版中这样使用：`{{dogs.1.name}}`
