### ISSUE TITLE
表格内嵌套表格生成出错

### ISSUE THREAD

**Issue by xingya771** [Sayi/poi-tl#22]
您好，我在生成嵌套表格时遇到一些问题，样式如下：
![default](https://user-images.githubusercontent.com/17630155/33155632-1567b988-d02d-11e7-9362-6cda6b9e65c8.jpg)

堆栈如下：
java.lang.IndexOutOfBoundsException: Index: 11, Size: 4

	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:661)
	at java.util.ArrayList.add(ArrayList.java:473)
	at com.deepoove.poi.NiceXWPFDocument.insertNewTable(NiceXWPFDocument.java:158)
	at com.deepoove.poi.policy.SimpleTableRenderPolicy.render(SimpleTableRenderPolicy.java:86)
	at com.deepoove.poi.render.RenderAPI.render(RenderAPI.java:126)
	at com.deepoove.poi.XWPFTemplate.render(XWPFTemplate.java:140)
看了下是bodyElements.add(i, newT)时下标越界了。
尝试将嵌入的表格移到外边，可正常生成，希望能得到您的帮助，谢谢

**Comment by Sayi** [comment]
把模板的样式附上来看看。

**Comment by xingya771** [comment]
模板如下：
[table2.docx](https://github.com/Sayi/poi-tl/files/1498001/table2.docx)
测试代码如下：
`Configure plugin = Configure.createDefault().plugin('$', new CustomTableRenderPolicy());

		XWPFTemplate template = XWPFTemplate.compile("/Users/Arthur/Desktop/table2.docx",
				plugin);

		Map<String, Object> map=new HashMap<>();
		List<Object> tableRows_kcb = new ArrayList<>();
		tableRows_kcb.add("2017年11月1日09:00-10:30;课程1;1;张三");
		tableRows_kcb.add("2017年11月1日11:00-12:30;课程2;1;张三");
		tableRows_kcb.add("2017年11月1日14:00-15:30;课程3;1;张三");
		map.put("kcb", new TableRenderData(new ArrayList<RenderData>() {{
			add(new TextRenderData("培训时间"));
			add(new TextRenderData("课程名称"));
			add(new TextRenderData("课时"));
			add(new TextRenderData("教师名称"));
		}}, tableRows_kcb));

		template.render(map);
		String fileName = UUID.randomUUID().toString() + ".docx";
		Path path = Paths.get("/tmp", fileName);

		try (FileOutputStream out = new FileOutputStream(path.toString())) {
			template.write(out);
			out.flush();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}

		System.out.println(path);`
比较费解的是，在我上传附件前想让模板变得只够简单，就删掉了内嵌表格前的内容，结果能正常生成表格。删减后的如下：
[table.docx](https://github.com/Sayi/poi-tl/files/1498016/table.docx)

**Comment by Sayi** [comment]
@xingya771 在计算元素的时候越界了，原因是在一个单元格内元素过多。

1. 下一个版本将会修复。
2. 旧版本可以考虑把表格再拆分成三行，{{#kcb}}单独在一个单元格内，然后去除单元格的上下边框，这样展现的样式和你想要的是一样的。你可以试试这个方法。

![image](https://user-images.githubusercontent.com/1394854/33161887-68377dd6-d061-11e7-8b2e-876cf284ffeb.png)

**Comment by xingya771** [comment]
@Sayi 万分感谢，刚试了下已经可以了
