### ISSUE TITLE
单行文本如何实现颜色不同？

### ISSUE THREAD

**Issue by goly1234** [Sayi/poi-tl#220]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/4981112/56679633-1e6ea100-66f8-11e9-9cd8-0295114eee32.png">
我是试着把TextRenderData类放到数组或者list里面，结果docx文档只得到了对象的哈希地址，
请问有高明的解决办法吗？我现在用的是1.3.0版的

**Comment by Sayi** [comment]
额。。。目前解决方案只能是用多个标签，为每个标签设置样式

**Comment by goly1234** [comment]
那么以后会考虑添加此功能吗？就是单个标签支持数组或者集合形式的TextRenderData，然后程序挨个解析
