### ISSUE TITLE
您好，这边需要动态呈现行列

### ISSUE THREAD

**Issue by owenwong** [Sayi/poi-tl#222]
具体需求见图片，大神有没有解决方案啊，可以有偿
![系统需求](https://user-images.githubusercontent.com/31199869/56786829-d8ffc000-682c-11e9-8b54-7b51ea3fad7b.png)

**Comment by Sayi** [comment]
很简单的需求，看下这个例子：http://deepoove.com/poi-tl/#example-table

**Comment by owenwong** [comment]
这个例子看过了，比这个稍微还复杂点，应该就是需要定义每一行有哪些标签，要不然不知道客户到底维护了十个标签中的那几个标签，然后再进行动态展示了。

**Comment by Sayi** [comment]
@owenwong 是的

**Comment by owenwong** [comment]
@Sayi 如果您这边有时间的话，能帮忙写下图片中的效果嘛，可以支付酬劳的
