### ISSUE TITLE
当循环模版包含形状元素时，Office 365打开生成的合并文档报错

### ISSUE THREAD

**Issue by taojinjing** [Sayi/poi-tl#225]
当循环模版包含形状元素时，打开生成的合并文档是成功的，但是有报错信息。
我用的版本是1.4.2。
循环模版代码：
datas.put("segment", new DocxRenderData(..., ...));

打开后显示的错误信息：
![image](https://user-images.githubusercontent.com/3163516/57181946-66e24780-6ecc-11e9-94cb-92c24fdb7a34.png)
![image](https://user-images.githubusercontent.com/3163516/57181968-b0329700-6ecc-11e9-965d-f01c0e404acd.png)

Segment 文件:
[segment.docx](https://github.com/Sayi/poi-tl/files/3144576/segment.docx)

请问是否有什么解决方法，或者后续清理可以避免出现这个问题？

**Comment by Sayi** [comment]
写了个单元测试没能重现你的问题：https://github.com/Sayi/poi-tl/blob/master/src/test/java/com/deepoove/poi/tl/issue/Issue225.java

你可以把根模板发给我？

**Comment by taojinjing** [comment]
修改如下代码，可重现打开合并后文件报错的问题：
put("first", new DocxRenderData(new File("src/test/resources/issue/225.docx"), Arrays.asList(1, 2)));

另外，styles 1 报错看来是我的原segment子模版格式问题引起的。整理格式后已无法重现，上传原问题文件仅供参考。
[225_1.docx](https://github.com/Sayi/poi-tl/files/3146439/225_1.docx)

**Comment by Sayi** [comment]
@taojinjing 按照你的做法似乎也没有报错，不过形状的位置不符合期望。

**Comment by taojinjing** [comment]
谢谢帮忙重现，有可能是word版本的问题？
我的Word是 Word for Office 365 64位英文版。
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

详细看第二个报错是文档里有"unreachable content"，这部分是不是有什么方法可以定位到？或者做后续的处理？
![image](https://user-images.githubusercontent.com/3163516/57276116-2a346d00-70d3-11e9-9a8a-4627217bd4f8.png)
![image](https://user-images.githubusercontent.com/3163516/57276086-125ce900-70d3-11e9-9274-8afbbae147bf.png)
把我生产出来的文件也上传了：
[out_225.docx](https://github.com/Sayi/poi-tl/files/3151062/out_225.docx)

**Comment by Sayi** [comment]
用你的文件在我这边打开也没有问题。一般Details点开会告诉你具体出错的位置，能看到Details展开显示了什么啊？

**Comment by taojinjing** [comment]
重新贴一下:
![image](https://user-images.githubusercontent.com/3163516/57277491-d461c400-70d6-11e9-8e66-c6d4ba8b8f8a.png)
我解过document.xml出来也是合法的xml文件。

**Comment by taojinjing** [comment]
@Sayi 你好，我看你改了标题，可以确认是office 365下会有的问题？

**Comment by Sayi** [comment]
@taojinjing 我试了Microsoft Office 和 WPS 打开都是没问题的，下载了一个office365会重现你这个问题，但是的确没有好的办法定位哪里出问题了。

**Comment by Sayi** [comment]
#361
新版本office 唯一id的问题，已解决。
