### ISSUE TITLE
当循环模版文件打包在jar资源文件里时的，读取问题

### ISSUE THREAD

**Issue by taojinjing** [Sayi/poi-tl#226]
DocxRenderData(File docx, List<?> dataList)

当循环模版 docx 打包在jar资源文件里时，上述 api 的 File 参数无法获取文件。

当前版本下，是否只能先写到一个地方，然后再传入 File 类参数？

**Comment by Sayi** [comment]
@taojinjing 下个版本加上InputStream类型的参数。

当前可以想办法通过`java.io.File.File(URI)`这个来构造传参吗？

**Comment by taojinjing** [comment]
您好，如果像 PictureRenderData 有个 byte[] 接口就好了。
试了 File(URI) 也没有成功。谢谢建议。
