### ISSUE TITLE
文本换行使用 \n 字符  这个\n是要怎么用的呢

### ISSUE THREAD

**Issue by Godfavorstheinfantry** [Sayi/poi-tl#228]
templateMap.put("content","\n\n\n\n\n"); 
templateMap.put("content","\\n\\n\\n\\n\\n");
templateMap.put("content","/n/n/n/n/n");
分别显示
{{content}}
\n\n\n\n\n
/n/n/n/n/n

要怎么做才能在文档中换行呢？

**Comment by Godfavorstheinfantry** [comment]
>  put("content", "我是换行的文字,\n End.");
> 全是\n目前有个小bug，下版本会修复

emm。。 又发现了个神奇的问题， 这个\n 在word中显示的并不是换行符号呀？ 
正常换行用的是分段符，而\n转的是手动换行符欸?

**Comment by Sayi** [comment]
@Godfavorstheinfantry 的确是的，我正在考虑将换行符\r显示成回车换行符。

**Comment by Godfavorstheinfantry** [comment]
;D 这个大概什么时候能实现呢，目前有可行的插入分段符的方法吗

**Comment by Sayi** [comment]
按道理换行还是回车不影响显示效果的啊，因为什么原因必须用分段符呢？

**Comment by Godfavorstheinfantry** [comment]
想转PDF给网页显示的，

使用xdocreport转PDF会失真，
使用openOffice 转pdf时会把换行的显示不一样 T-T   

您有转pdf的建议吗

**Comment by Godfavorstheinfantry** [comment]
我勒个去- -  我发现使用openOffice转pdf也会失真

**Comment by Godfavorstheinfantry** [comment]
我想要把word文档显示在前端，并且可以打印
但是发现转pdf样式会失真（比如行距什么的）
有什么其他的解决方案吗

**Comment by Sayi** [comment]
sorry...没有更好的建议哦~
