### ISSUE TITLE
特定文档位置放变量会出现空指针：存在bug

### ISSUE THREAD

**Issue by arfish** [Sayi/poi-tl#23]
在特定文档位置放变量会出现空指针 startText为null
if (startOffset <= 0) {
				//start run 无需split
				XWPFRun templateRun = runs.get(startRunPos);
				templateRun.setText(tags.get(--tagIndex), 0);
				runTemplate = parseRun(runs.get(startRunPos));
			} else {
				//split start run, set extra in a run
				String extra = startText.substring(0, startOffset);
				XWPFRun extraRun = runs.get(startRunPos);
				extraRun.setText(extra, 0);
				
				XWPFRun templateRun = paragraph.insertNewRun(startRunPos + 1);
				StyleUtils.styleRun(templateRun, extraRun);
				templateRun.setText(tags.get(--tagIndex), 0);
				runTemplate = parseRun(runs.get(startRunPos + 1));
			}

**Comment by arfish** [comment]
相同变量放到其他位置又OK了 感觉逻辑有问题.文本框中内容不能识别

**Comment by arfish** [comment]
附件

**Comment by Sayi** [comment]
@arfish 可以把出现空指针变量的模板文件附上来，可能是该变量前后出现了一些**特别的字符**

恩，不支持文本框，不过表格可以满足所有的样式。

**Comment by Sayi** [comment]
BUG过期关闭
