### ISSUE TITLE
XWPFTemplate.compile编译模板时问题

### ISSUE THREAD

**Issue by loong-chen** [Sayi/poi-tl#232]
XWPFTemplate.compile 不管是传file 还是传流,都报  Failed to read zip entry source  这个错误.
我是以springboot maven导入包的方式运行的, 资源文件放在resource下的,我看我的问题和 #66 很像,但我也用getResourceAsStream 还是一样.看了源码,是不是英文compile的代码是封装在jar包里的,所以读不到我外面的文件.作者帮我看下,感激不尽

**Comment by loong-chen** [comment]
~~~
InputStream inputStream = getClass().getClassLoader().getResourceAsStream("fileTemplate/renice-contract-template.docx");

XWPFTemplate template = XWPFTemplate.compile(inputStream,config).render(agreementTemplateVO);

~~~
这样报错,不管传什么类型的参数都没用

**Comment by Sayi** [comment]
传入都是流了，和jar没关系。你先确保获取的inputStream是有效的吧

**Comment by loong-chen** [comment]
好像是这个道理,我直接写绝对路径就可以

~~~

FileInputStream fis = new FileInputStream(new File("D:\\workspace\\renice_platform\\rp-backend\\rp-management\\src\\main\\resources\\fileTemplate\\renice-contract-template.docx"));
~~~

**Comment by alcq77** [comment]
> 好像是这个道理,我直接写绝对路径就可以
> 
> ```
> 
> FileInputStream fis = new FileInputStream(new File("D:\\workspace\\renice_platform\\rp-backend\\rp-management\\src\\main\\resources\\fileTemplate\\renice-contract-template.docx"));
> ```

最后怎么解决的

**Comment by loong-chen** [comment]
> > 好像是这个道理,我直接写绝对路径就可以
> > ```
> > 
> > FileInputStream fis = new FileInputStream(new File("D:\\workspace\\renice_platform\\rp-backend\\rp-management\\src\\main\\resources\\fileTemplate\\renice-contract-template.docx"));
> > ```
> 
> 最后怎么解决的

把文件放在同一个项目的resource目录下，然后用以下代码：

~~~
fis = this.getClass().getClassLoader().getResourceAsStream(templaePath);
template = XWPFTemplate.compile(fis, builder.build()).render(datas);

~~~

**Comment by micky2333** [comment]
`        //获取 resources 目录
        InputStream inputStream = getClass().getResourceAsStream("/word/template.docx");
        // 创建用于插入数据的Map
        Map<String, Object> map = new HashMap<>(18);
        map.put("title", "Hi, poi-tl Word模板引擎");
        map.put("name", "小蜜蜂~");

        // 填充word文档
        XWPFTemplate template = XWPFTemplate.compile(inputStream).render(map);
        template.writeAndClose(new FileOutputStream("templateAAA.docx"));
`
![](https://pic1.58cdn.com.cn/nowater/webim/big/n_v2ed845c50b6024e74886f2ebdbf7cc132.png "")
