### ISSUE TITLE
有文字word模板我只需替换几个变量的值

### ISSUE THREAD

**Issue by zengdingxin** [Sayi/poi-tl#233]
你好，现在加载word就报错，我的模板是基于需求替换几个数值和插入图片不是一个空白的，直接去读取word直接就报错了。
![TIM截图20190514184106](https://user-images.githubusercontent.com/14012002/57691853-dcda7180-7677-11e9-910e-cb1a486b5631.png)

**Comment by zengdingxin** [comment]
![TIM截图20190514184820](https://user-images.githubusercontent.com/14012002/57692245-e1535a00-7678-11e9-8273-3edf39433654.png)

报错信息

**Comment by Sayi** [comment]
docx格式

**Comment by zengdingxin** [comment]
DOC的格式

**Comment by Sayi** [comment]
仔细阅读文档
