### ISSUE TITLE
树状数据结构 1.3版本存在 图片覆盖 1.4版本二级图片不见

### ISSUE THREAD

**Issue by lhl14** [Sayi/poi-tl#235]
数据有三级结构 类似目录的 类 章 节 树状结构
第一级   包含 多个第二级   第二级包含多个第三级
每一级都有一个对应模板 能放一张图片 和一些其他的 内容
1.3版本 发现问题  当存在两个第二级时  后一个图片 覆盖了前一个图片

1.4版本 发现 第二级的图片都不见了

**Comment by Sayi** [comment]
@lhl14 hi，可以給個單元測試嗎

**Comment by lhl14** [comment]
@Sayi   我重新试了一下  把嵌入的模板标签 {{+level}} 单独放一行就能展示图片了 
如果跟在{{@}} 图片后面就有点问题

**Comment by Sayi** [comment]
{{+level}} 需要合并文档，所以需要单独一行才行~~
