### ISSUE TITLE
poi-tl 1.5.0-SNAPSHOT 在指定poi版本升级到4.0.1或者4.1.0之后报错

### ISSUE THREAD

**Issue by luoqiz** [Sayi/poi-tl#236]
公司项目是基于poi 4.0.0开发的，若是降级项目需要修改的地方太多了。使用poi-tl 1.5.0-SNAPSHOT 仍然报错 java.lang.NoClassDefFoundError: org/apache/poi/POIXMLDocumentPart。

读取说明，会升级到poi4，请问大概什么时候可以正常使用poi 4版本的poi-tl？？？

![image](https://user-images.githubusercontent.com/22161059/57919381-4d2d0100-78cb-11e9-9af7-ffa35b6d04fb.png)

**Comment by Sayi** [comment]
@luoqiz hi，并没有出现你这个问题，`org.apache.poi.ooxml.POIXMLDocumentPart`是在poi-ooxml这个jar里面。

**Comment by luoqiz** [comment]
我也看过，也找到了这个类，和抛出来的类路径不一样，我一直以为是这个项目里引入的poi3的问题。我明天上传一个测试项目，你可以试试

**Comment by luoqiz** [comment]
写的测试项目  https://github.com/luoqiz/poi-tl-demo.git。
当我将 poi-tl 项目的依赖升级到 4.1.0 版本后就没有问题了。

**Comment by Sayi** [comment]
@luoqiz :smile:

**Comment by muyiluop** [comment]
> 
> 
> 我也看过，也找到了这个类，和抛出来的类路径不一样，我一直以为是这个项目里引入的poi3的问题。我明天上传一个测试项目，你可以试试

我也存在这个情况，请问你可解决了？我也是新建项目单独测试没问题，在原项目中就存在问题

**Comment by luoqiz** [comment]
我是将poi-tl项目下载下来，更改了poi依赖版本后，重新打包到项目中可以使用的。

**Comment by muyiluop** [comment]
> 
> 
> 我是将poi-tl项目下载下来，更改了poi依赖版本后，重新打包到项目中可以使用的。

看来目前只能这样了，这样依赖就是需要把依赖放到本地仓库了。不过还是不明白为啥会找一个确实不存在的类。

**Comment by Sayi** [comment]
@luoqiz @muyiluop 1.5.0正式版本发布后，应该就可以直接使用了，预计月底发布吧。

**Comment by luoqiz** [comment]
ok
