### ISSUE TITLE
合并列单元格错误问题

### ISSUE THREAD

**Issue by zengdingxin** [Sayi/poi-tl#237]
![无标题](https://user-images.githubusercontent.com/14012002/58073713-e878eb80-7bd5-11e9-98c9-fe839301b12d.png)
![TIM截图20190521143623](https://user-images.githubusercontent.com/14012002/58073714-e9118200-7bd5-11e9-8fdc-bc94fe7d4550.png)
根据参数是需要合并第一行到第三行的第一列的单元格，最终结果是合并了第三行和第四行的第一列

**Comment by zengdingxin** [comment]
执行程序为报错唯有任何异常

**Comment by zengdingxin** [comment]
![image](https://user-images.githubusercontent.com/14012002/58075828-3fcd8a80-7bdb-11e9-81c4-4c639a04f64f.png)
这个方法判断有问题，参考了代码改成这样是没有问题的
![image](https://user-images.githubusercontent.com/14012002/58075950-8ae79d80-7bdb-11e9-8fae-f5ecc791a3f0.png)

**Comment by zengdingxin** [comment]
mergeCellsVertically这个方法判断有问题，参考了代码改成这样是没有问题的

**Comment by Sayi** [comment]
合并单元格你代码套用的有问题，官方示例给的是合并一行中的某几列，你是需要合并一列中的三行，不能你这样来合并，至少要在for循环把所有行创建完成才能调用合并方法。

**Comment by terwer** [comment]
> 合并单元格你代码套用的有问题，官方示例给的是合并一行中的某几列，你是需要合并一列中的三行，不能你这样来合并，至少要在for循环把所有行创建完成才能调用合并方法。

非常感谢作者的回复，完美解决了我的问题！这里确实是需要等待行创建完成才能进行合并。
