### ISSUE TITLE
插入图片成功单打开word打开文档提示错误

### ISSUE THREAD

**Issue by zengdingxin** [Sayi/poi-tl#238]
![image](https://user-images.githubusercontent.com/14012002/58087715-baa29f80-7bf3-11e9-9ebb-0b8400a5a18d.png)
office修复后文档可以正常打开
![image](https://user-images.githubusercontent.com/14012002/58087786-db6af500-7bf3-11e9-8228-db969e6a90aa.png)
 不插入图片文档打开不会有错误提示

**Comment by zengdingxin** [comment]
不插入图片文档打开正常

**Comment by zengdingxin** [comment]
office确定后修复文档可以正常打开， 不插入图片文档打开不会有错误提示

**Comment by zengdingxin** [comment]
[word_test.zip](https://github.com/Sayi/poi-tl/files/3202002/word_test.zip)
代码程序资源都在

**Comment by Sayi** [comment]
@zengdingxin 运行你的代码后打开文档并没有出现你的问题，可以告知一下office具体版本号吗

**Comment by zengdingxin** [comment]
辛苦了，支持下开源精神

**Comment by Sayi** [comment]
@zengdingxin 感谢捐款哦~~ :smile:

**Comment by zengdingxin** [comment]
微微表示支持开源，不用谢

**Comment by zengdingxin** [comment]
这个是poi的BUG，参考这个遍文章：https://blog.csdn.net/zhyh1986/article/details/8717585，希望对你有帮助

**Comment by Sayi** [comment]
poi3.16+版本这个BUG已经修复了。你这个生成的文档我用wps、Apple pages、office 2011打开都没有问题，我需要找到office 2013试验一下。

**Comment by zengdingxin** [comment]
恩，office2013 全套安装包地址：链接：https://pan.baidu.com/s/1ye-02X6esTpJ5rAq8SlY2A 
提取码：hl1d

**Comment by zengdingxin** [comment]
跟文件大小有关在原模板上删除很多内容就没问题，自己新建的模板只写入自己的需要替换的变量也没问题
![image](https://user-images.githubusercontent.com/14012002/58225513-eb4e1a80-7d54-11e9-8828-210a52c234cf.png)

**Comment by Sayi** [comment]
不是大小的问题，看来和模板文件有关。

你把所有文本框都去掉，用表格代替试试？

**Comment by zengdingxin** [comment]
好像是模板文件问题，现在我把插入的图片的{{@xxxx}}换个位置打开文件也是没有问题的

**Comment by a1105013796** [comment]
3.17版本遇到这个问题，通过java生成图片的byte数组来进行渲染，word打开提示这个报错 @Sayi

**Comment by zengdingxin** [comment]
解决插入图片插入报错，自定义编写插件插入图片解决
MyPictureRenderPolicy.java

如果有子模板合并到子模板中，子模板先用{{@var}}不插入图片，组装数据再次渲染数据，不然子模板中直接插入图片还是会提示报错

Configure config = Configure.newBuilder().addPlugin(GramerSymbol.TABLE.getSymbol(), new MyMiniTableRenderPolicy())
                .addPlugin(GramerSymbol.IMAGE.getSymbol(), new MyPictureRenderPolicy()).addPlugin('%', new MyTextRenderPolicy()).build();
        XWPFTemplate template = XWPFTemplate.compile(exportReportResource.getInputStream(), config).render(exportReport).render(imgMap);

功能上限了，闲着瞎搞解决了这个问题，导出一切正常。 @a1105013796

**Comment by zengdingxin** [comment]
MyPictureRenderPolicy插件代码：
package com.crc.ehs.model.audit.word;

import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.io.InputStream;

import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.apache.xmlbeans.XmlException;
import org.apache.xmlbeans.XmlToken;
import org.openxmlformats.schemas.drawingml.x2006.main.CTNonVisualDrawingProps;
import org.openxmlformats.schemas.drawingml.x2006.main.CTPositiveSize2D;
import org.openxmlformats.schemas.drawingml.x2006.wordprocessingDrawing.CTInline;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTDrawing;

import com.deepoove.poi.NiceXWPFDocument;
import com.deepoove.poi.XWPFTemplate;
import com.deepoove.poi.data.PictureRenderData;
import com.deepoove.poi.exception.RenderException;
import com.deepoove.poi.policy.PictureRenderPolicy;
import com.deepoove.poi.template.run.RunTemplate;

public class MyPictureRenderPolicy extends PictureRenderPolicy{

    @Override
    public void doRender(RunTemplate runTemplate, PictureRenderData picture, XWPFTemplate template) throws Exception {
        XWPFRun run = runTemplate.getRun();
        NiceXWPFDocument document = template.getXWPFDocument();
        Helper.renderPicture(run, document, picture);
    }
    
    public static class Helper {
        public static final int EMU = 9525;

        public static void renderPicture(XWPFRun run, NiceXWPFDocument document, PictureRenderData picture) throws Exception {
            CTDrawing drawing = run.getCTR().addNewDrawing();
            CTInline inline = drawing.addNewInline();
            int suggestFileType = suggestFileType(picture.getPath());
            InputStream ins = null == picture.getData() ? new FileInputStream(picture.getPath())
                    : new ByteArrayInputStream(picture.getData());
            String blipId = document.addPictureData(ins, suggestFileType);
            
            String picXml = "" +
                    "<a:graphic xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\">" +
                    "   <a:graphicData uri=\"http://schemas.openxmlformats.org/drawingml/2006/picture\">" +
                    "      <pic:pic xmlns:pic=\"http://schemas.openxmlformats.org/drawingml/2006/picture\">" +
                    "         <pic:nvPicPr>" +
                    "            <pic:cNvPr id=\"" + document.getNextPicNameNumber(XWPFDocument.PICTURE_TYPE_PNG) + "\" name=\"Generated\"/>" +
                    "            <pic:cNvPicPr/>" +
                    "         </pic:nvPicPr>" +
                    "         <pic:blipFill>" +
                    "            <a:blip r:embed=\"" + blipId + "\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"/>" +
                    "            <a:stretch>" +
                    "               <a:fillRect/>" +
                    "            </a:stretch>" +
                    "         </pic:blipFill>" +
                    "         <pic:spPr>" +
                    "            <a:xfrm>" +
                    "               <a:off x=\"0\" y=\"0\"/>" +
                    "               <a:ext cx=\"" + picture.getWidth() * EMU + "\" cy=\"" + picture.getHeight() * EMU + "\"/>" +
                    "            </a:xfrm>" +
                    "            <a:prstGeom prst=\"rect\">" +
                    "               <a:avLst/>" +
                    "            </a:prstGeom>" +
                    "         </pic:spPr>" +
                    "      </pic:pic>" +
                    "   </a:graphicData>" +
                    "</a:graphic>";
            inline.addNewGraphic().addNewGraphicData();
            XmlToken xmlToken = null;
            try {
                xmlToken = XmlToken.Factory.parse(picXml);
            } catch(XmlException xe) {
                xe.printStackTrace();
            }
            inline.set(xmlToken);
     
            inline.setDistT(0);
            inline.setDistB(0);
            inline.setDistL(0);
            inline.setDistR(0);
     
            CTPositiveSize2D extent = inline.addNewExtent();
            extent.setCx(picture.getWidth() * EMU);
            extent.setCy(picture.getHeight() * EMU);
     
            CTNonVisualDrawingProps docPr = inline.addNewDocPr();
            docPr.setId(document.getNextPicNameNumber(XWPFDocument.PICTURE_TYPE_PNG));
            docPr.setName("Generated" + document.getNextPicNameNumber(XWPFDocument.PICTURE_TYPE_PNG));
            docPr.setDescr("Generated");
        }

        public static int suggestFileType(String imgFile) {
            int format = 0;

            if (imgFile.endsWith(".emf"))
                format = XWPFDocument.PICTURE_TYPE_EMF;
            else if (imgFile.endsWith(".wmf"))
                format = XWPFDocument.PICTURE_TYPE_WMF;
            else if (imgFile.endsWith(".pict"))
                format = XWPFDocument.PICTURE_TYPE_PICT;
            else if (imgFile.endsWith(".jpeg") || imgFile.endsWith(".jpg"))
                format = XWPFDocument.PICTURE_TYPE_JPEG;
            else if (imgFile.endsWith(".png"))
                format = XWPFDocument.PICTURE_TYPE_PNG;
            else if (imgFile.endsWith(".dib"))
                format = XWPFDocument.PICTURE_TYPE_DIB;
            else if (imgFile.endsWith(".gif"))
                format = XWPFDocument.PICTURE_TYPE_GIF;
            else if (imgFile.endsWith(".tiff"))
                format = XWPFDocument.PICTURE_TYPE_TIFF;
            else if (imgFile.endsWith(".eps"))
                format = XWPFDocument.PICTURE_TYPE_EPS;
            else if (imgFile.endsWith(".bmp"))
                format = XWPFDocument.PICTURE_TYPE_BMP;
            else if (imgFile.endsWith(".wpg"))
                format = XWPFDocument.PICTURE_TYPE_WPG;
            else {
                throw new RenderException(
                        "Unsupported picture: " + imgFile + ". Expected emf|wmf|pict|jpeg|png|dib|gif|tiff|eps|bmp|wpg");
            }
            return format;
        }

    }
    
    
    
}

**Comment by zengdingxin** [comment]
![image](https://user-images.githubusercontent.com/14012002/63096076-7c710e00-bf9f-11e9-9be2-7ed10b66cc93.png)
imgMap是再次渲染图片数据

**Comment by HzrRong** [comment]
我也是遇到这个问题的，用的3.17 poi，我是读取一个word成DocxRenderData，然后替换到模板里面，读取的word有图片也会提示文件错误，不过能打开，内容也没错

**Comment by Sayi** [comment]
https://github.com/Sayi/poi-tl/blob/b0c7342914d485b5f1c30e84d5aad6a17469b23d/src/main/java/com/deepoove/poi/policy/PictureRenderPolicy.java  也可以参考poi-tl 1.4.0版本的实现。

**Comment by z172362753** [comment]
我也碰到了这个问题。版本1.6.0。图片插入表格就打开出错，插到表格外面就没问题
