### ISSUE TITLE
请问模板中有多个customPolicy，该如何实现？

### ISSUE THREAD

**Issue by Dra-CuLa** [Sayi/poi-tl#239]
`
代码如下：

        Configure.ConfigureBuilder builder = Configure.newBuilder();
        builder.customPolicy("detailTable", benefitPolicy);
        builder.customPolicy("detailTable2", benefitPolicy);
        String relativePath = Global.getProjectPath() + "/src/main/webapp/template/";
        XWPFTemplate template = XWPFTemplate.compile(relativePath + "3.docx",builder.build()).render(data);
        FileOutputStream out = new FileOutputStream(relativePath + "out_3.docx");
        template.write(out);
        out.flush();
        out.close();
        template.close();
`

你好，多个customPolicy，只有第一个数据被渲染了，请问我哪里写的有问题，望指教，谢谢！

**Comment by Dra-CuLa** [comment]
自己发现问题了，忘了给detailTable2赋值，感谢。

**Comment by Sayi** [comment]
@Dra-CuLa 写法看似没有问题。

data中包括这两个detailTable和detailTable2字段吗？模板标签拼写是对的吗？

**Comment by a1105013796** [comment]
你好，我也是这样渲染的，但是渲染后两个数据都在同一个标签里面了
![image](https://user-images.githubusercontent.com/32124539/61340588-8a832000-a875-11e9-98c9-6fafd342ed97.png)
