### ISSUE TITLE
表格处理（超出边界自动下列表格）

### ISSUE THREAD

**Issue by luoqiz** [Sayi/poi-tl#240]
例如这样，一行显示不下的情况自动另起一行
![image](https://user-images.githubusercontent.com/22161059/58166333-2bad8a00-7cbc-11e9-853a-e9eb895e207a.png)

**Comment by Sayi** [comment]
@luoqiz 没听懂~~~额。。。

**Comment by luoqiz** [comment]
就是一个表格超过word的宽度了，超过的部分在另起一个表格显示剩下的几列

**Comment by Sayi** [comment]
感觉自动另起一个表格的需求不是很重要呀。。。看下有没有其它方案可以解决这个需求~

**Comment by luoqiz** [comment]
客戶要求之後，不是我們來決定重不重要的啊

**Comment by Sayi** [comment]
这个有点难度了  需要新建两个表格了 😃

**Comment by luoqiz** [comment]
哈哈，所以才会有和产品经理干架的机会啊😃
