### ISSUE TITLE
放到表格中的中的超链接失效

### ISSUE THREAD

**Issue by luoqiz** [Sayi/poi-tl#241]
如下圖所示：第三種将超链接放到表格中，字体颜色变化了，但是超链接失效
![image](https://user-images.githubusercontent.com/22161059/58241419-8b209e00-7d7f-11e9-9dfc-33e7362dd616.png)
![image](https://user-images.githubusercontent.com/22161059/58241555-c7ec9500-7d7f-11e9-99d2-2033bf020fed.png)

**Comment by Sayi** [comment]
是个遗漏的功能，下个版本会修复~

**Comment by luoqiz** [comment]
ok
