### ISSUE TITLE
指定行合并单元格如何实现？

### ISSUE THREAD

**Issue by Dra-CuLa** [Sayi/poi-tl#243]
![222](https://user-images.githubusercontent.com/26604499/58450769-df8e9980-8142-11e9-8bb6-2675501217c4.png)

**Comment by Sayi** [comment]
参见com.deepoove.poi.util.TableTools

**Comment by Dra-CuLa** [comment]
`private class AttachmentPolicy extends AbstractRenderPolicy {

        @Override
        protected boolean validate(Object data) {
            return null != data;
        }

        @Override
        public void doRender(RunTemplate runTemplate, Object data, XWPFTemplate template) throws Exception {

            CommonAttachmentTable commonAttachmentTable = (CommonAttachmentTable) data;
            List<AttachmentRowRenderData> rowRenderDatas = commonAttachmentTable.getAttachmentRowRenderDataList();

            NiceXWPFDocument doc = template.getXWPFDocument();
            XWPFRun run = runTemplate.getRun();
            // 定义行列
            int row = commonAttachmentTable.getAttachmentRowRenderDataList().size(), col = 2;
            // 插入表格
            XWPFTable table = doc.insertNewTable(run, row, col);

            // 定义表格宽度、边框和样式
            TableTools.widthTable(table, MiniTableRenderData.WIDTH_A4_FULL, col);
            TableTools.borderTable(table, 4);

            setCellWidth(table,0,0,1500);

            TableStyle horizontallyCenter = new TableStyle();
            horizontallyCenter.setAlign(STJc.CENTER);

            for (int i = 0; i < rowRenderDatas.size(); i++) {

                AttachmentRowRenderData attachmentData = rowRenderDatas.get(i);

                RowRenderData rowRenderData = RowRenderData.build(attachmentData.sortNo, attachmentData.getAttachmentName());
                rowRenderData.setStyle(horizontallyCenter);
                if(i > 0){

                    //  合并单元格
                    if(attachmentData.isMergeCell()){
                        TableTools.mergeCellsHorizonal(table, i, 0, 1);
                    }else{
                        XWPFTableCell cell = table.getRow(i).getCell(1);
                        CTTc cttc = cell.getCTTc();
                        CTTcPr ctPr = cttc.addNewTcPr();
                        ctPr.addNewVAlign().setVal(STVerticalJc.CENTER);
                        cttc.getPList().get(0).addNewPPr().addNewJc().setVal(STJc.LEFT);
                    }
                }
                MiniTableRenderPolicy.renderRow(table,i,rowRenderData);
            }
            // 清空原先模板
            clearPlaceholder(run);
        }
    }`
您好，我按照例子，实现了合并单元格，现在有个需求是：有些单元格是需要居中显示，有些需要居左显示，我百度了一个【水平居左】的实现方式，我试了下，结果报错了（找不到该类）
`Caused by: java.lang.NoClassDefFoundError: org/openxmlformats/schemas/wordprocessingml/x2006/main/impl/CTTcImpl$1PList
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTTcImpl.getPList(Unknown Source)
	at com.thinkgem.jeesite.modules.award.web.gendoc.GenerateAward$AttachmentPolicy.doRender(GenerateAward.java:640)`
您能帮我看看么？

**Comment by Sayi** [comment]
@Dra-CuLa 马上要发布的版本1.5.0支持单元格级别的对齐和背景色设置。

目前你的问题是缺少一个包：
```xml
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>ooxml-schemas</artifactId>
    <version>1.4</version>
</dependency>

```

**Comment by Dra-CuLa** [comment]
太感谢了！
