### ISSUE TITLE
在生成word文件的模板中可以使用多层的嵌套吗，应该怎样实现多层嵌套呢。例子中实现了两层的嵌套，如果需要增加层数应该怎样做。

### ISSUE THREAD

**Issue by DevilTerminator** [Sayi/poi-tl#244]
模板一，
![image](https://user-images.githubusercontent.com/44009699/58544340-a124d780-8233-11e9-93bb-5d4bf130248d.png)
模板二，
![image](https://user-images.githubusercontent.com/44009699/58544388-ba2d8880-8233-11e9-8a5b-cfcde4d5460a.png)
模板三，
![image](https://user-images.githubusercontent.com/44009699/58544410-c74a7780-8233-11e9-8555-83870dcb5093.png)

第一个模板会使用第二个模板中的数据，第二个模板会使用到第三个模板中的数据，这样的话，如何使其最后可以整合成一个文件生成。

**Comment by Sayi** [comment]
参见这个：https://github.com/Sayi/poi-tl/blob/master/src/test/java/com/deepoove/poi/tl/issue/IssueMerge.java

**Comment by DevilTerminator** [comment]
晚上好，向您咨询一下。我学习了您告诉我的标题的整理思想。我想实现多个标题级别的循环，这个循环应该怎样实现呢？循环语句应该放在哪里？
![image](https://user-images.githubusercontent.com/44009699/58811055-aded6500-8651-11e9-90af-c238389f42fa.png)
还有个问题，
![image](https://user-images.githubusercontent.com/44009699/58811395-50a5e380-8652-11e9-8f75-f5d29783e20a.png)


请问，咱们有没有交流群，或者论坛，贴吧，等大众讨论的方式，总是这样麻烦您有点不好意思

**Comment by DevilTerminator** [comment]
@Sayi ，早上好

**Comment by Sayi** [comment]
多看看文档吧 没有时间手把手教你。。。

**Comment by DevilTerminator** [comment]
好的，谢谢您

**Comment by DevilTerminator** [comment]
您好，最后打扰一下
http://deepoove.com/poi-tl/#_%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF%E7%AD%96%E7%95%A5，
http://deepoove.com/poi-tl/#_%E6%96%B0%E5%A2%9E%E8%AF%AD%E6%B3%95%E6%8F%92%E4%BB%B6，
这两章有实例可以参考吗，不太了解builder.customPolicy以及builder.addPlugin的用法。

**Comment by DevilTerminator** [comment]
@Sayi ，您好，最后提出一个问题，关于
[5.2自定义模板策略](http://deepoove.com/poi-tl/#_%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF%E7%AD%96%E7%95%A5)
[5.3新增语法插件](http://deepoove.com/poi-tl/#_%E6%96%B0%E5%A2%9E%E8%AF%AD%E6%B3%95%E6%8F%92%E4%BB%B6)
这两个模块有实例可以参考吗，不了解builder.customPolicy以及builder.addPlugin的具体用法。
谢谢您

**Comment by Sayi** [comment]
@DevilTerminator 你貌似Java功底不够啊，把这个项目clone到本地  先把单元测试都看懂把。

**Comment by DevilTerminator** [comment]
好的吧，我功底确实不太好，嘻嘻。我再学习一下
