### ISSUE TITLE
关于后台操作POI模板

### ISSUE THREAD

**Issue by DevilTerminator** [Sayi/poi-tl#245]
您好，辛苦的程序员！冒昧打扰，请问，如果通过JAVA后台代码操作POI（word）模板中（{{+var}}，{{#var}}）这些东西，有办法去处理吗？就是通过JAVA修改word模板中是表格还是文本，就像，通过判断去生成一个模板，根据内容判断这块是使用表格，还是内容，这样可以实现吗？感谢您的回答

**Comment by Sayi** [comment]
@DevilTerminator 可以吧，你描述的很模糊。。。。。

**Comment by DevilTerminator** [comment]
嗯，是这个样子，给您截图吧，这样好理解一些，这个是目前相当于已经固定好了的模板
![image](https://user-images.githubusercontent.com/44009699/58711707-94e67900-83f1-11e9-90d7-f126b5a63025.png)，长这个样子，然后可以通过JAVA向模板传入参数，这样是一般情况。然后现在我打算写一个类似这样的模板
![image](https://user-images.githubusercontent.com/44009699/58712484-391cef80-83f3-11e9-92fd-d1cda7bc3ca2.png)，您看您可以理解吗。因为在下基础不好，没法独立完成word的生成，因此使用POI工具，觉得很符合要求。感谢作者的开发和解答

**Comment by Sayi** [comment]
http://deepoove.com/poi-tl/#_%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E6%9D%BF%E7%AD%96%E7%95%A5

**Comment by DevilTerminator** [comment]
您好，请问，我想系统的了解POI的使用，有没有整体上的教学流程或者讲解之类的。只可以通过查看源码以及http://deepoove.com/poi-tl/#example-table两种形式来学习POI的使用吗？有没有更为详细的讲解或者教程之类的。

**Comment by Sayi** [comment]
@DevilTerminator 就一个工具包的使用而已，百度有很多的~
