### ISSUE TITLE
升级1.5报错 nested exception is java.lang.NoClassDefFoundError: org/apache/poi/POIXMLDocumentPart

### ISSUE THREAD

**Issue by luoqiz** [Sayi/poi-tl#246]
我个人认为先前版本可以修补一些bug之后停止维护，将jdk和poi都升级，没必要守着低版本。你看很多工具是固定一个版本之后开发一段时间，会继续升级，在新版本上进行新功能开发，会摒弃低版本的功能迭代。    ------------  升级到1.5正式版后报错nested exception is java.lang.NoClassDefFoundError: org/apache/poi/POIXMLDocumentPart
![image](https://user-images.githubusercontent.com/22161059/58846242-17509080-86b1-11e9-975c-03c747d4d1e8.png)

**Comment by Sayi** [comment]
@luoqiz 你这个错误我这边重现不了。。

你说的很对，本来1.5.0打算升级成JDK1.8和poi4.1.0，后来回滚了，决定还是低版本再发一版。目前正在开发的1.6.0-SNAPSHOT已经升级了。

**Comment by luoqiz** [comment]
嗯嗯，我暂时还用我修改之后的pom文件吧，期待你的升级。等公司项目工作量减小后，我就研究一下这个项目，希望能够一起开发

**Comment by Sayi** [comment]
@luoqiz 辛苦了。不过你这个BUG我居然重现了，很奇怪的BUG。

**Comment by luoqiz** [comment]
哈哈，我没深入去看，但是用最新版的话，是没问题的。

**Comment by Sayi** [comment]
```xml
<dependency>
  <groupId>com.deepoove</groupId>
  <artifactId>poi-tl</artifactId>
  <version>1.6.0-beta1</version>
</dependency>
```
@luoqiz 发布了1.6.0的beta版本，升级了JDK到1.8，poi到4.1.0，测试了下，没有你这个问题。
