### ISSUE TITLE
超链接文档合并出现无法识别的内容

### ISSUE THREAD

**Issue by FlyingHe** [Sayi/poi-tl#247]
当使用片段表达式时(即{{+xxxx}})，在片段模板中若存在超链接文本，则合并到主模板后，程序未报任何异常，但生成的最终word文档报以下错误：
![image](https://user-images.githubusercontent.com/22047888/58860204-2ef23e00-86de-11e9-8669-102dfe965e2d.png)。

另：
希望能够在同一word模板中支持循环操作，而不是循环的内容需要放入另一模板中，若循环部分较多则需要创建多个片段模板，文件数量会大幅增加

**Comment by FlyingHe** [comment]
类似于这种，在模板内部循环
![image](https://user-images.githubusercontent.com/22047888/58864532-80eb9180-86e7-11e9-9069-e6694a6bf120.png)

**Comment by Sayi** [comment]
这种思路内部很复杂的，按你这种格式 其实空白单元格应该也要循环的。。。。

**Comment by FlyingHe** [comment]
> 类似于这种，在模板内部循环
> ![image](https://user-images.githubusercontent.com/22047888/58864532-80eb9180-86e7-11e9-9069-e6694a6bf120.png)

**Comment by FlyingHe** [comment]
上下空白单元格不需要循环呐，可以删掉，就跟你内部删掉占位符一样。
那个Bug复现了么

**Comment by Sayi** [comment]
的确是个超链接无法识别的BUG~

**Comment by FlyingHe** [comment]
> 的确是个超链接无法识别的BUG~

是1.5.1-SNAPSHOT还是1.6.0-SNAPSHOT

![image](https://user-images.githubusercontent.com/22047888/58923567-cc974d00-8772-11e9-90c8-23162870faab.png)
