### ISSUE TITLE
请问一下Sayi,文档模板{{+var}} 能不能继承标签的样式呢？

### ISSUE THREAD

**Issue by saplmm** [Sayi/poi-tl#248]
请问一下Sayi,文档模板{{+var}} 能不能继承标签的样式呢？
就像文本模版那样继承样式一样

**Comment by saplmm** [comment]
@Sayi  仅仅继承文本的样式就行了，这种能不能提供一下思路呢？🙏

**Comment by Sayi** [comment]
文档模板的样式在另一个子文档里面呀 你需要啥样式

**Comment by saplmm** [comment]
> 文档模板的样式在另一个子文档里面呀 你需要啥样式

比如 我设置 {{+var}} 这个是红色的，子模版 替换{{+var}} 之后，子模版的文字也变成红色的，或者说文档模版 能不能想文本模版 那样设置 样式？

**Comment by Sayi** [comment]
子文档你设置成红色就是的咯~

**Comment by saplmm** [comment]
> 子文档你设置成红色就是的咯~
现在的需求就是，子文档是公用的，但是模版有很多歌，要求的格式不一样....我现在的思路是根据标签的样式，新生成一个临时的子文档，然后再来合并，不知道这样行不行，标签的样式 poi-tl 应该可以获取吧

**Comment by Sayi** [comment]
新生成一个临时的子文档 的难度很大吧？
