### ISSUE TITLE
子模板新增了xsi:nil标签，合并到主模板丢失

### ISSUE THREAD

**Issue by menglaoer** [Sayi/poi-tl#249]
您好，最近有在尝试学习POI工具。在使用表格标签和文档标签整合的时候出现问题，会抛出异常，但是文本内容和文件整合一起没有问题。请问，表格和文件不可以放在一起吗？
(主要问题部分)模板如下：
![image](https://user-images.githubusercontent.com/39696529/59012855-22e7b700-886b-11e9-8f2c-26d960aad9ba.png)
代码是这样写的
![image](https://user-images.githubusercontent.com/39696529/59013057-a6090d00-886b-11e9-9ea6-fdae5bb5bdaa.png)

**Comment by Sayi** [comment]
没有你说的这个限制，可以把异常信息发出来

**Comment by menglaoer** [comment]
长这个样子
![image](https://user-images.githubusercontent.com/39696529/59020581-d6a57280-887c-11e9-9b6c-207b6aa52aaa.png)
![image](https://user-images.githubusercontent.com/39696529/59020604-ecb33300-887c-11e9-8359-ab1846dd14ce.png)

**Comment by menglaoer** [comment]
不是很懂哪里出了问题，是我写的不对吗？

**Comment by Sayi** [comment]
看似是你這個文檔很特別

**Comment by menglaoer** [comment]
您好，请问是，我文件的模板有问题吗？我觉得应该也不会有问题，但是实际操作上之后，整合会出异常。也不太清楚是哪里的问题。您觉得有什么好的建议或者方法吗？

**Comment by Sayi** [comment]
@menglaoer 你能给个能重现的单元测试吗？

**Comment by menglaoer** [comment]
[word.zip](https://github.com/Sayi/poi-tl/files/3295528/word.zip)
您看，这个文件符合您的要求吗。我测试了一下，没通过。

**Comment by Sayi** [comment]
@menglaoer Hi，定位出来了，这行代码改成这样就可以了：
```java
second.put("table", new MiniTableRenderData(RowRenderData.build("序号", "问题描述", "责任人"), null, "desc", 22.5F));
```
当表格为空时描述内容需要有值，不能为null，后续我会想办法修复这个BUG~

**Comment by menglaoer** [comment]
说实话，很开心能找到bug，不然总感觉自己问的一些低级问题，打扰了您的工作。

**Comment by Sayi** [comment]
给你点个赞~~
