### ISSUE TITLE
1.5版本能否兼容1.2版本？是否存在不兼容升级的情况

### ISSUE THREAD

**Issue by Fengjiya** [Sayi/poi-tl#251]
去年用的是1.2版本的，现在看到最新版是1.5版本，未找到1.2到1.5的升级特性是哪些？
能否兼容升级到1.5？

**Comment by Sayi** [comment]
版本说明：https://github.com/Sayi/poi-tl/releases

1.5和1.2不兼容的地方可能是几个方法名，功能是兼容的。
