### ISSUE TITLE
重复样式复制不对

### ISSUE THREAD

**Issue by louyizu** [Sayi/poi-tl#253]
com.deepoove.poi.util.StyleUtils  
 destRun.setColor(srcRun.getColor());
这个类的124行建议如下写法：
        CTR srcCTR = srcRun.getCTR();
        CTR destCTR = destRun.getCTR();
        if (srcCTR.isSetRPr()) {
            CTRPr srcRPr = srcCTR.getRPr();
            CTRPr destcRPr = destCTR.isSetRPr() ? destCTR.getRPr() : destCTR.addNewRPr();
            if (srcRPr.isSetColor()) {
                CTColor srcColor = srcRPr.getColor();
                CTColor destColor = destcRPr.isSetColor() ? destcRPr.getColor() : destcRPr.addNewColor();
                destColor.setVal(srcColor.getVal());
            }
        }

**Comment by Sayi** [comment]
@louyizu 谢谢你提建议。但是看了下`destRun.setColor(srcRun.getColor());`的源码，写法和你的是一样的，所以直接用就好了，没必要像你这么麻烦。
