### ISSUE TITLE
DocxRenderData 使用模板中如果存在表格，无法输出，存在错误values.XmlValueDisconnectedException

### ISSUE THREAD

**Issue by demon0228** [Sayi/poi-tl#254]

**Comment by demon0228** [comment]
父模板  +content
子模版内容  {{text}}{{#table}}{{@picture}}

对于表格 新版本存在异常
1.5.0版本之前 可以导出 但是{{#table}} 没有隐藏

**Comment by demon0228** [comment]
对于子模版  必须在第一个位置

**Comment by Sayi** [comment]
没有你这个顺序的说法，单元测试里面就有表格不在第一个位置的代码示例，是可以正常合并的。

你可以给个能复现你这个问题的testcase给我。
