### ISSUE TITLE
1.5版本

### ISSUE THREAD

**Issue by zenghuabin** [Sayi/poi-tl#255]
16:18:14.947 [main] DEBUG com.deepoove.poi.resolver.RunningRunParagraph - [LEFT]:段落内第5个run,标签为{{Date}}, 在这个run内的边界位置为：0
16:18:14.947 [main] DEBUG com.deepoove.poi.resolver.RunningRunParagraph - [RIGHT]:段落内第7个run,标签为{{Date}}, 在这个run内的边界位置为：1

**Comment by Sayi** [comment]
sorry，没理解问题点在哪。
