### ISSUE TITLE
使用文档标签插入文档的时候，编号错误了

### ISSUE THREAD

**Issue by saplmm** [Sayi/poi-tl#257]
假如文档A的标签var 在一个编号下边，这个时候在这里插入其他带有编号的文档B，插入之后，文档B的内容的编号会被自动修改...请问作者，怎么才能避免被编号被修改呢?

**Comment by saplmm** [comment]
@Sayi  作者空了帮忙看看吧，生产项目中有问题，求帮忙

**Comment by Sayi** [comment]
@saplmm 我写了个单元测试，似乎没有重现你的问题。

https://github.com/Sayi/poi-tl/blob/master/src/test/java/com/deepoove/poi/tl/issue/Issue257.java
