### ISSUE TITLE
一点点奇怪的想法

### ISSUE THREAD

**Issue by Ewasong** [Sayi/poi-tl#26]
我觉得这个项目要是可以函数化参数就太棒了。
比如我在word中 写{{add(1,2)}}
后台模板参数替换 add(*,*) 
1和2形成一个String 的参数列表, 传给后台
后台再进行处理

**Comment by Sayi** [comment]
意思是word模板中可以调用指定的后台Java方法？

**Comment by Ewasong** [comment]
我觉得调用后台方法太困难了，
只需要后台能获取到参数列表就可以了
比如有个方法能够获取到add(*,*)的参数列表就可以了

**Comment by Sayi** [comment]
解析  add(,)   有规则还是比较简单的，就看什么场景使用这类模板了。

[参见Poi-tl数学表达式插件](https://github.com/Sayi/poi-tl/wiki/3.%25%E8%AF%AD%E6%B3%95%E6%8F%92%E4%BB%B6%E4%B9%8B%E6%9C%89%E8%B6%A3%E7%9A%84%E6%95%B0%E5%AD%A6%E8%A1%A8%E8%BE%BE%E5%BC%8F)
如模板内容为{{%200*(10-1)}}
渲染后是1800
