### ISSUE TITLE
template.getXWPFDocument() 生成pdf表格数据为空

### ISSUE THREAD

**Issue by zenghuabin** [Sayi/poi-tl#260]
就是我直接用template.getXWPFDocument() 这个遍历我生成的表格的时候，表格的数据是空的，但是 是 template.getXWPFDocument() .writeToFile 直接输出到文件里却是有数据的
我直接转换成pdf表格里的数据也是空的，

**Comment by zenghuabin** [comment]
我直接用下面这个测试的，这样输出表格数据为空，如果我直接读取一个word表格里的数据，是直接可以读出表格里的数据的

        int curT = 0;
        int curP = 0;
        Iterator<IBodyElement> iBody = template.getXWPFDocument().getBodyElementsIterator();
        while(iBody.hasNext()){
            IBodyElement body = iBody.next();
            if(BodyElementType.TABLE.equals(body.getElementType())){//处理表格
                XWPFTable table = body.getBody().getTableArray(curT);
                List<XWPFTable> tables = body.getBody().getTables();
                table = tables.get(curT);
                if(table != null){
//                    htmlText = htmlText+
                    try {
                        readTableX(table);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    curT++;
                }
            }else if(BodyElementType.PARAGRAPH.equals(body.getElementType())){//处理段落
                XWPFParagraph ph = body.getBody().getParagraphArray(curP);
                if(ph != null){
                    readParagraphX(ph);
//                    htmlText = htmlText
                    curP++;
                }
            }
        }
    }

    public static String readParagraphX(XWPFParagraph p) {
        String tempStr = "";
        String text = p.getText();
       System.out.println(text);
        return tempStr;
    }
    public static String readTableX(XWPFTable tb) throws Exception {


        List<XWPFTableRow> rows = tb.getRows();
        //遍历行
        for(XWPFTableRow row:rows){
            //int rowHight = row.getHeight();
            String tr = "";
            List<XWPFTableCell> cells = row.getTableCells();
            //遍历列
            for(XWPFTableCell cell:cells){
                String text = "";
                List<XWPFParagraph> graphs = cell.getParagraphs();
                //遍历段落
                for(XWPFParagraph pg:graphs){
//                    text = text+pg.getText()+"<br/>";
                    System.out.println(pg.getText());
                }
                tr += "<td>"+text+"</td>";
            }

        }



        return "";
    }

**Comment by Sayi** [comment]
没有复现你的问题，我本地是可以获取所有表格的，具体是指哪一步数据为空？
