### ISSUE TITLE
HTML支持

### ISSUE THREAD

**Issue by daye** [Sayi/poi-tl#261]
因为合同模板内容是比较灵活的。比如一个段落内容里  某些字是加粗 黑体 字号比较大的。所以用编辑器来实现。poi-tl如何结合编辑器UE 来实现呢word模板制作呢

**Comment by Sayi** [comment]
#219

**Comment by Sayi** [comment]
其实就是HTML转化为word，自定义一个RenderPolicy，具体怎么转化可能需要研究下。

**Comment by Sayi** [comment]
#275

**Comment by Sayi** [comment]
Duplicate of #219
