### ISSUE TITLE
插入图片文件受损问题有解决办法吗？

### ISSUE THREAD

**Issue by zengdingxin** [Sayi/poi-tl#262]
![image](https://user-images.githubusercontent.com/14012002/61284801-5581b980-a7f2-11e9-8d5d-0d4f25519caa.png)
word本地插入图片同事也有替换变量的值，打开文档后提示文档受损

**Comment by Sayi** [comment]
文件发给我，我来复现定位下。

**Comment by zengdingxin** [comment]
文件模板测试用例都在里面 @

[word.zip](https://github.com/Sayi/poi-tl/files/3413200/word.zip)

**Comment by Sayi** [comment]
我这边一切正常~
