### ISSUE TITLE
页眉有水印图片解析出错

### ISSUE THREAD

**Issue by yvoneshau** [Sayi/poi-tl#263]
word文件页眉有水印图片，调用XWPFTemplate template = XWPFTemplate.compile(in)会出异常。//in：word二进制
异常：WARN  c.d.poi.resolver.RunningRunParagraph - found the empty text run,may be produce bug

**Comment by yvoneshau** [comment]
> word文件页眉有水印图片，调用XWPFTemplate template = XWPFTemplate.compile(in)会出异常。//in：word二进制
> 异常：WARN c.d.poi.resolver.RunningRunParagraph - found the empty text run,may be produce bug

去掉水印图片正常，请问在不调整word文件情况下可以规避此异常吗，而且多线程环境下该异常会导致内存溢出

**Comment by Sayi** [comment]
可以把带有水印的word文件发给我，我来复现下吗？  @yvoneshau

**Comment by yvoneshau** [comment]
[湖南非诉讼代理合同 (1).docx](https://github.com/Sayi/poi-tl/files/3415287/1.docx)
发给你了哈

**Comment by yvoneshau** [comment]
产生的异常的版本是1.4.2，升级为1.5.0版本后没有该异常，但是并发高时还是会报堆内存溢出，其它word无此问题
