### ISSUE TITLE
怎么进行数学公式TeX或MathMl的写入呢？

### ISSUE THREAD

**Issue by duttian** [Sayi/poi-tl#27]
就是怎么将数学公式的tex格式或mathml格式的写到word，打开的时候显示正常的数学公式。如：{A= \\{(x,\\, y)\\mathrel{|} x^{2}+ y^{2}\\leq 16\\}} 的tex，将显示x的平方加y的平方等，而不是tex格式串。

**Comment by Sayi** [comment]
sorry, 没有研究过数学公式的排版，可能帮不到你了。

**Comment by duttian** [comment]
谢谢，不知道怎么解决了，研究好几天了，一直没解决，不知道用什么api接口写入。有会的，给个提示，非常感谢！

**Comment by zyp0759** [comment]
> 就是怎么将数学公式的tex格式或mathml格式的写到word，打开的时候显示正常的数学公式。如：{A= \{(x,\, y)\mathrel{|} x^{2}+ y^{2}\leq 16\}} 的tex，将显示x的平方加y的平方等，而不是tex格式串。

你可以tex/mathml转图片然后再插入到word当中

**Comment by Sayi** [comment]
应该会有专门的API来操作公式的，考虑在后续版本对公式的插入给予支持，这样就可以生成高等数学考试卷了 :smile:
```xml
<m:oMathPara>
    <m:oMath>
        <m:r>
        </m:r>
        <m:f>
        </m:f>
    </m:oMath>
</m:oMathPara>
```

**Comment by draco1023** [comment]
在写html渲染插件的时候顺带支持了mathml的渲染，参见 https://github.com/draco1023/poi-tl-ext
但是目前poi-tl的clearPlaceholder存在一点问题，只检测了文本和图片，并未检测是否存在公式，所以当一个段落仅仅只有一个公式的占位符时既然完成了渲染也会被清理掉。
TeX也是可以转的，不过一般是先将TeX转MathML，然后再将MathML转为OMath。

**Comment by diaohancai** [comment]
> 就是怎么将数学公式的tex格式或mathml格式的写到word，打开的时候显示正常的数学公式。如：{A= \{(x,\, y)\mathrel{|} x^{2}+ y^{2}\leq 16\}} 的tex，将显示x的平方加y的平方等，而不是tex格式串。

大兄弟，解决了嘛？

**Comment by daixianjun** [comment]
> 应该会有专门的API来操作公式的，考虑在后续版本对公式的插入给予支持，这样就可以生成高等数学考试卷了 😄
> 
> ```
> <m:oMathPara>
>     <m:oMath>
>         <m:r>
>         </m:r>
>         <m:f>
>         </m:f>
>     </m:oMath>
> </m:oMathPara>
> ```

是否可以考虑支持一下呢？

**Comment by yinhexiaobai** [comment]
参见 [https://github.com/draco1023/poi-tl-ext](https://github.com/draco1023/poi-tl-ext)
写了一个示例，插入Latex公式。
```shell
<dependency>
    <groupId>io.github.draco1023</groupId>
    <artifactId>poi-tl-ext</artifactId>
    <version>0.4.5-poi5</version>
</dependency>

```

```java
 LaTeXRenderPolicy laTeXRenderPolicy  = new LaTeXRenderPolicy();
        Configure configure = Configure.builder()
                .bind("key",laTeXRenderPolicy)
                .build();
        XWPFTemplate template =
                XWPFTemplate.compile("template.docx",configure).render(
                        new HashMap<String, Object>(){{
                            put("title", "Hi, poi-tl Word模板引擎");
                            put("key", "$\\sum_{1}^{2} $");
                        }});
        template.writeAndClose(new FileOutputStream("output111.docx"));

```

**Comment by losky** [comment]
> > 应该会有专门的API来操作公式的，考虑在后续版本对公式的插入给予支持，这样就可以生成高等数学考试卷了 😄
> > ```
> > <m:oMathPara>
> >     <m:oMath>
> >         <m:r>
> >         </m:r>
> >         <m:f>
> >         </m:f>
> >     </m:oMath>
> > </m:oMathPara>
> > ```
> 
> 是否可以考虑支持一下呢？

这个就是word原生支持的公式，只需要将letex或者mml转换为omml公式就可以了
