### ISSUE TITLE
当模板内存在表格时，使用 '\n' 不能在表格内换行

### ISSUE THREAD

**Issue by Lmy0217** [Sayi/poi-tl#270]
模板 `template.docx` 如下：
![Snipaste_2019-07-23_00-38-12](https://user-images.githubusercontent.com/16065878/61648529-2e3f5680-ace2-11e9-8680-9af52ff8e70d.jpg)
poi 代码如下：
```java
HashMap<String, Object> hashMap = new HashMap<String, Object>();
hashMap.put("body3", "a\nb");
TemplateUtil.render("template.docx", hashMap, "out.docx");
```
生成的 `out.docx` 如下：
![Snipaste_2019-07-23_00-42-41](https://user-images.githubusercontent.com/16065878/61648836-cccbb780-ace2-11e9-869d-63f5b5874c22.jpg)

**Comment by Sayi** [comment]
poi-tl版本用的是多少

**Comment by Lmy0217** [comment]
@Sayi 1.6.0-beta1

**Comment by Lmy0217** [comment]
我按照 [TextRenderPolicy.java](https://github.com/Sayi/poi-tl/blob/master/src/main/java/com/deepoove/poi/policy/TextRenderPolicy.java) 新建了一个 TextRenderPolicy 类，将其中的
```java
run.addCarriageReturn();
```
改为
```java
run.addBreak();
```
能解决表格内换行的问题。
另外，我将其中的 `REGEX_LINE_CHARACTOR = "\\n"` 换成了 `REGEX_LINE_CHARACTOR = "\n"`。
