### ISSUE TITLE
多个文档标签如何处理？

### ISSUE THREAD

**Issue by jasonqusen** [Sayi/poi-tl#271]
一个模板文件里有多个文档标签，比如：{{+doc1}}{{+doc2}}{{+doc3}}
数据渲染后，生成的结果文件里，只有最后一个doc的内容，即doc3的内容

**Comment by xuwangcheng14** [comment]
参考下
`
templateData.put("doc1", new DocxRenderData(doc1TemplatePath, data1));
templateData.put("doc2", new DocxRenderData(doc2TemplatePath, data2));
templateData.put("doc3", new DocxRenderData(doc3TemplatePath, data3));
XWPFTemplate template = XWPFTemplate.compile(FileUtil.getResourceInputStream(templatePath), config).render(templateData);
`

**Comment by jasonqusen** [comment]
我就是这么写的，问题是合并后只有doc3的内容，没有doc1和doc2的内容

**Comment by jasonqusen** [comment]
我发现 用代码生成的标签会有这个问题，在word文档直接添加标签没有这个问题，请问是处理了什么元素吗

**Comment by Sayi** [comment]
无法重现这个问题，请尝试使用最新版本的poi-tl
