### ISSUE TITLE
SpELRenderDataCompute类中的compute方法内建议添加异常捕获

### ISSUE THREAD

**Issue by xuhai-sy** [Sayi/poi-tl#273]
@Override
    public Object compute(String el) {
		try{
			return parser.parseExpression(el).getValue(context);
		}catch (Exception e){
			return null;
		}
    }
建议这个修改和ELObjectRenderDataCompute一样，用SpEL会方便很多

**Comment by Sayi** [comment]
@xuhai-sy 你可以按照SpELRenderDataCompute代码随便改造的。
