### ISSUE TITLE
如何插入html内容？

### ISSUE THREAD

**Issue by xuwangcheng14** [Sayi/poi-tl#275]
你好！
我的子模板里有一块区域是html内容，里面有很多html标签，主要是前端返回的富文本内容，请问这种该如何插入到模板？

我百度了不少，网上都是将html全部转换成word（默认打开时web视图），但是我这个是只是一个子模板。
目前我想到的方案是利用jsoup将html解析，递归解析，将不同的html标签内容转换成poi支持的内容，但是想到里面可能存在很多种样式、段落、表格、图片的什么有感觉是不是太麻烦了。

不知道大神也没有什么好的解决方案？

PS：为什么没有交流群呢？

**Comment by Sayi** [comment]
#219

**Comment by xuwangcheng14** [comment]
遇到此问题的可以参考下。虽然不太完善：http://www.xuwangcheng.com/articles/2019/08/21/1566371746217.html
