### ISSUE TITLE
两个docx合并，文本框位置错乱了

### ISSUE THREAD

**Issue by Superman3691** [Sayi/poi-tl#280]
![image](https://user-images.githubusercontent.com/53902859/62701376-b62d9c00-ba16-11e9-80a2-0c305c247ff0.png)
![image](https://user-images.githubusercontent.com/53902859/62701433-d0677a00-ba16-11e9-914a-931e570ef76d.png)
合并之后的：
![image](https://user-images.githubusercontent.com/53902859/62701492-06a4f980-ba17-11e9-87cc-62db4c7af15e.png)

docx文件：
[25.docx](https://github.com/Sayi/poi-tl/files/3481589/25.docx)
[26.docx](https://github.com/Sayi/poi-tl/files/3481590/26.docx)

**Comment by Superman3691** [comment]
大神，希望您有时间时能尽快解决，谢谢啦！我这边急需使用。

**Comment by Superman3691** [comment]
大神，方便加一下qq吗？方便交流。 我的qq是1911514107@qq.com

**Comment by Sayi** [comment]
Hi, @Superman3691 你里面的几张图片用的是绝对位置拖动的，你用表格约束下，用相对位置就不会出现错乱的问题。

**Comment by Superman3691** [comment]
> Hi, @Superman3691 你里面的几张图片用的是绝对位置拖动的，你用表格约束下，用相对位置就不会出现错乱的问题。

谢谢大神回复，我不太理解您的意思,。方便加一下qq吗？1911514107@qq.com
[25.docx](https://github.com/Sayi/poi-tl/files/3485151/25.docx)
