### ISSUE TITLE
可以在word文档中，动态的生成柱状图和折线图吗

### ISSUE THREAD

**Issue by zhanghenghengheng** [Sayi/poi-tl#283]
![image](https://user-images.githubusercontent.com/29793611/63400530-b8282f80-c406-11e9-8c93-60ce0c5513db.png)

**Comment by xuwangcheng14** [comment]
这种建议使用jfreechart生成图片在插入到word中

**Comment by zhanghenghengheng** [comment]
好滴

发自我的 iPhone
