### ISSUE TITLE
怎么在指定位置设置文字样式颜色

### ISSUE THREAD

**Issue by LitChi666** [Sayi/poi-tl#286]
比如：有这么一个字符串
“好好学习，天天向上！”
在这串字符串中我要‘’学习'’改变颜色为红色加粗，怎么解决？
new TextRenderData("d0d0d0","好好学习，天天向上！")
这样之后我根本改不了啊，我只有文本格式。
求大神及时回复，万分感谢！

**Comment by Sayi** [comment]
@LitChi666 模仿TextRenderPolicy这个类 自定义一个渲染器。

**Comment by LitChi666** [comment]
列表模板怎么打印出像这种集合里面套集合的  
 List<List<TextRenderData>>  hots=new ArrayList<List<TextRenderData>>();
put("feature", new NumbericRenderData（hots）
因为自己需求这样要怎么解决。

**Comment by Sayi** [comment]
集合里面套集合的是啥意思？多层列表吗？

**Comment by LitChi666** [comment]
对的



------------------ 原始邮件 ------------------
发件人: "卅一"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 上午10:38
收件人: "Sayi/poi-tl"<poi-tl@noreply.github.com>; 
抄送: "1239071811"<1239071811@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Sayi/poi-tl] 怎么在指定位置设置文字样式颜色 (#286)




集合里面套集合的是啥意思？多层列表吗？
 
- 
你收到这个是因为你被提到了。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by Sayi** [comment]
还是学习下插件吧，想显示什么就写什么：http://deepoove.com/poi-tl/#_%E6%8F%92%E4%BB%B6%E6%9C%BA%E5%88%B6plugin_mechanism

**Comment by LitChi666** [comment]
好的，谢谢






------------------ 原始邮件 ------------------
发件人: "卅一"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 上午10:44
收件人: "Sayi/poi-tl"<poi-tl@noreply.github.com>; 
抄送: "1239071811"<1239071811@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Sayi/poi-tl] 怎么在指定位置设置文字样式颜色 (#286)




还是学习下插件吧，想显示什么就写什么：http://deepoove.com/poi-tl/#_%E6%8F%92%E4%BB%B6%E6%9C%BA%E5%88%B6plugin_mechanism

**Comment by LitChi666** [comment]
List<List<TextRenderData>> netWorkSpot=map.get("netWorkSpot");
怎么放到

列表模板
put("number123", new NumbericRenderData(FMT_DECIMAL, netWorkSpot);
        }}));




------------------ 原始邮件 ------------------
发件人: "卅一"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 上午10:38
收件人: "Sayi/poi-tl"<poi-tl@noreply.github.com>; 
抄送: "1239071811"<1239071811@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Sayi/poi-tl] 怎么在指定位置设置文字样式颜色 (#286)




集合里面套集合的是啥意思？多层列表吗？

**Comment by Sayi** [comment]
就按照你写的代码可以放进去的

**Comment by LitChi666** [comment]
------------------ 原始邮件 ------------------
发件人: "卅一"<notifications@github.com>;
发送时间: 2019年9月2日(星期一) 上午10:54
收件人: "Sayi/poi-tl"<poi-tl@noreply.github.com>;
抄送: "1239071811"<1239071811@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Sayi/poi-tl] 怎么在指定位置设置文字样式颜色 (#286)




就按照你写的代码可以放进去的

**Comment by LitChi666** [comment]
怎么放进去，有没有简单示例






------------------ 原始邮件 ------------------
发件人: "@荔枝"<notifications@github.com>; 
发送时间: 2019年9月2日(星期一) 上午10:58
收件人: "Sayi/poi-tl"<poi-tl@noreply.github.com>; 
抄送: "1239071811"<1239071811@qq.com>; "Your activity"<your_activity@noreply.github.com>; 
主题: Re: [Sayi/poi-tl] 怎么在指定位置设置文字样式颜色 (#286)



------------------ 原始邮件 ------------------ 
 发件人: "卅一"<notifications@github.com>; 
 发送时间: 2019年9月2日(星期一) 上午10:54 
 收件人: "Sayi/poi-tl"<poi-tl@noreply.github.com>; 
 抄送: "1239071811"<1239071811@qq.com>;"Mention"<mention@noreply.github.com>; 
 主题: Re: [Sayi/poi-tl] 怎么在指定位置设置文字样式颜色 (#286) 
 
 
 
 
 就按照你写的代码可以放进去的
