### ISSUE TITLE
windows正常导出word，linux环境出现问题

### ISSUE THREAD

**Issue by qiuxingguo** [Sayi/poi-tl#288]
我在windows的tomcat上使用此框架导出word时正常,在 centos7上的weblogic导出word时用微软的word软件打开显示参数错误,打开word是空白的(用wps打开是正常的),但是windows上用office的word打开没问题,请问下作者这是为什么呢？？详细信息为
参数错误 位置部分:/word/document.xml 行:2 列:0

**Comment by Sayi** [comment]
@qiuxingguo windows和centos是同样的代码和运行时环境吗？

我需要复现，可以把生成后有问题的word发给我，我打开看看有没有问题？

**Comment by qiuxingguo** [comment]
好的。稍后我会发一份在windows下正常生成并且可以打开的word，还有一份在centos下打开用office打开出错的word，希望你能帮助我看下这个问题(这两份word用wps都能打开)

**Comment by qiuxingguo** [comment]
好的。稍后我会发一份在centos下生成后打开用office打开出错的word，希望你能帮助我看下这个问题(这个word用wps能打开)

**Comment by qiuxingguo** [comment]
[word.zip](https://github.com/Sayi/poi-tl/files/3564345/word.zip)
你好,我上传了一个压缩包,里面有一份我在centos环境下生成的word文档,后缀名为docx，用microsoft的office打开会出错,用wps则没有。

**Comment by qiuxingguo** [comment]
你好,经过试验是容器的问题,不是操作系统的问题。在本地相同代码和相同数据的情况下,tomcat中导出的word用office打开没问题,weblogic中的代码导出的word用office打开会报错(我在本地windows同时安装了tomcat和weblogic)

**Comment by qiuxingguo** [comment]
![test](https://user-images.githubusercontent.com/26346776/64136889-5c5a9f00-ce27-11e9-8097-ae492bd4f8a0.jpg)
作者你好,我发现在weblogic环境中生成的word文档用office打开会出现如上错误,有时还会出现格式错误，但是点击确认自动修复之后能够打开，但是上图这种错误,点击确定之后,打开就是空白的word文档

**Comment by qiuxingguo** [comment]
![test](https://user-images.githubusercontent.com/26346776/64136906-6d0b1500-ce27-11e9-9881-cefcc169e915.jpg)

**Comment by qiuxingguo** [comment]
[图片.zip](https://github.com/Sayi/poi-tl/files/3567335/default.zip)

**Comment by qiuxingguo** [comment]
![compare](https://user-images.githubusercontent.com/26346776/64138980-e9a2f100-ce31-11e9-8d4b-bb9b89742cd4.jpg)
![Uploading compare2.jpg…]()
作者你好,我发现在weblogic环境下生成的word中的document.xml文件中的pic:pic 标签 会自动省略里面的内容,写成一个闭合标签。不知道可以不可以定义一个图片渲染器来解决这个问题

**Comment by Sayi** [comment]
确定两个容器下用的apache poi是同一个版本吗，确定是同一个模板吗？按道理生成的文档和容器没有关系，只和apache poi的版本和word模板有关系。

**Comment by Sayi** [comment]
可以给我一下Junit的代码吗？邮件给我也行。adasai90#gmail.com

**Comment by qiuxingguo** [comment]
作者你好,很感激你在百忙之中回复我。不过我确实在不同容器中发现了这个问题，在代码相同数据相同的情况下，tomcat中生成的没有问题,weblogic中的就有这个问题。windows和linux都是如此。但是我在之前关闭的提问中，找到了类似的问题，且我引用他的解决办法(复制他的自定义图片渲染策略类代码)就解决了这个问题。至于原因我也不知道为什么，至于单元测试代码，由于我引用了项目中的相关代码,我担心单发你一个单元测试类,有可能在你本地运行不起来。

**Comment by whjspdi** [comment]
@qiuxingguo 你的tomcat是什么版本，我tomact6也遇到该问题了。

**Comment by Sayi** [comment]
你说的图片渲染策略代码是apache poi 3.16以前的操作图片方式

**Comment by qiuxingguo** [comment]
> 你说的图片渲染策略代码是apache poi 3.16以前的操作图片方式

好吧，我们之前用的版本是3.17的好像 现在改成4.0的了。但是复制了那段自定义图片渲染策略代码确实管用..升级poi版本至4.0之后好像又报其他错误了

**Comment by qiuxingguo** [comment]
> @qiuxingguo你的tomcat的是什么版本，我tomact6也遇到该问题了。

我用的是tomcat9,之前tomcat没有出现问题,在weblogic出现生成的word用office出现参数错误的情况。后来升级poi版本之后又出现了其他错误

**Comment by qiuxingguo** [comment]
> @qiuxingguo你的tomcat的是什么版本，我tomact6也遇到该问题了。

我用的是tomcat9，之前的tomcat没有出现问题，在weblogic的出现生成的word用office出打开出现参数错误的情况。后来升级POI版本之后又出现了其他错误

**Comment by qiuxingguo** [comment]
> 你说的图片渲染策略代码是apache poi 3.16以前的操作图片方式

好的.感谢回复。

**Comment by qiuxingguo** [comment]
> 你说的图片渲染策略代码是apache poi 3.16以前的操作图片方式


![error](https://user-images.githubusercontent.com/26346776/64242992-24438100-cf39-11e9-9dab-5e106373fc3c.jpg)
作者你好,当之前我使用poi3.17版本的时候,zhe正常运行没有问题。当我将poi的版本升级到4.1.0的时候出现以上错误
java.lang.xmlbeans.xmloptions.setEntityExpansionLimit org/apache/xmlbeans/xmloptions

**Comment by Sayi** [comment]
@qiuxingguo NoSuchMethodError是类加载的时候报的错，应该是xmlbeans在poi 4.1.0 和 你的spring-webmvc版本号冲突了

**Comment by qiuxingguo** [comment]
> @qiuxingguo NoSuchMethodError是类加载的时候报的错，应该是xmlbeans在poi 4.1.0和你的spring-webmvc版本号冲突了。
> 
> 备注：poi4.1.0要求jdk1.8，poi-tl 1.6.0-beta1

好吧,谢谢作者。但是很奇怪的是在tomcat中没有出现这种错误,又是在weblogic中运行时产生的。同样的代码同样的数据

**Comment by qiuxingguo** [comment]
好吧，谢谢。但是很奇怪的是在tomcat的中没有出现这种错误，又是在weblogic中运行时产生的。同样的代码同样的数据。

**Comment by qiuxingguo** [comment]
> @qiuxingguo NoSuchMethodError是类加载的时候报的错，应该是xmlbeans在poi 4.1.0和你的spring-webmvc版本号冲突了。
> 
> 备注：poi4.1.0要求jdk1.8，poi-tl 1.6.0-beta1
![image](https://user-images.githubusercontent.com/26346776/64253488-fb7ab600-cf4f-11e9-9aa8-99d2b07b8087.png)

说错了,这个错误是我将poi版本升级至4.0导致的。然后我将poi版本升级至4.1.0 报错信息又不一样了
有篇文章跟我的情况一样,也是发布到weblogic 这是链接: https://issues.liferay.com/browse/LPS-92372
但是他也没有解决这个问题，也是报如下错误
java.lang.NoClassDefFoundError: Could not initialize class org.apache.poi.ooxml.POIXMLTypeLoader

**Comment by qiuxingguo** [comment]
> @qiuxingguo NoSuchMethodError是类加载的时候报的错，应该是xmlbeans在poi 4.1.0和你的spring-webmvc版本号冲突了。
> 
> 备注：poi4.1.0要求jdk1.8，poi-tl 1.6.0-beta1
![image](https://user-images.githubusercontent.com/26346776/64303665-aaa0a700-cfbb-11e9-877d-b7670eee8538.png)

有篇文章跟我的情况一样，也是发布到weblogic这是链接：https://issues.liferay.com/browse/LPS-92372
但是他也没有解决这个问题r

**Comment by whjspdi** [comment]
@qiuxingguo 解决了吗

**Comment by qiuxingguo** [comment]
解决了，通过在图片渲染策略类里面手动添加标签，是参照了之前别人写的，你可以在之前别人提交过已经关闭了的issue中找到 742432668 邮箱：742432668@qq.com 签名由 网易邮箱大师 定制 在2019年11月20日 08:11，whjspdi 写道： @qiuxingguo 解决了吗 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Sayi** [comment]
https://github.com/Sayi/poi-tl/blob/b0c7342914d485b5f1c30e84d5aad6a17469b23d/src/main/java/com/deepoove/poi/policy/PictureRenderPolicy.java 可以参考poi-tl 1.4.0图片策略版本的实现，后续poi3.16已经修复了这个问题，有些人出现bug可能还是版本原因吧。

**Comment by Sayi** [comment]
#238
