### ISSUE TITLE
最大的问题还是没有模板循环判断以及自定义函数语法功能！

### ISSUE THREAD

**Issue by ricozhou** [Sayi/poi-tl#291]
**最大的问题还是没有模板循环判断以及自定义函数语法功能**
像velocity，jxls等生成文本或者excel都只需要传入data，其他都是通过模板语法实现，但是poi-tl虽然解决了大多数生成word否问题，但依然需要通过传递data的时候特殊指定，也就是说还是需要更改后台java代码，建议能否像jxls一样可以实现类似jx:each等循环判断模板语法，这样将更加灵活！

**Comment by Sayi** [comment]
Hi, @ricozhou 好的建议，我也考虑过，但是word文档是强样式的，如果加入过多的标签(比如each)，会影响可读性和样式。所以循环的功能用{{+template}}实现，自定义函数功能用RenderPolicy插件实现。

**Comment by ricozhou** [comment]
完全理解word的难处，确实它是重样式，但这样的话确实也会有限制，可不可以考虑在需要的地方添加批注实现命令，像jxls那样，如果我想在word中操作表格，例如传入data是集合，然后循环按照行递增，貌似好像也得修改代码才行，再比如我想格式化一下date输出，模板中好像也没有类似实现，或者我只想产生一个随机数而不是通过data传入的随机数。
poi-tl确实是一个非常好的工具，对于样式生成非常好用，但好像对于纯文本操作没有完全实现，如果能实现类似velocity或者jxls功能那就完美了。
之所以提出这样的问题是因为我现在公司使用代码生成器，可以生成任何代码，但是后期需要补充大量的文档，excel也可以生成了，但是由于所有的数据来源都是数据库表，而word文档是多种多样的，格式等都不固定，所以就考虑能不能不针对每个不同的word做代码修改，而是可以像纯文本那样语法实现，并且还能保住样式，这样就完美了。


一点建议而已，希望作者的工具越来越好，哈哈哈谢谢




------------------ 原始邮件 ------------------
发件人: "卅一"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 中午11:32
收件人: "Sayi/poi-tl"<poi-tl@noreply.github.com>;
抄送: ""<2320095772@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Sayi/poi-tl] 最大的问题还是没有模板循环判断以及自定义函数语法功能！ (#291)




Hi, @ricozhou 好的建议，我也考虑过，但是word文档是强样式的，如果加入过多的标签(比如each)，会影响可读性和样式。所以循环的功能用{{+template}}实现，自定义函数功能用RenderPolicy插件实现。

**Comment by Sayi** [comment]
谢谢你的建议。

你说的格式化date和随机数功能都可以通过 SpringEL表达式实现的：http://deepoove.com/poi-tl/#_el%E8%A1%A8%E8%BE%BE%E5%BC%8Fspingel

**Comment by Sayi** [comment]
循环问题统一在这个issue #311
