### ISSUE TITLE
一个文档出现不相邻的多个动态表格怎么处理

### ISSUE THREAD

**Issue by MichealKen** [Sayi/poi-tl#293]
如果两个动态表格，怎么处理？不像例子中的那种两个表格一起的，两个动态表格在不同的页上，比如第一页有个动态表格，第3也有个动态表格的情况
Configure config = Configure.newBuilder().customPolicy("detail_table", new DetailTablePolicy())
.customPolicy("detail_equ", new EquTablePolicy())
.build();
这样设置不管用，第二个策略不会走，请问怎么处理

**Comment by Sayi** [comment]
@MichealKen 第二个策略会走的。

确认下表格内有这个标签{{detail_equ}}吗？

**Comment by MichealKen** [comment]
是的，确定有

**Comment by MichealKen** [comment]
这样的写法是否正确？

**Comment by MichealKen** [comment]
我在EquTablePolicy这个里面打了断点，没有进，生成的模板中{{detail_equ}}已经没了

**Comment by Sayi** [comment]
你给个单元测试给我
