### ISSUE TITLE
大规模并发场景下循环合并文档存在内存溢出情况。。

### ISSUE THREAD

**Issue by Halooooooo** [Sayi/poi-tl#296]
![image](https://user-images.githubusercontent.com/16648073/65028303-725f7800-d96e-11e9-8464-076f792cabc5.png)

**Comment by Halooooooo** [comment]
能否将DocxRenderPolicy 的 getMergedDocxs改成下面的方法呢

`
private List<NiceXWPFDocument> getMergedDocxs(DocxRenderData data, Configure configure) throws IOException {
        List<NiceXWPFDocument> docs = new ArrayList<NiceXWPFDocument>();
        byte[] docx = data.getDocx();
        List<?> dataList = data.getRenderDatas();
        if (null == dataList || dataList.isEmpty()) {
            // 待合并的文档不是模板
            docs.add(new NiceXWPFDocument(new ByteArrayInputStream(docx)));
        } else {
            XWPFTemplate temp = XWPFTemplate.compile(new ByteArrayInputStream(docx), configure);
            try {
                for (int i = 0; i < dataList.size(); i++) {
                    // 浅拷贝
                    XWPFTemplate cloenTemp = (XWPFTemplate) temp.clone();
                    cloenTemp.render(dataList.get(i));
                    docs.add(cloenTemp.getXWPFDocument());
                }
            } catch (CloneNotSupportedException e) {
                e.printStackTrace();
            }
        }
        return docs;
    }
`
并且最后进行一次 doc 的close

**Comment by Halooooooo** [comment]
```
private List<NiceXWPFDocument> getMergedDocxs(DocxRenderData data, Configure configure) throws IOException {
        List<NiceXWPFDocument> docs = new ArrayList<NiceXWPFDocument>();
        byte[] docx = data.getDocx();
        List<?> dataList = data.getRenderDatas();
        if (null == dataList || dataList.isEmpty()) {
            // 待合并的文档不是模板
            docs.add(new NiceXWPFDocument(new ByteArrayInputStream(docx)));
        } else {
            XWPFTemplate temp = XWPFTemplate.compile(new ByteArrayInputStream(docx), configure);
            try {
                for (int i = 0; i < dataList.size(); i++) {
                    XWPFTemplate cloenTemp = (XWPFTemplate) temp.clone();
                    cloenTemp.render(dataList.get(i));
                    docs.add(cloenTemp.getXWPFDocument());
                }
            } catch (CloneNotSupportedException e) {
                e.printStackTrace();
            }
        }
        return docs;
    }
```

**Comment by Sayi** [comment]
@Halooooooo 能做到浅拷贝吗？该如何实现

**Comment by Halooooooo** [comment]
@Sayi 我今天试一下= =主要是有些逻辑我不是很清楚。。怕改了以后是坑

**Comment by Halooooooo** [comment]
@Sayi 有办法只进行一次compile么 
```
                ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(docx);
                byteArrayInputStream.mark(0);
                XWPFTemplate temp = XWPFTemplate.compile(byteArrayInputStream, configure);
                for (int i = 0; i < dataList.size(); i++) {
//                    XWPFTemplate cloenTemp = (XWPFTemplate) temp.clone();
                    temp.render(dataList.get(i));
                    docs.add(temp.getXWPFDocument());
                    byteArrayInputStream.reset();
                    byteArrayInputStream.mark(0);
                    // help gc
//                    temp.clearRef();
                }
```
temp.render(dataList.get(i))
这一行一直有问题。。

**Comment by Sayi** [comment]
@Halooooooo 如果能只进行一次编译，那性能会有很大的提升，需要继续研究下

**Comment by xumin318** [comment]
你解决了吗？我也是合并大量word就会gc

**Comment by Sayi** [comment]
#329
