### ISSUE TITLE
是否可以支持动态循环生成title

### ISSUE THREAD

**Issue by DestinyL** [Sayi/poi-tl#297]
![image](https://user-images.githubusercontent.com/7259482/65138422-8a51fd00-da3d-11e9-91d9-ada6e891a800.png)

**Comment by Sayi** [comment]
没听明白~~

**Comment by DestinyL** [comment]
> 没听明白~~

就是说内外循环是嵌套的关系，预期效果:工作经历和{{+experience}}是一整块，但是呢，工作经历循环一次，而{{+experience}}里面的东西本就是循环，但是工作经历这样的数据是动态得到的，如果放到{{+experience}}就会和里面元素一起循环n次，实际上不想要这个效果
截一张图说明吧，实际上建议暴露一个接口，昨天试了很多种方式不好使，多加了一个模板才能解决问题：
![image](https://user-images.githubusercontent.com/7259482/65209479-deef8980-daca-11e9-9784-e1d3c5991098.png)

**Comment by fei3fei** [comment]
> > 没听明白~~
> 
> 就是说内外循环是嵌套的关系，预期效果:工作经历和{{+experience}}是一整块，但是呢，工作经历循环一次，而{{+experience}}里面的东西本就是循环，但是工作经历这样的数据是动态得到的，如果放到{{+experience}}就会和里面元素一起循环n次，实际上不想要这个效果
> 截一张图说明吧，实际上建议暴露一个接口，昨天试了很多种方式不好使，多加了一个模板才能解决问题：
> ![image](https://user-images.githubusercontent.com/7259482/65209479-deef8980-daca-11e9-9784-e1d3c5991098.png)
emmm 不知道我理解的对不对，如果把视野放大一点，是不是能看成一个列表呢？如果是的话，那应该就是一个renderData和一个renderPolicy可以解决的，如果不是太复杂的话感觉应该不需要，如果复杂的话扩展一下已有的就好了，多文档合并应该也可以。如果有理解不对的地方还请谅解！
关于接口的问题：接口只是一个规范而已，给出来了还是得自己实现，如果您是希望有这么一个实现类的话，有两个方法，第一：找作者，作者根据是否必要和投入情况来决定。第二：自己实现写一个（如果觉得可以的话可以顺带发个Pull Request，嘿嘿嘿）
