### ISSUE TITLE
{{*xxxx}}现在只支持TextRenderData，是否考虑图片或超链接？

### ISSUE THREAD

**Issue by DestinyL** [Sayi/poi-tl#298]
![image](https://user-images.githubusercontent.com/7259482/65212385-7907ff80-dad4-11e9-8f41-cb94ca948265.png)
并且图片或链接编号可选择属性进行跳过？

**Comment by Sayi** [comment]
源码很简单的，不妨你实现下？

**Comment by fei3fei** [comment]
效果：
![image](https://user-images.githubusercontent.com/29279905/65222916-a6fc3c80-daf2-11e9-8833-6dbe5f6724b0.png)
修改：
1.NumbericRenderData(想要啥封装成啥，看自己高兴)
![image](https://user-images.githubusercontent.com/29279905/65223297-78cb2c80-daf3-11e9-9c56-9eaeafc824b2.png)
2.策略：
![image](https://user-images.githubusercontent.com/29279905/65223461-d3fd1f00-daf3-11e9-8bd4-347dc6e51da2.png)
3.设置policy（ConfigureBuilder、或者新建语法）：为了方便我直接改了Configure的初始化方法
![image](https://user-images.githubusercontent.com/29279905/65223961-ce540900-daf4-11e9-8c21-bce3ae9e29ef.png)

**Comment by fei3fei** [comment]
> ![image](https://user-images.githubusercontent.com/7259482/65212385-7907ff80-dad4-11e9-8f41-cb94ca948265.png)
> 并且图片或链接编号可选择属性进行跳过？

效果：
![image](https://user-images.githubusercontent.com/29279905/65224689-41aa4a80-daf6-11e9-86e4-53226fb93637.png)
修改：
1.NumbericRenderData(想要啥封装成啥，看自己高兴)
![image](https://user-images.githubusercontent.com/29279905/65224939-c4330a00-daf6-11e9-9153-d346ab178b29.png)
2.策略（真正的渲染策略拿来就是用，啥也不用管，只是做个分配而已）
![image](https://user-images.githubusercontent.com/29279905/65226263-25f47380-daf9-11e9-82a8-4885d11551d0.png)
3.设置policy（ConfigureBuilder、或者新建语法）：为了方便我直接改了Configure的初始化方法
![image](https://user-images.githubusercontent.com/29279905/65226435-6ce26900-daf9-11e9-98e5-dbe61479eba9.png)

编号跳过：我看一下xml，编号是通过numID设置到pPr里的numPr标签里的，也就是这个编号控制的是段落的
``` xml
<w:pPr>
<w:numPr>
<w:numId w:val="11"/>
</w:numPr>
<w:rPr/>
</w:pPr>
```
rPr里能不能设置我就不知道了（如果不能，我觉得可以分段来解决这个问题）

**Comment by Sayi** [comment]
@fei3fei 你的理解很赞哦~

**Comment by fei3fei** [comment]
> @fei3fei 你的理解很赞哦~

感谢您的认同！也感谢您分享的代码！我的理解建立在poi-tl的基础上，照葫芦画瓢而已。
