### ISSUE TITLE
该插件可以在word文档中添加水印么

### ISSUE THREAD

**Issue by pengchant** [Sayi/poi-tl#299]

**Comment by pengchant** [comment]
如果是固定文字的水印，可以直接在word中操作模板实现需求（好像一般需求都满足了）
但是如果需要动态添加水印，还是需要该功能的。

**Comment by Sayi** [comment]
动态水印怎么理解？

**Comment by Sayi** [comment]
word水印属于poi的功能，请参考：org.apache.poi.xwpf.model.XWPFHeaderFooterPolicy.createWatermark(String)

**Comment by tianbymy** [comment]
同一个模板，不同的年份，水印文字不一样
