### ISSUE TITLE
DOC格式的文档没有办法支持吗？

### ISSUE THREAD

**Issue by likeZmy** [Sayi/poi-tl#30]

**Comment by Sayi** [comment]
你好，本项目是基于DOCX格式的。

**Comment by likeZmy** [comment]
请问那咱们项目没有针对DOC的吗？

**Comment by Sayi** [comment]
这个项目没有针对DOC的。操作DOC可以参考Apache POI HWPF***的API。

**Comment by likeZmy** [comment]
好的，谢谢。

**Comment by likeZmy** [comment]
请问Apache POI 存在一个BUG，就是读入一个页眉有图片的doc的时候，再导出，图片显示为X。想请您们在开发中是否碰到。

**Comment by Sayi** [comment]
没有处理过doc格式，所以无法回答你的这个问题了。

**Comment by likeZmy** [comment]
好的，还是感谢。
