### ISSUE TITLE
文本渲染中\n失效

### ISSUE THREAD

**Issue by a1105013796** [Sayi/poi-tl#300]
在使用自定义策略后，文本渲染完成后\n失效，以字符串的形式直接输出在文档中
![image](https://user-images.githubusercontent.com/32124539/65303036-644c6a00-dbaf-11e9-8b90-027c4c715962.png)

**Comment by pengchant** [comment]
`strbuild.append("\n\r");`

**Comment by a1105013796** [comment]
因为业务需求的问题，暂时不想用这种办法来处理，想用现有poitl支持的\n作为分隔符在前端输入，但是在自定义策略后\n失效了

**Comment by Sayi** [comment]
#295 应该是表格内部的一个换行bug

**Comment by a1105013796** [comment]
我在使用文本渲染的时候出现\n直接作为字符串打印了，但是没有找到具体的原因
![image](https://user-images.githubusercontent.com/32124539/65398761-a82bb300-ddeb-11e9-885c-19129de04dcc.png)
![image](https://user-images.githubusercontent.com/32124539/65398779-c5f91800-ddeb-11e9-8761-2a441d550f59.png)

**Comment by Sayi** [comment]
@a1105013796 调试下呗？断点应该在TextRenderPolicy类里面

**Comment by a1105013796** [comment]
![image](https://user-images.githubusercontent.com/32124539/65474021-ca393a00-deac-11e9-9f34-e26647060f6c.png)
\n在`renderTextRun`方法中没有被正确的分割。
POITL版本：1.5

**Comment by Sayi** [comment]
无法重现
