### ISSUE TITLE
java.lang.NoClassDefFoundError：org.apache.poi.POIXMLDocument

### ISSUE THREAD

**Issue by zhanghenghengheng** [Sayi/poi-tl#302]
因为业务需求 ，需要图表。还需要填充一些基本的表格信息。所以我 我引入了两种jar
<dependency>
            <groupId>com.deepoove</groupId>
            <artifactId>poi-tl</artifactId>
            <version>1.5.0</version>
        </dependency>
------------------
  <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-scratchpad</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml-schemas</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.18</version>
        </dependency>

**Comment by Sayi** [comment]
@zhanghenghengheng 直接用poi-tl 1.6.0-beta1

**Comment by zhanghenghengheng** [comment]
好事啦

发自我的 iPhone
