### ISSUE TITLE
com.deepoove.poi.util.BytePictureUtils.getUrlBufferedImage(BytePictureUtils.java:133) - getUrlBufferedImage error

### ISSUE THREAD

**Issue by yingpeili** [Sayi/poi-tl#303]
请求后缀名是jpeg的网络图片时，出现异常：javax.imageio.IIOException: Unsupported Image Type

**Comment by Sayi** [comment]
试了下，可能是你的jpeg图片不是标准的RGB模式，可以尝试使用https://github.com/haraldk/TwelveMonkeys 来解析这个图片文件。
