### ISSUE TITLE
咨询下如何导出一张或多张（数量无法固定）图片

### ISSUE THREAD

**Issue by qw1210p** [Sayi/poi-tl#304]
需求如下：不同的问题关联1张或多张图片，数量不固定，需要从数据库中查询后找到对应的图片文件并导出到word。
针对这种场景，模板和代码该如何设计呢？目前想采用NumbericRenderData,做成照片墙的样式，但是NumbericRenderData只支持Text文本作为参数，不支持照片；又看了下PictureRenderData ,貌似一次只能添加一张照片，能够采用List<PictureRenderData>，但是报如下错误：
![image](https://user-images.githubusercontent.com/3141573/65667875-36659a80-e073-11e9-8b43-c141beed5265.png)

**Comment by Sayi** [comment]
http://deepoove.com/poi-tl/#cus-policy-section
