### ISSUE TITLE
固定Table列数据填充

### ISSUE THREAD

**Issue by PanLei72** [Sayi/poi-tl#306]
能不能支持固定的Table列数据填充，比如这种是一个数据列表，需要根据id填充对应列的值。
![image](https://user-images.githubusercontent.com/29574794/66479425-0d132880-eacf-11e9-8e29-52d570096e27.png)

**Comment by Sayi** [comment]
没能理解你的表达哦？

**Comment by owenwong** [comment]
同求此方案

**Comment by coldstone** [comment]
是的，强烈需求此方案的实现方法。我来说一下场景吧：用户根据系统给定的模板标签自己制作和上传 word 模板。所以要解析的 Word 文档并不是开发人员处理的，无法得知表格在第几行要写入数据，也无法得知第几行要显示什么内容。

**Comment by Sayi** [comment]
@coldstone 如果实现此功能，具体怎么使用呢？比如模板怎么配置，服务端怎么匹配这个模板配置

**Comment by owenwong** [comment]
@Sayi 我举个例子啊，比如后台有一个用户实体，实体有属性姓名、性别、年龄、出生日期、住址等等。有的客户模板只需要呈现用户实体中的姓名、年龄、地址；有的客户需要显示全部（限定后台实体维护的属性）。如果前台想获取对应实体的属性，直接在模板中配置即可。

**Comment by coldstone** [comment]
或者是参考一下这个项目的思路：[https://github.com/snowindy/scriptlet4docx](url)

**Comment by Sayi** [comment]
类似一个循环问题，统一在 #311 讨论。
