### ISSUE TITLE
导出带图片Word，IO资源没有关闭BUG

### ISSUE THREAD

**Issue by leekoko** [Sayi/poi-tl#309]
我调用这个方法导出带图片的word
```java
XWPFTemplate template = XWPFTemplate.compile(inputStream2, Configure.createDefault()).render(mainEdaMajorEvent);
```
但是图片资源IO在``template.close()``时没有关闭

**Comment by Sayi** [comment]
图片资源是调用什么方法？

**Comment by leekoko** [comment]
> 图片资源是调用什么方法？

edaMajorEvent.setPicture(new PictureRenderData(500, 400, resultPath));

**Comment by leekoko** [comment]
> > 图片资源是调用什么方法？
> 
> edaMajorEvent.setPicture(new PictureRenderData(500, 400, resultPath));

可能是com.deepoove.poi.policy.PictureRenderPolicy.Helper#renderPicture的ins
