### ISSUE TITLE
请问现在poi-tl 1.2.0版本是否支持数据集合替换？

### ISSUE THREAD

**Issue by lcrandys1128** [Sayi/poi-tl#31]

**Comment by Sayi** [comment]
还不支持，正在考虑这方面的特性。

想问下，你们是什么场景需要集合替换？

**Comment by lcrandys1128** [comment]
这样的，其实类似于简历，有用户基本信息，然后有工作经验(数据集合)、项目经验(数据集合)、教育经历(数据集合)，类似这种的，只是举个例子方便你理解~

**Comment by Sayi** [comment]
恩，数据集合其实很好实现。
但是数据集合之间的样式无法做到通用(可能空一行，或者空两行，或者干脆不空行)，最简单的就是是每一条数据新起一行。

就因为集合之间的样式需要自定义，所以一直没有实现这个功能。

**Comment by lcrandys1128** [comment]
期待这个功能早日上线，加油~

**Comment by Sayi** [comment]
1.3.0 版本已支持。
