### ISSUE TITLE
循环for-each和判断if

### ISSUE THREAD

**Issue by tobenotobee** [Sayi/poi-tl#311]
我目前一直有通过word模板生成文档的需求，模板语法和您的非常相似，只不过我目前使用的必须基于windows平台，最近也在学习是否有完全基于java的解决方案，通过学习你的库，发现大部分功能都是可以使用的，我目前有很多下面描述的需求

根据word模板生成文档：
1. 根据前端页面的选项来控制某些段落是否出现 
2. 根据前端页面的选项来控制段落里的某一句话是否出现 
3. 根据前端页面的选项来控制某一整页是否显示

我的初步设想是：
是否可以支持 {{^var1}}内容{{/var1}} 这样的格式；{{^var1}}为起始符号，{{/var1}} 为结束符号。
1. 当var1的值是true，则内容会显示出来；
2. 当var1的值是false，则内容不会显示出来。

这样我就可以将：
1. 起始符号{{^var1}}放在段落前，结束符号{{/var1}} 放在段落后来控制整段是否显示
2. 起始符号{{^var1}}放在段落里某一句话前，结束符号{{/var1}} 放在这句话后来控制整句话是否显示
3.起始符号{{^var1}}放在整页前，结束符号{{/var1}} 放在整页后来判断整页是否显示

**Comment by monkey0376** [comment]
@tobenotobee  你好，我觉得你这个功能创意挺好，我对您的需求研究了一下，我觉得你上面的添加显式的标签太麻烦了， 我有个建议：
如果你有时间的话可以查看一下通过word标签的形式来进行操作，因为 标签是选中范围性的
> <w:bookmarkStart w:id="0" w:name="qqqq"/>
<w:r>
<w:rPr>
<w:rFonts w:hint="eastAsia"/>
</w:rPr>
<w:t>333333333</w:t>
</w:r>
<w:bookmarkEnd w:id="0"/>

这样你可以独立处理哪些标签范围内的节点是否删除。
只不过这种对poi的版本有要求，所以我觉得不能作为这个工具类的一部分。你可以了解一下，poi对这种标签操作我也没试过，嘿嘿。
我也很感兴趣，如果你实现了请贴一下代码。让大家观摩学习一下。谢谢

**Comment by Sayi** [comment]
有考虑过，但是在word里加上起始标签，整体可阅读性和理解起来不那么友好~~ @tobenotobee

**Comment by tobenotobee** [comment]
明白您的意思

那针对我所描述的这种需求，如果想统一使用模板来实现，有什么建议吗

因为不仅有动态内容，还需要使用poi-tl提供的其他policy

在2019年10月21日 09:31，卅一<mailto:notifications@github.com> 写道：

有考虑过，但是在word里加上起始标签，整体可阅读性和理解起来不那么友好~~ @tobenotobee<https://github.com/tobenotobee>

**Comment by Sayi** [comment]
@tobenotobee 
可以这样，如果是普通文本，就把动态显示的内容用文本标签{{var}}，后台判断不显示的时候附个空值。

如果是一个段落或者是一夜，就把动态显示的内容用文档标签{{+var}}，同理，后台判断不显示的时候附个空值。

**Comment by tobenotobee** [comment]
我也有考虑过您描述的做法

但是更多的时候文档是由业务部门出具的，内容经过层层审核:
1. 针对第一种使用{{var}}来控制显示内容，从实现角度来说，是没有问题的，但是这也导致，一旦var的内容变化就需要改代码，其次业务部门的人对显示内容，显示样式没有直观的感受，修改起来也比较笨拙，样式需要编码人员翻译成代码

我的想法是，尽量将文档生成与业务剥离，做成独立的微服务，文档所有内容的逻辑在文档模板上完成， 调用文档微服务的时候只需要传入模板编号，文档变量jsonObj，这样文档引擎只需要专注于渲染文档，最终输出word

所以才有我的提出的问题， 目前poi-tl可以支持文本变量，dynamicTable等等，可以满足绝大部分需求，唯独内容控制上暂时没有模板上的解决方案，所以才想起有没有办法可以通过{{^var}}{{/var}}标签包裹内容来控制。


另外我想要问一下，可不可以通过自定义policy来实现{{^var}}{{/var}}这样的需求

在2019年10月21日 14:53，卅一<mailto:notifications@github.com> 写道：

@tobenotobee<https://github.com/tobenotobee>
可以这样，如果是普通文本，就把动态显示的内容用文本标签{{var}}，后台判断不显示的时候附个空值。

如果是一个段落或者是一夜，就把动态显示的内容用文档标签{{+var}}，同理，后台判断不显示的时候附个空值。

**Comment by Sayi** [comment]
@tobenotobee 自定义policy是完全用代码控制word。

你的想法是个好想法，**如果能解决下面问题，很乐意接受你的想法**：

由于word的背后存储是xml格式的，所以你在word文档里面加上标签后，可能xml变成了这样：

```xml
<p>
    {{^var}}
</p>
<p>
    {{/var}}
</p>
```
显然，在word中写标签是没有问题的，但是当word保存后的xml数据格式是不合法的。

**Comment by ricozhou** [comment]
可不可以考虑将循环语法等脚本放置在侧边批注那，如excel的jxls实现方式

**Comment by coldstone** [comment]
所以这个需求是做还是不做？

**Comment by Sayi** [comment]
V1.7.1
