### ISSUE TITLE
通过模板生成模板存在【bug】

### ISSUE THREAD

**Issue by aixinyongheng** [Sayi/poi-tl#313]
再对通过模板生成的模板进行使用时，无法同时插入两个表格，并且插入一个表格时还会将生成模板的文档的其它的内容删除，只剩一个表格，这个如何解决？

**Comment by Sayi** [comment]
我需要一个单元测试来重现

**Comment by aixinyongheng** [comment]
` public void excelRender(String temppath,String outpath) throws Exception {
        TextRenderData[] arr=new TextRenderData[10];
        arr[1]=new TextRenderData("FFFFFF", "姓名");
        TableStyle headerStyle = new TableStyle();
        headerStyle.setBackgroundColor("80C687");//表的标题背景
        RowRenderData header = RowRenderData.build(new TextRenderData("FFFFFF", "姓名"), new TextRenderData("FFFFFF", "学历"),new TextRenderData("FFFFFF", "aaf"));//表头
        header.setRowStyle(headerStyle);
        RowRenderData row0 = RowRenderData.build("张三", "研究生","");//每列的数据
        RowRenderData row1 = RowRenderData.build("李四", "博士","aa");
        RowRenderData row2 = RowRenderData.build("王五", "博士后","");
        HashMap<String, Object> map = new HashMap<String, Object>();
        map.put("excel_first", new MiniTableRenderData(header, Arrays.asList(row0, row1)));
        map.put("excel_second", new MiniTableRenderData(header, Arrays.asList( row2)));
        XWPFTemplate template = XWPFTemplate.compile(temppath!=null&&!"".equals(temppath)?temppath:"T:\\wordtemp\\exceltemp.docx").render(map);
        FileOutputStream out = new FileOutputStream(outpath!=null&&!"".equals(outpath)?outpath:"T:\\wordtemp\\resulttest\\out_excel.docx");
        template.write(out);
        out.flush();
        out.close();
        template.close();
    }



    //模板生成模板
    @Test
    public void tempToTemp()throws Exception{
        HashMap<String, Object> map = new HashMap<String, Object>();
        map.put("item1", "{{#excel_first}}\n{{#excel_second}}");
        XWPFTemplate template = XWPFTemplate.compile("T:\\wordtemp\\newtemp.docx").render(map);
        FileOutputStream out = new FileOutputStream("T:\\wordtemp\\resulttest\\out_exceltemp.docx");
        template.write(out);
        out.flush();
        out.close();
        template.close();
        //模板生成表格
 excelRender("T:\\wordtemp\\resulttest\\out_exceltemp.docx","T:\\wordtemp\\resulttest\\out_out.docx");
    }`

**Comment by aixinyongheng** [comment]
public void excelRender(String temppath,String outpath) throws Exception {
        TextRenderData[] arr=new TextRenderData[10];
        arr[1]=new TextRenderData("FFFFFF", "姓名");
        TableStyle headerStyle = new TableStyle();
        headerStyle.setBackgroundColor("80C687");//表的标题背景
        RowRenderData header = RowRenderData.build(new TextRenderData("FFFFFF", "姓名"), new TextRenderData("FFFFFF", "学历"),new TextRenderData("FFFFFF", "aaf"));//表头
        header.setRowStyle(headerStyle);
        RowRenderData row0 = RowRenderData.build("张三", "研究生","");//每列的数据
        RowRenderData row1 = RowRenderData.build("李四", "博士","aa");
        RowRenderData row2 = RowRenderData.build("王五", "博士后","");
        HashMap<String, Object> map = new HashMap<String, Object>();
        map.put("excel_first", new MiniTableRenderData(header, Arrays.asList(row0, row1)));
        map.put("excel_second", new MiniTableRenderData(header, Arrays.asList( row2)));
        XWPFTemplate template = XWPFTemplate.compile(temppath!=null&&!"".equals(temppath)?temppath:"T:\\wordtemp\\exceltemp.docx").render(map);
        FileOutputStream out = new FileOutputStream(outpath!=null&&!"".equals(outpath)?outpath:"T:\\wordtemp\\resulttest\\out_excel.docx");
        template.write(out);
        out.flush();
        out.close();
        template.close();
    }



    //模板生成模板
    @Test
    public void tempToTemp()throws Exception{
        HashMap<String, Object> map = new HashMap<String, Object>();
        map.put("item1", "{{#excel_first}}\n{{#excel_second}}");
        XWPFTemplate template = XWPFTemplate.compile("T:\\wordtemp\\newtemp.docx").render(map);
        FileOutputStream out = new FileOutputStream("T:\\wordtemp\\resulttest\\out_exceltemp.docx");
        template.write(out);
        out.flush();
        out.close();
        template.close();

        excelRender("T:\\wordtemp\\resulttest\\out_exceltemp.docx","T:\\wordtemp\\resulttest\\out_out.docx");
    }
