### ISSUE TITLE
文档模板只能支持外部模板

### ISSUE THREAD

**Issue by imyuyu** [Sayi/poi-tl#314]
{{+var}} 

目前只支持外部的word模板，如：

`put("docx_word", new DocxRenderData(new File("~/segment.docx"), segments));`

请问是否有计划支持当前模板内（即使用一个模板文件内的某个segment）循环生成？

**Comment by Sayi** [comment]
有这个想法，但是还不知道怎么实现才最好

**Comment by imyuyu** [comment]
我看了一下源码，发现其实就是一个segment标签，不知道可不可以针对某个run所在的segment的直接进行单独循环渲染。
就像下面这种,获取占位符run所在的segment进行循环渲染。
`{{*segment}}`

第二种就是利用标签包裹：
`
{{segment}}
 内容
{{/segment}}
`

后台直接put一个集合或者数组

**Comment by Sayi** [comment]
Duplicate of #311
