### ISSUE TITLE
使用poi-tl  +xdocreport转换pdf，存在问题

### ISSUE THREAD

**Issue by xxoogov** [Sayi/poi-tl#316]
测试案例中的简历，转换成pdf。格式内容都正确。但是测试表格，转换成pdf，内容丢失
转换的文档是案例中简历生成的docx和案例中的一个表格，
转换代码如下
`    public static void makePdf(String docPath,String pdfPath){
        long startTime=System.currentTimeMillis();
        try {
            FileInputStream fileInputStream=new FileInputStream(new File(docPath));
            File outFile=new File(pdfPath);
            outFile.getParentFile().mkdirs();
            OutputStream out=new FileOutputStream(outFile);
            PdfOptions options= PdfOptions.create();
            PdfConverter.getInstance().convert(new XWPFDocument(fileInputStream), out, options);
        } catch (IOException e) {

            e.printStackTrace();
        }
        System.out.println("Generate pdf with " + (System.currentTimeMillis() - startTime) + " ms.");

    }`

**Comment by xxoogov** [comment]
经过测试，是xdocreport的原因，故关闭本记录

**Comment by ambition0802** [comment]
> 经过测试，是xdocreport的原因，故关闭本记录

请问你也遇到使用xdocreport将word转成pd时，中文内容丢失了嘛？
请问你后来有解决这个吗？

**Comment by xxoogov** [comment]
@ambition0802 

时间太久，已经忘记了
