### ISSUE TITLE
是否考虑加入循环与判断

### ISSUE THREAD

**Issue by Xenos3811** [Sayi/poi-tl#317]
没有循环导致模板整个很死.无法使用list动态生成,虽然后SPEL的判断运算符,但是我在动态插入图片时,使用Spel语法插入图片报错.

**Comment by Sayi** [comment]
可以具体说下你想要的功能

**Comment by Xenos3811** [comment]
循环方面:目前我需要在一个表格中插入多张图片,在图片个数不确定的情况下我无法做到.我只能限制图片个数才能解决.
判断方面:目前有SPEL可以使用,但是只局限于文本模板,其他模板并不能使用SPEL做判断

**Comment by Sayi** [comment]
判断方面其它模板不能使用SPEL这个没理解，可以再具体吗？

**Comment by Xenos3811** [comment]
由于没有循环语句,所以很多动态显示功能实现不了.例如List集合,所以只能写死的模板数据 例如:
{{   maL.size()>0?maL[0].maName:''}} 
图片也是一样,无法循环输出图片,所以想像以下方式输出
{{   maL.size()>0?@maL[0].img:''}}

**Comment by Sayi** [comment]
@Xenos3811 Hi，我想问下这种判断逻辑为什么不放到后端代码里面去做呢？比如标签{{name}}，后端代码如下：
```java
map.put("name", maL.size() > 0 ? maL[0].getMaName() : "");
```

**Comment by Xenos3811** [comment]
@Sayi 谢谢,这很好的解决了判断的问题,请教一下,如何解决循环的问题

**Comment by Sayi** [comment]
Duplicate of #311
