### ISSUE TITLE
word合并的时候从新的页面开始

### ISSUE THREAD

**Issue by xumin318** [Sayi/poi-tl#320]
<img src="http://newwx.ahghw.org//upload/file/vote/0/402881f73e1c4ba4013e1c4c08470001_20191112125932249.png">
怎么在合并的时候另起新页面

**Comment by Sayi** [comment]
你在制作模板的时候，让标签{{+docx}}新启一页呀~

**Comment by xumin318** [comment]
我按照例子来的 怎么新起一页

**Comment by xumin318** [comment]
> 你在制作模板的时候，让标签{{+docx}}新启一页呀~
怎么新启一页

**Comment by Sayi** [comment]
word里面插入一个分页符吧。。。。。

**Comment by xumin318** [comment]
可以用
