### ISSUE TITLE
数组该如何取值？

### ISSUE THREAD

**Issue by zsf513** [Sayi/poi-tl#321]
参数里面传入了数组，在模板里该如何取值呢？通过{{arrStr[0]}}并取不到值

**Comment by Sayi** [comment]
有一套标准的表达式称为Spring表达式，[poi-tl 支持Spring EL表达式所有语法，包括数组](http://deepoove.com/poi-tl/#_el%E8%A1%A8%E8%BE%BE%E5%BC%8Fspingel)
