### ISSUE TITLE
请问在自定义策略中表格合并行要怎么实现？

### ISSUE THREAD

**Issue by RuiCR** [Sayi/poi-tl#322]
demo示范了在自定义策略中如何合并列，那要怎么才能合并行呢？

**Comment by Sayi** [comment]
com.deepoove.poi.util.TableTools.mergeCellsHorizonal(XWPFTable, int, int, int)

com.deepoove.poi.util.TableTools.mergeCellsVertically(XWPFTable, int, int, int)
