### ISSUE TITLE
关于动态表格

### ISSUE THREAD

**Issue by qiuxingguo** [Sayi/poi-tl#324]
请问下作者实现DynamicTableRenderPolicy 这个类实现自定义渲染策略的时候。可不可以做到在不影响现有表格的情况下 在行中动态插入多列数据。我看了一下有插入行的api,没有找到关于新增列的。在XWPFTableRow 这个操作行对象的类中只找到了 createCell()  和 addNewTableCell() 两个新增列的方法。

**Comment by makuo123** [comment]
你好，有找到解决方法吗
