### ISSUE TITLE
动态表格 在已有行数据中,动态插入列

### ISSUE THREAD

**Issue by qiuxingguo** [Sayi/poi-tl#325]
请问下作者实现DynamicTableRenderPolicy这个类实现自定义呈现策略的时候。可不可以做到在不影响现有表格的情况下在行中动态插入多列数据。我看了一下有插入行的api，没有找到关于插入列的API.在XWPFTableRow这个操作行对象的类中只找到了createCell（）和addNewTableCell（）两个添加列的方法。请问下作者能实现这种业务需求吗

**Comment by Sayi** [comment]
@qiuxingguo 不影响现有表格是指怎么不影响？

一般情况下增加列要指明在哪一行增加列，所以首先需要有XWPFTableRow这个对象，然后通过createCell增加列。

**Comment by qiuxingguo** [comment]
不能直接指定插入列位置吗。比如现在我这个表格比较特殊。前后单元格都涉及到合并了。我需要在一行中间插入不定数量的列。
![image](https://user-images.githubusercontent.com/26346776/69133681-46d54700-0af1-11ea-8130-18c8854864af.png)
如上图,我需要在标识部分插入若干列

![image](https://user-images.githubusercontent.com/26346776/69133638-345b0d80-0af1-11ea-8c8d-c9424f1dee78.png)

**Comment by tiaoxixiaoji** [comment]
大佬，同求方法

**Comment by slolwind** [comment]
最近遇同样的场景，同求
