### ISSUE TITLE
模板中文本标签为非黑色时，设置文字的颜色不起作用

### ISSUE THREAD

**Issue by whjspdi** [Sayi/poi-tl#326]
#289 
这个之前忘记说了，我不知道提交单元测试给你。我就用项目里的测试用例来复现吧。

1.修改\poi-tl\src\test\resources\text_render.docx 中{{text}}为白色
2.运行\poi-tl\src\test\java\com\deepoove\poi\tl\policy\TextRenderTest.java#testTextRender
3.输入的结果out_text_render.docx中，应为绿色的text字样，还是白色。

![image](https://user-images.githubusercontent.com/20513975/69212211-9ff9b500-0b9b-11ea-81c5-61642f8d9d1a.png)

图片中加了高亮，便于看出颜色

**Comment by Sayi** [comment]
因为段落样式白色覆盖了设置的绿色，bug已修复随着下个版本发布。
