### ISSUE TITLE
请问 文档合并中chart图表的合并问题

### ISSUE THREAD

**Issue by silentbody** [Sayi/poi-tl#327]
sayi 您好， 1.6bate 版本目前不支持 chart 图表内容的合并，这个功能是不是难度较大呢，我已经看了好几天了，不知道怎么把待合并文件中的图表 packagePart 及 relationship 和 关联的 数据excel 的packagePart 合并进输出文档中。

**Comment by Sayi** [comment]
@silentbody 是的，我还没有仔细研究chart

**Comment by Sayi** [comment]
#172
