### ISSUE TITLE
极端情况下性能，文档模板合并8000次内存溢出

### ISSUE THREAD

**Issue by Sayi** [Sayi/poi-tl#329]
如题，在极端状况下内存会持续增长。

**Comment by Sayi** [comment]
POI has to load the whole document into memory using the usermodel and into Java objects.
poi会把文档全部加载到内存中，文档只有几十KB，但是内存占用可能会有几MB

https://bz.apache.org/bugzilla/show_bug.cgi?id=50993
https://bz.apache.org/bugzilla/show_bug.cgi?id=61251

**Comment by Sayi** [comment]
## 基本定位方法
内存溢出最简单的两个方法是查看gc日志和查看堆dump。
### 查看gc日志
设置JVM参数，开启gc日志
```shell
-Xloggc:gc.log  -XX:+PrintGCDetails -XX:+PrintGCDateStamps
```
可以看到gc.log的输出中老年代的空间持续在增加。
也可以使用jstat命令查看gc（先通过jcmd命令确定进程pid）：
```shell
 jstat -gc 33312 1000 500
```

### 查看堆dump
堆dump的时候虚拟机会触发一次gc，如果不希望虚拟机触发gc，可以使用-all选项：
```shell
jcmd 33312  GC.heap_dump -all ~/pidXXX.hprof
```

**Comment by Sayi** [comment]
## 优化
poi-tl原先会将子模板优先全部渲染装载到List里面去，改成使用Iterator去逐个渲染会是一种优化。
简单的比较了下List和Iterator方式下poi-tl的GC情况：
* List
![image](https://user-images.githubusercontent.com/1394854/70307373-f9bcd900-1843-11ea-8b96-222f567dd774.png)

* Iterator
![image](https://user-images.githubusercontent.com/1394854/70307394-06413180-1844-11ea-8ddf-a098a7620c23.png)

可以简单的看到Iterator下年轻代回收对象更多，老年代回收更少。

**备注：此次实验不是很严格，后续会考虑对极端情况下的性能优化**。

**Comment by Sayi** [comment]
# 优化二
V1.7.1版本支持模板内循环，将一篇文章示例循环5200次性能情况良好。如果在极端情况下，可以考虑采用区块对标签代替文档合并。

![image](https://user-images.githubusercontent.com/1394854/76273162-2c012b00-62b8-11ea-8e61-e8be2e13b244.png)

**Comment by Xlinlin** [comment]
这应该是本身POI的性能问题吧
