### ISSUE TITLE
请问文本框的变量怎么替换?

### ISSUE THREAD

**Issue by DonalLiu** [Sayi/poi-tl#33]
在模板word里插入一个 文本框 , 文本框里 输入 {{xxx}} 变量 , 可是生成后的word 文档中 依然存在{{xxx}} ,没有替换成功

**Comment by Sayi** [comment]
目前不支持文本框。

不过大多数情况，表格格式可以和文本框有着一样的排版效果，表格甚至更专业，可以尝试用表格布局问文档。

**Comment by InvincibleXG** [comment]
如果这个库能集成遍历并修改文本框的API那就更好了，说实话除了XMLObject其他都比较容易操作
