### ISSUE TITLE
新增的表格、图片、列表功能合并探讨

### ISSUE THREAD

**Issue by xuanbo** [Sayi/poi-tl#332]
作者你好，这个开源项目特别好，满足很多基本的场景。
因此，我fork了一份代码，然后加了几个新功能，在这里与你探讨一下。

1. 表格
目前表格是需要用代码指定几行几列，以及样式。复杂一点的表格需要写代码实现，这里不做考虑。
我这里实现了 table|limit:var 的语法。把第一行作为表头，第二行作为模板，然后基于第二行的模板复制出新的行，保证与模板样式一样。

2. 图片
目前图片是需要在代码中指定高度、宽度。
我这里实现了 image|height*width:var 的语法。模板中就能指定高度、宽度，数据传入只需要传递图片字节数组base64加密的字符串。

3. 列表
目前列表也是需要在代码中指定列表的样式。
我这里实现了 list|limit:var 的语法。把第一个列表当作模板，复制出新的行。

这三个扩展点，均采用 name|attr:var 的语法，主要是想最大程度的利用 word 的样式，减少代码编写。

不知道这些扩展功能是否可以合并到 poi-tl ，或者能给 poi-tl 带来更多的思考。

毕竟从 poi-tl 中受益很多，工作中大大减少了开发量。希望能回馈 poi-tl 。

这是我fork出来的地址：https://github.com/xuanbo/poi-tl

**Comment by Sayi** [comment]
如果有循环功能，第一个表格问题似乎迎刃而解了，而且循环支持的场景更广，不仅仅是表格。接下来poi-tl的迭代重点就是for-each语法和if判断语法。

height、width、limit的想法是认同的，为什么不在poi-tl默认的语法上扩展，支持语法带参数？这样就可以用最少的代码量实现你这个功能。

最后，给你点个赞 👍 ，做的不错!

**Comment by xuanbo** [comment]
这个确实没有默认语法扩展，前天才接触这个项目。领导要调研word模板引擎，然后提出我上述说的功能要求。因此，比较粗暴的加了一个我称为 pattern（name|attr:var） 的模式，这个render的优先级介于custom与default之间。后面看怎么扩展默认语法，更优雅一点。感谢作者，让工作轻松不少:)
