### ISSUE TITLE
在复杂样式的表格下，如何用插件实现保留样式下渲染新的行列？希望不使用{{#var}}实现

### ISSUE THREAD

**Issue by CodeNoobLH** [Sayi/poi-tl#333]
![微信截图_20191216165807](https://user-images.githubusercontent.com/49932926/70893057-42834780-2025-11ea-807f-1dddc1254ec1.png)
如图片所示，表头是一个浅黄色底色的样式，表格内容由浅黄色和白色样式交替换行，并且有绿√红×出现，这种表格如何用poi-tl实现呢？我用DynamicTableRenderPolicy实现的并没有原本表格的样式，项目经理不希望使用{{#var}}实现，因为对于制作模板的人来说预览是否不直观，有没有更好的方式实现呢？如果实在不得不使用{{#var}}实现，又应该怎么做呢？谢谢

**Comment by CodeNoobLH** [comment]
留两行不同颜色的内容，然后复制这行内容从而保留样式再替换文字内容会不会比较实际点呢？

**Comment by Sayi** [comment]
把预留行的样式复制到新增的行是个可行的思路。

**Comment by CodeNoobLH** [comment]
> 把预留行的样式复制到新增的行是个可行的思路。

那单元格内容的样式该怎么处理呢？像正文√×！有三个颜色样式的应该如何处理？可以针对单元格进行设置字体颜色吗？（√×！是文字）。行的样式我已经完成了。

**Comment by Sayi** [comment]
同理，单元格也可以设置样式。单元格里面的文字也可以设置样式。

**Comment by Sayi** [comment]
#334
