### ISSUE TITLE
表格新增一行 如何保留上一行的样式

### ISSUE THREAD

**Issue by zy5651768** [Sayi/poi-tl#334]
demo里的  public class DetailTablePolicy extends DynamicTableRenderPolicy

   XWPFTableRow insertNewTableRow = table.insertNewTableRow(goodsStartRow);
insertNewTableRow 是没有样式的

如何复制上一行的样式

**Comment by CodeNoobLH** [comment]
TableStyle可以设置行样式，Style可以设置文本样式
List<RowRenderData> goods=new ArrayList<RowRenderData>();
TextRenderData[] textRenderData=new TextRenderData[11];
textRenderData[0]=new TextRenderData("文字", style);
RowRenderData good = RowRenderData.build(textRenderData);
goods.add(good);
datas.put(key,goods);
builder.customPolicy(key, new DetailTablePolicy());

类似这样的写法可以完成

**Comment by zy5651768** [comment]
TableStyle 我看代码里只有

/**
     * 背景色
     */
    private String backgroundColor;

    /**
     * 对齐方式 STJc.LEFT 左对齐 STJc.CENTER 居中对齐 STJc.RIGHT 右对齐
     */
    private STJc.Enum align;

这两个属性 ，想要复制原来cell里面的样式到新的cell里，例如加粗 字号大小。

**Comment by CodeNoobLH** [comment]
另一个Style就是针对文字的，结合TableStyle一起使用，就可以把整个表格的样式和表格里面的字样式都调整了，我昨天刚在项目里做了这个功能，一起探讨



---原始邮件---
发件人: "zy5651768"<notifications@github.com&gt;
发送时间: 2019年12月19日(周四) 下午4:13
收件人: "Sayi/poi-tl"<poi-tl@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"CodeNoobLH"<846085297@qq.com&gt;;
主题: Re: [Sayi/poi-tl] 表格新增一行 如何保留上一行的样式 (#334)



TableStyle 我看代码里只有
 
/**
 * 背景色
 */
 private String backgroundColor;
 /**  * 对齐方式 STJc.LEFT 左对齐 STJc.CENTER 居中对齐 STJc.RIGHT 右对齐  */ private STJc.Enum align;  
这两个属性 ，想要复制原来cell里面的样式到新的cell里，例如加粗 字号大小。

**Comment by Sayi** [comment]
参考下表格行循环插件： [HackLoopTableRenderPolicy](http://deepoove.com/poi-tl/#hack-loop-table)

**Comment by zlp8013** [comment]
> 参考下表格行循环插件： [HackLoopTableRenderPolicy](http://deepoove.com/poi-tl/#hack-loop-table)

复杂的文本样式怎么设置,Style中只有一部分,行高这些复杂的没有
