### ISSUE TITLE
一份模板如何渲染出多页内容？

### ISSUE THREAD

**Issue by CodeNoobLH** [Sayi/poi-tl#337]
例如demo的付款通知书，我在表格达到一定行数是需要分页，而第二页的格式需要和第一页完全一样，然后将未写完的数据在第二页的表格里继续填，例如付款通知书里的抬头等信息第二页都要保留，然后表格假设设置10行，我实际有17行数据，将模板复制一份，在第二页的表格里继续后7行内容。如何用一页的模板去渲染多页的数据呢？

**Comment by Sayi** [comment]
模板中使用已有的表格，设置表格属性：表格属性--行--勾选"在各页顶端以标题行形式重复出现"，然后动态操作这个表格就行了。
