### ISSUE TITLE
模板配置数据格式转化函数

### ISSUE THREAD

**Issue by forestMr** [Sayi/poi-tl#338]
希望能够封装一些数据格式转化的函数

**Comment by Sayi** [comment]
有数据格式转换需求的可以考虑使用 Spring EL表达式

**Comment by forestMr** [comment]
我的意思是使用spring el表达式在引用自定义函数的时候需要写全包路径，能否在在类加载那里给个接口。

**Comment by Sayi** [comment]
完全使用Spring EL的方式，要看SpringEL有没有提供接口了。

可以换个思路，把你的自定义函数当作变量放到模型中，这样就可以用这个变量来调用了。
