### ISSUE TITLE
不知道可不可以动态插入图片

### ISSUE THREAD

**Issue by mosaic666** [Sayi/poi-tl#341]
动态插入多个图片，图片的数量不知道的情况下

**Comment by Sayi** [comment]
参见 [ListRenderPolicy 集合插件，允许同时渲染多个文本、图片、表格、列表等](http://deepoove.com/poi-tl/#_%E5%8F%AF%E9%80%89%E6%8F%92%E4%BB%B6%E5%88%97%E8%A1%A8)
