### ISSUE TITLE
目前工具只支持docx生成，如果想要支持doc呢？

### ISSUE THREAD

**Issue by tang147** [Sayi/poi-tl#345]
![image](https://user-images.githubusercontent.com/24455574/72331071-88016600-36f2-11ea-961d-9872357cef91.png)

docx和doc是两种生成方式，能否扩展doc格式支持？

**Comment by tang147** [comment]
我在项目中想同时支持doc,docx,目前想要用动态灵活变量，目前的做法是 先将doc转成docx;去调用模板渲染结果 ，再将结果docx转回doc，这块能否预留接口或者什么的，让实现者自己 来转doc渲染？

**Comment by tang147** [comment]
或者要支持动态生成doc,需要用原生的xml方式，用freemarker来转？

**Comment by Sayi** [comment]
@tang147 doc和docx格式不一样，没有过多的精力来支持doc哦，不过poi-tl的模板思想可以用到doc模板的设计中。
