### ISSUE TITLE
请教个spring-el 列表问题?

### ISSUE THREAD

**Issue by tang147** [Sayi/poi-tl#346]
目前用el表达式，单个对象是可以用的？但如果是集合，也想通过集合的方式来获取模板的内容。
这个该怎么做呢？
思路是不是通过多个子word文件，然后再合并成一个文档记录？
例如模板配置

{{custName}}
{{new java.text.SimpleDateFormat('yyyy').format(dateCash)}}年{{new java.text.SimpleDateFormat('mm').format(dateCash)}}月{{new java.text.SimpleDateFormat('dd').format(dateCash)}}

**Comment by Sayi** [comment]
没太理解你说的问题
