### ISSUE TITLE
关于run处于表格中时的位置

### ISSUE THREAD

**Issue by amkile** [Sayi/poi-tl#350]
doRender回调函数接受的参数希望带有表格相关的位置信息(行/列)及单元格cell完整的信息

**Comment by amkile** [comment]
我现在的业务是在主table中某个单元格cell中,创建一个子table,而主table的宽度不知道的话会造成子table撑大主table的现象
![image](https://user-images.githubusercontent.com/44280409/72603953-f8a7bd00-3954-11ea-978d-bfa32663bbe4.png)

**Comment by MybeautifulSunShine** [comment]
怎么解决的呀怎么自己关闭了呢
