### ISSUE TITLE
SpingEL表达式使用问题：切换ELMode.SPEL_MODE后报错

### ISSUE THREAD

**Issue by GraysonFung** [Sayi/poi-tl#351]
![](https://tva1.sinaimg.cn/large/006tNbRwgy1gbjd54ylfaj31jk0dqjv0.jpg)

![](https://tva1.sinaimg.cn/large/006tNbRwgy1gbjd6jldbfj32du0mw47v.jpg)

**Comment by Sayi** [comment]
SpringEL在找不到属性的时候就会报错的，可以看下supplier_name是否存在，或者EL使用方式是否有问题
