### ISSUE TITLE
列表循环

### ISSUE THREAD

**Issue by CodeToSurvive1** [Sayi/poi-tl#352]
@Sayi 咨询下是否支持下面方式或者什么思路能实现该效果？

1. title
    content
    url
2. title
    content
    url
3. title
    content
   url

**Comment by Sayi** [comment]
自定义策略

**Comment by Sayi** [comment]
1.7.2 版本完全支持这种写法，不需要自定义策略。

参考文档：[区块对](http://deepoove.com/poi-tl/#_%E5%8C%BA%E5%9D%97%E5%AF%B9)

**Comment by zhongyong168** [comment]
> 1.7.2 版本完全支持这种写法，不需要自定义策略。
> 
> 参考文档：[区块对](http://deepoove.com/poi-tl/#_%E5%8C%BA%E5%9D%97%E5%AF%B9)
您好，我遇到类似问题：
1.title
  content
  url
2.title
  url
3.title
  content
  url

如果我第二个没有content，会显示null，如何不渲染这个null呢

**Comment by zhongyong168** [comment]
> 1.7.2 版本完全支持这种写法，不需要自定义策略。
> 
> 参考文档：[区块对](http://deepoove.com/poi-tl/#_%E5%8C%BA%E5%9D%97%E5%AF%B9)

您好，我遇到类似问题：
1.title
content
url
2.title
url
3.title
content
url

如果我第二个没有content，会显示null，如何不渲染这个null呢

**Comment by Sayi** [comment]
@zhongyong168 Hi，会显示null是什么意思？应该不会显示任何文本。
