### ISSUE TITLE
模板合并

### ISSUE THREAD

**Issue by bjxiaoaimin** [Sayi/poi-tl#353]
不想在主模板配{{+var}}，能直接把子模板直接合并到主模板并从第二页开始合并吗。

**Comment by Sayi** [comment]
你想要主模板中直接包含子模版的格式可以简单描述下？

**Comment by bjxiaoaimin** [comment]
子模板就是{{var}}纯文本

**Comment by bjxiaoaimin** [comment]
子模板就是{{var}}纯文本，只是想把子模板直接从主模板第二页进行合并，不想在主模板配置{{+var}}这种语法




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"卅一"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月27日(星期四) 晚上6:41
收件人:&nbsp;"Sayi/poi-tl"<poi-tl@noreply.github.com&gt;;
抄送:&nbsp;"一切从头开始"<7502415@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Sayi/poi-tl] 模板合并 (#353)




你想要主模板中直接包含子模版的格式可以简单描述下？

**Comment by Sayi** [comment]
可以试试V1.7.1
