### ISSUE TITLE
把预留行的样式复制到新增的行是个可行的思路。

### ISSUE THREAD

**Issue by yangbnh** [Sayi/poi-tl#355]
把预留行的样式复制到新增的行是个可行的思路。

我的操作是这样
1.XWPFTableRow row0 = table.getRow(0);  // 取预留行
2.table.addRow(row0);  //添加到新行
3.XWPFTableRow newRow = table.getRow(startRow); // 取出新添加行
4.循环newRow的每个cell 
5.cell.setText("xx");来设置值
问题是
1.新行的数据仍然存在,通过哪个api删除或者替换?
2.新setText的数据的样式仍然没有和原数据样式一致,怎么取的预留行的样式style?

感谢不吝赐教.

_Originally posted by @Sayi in https://github.com/Sayi/poi-tl/issues/333#issuecomment-566345656_

**Comment by Sayi** [comment]
参考下表格行循环插件： [HackLoopTableRenderPolicy](http://deepoove.com/poi-tl/#hack-loop-table)
 
如果不满足，可以参考下这个插件的实现，它实现了行复制和循环。
