### ISSUE TITLE
感谢分享，感觉整个项目对预留信息的循环支持有点弱

### ISSUE THREAD

**Issue by ww269099591** [Sayi/poi-tl#357]
这两天在看这个项目，自己动手写了一下，基本上功能都能满足，但是表格里有预留信息，添加一行就复制一遍，这功能感觉能做，但是又会比较繁琐；一段预留的文字，填充里面的数据，带着序号循环，也感觉比较难实现。可能是我想少了。

**Comment by Sayi** [comment]
Hi, @ww269099591 

基本上在分支dev-1.7.0都已经实现了(针对"表格行循环"写了个`HackLoopTableRenderPolicy`插件，“序号循环”也顺便完成了)，还未发布而已，有兴趣可以看看这个分支里面的`com.deepoove.poi.tl.example.SwaggerToWordExample`的示例，可以用很简单的代码将Swagger转化为Word文档。

**Comment by Sayi** [comment]
v1.7.2 已发布
