### ISSUE TITLE
区块标签{{?list}}{{/list}}使用问题

### ISSUE THREAD

**Issue by jialanzhidong** [Sayi/poi-tl#358]
我尝试利用{{?list}}{{/list}}循环输出文本，但问题是在区块中无法引用item本身，只能引用item的属性，请问有更好的办法吗？

**Comment by Sayi** [comment]
Hi, @jialanzhidong 

很巧，昨晚发布了1.7.2版本，今天更新了文档。使用#this，如果是文本就是{{=#this}}

参考文档：[区块对](http://deepoove.com/poi-tl/#_%E5%8C%BA%E5%9D%97%E5%AF%B9)

参考示例：[Swagger文档](http://deepoove.com/poi-tl/#example-swagger)
