### ISSUE TITLE
生成的docx文件,office打开是正常,wps打开,里头的表格会挤在一边,不会自适应宽度

### ISSUE THREAD

**Issue by hznwind** [Sayi/poi-tl#36]
生成的docx文件,office打开是正常,wps打开,里头的表格会挤在一边,不会自适应宽度,请问下是不是不兼容wps的？

**Comment by Sayi** [comment]
没有在wps测试过，但是这个问题应该和 #24 是一个问题。
office支持自适应属性，pages和wps好像不支持这个属性，我会再看看。

**Comment by hznwind** [comment]
你好，我测试了下，自适应宽度这个确实有问题，自定义宽度可以用，不过，源码包可以用，maven库最新版本是1.2.0 这个自定义宽度也不能用，能否麻烦您更新下maven的库包呢 ，或者开个snoashop版本也可以，谢谢哈

**Comment by Sayi** [comment]
好，周末更新

**Comment by Sayi** [comment]
1.3.0 版本已支持。
