### ISSUE TITLE
模板生成模板【嵌套模板】。利用新生成的模板渲染新的数据，生成的新模板有10个嵌套标签，在渲染数据的时候为什么只渲染了第一个嵌套标签，其他标签没数据

### ISSUE THREAD

**Issue by Yeeeeez** [Sayi/poi-tl#364]
// 模板生成模板方法
public static void template() throws IOException{
        // 创建模板
        XWPFTemplate template = XWPFTemplate.compile("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\template.docx");
        // map 数据结构
        Map<String,Object> map = new HashMap<>();

        StringBuffer stringBuffer = new StringBuffer();
        stringBuffer.append("{{+template_00}}\n");
        stringBuffer.append("{{+template_01}}\n");
        stringBuffer.append("{{+template_02}}\n");
        stringBuffer.append("{{+template_03}}\n");
        stringBuffer.append("{{+template_04}}\n");
        stringBuffer.append("{{+template_05}}\n");
        stringBuffer.append("{{+template_06}}\n");
        stringBuffer.append("{{+template_07}}\n");
        stringBuffer.append("{{+template_09}}\n");
        stringBuffer.append("{{+template_08}}\n");

//        java.lang.String value = new java.lang.String(stringBuffer.toString().getBytes(),"UTF-8");

        map.put("template", stringBuffer.toString());
        template.render(map);
        FileOutputStream outputStream = new FileOutputStream("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\temp_template.docx");
        template.write(outputStream);
        outputStream.flush();
        outputStream.close();
        template.close();
    }

   // 渲染新模板方法
    public static void generate() throws IOException {
        // 创建模板
        XWPFTemplate template = XWPFTemplate.compile("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\temp_template.docx");
        // map 数据结构
        Map<String,Object> map = new HashMap<>();

        DataRendey dataRendey = new DataRendey();
        // 两个占位符不能在同一行内
        map.put("template_00", new DocxRenderData(new File("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\template_00.docx"), Arrays.asList(dataRendey.template_00())));
        map.put("template_01", new DocxRenderData(new File("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\template_01.docx"), Arrays.asList(dataRendey.template_01())));
        map.put("template_02", new DocxRenderData(new File("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\template_02.docx"), Arrays.asList(dataRendey.template_02())));
        map.put("template_03", new DocxRenderData(new File("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\template_03.docx"), Arrays.asList(dataRendey.template_03())));
        map.put("template_04", new DocxRenderData(new File("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\template_04.docx"), Arrays.asList(dataRendey.template_04())));
        map.put("template_05", new DocxRenderData(new File("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\template_05.docx"), Arrays.asList(dataRendey.template_05())));
        map.put("template_06", new DocxRenderData(new File("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\template_06.docx"), Arrays.asList(dataRendey.template_06())));
        map.put("template_07", new DocxRenderData(new File("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\template_07.docx"), Arrays.asList(dataRendey.template_07())));
        map.put("template_09", new DocxRenderData(new File("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\template_09.docx"), Arrays.asList(dataRendey.template_09())));
        map.put("template_08", new DocxRenderData(new File("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\template_08.docx"), Arrays.asList(dataRendey.template_08())));

        template.render(map);
        FileOutputStream outputStream = new FileOutputStream("C:\\Users\\Admin\\Desktop\\产品标准模板生成\\poi-tl\\template\\out.docx");
        template.write(outputStream);
        outputStream.flush();
        outputStream.close();
        template.close();
    }

    public static void main(String[] args) throws IOException{
        template();
        generate();
    }

**Comment by xhyan0427** [comment]
兄弟，你解决该问题了么，我也碰到同样的问题了，多个嵌套标签只渲染了第一个标签，其他的没有数据，求救！！！

**Comment by Sayi** [comment]
不要使用\n的方式，使用区块对。
