### ISSUE TITLE
在区域块加入图片后去区域块内文字样式出现了丢失

### ISSUE THREAD

**Issue by GuoSakura** [Sayi/poi-tl#365]
{{?manuscripts}}
{{territory}}
{{?prefacetechs}}
{{title}}
{{progress}}
{{background}}
{{meaning}}
{{?images}}
{{@image}}
{{/images}}
{{/prefacetechs}}
{{/manuscripts}}

如果没有图片是没问题的加入图片后文字模版的样式没有了

**Comment by Sayi** [comment]
@GuoSakura Hi，可以给个单元测试来重现这个问题吗

**Comment by GuoSakura** [comment]
> @GuoSakura嗨，可以给个单元测试来重现这个问题吗
已经找到问题了。是自己的模版问题。麻烦问一下如果给文字加下角标上角标有解决方案吗

**Comment by Sayi** [comment]
@GuoSakura 上下角标写个小插件很简单的。

**Comment by GuoSakura** [comment]
> @GuoSakura 上下角标写个小插件很简单的。

求大神给个demo

**Comment by Sayi** [comment]
现在没空。。。靠自己哦。。。

**Comment by GuoSakura** [comment]
> 现在没空。。。靠自己哦。。。

好的谢谢大神。希望大神有时间了给个思路
