### ISSUE TITLE
1.5.1版本，复用模板文件后，如果没有给标签赋值，会出现换行

### ISSUE THREAD

**Issue by SallyRex** [Sayi/poi-tl#366]
因为项目中已经大量用了poi3.17，所以没法升级，只有用1.5的版本，我看1.5版本里面想实现类似freemarker那种循环生成的功能，只有引用模板文件这种方法，但是循环里面的内容又不尽相同，所以写了四个模板文件，已经是做了一定的复用了。比如一个模板文件中有title，content，+outerTemplate，有的只需要title，outerTemplate，有的只需要title，content，但是这样造成的后果就是由于没有给其中一个字段赋值，所以两个模板生成的内容之间有大量空行。我看了作者之间给别人的回复，说模仿table写个afterRender，但是我下载源代码下来，直接手动给DocxPolicy那个类加上after方法，结果直接报错。
我有看到作者在1.7里面更新了一个区块对的功能，这应该是类似于循环控制显示的效果，请问可以把这个功能同步到1.5吗。。。

**Comment by Sayi** [comment]
只有文本或者图片才会产生空行吧，把文本和图片的空行去掉应该就行了。


木有精力迁移到1.5里面去呀~~~~

**Comment by Sayi** [comment]
过期关闭。
