### ISSUE TITLE
空值替换的问题

### ISSUE THREAD

**Issue by mianbaoking** [Sayi/poi-tl#367]
默认情况下标签值为null的话，生成的文档替换后是空的，有没有全局设置能让其他值（例如NA还或者/）来替换这种空的情况

**Comment by Sayi** [comment]
```java
ConfigureBuilder.setValidErrorHandler(ValidErrorHandler)
```

**Comment by mianbaoking** [comment]
OK 发自我的华为手机-------- 原始邮件 --------发件人： 卅一 <notifications@github.com>日期： 2020年4月22日周三 21:09收件人： Sayi/poi-tl <poi-tl@noreply.github.com>抄送： mianbaoking <mianbaoking@sina.com>, Author <author@noreply.github.com>主    题： Re: [Sayi/poi-tl] 空值替换的问题 (#367)
ConfigureBuilder.setValidErrorHandler(ValidErrorHandler)
