### ISSUE TITLE
关于使用SpringEL解析模式对Map参数访问的建议

### ISSUE THREAD

**Issue by yuehuanghun** [Sayi/poi-tl#369]
在SPEL_MODE 的场景下，使用Map作为参数时，表示式${aa}或${aa.bb}渲染异常
EL1008E: Property or field 'xxx' cannot be found on object of type 'java.util.HashMap'
只能使用${[aa]} ${[aa][bb]}这种表示式，相当别扭。
经过查看在类SpELRenderDataCompute中StandardEvaluationContext这个类，默认的PropertyAccessor只有一个，为ReflectivePropertyAccessor。
为了增加对Map对象参数按${aa}这种模式读取，可能通过context.addPropertyAccessor(PropertyAccessor accessor); 追加属性访问器。
org.springframework.context.expression.MapAccessor这个类就是所需要的类
     
     public class SpELRenderDataCompute implements RenderDataCompute {

    ExpressionParser parser;
    EvaluationContext context;

    public SpELRenderDataCompute(Object root) {
        parser = new SpelExpressionParser();
        StandardEvaluationContext context = new StandardEvaluationContext(root);
        context.addPropertyAccessor(new MapAccessor());    
        this.context = context;
    }

    @Override
    public Object compute(String el) {
        // mark: 无法计算或者读取表达式，会直接抛异常
        return parser.parseExpression(el).getValue(context);
    }

    }

我看了历史类似的issue，都没有正式解决这个问题，建议作者采纳。
另外，本想通过配置的方式使用自定义的SpELRenderDataCompute，发现未开放配置，只好写相同类覆盖了，也建议作者开放如RenderDataComputeFactory等的配置功能，以便重写重设。

**Comment by Sayi** [comment]
自己实现下RenderDataComputeFactory，通过这个配置应该能达到你想要的：
```java
ConfigureBuilder.setRenderDataComputeFactory(RenderDataComputeFactory)
```

**Comment by Sayi** [comment]
MapAccessor在Spring-context模块下，poi-tl提供了一个移植版本不需要依赖此包：ReadMapAccessor，这个建议随着下一个版本发布。
