### ISSUE TITLE
问题，集成到spring boot框架内使用，魔板读取到和单元测试不一样

### ISSUE THREAD

**Issue by feifeifeiname** [Sayi/poi-tl#37]
无法进行数据载入

**Comment by feifeifeiname** [comment]
Resource resource = new ClassPathResource("PB.docx");
        XWPFTemplate template = XWPFTemplate.compile(resource.getFile());
        template.registerPolicy("website", new ListDataRenderPolicy());

        template.render(datas);//这一句出的错，Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.poi.xwpf.usermodel.XWPFRun.isStrikeThrough()Z

**Comment by Sayi** [comment]
你看下是不是poi包冲突了，导致引入了低版本的poi<3.16，默认引用的是3.16
```
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml</artifactId>
    <version>3.16</version>
</dependency>
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi</artifactId>
    <version>3.16</version>
</dependency>
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml-schemas</artifactId>
    <version>3.16</version>
</dependency>
```

**Comment by feifeifeiname** [comment]
恩，成功了谢啦
