### ISSUE TITLE
能否插入图表？

### ISSUE THREAD

**Issue by BigBroB** [Sayi/poi-tl#373]
目前看教程是没有插入图表功能的，如果使用 自定义插件，插入图表功能是否可以成功？

**Comment by Sayi** [comment]
你可以试试~~

**Comment by BigBroB** [comment]
https://www.jianshu.com/p/6a60b98effb9 我实现了一个版本，希望你看看

**Comment by Sayi** [comment]
Hi，很棒，把文末的问题优化下就能成为标准的折线图解决方案了。

**Comment by BigBroB** [comment]
标题现在已经可以了，但是图线颜色这些没办法，图表的线可能变化，所以模板的话也是有局限性的，不像表格样式都是一样的

**Comment by vega0707** [comment]
> 目前看教程是没有插入图表功能的，如果使用 自定义插件，插入图表功能是否可以成功？

我之前改过利用poi做过改颜色的功能,回头可以看看能不能加入到这个项目中

**Comment by Sayi** [comment]
1.8.0版本将支持图表功能。
