### ISSUE TITLE
怎么从模板中抓取参数

### ISSUE THREAD

**Issue by zt1820057934** [Sayi/poi-tl#376]
你好， 如果定义好若干个模板后， 例如合同文件， 当呈现给用户填写参数的时候， 需要扫描出合同上参数及格式的JSON 供前端处理并呈现给用户填写（  单个、列表、嵌套、对象元素  ），我我找寻了好几个出名的word处理工具， 好像都没有这个功能， POI-ti中有吗？  或者大牛告诉我下思路 (我自己弄了个字符扫描的，感觉很烂)。
<img width="744" alt="截屏2020-04-29下午2 58 22" src="https://user-images.githubusercontent.com/31762662/80568583-e1836b80-8a29-11ea-94b1-3c5228ca4756.png">

**Comment by zt1820057934** [comment]
看到了compile.getElementTemplates()方法来获取标签， 有两个小问题， 动态表格中[name],[age]对象属性获取不到，还有就是只有标签名的话，  还是需要自己来实现根据不同标签转不同数据结构的json吧？ 😂

**Comment by Sayi** [comment]
是你说的这样，可以参考源码实现你的转json效果

**Comment by zt1820057934** [comment]
好的
