### ISSUE TITLE
请问1.6分支支持“Loop表格行“操作吗?

### ISSUE THREAD

**Issue by qiweiview** [Sayi/poi-tl#377]
”Loop表格行“非常适合我们业务环节的需求，但无奈生产环境使用的是jdk1.7,我阅读了1.6分支版本的文档，没有找到这个功能的说明，我能否通过什么办法在1.6版本上实现这个功能

**Comment by Sayi** [comment]
1.6 不支持哎。可以参考1.7的方式实现下，但是会比较麻烦，1.7优化了不少代码。

**Comment by qiweiview** [comment]
> 1.6 不支持哎。可以参考1.7的方式实现下，但是会比较麻烦，1.7优化了不少代码。

非常感谢您的回复，已通过参照master版本，“不是很漂亮”地在1.6分支上实现了😅

**Comment by Sayi** [comment]
@qiweiview NB
