### ISSUE TITLE
请问大佬，页眉后续能否出一个支持文本框的填充方式？

### ISSUE THREAD

**Issue by qqizai** [Sayi/poi-tl#379]
页眉后续能否出一个支持文本框的填充方式？比如:报告中，全部的页眉添加 订单编号，想使用这种 {{order_num}} 方式来填充数据，请问是否考虑增加这个功能？

如果不行，请问有什么替代方案，提供选择的？

谢谢您

**Comment by Sayi** [comment]
用表格布局

**Comment by qqizai** [comment]
噢好的谢谢

**Comment by Sayi** [comment]
最新版本1.8.0已支持文本框。
