### ISSUE TITLE
接口根据模版生成word文档很慢，有什么解决方案么

### ISSUE THREAD

**Issue by javadoge** [Sayi/poi-tl#384]
如题，大家怎么处理的？

我这边根据模版渲染一个文档，十多页，光渲染花的时间要好多秒

**Comment by Sayi** [comment]
Hi, 要明确哪里慢是关键。是准备数据慢(比如有IO操作获取数据)？还是模板标签太多渲染慢？哪些模板标签是慢的诱因...

**Comment by Danst-bjtu** [comment]
你好，我目前也遇到模板生成word文档很慢的问题，基本都是表格，然后表格用的还是嵌套标签，每种表格里面有很多属性，渲染数据的时候就很慢了，请问你是怎么解决的呢？

**Comment by Danst-bjtu** [comment]
我发现日志里面包含大量此类型日志，因为我主要是使用表格模板，然后表格里面有一部分字符串属性是空值
11:48:09.878 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [identification]
11:48:09.878 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [Start]:The run position of [identification] is 0, Offset in run is 0
11:48:09.878 [main] DEBUG com.deepoove.poi.resolver.RunningRunBody - [End]:The run position of [identification] is 0, Offset in run is 15
11:48:09.878 [main] DEBUG com.deepoove.poi.resolver.TemplateResolver - Resolve where text: [identification], and create RunTemplate for XWPFRun
11:48:09.878 [main] DEBUG com.deepoove.poi.expression.ReadMethodFinder - Fail introspector the property: identification from class com.poi.springbootpoi.model.ReferenceEntry, Method not found: isIdentification
11:48:09.878 [main] INFO com.deepoove.poi.render.processor.DelegatePolicy - Start render Template [identification], Sign: , policy:TextRenderPolicy
