### ISSUE TITLE
MiniTableRenderData数据表格如何适配Word模板表格宽度

### ISSUE THREAD

**Issue by chestnut-c** [Sayi/poi-tl#385]
代码MiniTableRenderData 生成的表格宽度如何去适配word模板里面表格的宽度呢，防止超出模板宽度。目前有好的解决方法吗？还是先读取word模板的宽度再去设置MiniTableRenderData的表格宽度呢？

**Comment by Sayi** [comment]
模板中表格宽度直接在模板中能看到，然后设置即可。

**Comment by chestnut-c** [comment]
一套代码，但是模板是动态的。所以需求动态传入设置宽度

**Comment by Sayi** [comment]
那可能要计算模板宽度，然后根据计算结果计算表格的宽度。
