### ISSUE TITLE
当文档内容有层级关系时无法正常工作

### ISSUE THREAD

**Issue by zt1820057934** [Sayi/poi-tl#386]
<img width="909" alt="截屏2020-05-25 下午3 11 29" src="https://user-images.githubusercontent.com/31762662/82788388-f3c2bf00-9e9a-11ea-874f-f35744c95782.png">
如图， 如果想在插入的文本框中使用参数填充功能无效，只能得到avatar这一个参数
文档地址(如果需要的话 https://self-file-server.oss-cn-shanghai.aliyuncs.com/disk/template.docx)

**Comment by Sayi** [comment]
Hi，表格布局更专业哦  http://deepoove.com/poi-tl/#_%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by zt1820057934** [comment]
![Uploading 截屏2020-05-27 上午10.31.28.png…]()
大神是指这个意思吗？  谢了😂

**Comment by zt1820057934** [comment]
<img width="983" alt="截屏2020-05-27 上午10 31 28" src="https://user-images.githubusercontent.com/31762662/82971558-9008d500-a005-11ea-96d7-4f4d49dc8e55.png">
大神是指这个意思吗？ 谢了😂

**Comment by Sayi** [comment]
祝你成功~
