### ISSUE TITLE
PictureRenderData  bug

### ISSUE THREAD

**Issue by javadoge** [Sayi/poi-tl#387]
PictureRenderData  对象  format 参数，不管传 jpg还是png，渲染后word得图片格式总是png

（测试渲染后word中图片右键另存为  是 png，而我手动存放一张jpg图片，右键另存为 是 jpg）

**Comment by javadoge** [comment]
另一个问题，在用 new PictureRenderData 的时候，怎么能使用 图片本身的大小呢，参数是固定大小

**Comment by Sayi** [comment]
Hi, @javadoge 
先说第二个问题，可以预先通过BufferedImage读取图片的宽高。

**Comment by javadoge** [comment]
谢谢，第一个问题麻烦有时间的话看一下哈，现在生成文档图片很多，都把jpg原图转成了png，导致文档很大

**Comment by Sayi** [comment]
@javadoge 另存为图片不是可以选择图片格式的吗，我好像没理解你说的意思？

![image](https://user-images.githubusercontent.com/1394854/83553165-6a1b8d00-a53d-11ea-9cc3-67767659f1ab.png)

**Comment by javadoge** [comment]
是的，我的意思是  word在生成时候 把网络图片 jpg格式的 转换为了png，png格式图片太大，导致word文档太大。

相关代码：

BufferedImage urlBufferedImage = BytePictureUtils.getUrlBufferedImage(urlImg);
attach.setPicture(new PictureRenderData(100, 100, PictureType.JPEG.extension, urlBufferedImage));

这里已经设置了 PictureType.JPEG.extension ，而且原图 urlImg也是jpg格式

不知道为什么 渲染后word里面 图片  变为了 png得，导致word太大

**Comment by javadoge** [comment]
而且  网络图片源文件很小得，word生成后得png格式的图片另存为后，查看png得文件比较大

**Comment by Sayi** [comment]
@javadoge master我已经修复了下个版本发布，你可以参考下修复方式，使用PictureRenderData这个构造函数试试：

```java
com.deepoove.poi.data.PictureRenderData.PictureRenderData(int, int, String, byte[])
```

另外，你从网络获取图片要注意下网络耗时带来的性能影响。

**Comment by javadoge** [comment]
感谢大神

**Comment by Syy-hue** [comment]
我想请问 如何才能导入多张图片到word文档呢?
