### ISSUE TITLE
高级使用问题执行方法或SQL

### ISSUE THREAD

**Issue by zJiaJun** [Sayi/poi-tl#388]
期望配置如下占位符
SQL: {{sql('select count(1) from table')}}
后端能够执行具体的SQL
或者使用el表达式调用具体的bean方法
请问有什么办法？这样个人觉得灵活度很高

**Comment by zJiaJun** [comment]
`public class SpELRenderDataCompute implements RenderDataCompute {

    public ExpressionParser parser;
    public EvaluationContext context;

    public SpELRenderDataCompute(Object root) {
        parser = new SpelExpressionParser();
        context = new StandardEvaluationContext(root);
    }

    @Override
    public Object compute(String el) {
        // mark: 无法计算或者读取表达式，会直接抛异常
        return parser.parseExpression(el).getValue(context);
    }

}`
可以将context权限开放处理，通过Configure build构造的模式让用户自定义设置
讨论下

**Comment by Sayi** [comment]
Hi, @zJiaJun awesome!!!

想法很强大，不过SQL暴露出去可能会带来安全问题。

**Comment by zJiaJun** [comment]
> Hi, @zJiaJun awesome!!!
> 
> 想法很强大，不过SQL暴露出去可能会带来安全问题。

安全问题因使用人群不同而不同，模版占位符书写只能由开发人员维护。
也有合适的场景。目前在不修改源码的情况下，做法是实现自定义的CustomSpELRenderDataCompute，通过setBeanResolver，可以实现调用任何bean的方法。
```java
Configure config = Configure.newBuilder().setElMode(Configure.ELMode.SPEL_MODE)
                .setRenderDataComputeFactory(new RenderDataComputeFactory() {
            @Override
            public RenderDataCompute newCompute(Object model) {
                return new CustomSpELRenderDataCompute(model);
            }
        }).build();
```
```java
 private final Wrapper model;

    public CustomSpELRenderDataCompute(Object root) {
        this.model = (Wrapper) root;
        parser = new SpelExpressionParser();
        context = new StandardEvaluationContext(root);
        try {
            context.setVariable("sql", SqlUtils.class.getDeclaredMethod("sql", String.class));
            ApplicationContext applicationContext = model.getApplicationContext();
            ((StandardEvaluationContext) context).setBeanResolver(new BeanFactoryResolver(applicationContext));
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        }
    }
```

**Comment by Sayi** [comment]
`RenderDataComputeFactory` 暴露出来就是给开发人员扩展的，给你点个赞！

**Comment by Sayi** [comment]
#389
