### ISSUE TITLE
我想通过docx生成模板，再用模板生成docx

### ISSUE THREAD

**Issue by ljtletters** [Sayi/poi-tl#39]
我的问题是，通过docx生成模板的时候，会遇到相同的文本会被替换成最后一个的值，有办法避免吗？

**Comment by ljtletters** [comment]
我想到了一个办法： 
1. 允许自定义替换符，可以设置为空，既{{title}}换成title。
2.匹配的时候从前向后匹配，一旦匹配到既从map中移除，并返回，这样就可以一对一生成模板了

**Comment by Sayi** [comment]
没有很理解你的问题，你是打算如何生成模板？会遇到相同的文本会被替换成最后一个的值？

**Comment by ljtletters** [comment]
是的，我想从已有的文档生成模板。

**Comment by Sayi** [comment]
那么打算如何从已有文档生成模板？

**Comment by ljtletters** [comment]
比如我上传一个doc，那么我希望把所有的文字替换成{{Title}}的标识符，可以用hash计算个串。

**Comment by Sayi** [comment]
抱歉 没听明白。。

**Comment by ljtletters** [comment]
我们的项目做的不是从模板生成文档吗，我想反着用。

**Comment by Sayi** [comment]
你可以fork一个分支  亲手改造一下~~

**Comment by ljtletters** [comment]
好的，我试试，如果成功了，我会提交的，谢谢。

**Comment by Sayi** [comment]
#111

**Comment by xuanlv886** [comment]
是标识符处于模板文档中可循环部分的问题吧？我也碰到了，目前有两个解决方案：①如模板文档中循环部分可以提取出来且提取出来后可以进行文档合并，那就把模板文档中循环部分拿出来当成子模板。具体参考{{+var}}标签。（如子模板中包含**图表**，注意是**图表**、Chart，那合并会成功，但打开时word文档会提示损坏，无法查看）②在生成模板文档时，给循环里的标识符附加个变量，如变成{{title1}}、{{title2}} 。我采用的是第二种，因为我的子模板中包含图表····
