### ISSUE TITLE
如何删除空白页？

### ISSUE THREAD

**Issue by GoodBoy123** [Sayi/poi-tl#390]
word表格下的换行符很容易到下一页，导致生成的word有空白页，是否有什么好的解决方式？
![image](https://user-images.githubusercontent.com/31762432/84097019-f3e3c280-aa35-11ea-8874-61500afe93d3.png)

**Comment by Sayi** [comment]
模板中会有换行符这一行吗？删掉？

**Comment by GoodBoy123** [comment]
是的 模板中就有的 但是模板有点多 不知道是否可以直接代码判断删除的

**Comment by Sayi** [comment]
空白页是最后一页吗？

**Comment by GoodBoy123** [comment]
这个不确定的，也可能是在文档的中间几处，所以想问问是否有通用的方式可以解决这样的问题

**Comment by Sayi** [comment]
貌似没有。
