### ISSUE TITLE
poi-tl有什么方式支持树状数据吗？

### ISSUE THREAD

**Issue by waitting49** [Sayi/poi-tl#392]
数据是树，如何一级级的向下渲染，之前想过模板合并，但是那样合并太频繁了，有什么更好的方式吗？

**Comment by Sayi** [comment]
区块对可以做到吗？

**Comment by waitting49** [comment]
> 区块链对可以做到吗？

区块对？如果是确定层级的树区块对应该可以做到，如果树向下的层级不确定，区块应该做不到吧，区块对应该支持循环不支持递归吧？

**Comment by Sayi** [comment]
嗯，可以自定义个插件。

**Comment by waitting49** [comment]
刚刚试过区块对，固定层级的树很方便就能实现
例如：
`{{uuid}}
{{name}}
{{?children}}
{{uuid}}
{{name}}
{{?children}}
{{uuid}}
{{name}}
{{?children}}
{{uuid}}
{{name}}
{{/children}}
{{/children}}
{{/children}}`
不定层级的树，我觉得应该可以通过模板生成模板去替换出下面最深层级，再通过区块对替换实现，应该会比模板嵌套的合并方式好一点

**Comment by Sayi** [comment]
我觉得还是自定义个插件简单。。。。。插件代码很容易写的。

**Comment by waitting49** [comment]
代码里面控制样式不是很灵活，标题栏前n层的样式不一样且不确定，n层深度以后样式才固定一样

**Comment by CHEL24483** [comment]
> 我觉得还是自定义个插件简单。。。。。插件代码很容易写的。

问一下最终实现了吗，能给参考一下吗？

**Comment by HongweiLee233** [comment]
我有一个想法，就是直接把树打平。
比如我现在想打印出一下内容，如下
`
# 标题1.1
## 标题2.1
这是一条内容
## 标题2.2
### 标题3.1
这是一条内容
### 标题3.2
这是一条内容
# 标题1.2
我是一只猫
`
我直接全部打平
数据是
```
  HashMap<String, Object> father = new HashMap<>();
        List<HashMap<String,Object>> children = Lists.newArrayList(
                new HashMap<String,Object>(){{
                    put("title1","标题1.1");
                }},
                new HashMap<String,Object>(){{
                    put("title2","标题2.1");
                    put("content","这是一条内容");
                }},
                new HashMap<String,Object>(){{
                    put("title2","标题2.2");
                }},
                new HashMap<String,Object>(){{
                    put("title3","标题3.1");
                    put("content","这是一条内容");
                }},
                new HashMap<String,Object>(){{
                    put("title3","标题3.2");
                    put("content","这是一条内容");
                }},
                new HashMap<String,Object>(){{
                    put("title1","标题1.2");
                    put("content","这是一条内容");
                }}
        );
        father.put("father",children);
```
模板是这样：
![image](https://user-images.githubusercontent.com/52847847/186841101-69f1a2fa-680c-46b7-a6a9-3f44a445f438.png)

结果：
![image](https://user-images.githubusercontent.com/52847847/186841013-75432478-7981-4fd2-9be9-219c8db1c9e0.png)
