### ISSUE TITLE
表格跨页单元格上下居中

### ISSUE THREAD

**Issue by kingalwaysbelonly** [Sayi/poi-tl#397]
自定义表格生成后，进行合并行单元格上下对齐，但是表格生成比较大产生分页之后，后面的上下对齐都没实现，只有第一页实现了，有没有解决办法

**Comment by kingalwaysbelonly** [comment]
![image](https://user-images.githubusercontent.com/36280752/85241726-62ca0e00-b46f-11ea-8dc7-378a702c5917.png)

**Comment by kingalwaysbelonly** [comment]
上下对齐我是这样写的
![image](https://user-images.githubusercontent.com/36280752/85241773-8ab97180-b46f-11ea-98ed-4a6285aa7562.png)

**Comment by Sayi** [comment]
给个单元测试
