### ISSUE TITLE
不定长行列实现可行方案参考

### ISSUE THREAD

**Issue by waitting49** [Sayi/poi-tl#398]
原因：
        业务需要，表格的列是可拓展的，表格样式简单一致时不想在代码层面控制样式（方便运维调整样式）
方案：
         poi-tl本身提供了HackLoopTableRenderPolicy策略实现了行的自定义拓展，因此行拓展参考HackLoopTableRenderPolicy可以实现，列的拓展可以调用poi的接口复制第一列单元格样式，表格样式由文档控制，类似HackLoopTableRenderPolicy，填充一个两行单列或者单行单列的样式模板
缺陷：
        由于列可拓展，因此数据没法用对象去映射，目前我实现方案使用List<List<?>>，采用数据提前处理好的方式
简单方案，仅供参考

**Comment by Sayi** [comment]
参见Loop column
