### ISSUE TITLE
模板标签循环遍历并合并成word文档

### ISSUE THREAD

**Issue by kingalwaysbelonly** [Sayi/poi-tl#401]
我想实现像这样的：
{{title}}
{{tag1}}{{tag2}}
其中每个模板标签都有各自的样式，最后遍历生成这样
{{title}}
{{tag1}}{{tag2}}
{{title}}
{{tag1}}{{tag2}}
{{title}}
{{tag1}}{{tag2}}
这样有什么建议吗

**Comment by Sayi** [comment]
区块对的循环不能满足吗？
