### ISSUE TITLE
插入图片的时候如果图片宽度超过word默认的编辑取余宽度的时候可否设置让其居中

### ISSUE THREAD

**Issue by zhaoyunqi888** [Sayi/poi-tl#402]
用{{@var}} 这种方式 插入图片的时候如果图片宽度超过word默认的编辑区域宽度的时候，超过的部分就都往右侧显示，能不能增加属性让其居中显示，如果超出，左右两边都往外延伸，并不只是只往右侧偏移。

**Comment by Sayi** [comment]
Hi，可以给个单元测试来表达下吗，光看文字我貌似没理解。

**Comment by zhaoyunqi888** [comment]
[https://tjc-download.weiyun.com/ftn_handler/96da973d8238e497d52617e775877af4703d452106b390adefee6f8becdf3a3715670f8301655d339a7424081259a2e112cbca49aa46db78e3c06fd3ef197b12/%E5%9B%BE%E7%89%871.png?fname=%E5%9B%BE%E7%89%871.png&from=30013&version=3.3.3.3](url)
这样的效果，如果能设置图片居中就好了

**Comment by zhaoyunqi888** [comment]
map.put("chart1", new PictureRenderData(600, 200, ".png", jfreeChartUtils.createBarChart(ds)));
然后生成的图片过宽，多余的部分都显示到右边，不美观。

**Comment by Sayi** [comment]
多余的图片只能显示到右边。。。
