### ISSUE TITLE
【word模板】嵌套word模板后，后再最后一页生成一个空白页，如何处理

### ISSUE THREAD

**Issue by onlylivi** [Sayi/poi-tl#404]
版本号：1.3.1
主word模板后面，由于需要根据对象的数量动态生成表格页，所以使用了模板嵌套。功能正常，但是会在最后一页生成一个空白页，请教一下如何处理

![image](https://user-images.githubusercontent.com/34052950/87760369-39b85580-c842-11ea-8d8e-25026e322c2a.png)

**Comment by Sayi** [comment]
最后一个空页 是不是你哪里多了一个分页符导致的？

**Comment by Sayi** [comment]
关闭过期issue
