### ISSUE TITLE
word表格模板，一插入图片，表格线条就会消失

### ISSUE THREAD

**Issue by banyouu** [Sayi/poi-tl#405]
原图：
![image](https://user-images.githubusercontent.com/38764151/87858407-4206b280-c960-11ea-813e-1d7f999fbf7e.png)
插入图片后：
![image](https://user-images.githubusercontent.com/38764151/87858420-534fbf00-c960-11ea-97fe-dce5e27760aa.png)
不知道是不是我哪里写错了，请指点一下，谢谢

**Comment by Sayi** [comment]
@banyouu Hi，给个单元测试我来看看
