### ISSUE TITLE
柱状图 如何使用单系列图标来渲染

### ISSUE THREAD

**Issue by zhaoyunqi888** [Sayi/poi-tl#406]
柱状图 如何使用单系列图表来渲染
把柱状图的系列只选一个，但是还是报错
错误信息：
Caused by: java.lang.ClassCastException: com.deepoove.poi.data.ChartSingleSeriesRenderData cannot be cast to com.deepoove.poi.data.ChartMultiSeriesRenderData

这个有没有解决方案

**Comment by Sayi** [comment]
@zhaoyunqi888 多系列里面的数组传一个元素就行了吧。

**Comment by zhaoyunqi888** [comment]
用这种方式生成后，需要点击图表，然后点击图表筛选器，然后数据才能刷过来，这是咋回事(用的wps)。
还有个问题 就是 如果插入图表的时候 类别默认有4个，但是业务需要生成5个，生成后 点击 图表筛选器 图表数据刷出来以后，只能显示4个类别，还有一个需要点击选择数据，然后重新勾选下，数据才能刷过来。

**Comment by zhaoyunqi888** [comment]
代码如下：
ChartMultiSeriesRenderData  chart1 = new ChartMultiSeriesRenderData ();
chart1.setChartTitle("");
chart1.setCategories(new String[] { "2016年", "2017年", "2018年", "2019年", "2020年" });
seriesRenderData.add(new SeriesRenderData("", new Integer[] { 500, 600, 700,800,900 }));
chart1.setSeriesDatas(seriesRenderData);
returnMap.put("chart1", chart1);

**Comment by Sayi** [comment]
#411
