### ISSUE TITLE
頁尾(腳)表格內標籤處理異常

### ISSUE THREAD

**Issue by miragehsiao** [Sayi/poi-tl#407]
[test.docx](https://github.com/Sayi/poi-tl/files/4951003/test.docx)
[error.log](https://github.com/Sayi/poi-tl/files/4951005/error.log)

頁尾(腳)表格內標籤處理異常
1. 出現 java.lang.IndexOutOfBoundsException
07/21 10:38:30.097 [DEBUG] ：
07/21 10:38:30.098 [DEBUG] {{經理人}}
07/21 10:38:30.098 [DEBUG] [Start]:段落内第1个run,标签为{{經理人}}, 在这个run内的边界位置为：3
07/21 10:38:30.098 [DEBUG] [End]:段落内第0个run,标签为{{經理人}}, 在这个run内的边界位置为：0
07/21 10:38:30.098 [ERROR] Unexpected server error
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1

2. 標籤置換異常
07/21 10:38:30.096 [DEBUG] ：
07/21 10:38:30.096 [DEBUG] {{
07/21 10:38:30.096 [DEBUG] 董事長
07/21 10:38:30.096 [DEBUG] }}
07/21 10:38:30.097 [DEBUG] [Start]:段落内第2个run,标签为{{董事長}}, 在这个run内的边界位置为：1
07/21 10:38:30.097 [DEBUG] [End]:段落内第0个run,标签为{{董事長}}, 在这个run内的边界位置为：0
07/21 10:38:30.097 [DEBUG] Resolve where text: {{董事長}}, and create ElementTemplate for class org.apache.poi.xwpf.usermodel.XWPFRun

![image](https://user-images.githubusercontent.com/9477414/88007474-a1231d80-cb40-11ea-9095-b38ffac52b5d.png)

**Comment by Sayi** [comment]
![image](https://user-images.githubusercontent.com/1394854/89606591-e9fa0680-d8a2-11ea-8fdd-fe40628cf174.png)

这应该是有个特殊的内容控件导致的。

**Comment by Sayi** [comment]
目前内容控件内部拥有标签将不会被解析。未来考虑支持控件内部标签。

**Comment by Sayi** [comment]
内容控件特性将在1.10.4和1.12.0版本中发布。
