### ISSUE TITLE
请问下，填好模板之后可以直接输出流吗？

### ISSUE THREAD

**Issue by LUOBOTOUJ** [Sayi/poi-tl#408]
请问下我现在有个需求是需要将docx模板生成后再转为pdf，由于我不需要存word，可否直接输出流
`try {
			//输出模板到本地
			OutputStream out = new FileOutputStream("E:\\output.docx");
			template.write(out);
			out.flush();
			
			//将docx转为pdf
			DocToPDFConverter converter = new DocToPDFConverter(parse(out), target, true, true);
			converter.convert();
			out.close();
			template.close();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} `

**Comment by LUOBOTOUJ** [comment]
可不可以不保存在本地

**Comment by Sayi** [comment]
可以，参见https://github.com/Sayi/poi-tl/blob/edbb7df0e7693a13b03bb26eacf620fb424f82eb/src/main/java/com/deepoove/poi/xwpf/NiceXWPFDocument.java#L272
