### ISSUE TITLE
请问新版word（2016之后）怎么设置图片引用？

### ISSUE THREAD

**Issue by wyfligamo** [Sayi/poi-tl#409]
您好，请问2016之后的word怎么设置图片引用？
现在是不是去掉了可选文字的标题？
![image](https://user-images.githubusercontent.com/15527815/88374428-54ec0d80-cdcc-11ea-8bc0-d979ed43ff30.png)

**Comment by chuxuyang** [comment]
我的2019的word ,引用标签写在这里不好使

**Comment by chuxuyang** [comment]
换了个wps2019可以了

**Comment by Sayi** [comment]
下个版本发布，支持2019版本的替换文字。
