### ISSUE TITLE
通过流导出 Word 后用 Office 打开报错

### ISSUE THREAD

**Issue by Xarrow** [Sayi/poi-tl#410]
1.  Office 2007 版本

2. 使用的文档中流的例子
```java
response.setContentType("application/octet-stream");
response.setHeader("Content-disposition","attachment;filename=\""+"out_template.docx"+"\"");

// HttpServletResponse response
OutputStream out = response.getOutputStream();
BufferedOutputStream bos = new BufferedOutputStream(out);
template.write(bos);
template.close();
out.flush();
out.close();
```

![微信图片_20200727212313](https://user-images.githubusercontent.com/4395604/88546791-76a8f700-d04f-11ea-8c45-5e905fe983e2.png)

**Comment by Xarrow** [comment]
文档中 http://deepoove.com/poi-tl/#_output%E8%BE%93%E5%87%BA  output输出例子中，流关闭错误，应该是`bos.flush()`,  ` bos.close()` , 按照例子中写法， bos 字符流没有关闭，导致生成的 word 打开提示格式不对。

**Comment by Sayi** [comment]
感谢 @Xarrow ，文档已修复。
