### ISSUE TITLE
使用多系列图表生成图标收数据默认不显示，需要点击图标的筛选才能把数据刷新过来

### ISSUE THREAD

**Issue by zhaoyunqi888** [Sayi/poi-tl#411]
用多系列图表生成单系列柱状图时：
用这种方式生成后，需要点击图表，然后点击图表筛选器，然后数据才能刷过来，这是咋回事(用的wps)。
还有个问题 就是 如果插入图表的时候 类别默认有4个，但是业务需要生成5个，生成后 点击 图表筛选器 图表数据刷出来以后，只能显示4个类别，还有一个需要点击选择数据，然后重新勾选下，数据才能刷过来。这种情况是自己插入图表发现的问题，如果运行您的例子，打开数据就能展示不需要点击图表筛选器，但是有个问题如果不小心点击图表筛选器了，数据就不对了，尤其是图例的数据。
插入图表：插入--图表--添加可选文字处标签 其他都是默认 没有做任何操作。

代码如下：
ChartMultiSeriesRenderData chart1 = new ChartMultiSeriesRenderData ();
chart1.setChartTitle("");
chart1.setCategories(new String[] { "2016年", "2017年", "2018年", "2019年", "2020年" });
seriesRenderData.add(new SeriesRenderData("", new Integer[] { 500, 600, 700,800,900 }));
chart1.setSeriesDatas(seriesRenderData);
returnMap.put("chart1", chart1);

**Comment by Sayi** [comment]
hi,给个可以重现的单元测试？

**Comment by zhaoyunqi888** [comment]
附件内容为代码和模板


| |
zhaoyunqi123
|
|
zhaoyunqi123@126.com
|
签名由网易邮箱大师定制
在2020年7月31日 00:28，卅一<notifications@github.com> 写道：

hi,给个可以重现的单元测试？

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
package com.test.buildDoc.service;

import com.deepoove.poi.XWPFTemplate;
import com.deepoove.poi.config.Configure;
import com.deepoove.poi.data.ChartMultiSeriesRenderData;
import com.deepoove.poi.data.SeriesRenderData;
import com.deepoove.poi.policy.reference.MultiSeriesChartTemplateRenderPolicy;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Service;
import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
@Scope
public class test {
    
    public static void main(String[] args) throws IOException {
    	ChartMultiSeriesRenderData  chart1 = new ChartMultiSeriesRenderData ();
		chart1.setChartTitle("");
		List<String>names=new ArrayList<>();
		List<Integer>values=new ArrayList<>();
		List<SeriesRenderData> seriesRenderData = new ArrayList<>();
		for (int i = 0; i < 5; i++) {
			names.add("2000"+i+"年");
			values.add(i*10);
		}
		chart1.setCategories(names.toArray(new String[names.size()]));
		seriesRenderData.add(new SeriesRenderData("", values.toArray(new Integer[values.size()])));
		chart1.setSeriesDatas(seriesRenderData);
		
		Configure configure = Configure.newBuilder().bind("chart", new MultiSeriesChartTemplateRenderPolicy()).build();

        Map<String, Object> datas = new HashMap<String, Object>() {
            {
                put("barchart", chart1);
            }
        };
        XWPFTemplate template = XWPFTemplate.compile("src/test/resources/test.docx", configure).render(datas);
        template.writeToFile("out_test.docx");
	}


}

**Comment by Sayi** [comment]
@zhaoyunqi888 没有收到你的附件。。。。

**Comment by zhaoyunqi888** [comment]
附件有重发了一遍 您在查收下
| |
zhaoyunqi123
|
|
zhaoyunqi123@126.com
|
签名由网易邮箱大师定制
在2020年7月31日 09:32，卅一<notifications@github.com> 写道：

@zhaoyunqi888 没有收到你的附件。。。。

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
package com.test.buildDoc.service;

import com.deepoove.poi.XWPFTemplate;
import com.deepoove.poi.config.Configure;
import com.deepoove.poi.data.ChartMultiSeriesRenderData;
import com.deepoove.poi.data.SeriesRenderData;
import com.deepoove.poi.policy.reference.MultiSeriesChartTemplateRenderPolicy;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Service;
import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
@Scope
public class test {
    
    public static void main(String[] args) throws IOException {
    	ChartMultiSeriesRenderData  chart1 = new ChartMultiSeriesRenderData ();
		chart1.setChartTitle("");
		List<String>names=new ArrayList<>();
		List<Integer>values=new ArrayList<>();
		List<SeriesRenderData> seriesRenderData = new ArrayList<>();
		for (int i = 0; i < 5; i++) {
			names.add("2000"+i+"年");
			values.add(i*10);
		}
		chart1.setCategories(names.toArray(new String[names.size()]));
		seriesRenderData.add(new SeriesRenderData("", values.toArray(new Integer[values.size()])));
		chart1.setSeriesDatas(seriesRenderData);
		
		Configure configure = Configure.newBuilder().bind("chart", new MultiSeriesChartTemplateRenderPolicy()).build();

        Map<String, Object> datas = new HashMap<String, Object>() {
            {
                put("barchart", chart1);
            }
        };
        XWPFTemplate template = XWPFTemplate.compile("src/test/resources/test.docx", configure).render(datas);
        template.writeToFile("out_test.docx");
	}


}

**Comment by Sayi** [comment]
@zhaoyunqi888 直接发我邮箱，回复收不到。sayi@163.com

**Comment by zhaoyunqi888** [comment]
sayi@163.com 这个邮箱地址发不出去 直接退回


我从光网上找到了sayi90@163.com 这个地址 给发过去了 不知道是不是您的邮箱
| |
zhaoyunqi123
|
|
zhaoyunqi123@126.com
|
签名由网易邮箱大师定制
在2020年7月31日 09:51，卅一<notifications@github.com> 写道：

@zhaoyunqi888 直接发我邮箱，回复收不到。sayi@163.com

**Comment by Sayi** [comment]
没理解代码的写法：
```java
Configure configure = Configure.newBuilder().bind("chart", new MultiSeriesChartTemplateRenderPolicy()).build();

        Map<String, Object> datas = new HashMap<String, Object>() {
            {
                put("barchart", chart1);
            }
        };
```
barchart 、chart和模板的标签都不符合，重现不了你的问题。。。。

**Comment by zhaoyunqi888** [comment]
手误 代码是：


Configure configure =Configure.newBuilder().bind("barchart", newMultiSeriesChartTemplateRenderPolicy()).build();
Map<String, Object> datas =newHashMap<String, Object>() {

            {

                put("barchart", chart1);

            }

        };


这样的
| |
zhaoyunqi123
|
|
zhaoyunqi123@126.com
|
签名由网易邮箱大师定制
在2020年8月7日 17:12，Sayi<notifications@github.com> 写道：

没理解代码的写法：

Configure configure =Configure.newBuilder().bind("chart", newMultiSeriesChartTemplateRenderPolicy()).build();



        Map<String, Object> datas =newHashMap<String, Object>() {

            {

                put("barchart", chart1);

            }

        };

barchart 、chart和模板的标签都不符合，重现不了你的问题。。。。

**Comment by Sayi** [comment]
嗯，我试了下，还是没有重现你的问题哎

**Comment by zhaoyunqi888** [comment]
神奇，难道我是因为我用的是wps的原因

**Comment by Irvinghua** [comment]
我WPS复现了一样的问题。每次只能在生成的文档上，点击图表的筛选器(或者点击编辑数据,啥都不编辑关掉Excel弹窗)，然后数据就自己刷新出来了

**Comment by kangninglee** [comment]
我也遇到了这个问题，在使用嵌套模板中使用图表，比如饼形图，它最后展现数据是模板中的数据，点击编辑数据，查看数据是我写入的数据，然后图表就刷新过来了，请问自动刷新数据有何方法解决？

**Comment by Sayi** [comment]
@kangninglee 一定哪里有问题！尝试定位下？

**Comment by kangninglee** [comment]
是不是office版本问题呢，我用的是office2013

**Comment by zhangchaoxu** [comment]
@Sayi 我也遇到的相同的问题，在主模板中的图表能渲染出数据来，但是嵌套进来的子模板中的图表，需要右键重新勾选数据源后才会刷新数据。

版本：1.12.1
生成代码如下：
```
 @Test
    @DisplayName("渲染chart")
    void renderChart() throws Exception {
        String rootPath = "C:\\Workspaces\\";
        Map<String, Object> includesData = new HashMap<>();
        // 组装父模板中chart
        includesData.put("parentChart", Charts
                .ofMultiSeries("电商运营指数", new String[]{"京东", "淘宝", "天猫", "阿里巴巴", "抖音", "快手"})
                .addSeries("指标A（家)", new Number[]{1, 2, 3, 4, 5, 6})
                .addSeries("指标B（条）", new Number[]{1.2, 2.3, 3.2, 3, 5.2, 6.1}).create());
        Map<String, Object> sub1RenderModel = new HashMap<>();
        // 组装子模板chart1
        sub1RenderModel.put("sub1Chart", Charts
                .ofMultiSeries("电商运营指数", new String[]{"京东", "淘宝", "天猫", "阿里巴巴", "抖音", "快手"})
                .addSeries("指标A（家)", new Number[]{1, 2, 3, 4, 5, 6})
                .addSeries("指标B（条）", new Number[]{1.2, 2.3, 3.2, 3, 5.2, 6.1}).create());
        includesData.put("sub1", Includes.ofLocal(rootPath + "poi/sub1.docx").setRenderModel(sub1RenderModel).create());
        // 自定义图片标签渲染策略
        XWPFTemplate template = XWPFTemplate.compile(rootPath + "poi/parent.docx").render(includesData);
        template.writeToFile(rootPath + "poi/chart_result.docx");
    }
```
文件如下：
[parent.docx](https://github.com/Sayi/poi-tl/files/13193965/parent.docx)
[sub1.docx](https://github.com/Sayi/poi-tl/files/13193966/sub1.docx)

**Comment by zhangchaoxu** [comment]
@Sayi 接上，再补充一个修复的办法，在子模板中如果还存在嵌套的内容，居然就能修复这个主体了。

以下是可以出现的子模板文件：
[sub1_fix.docx](https://github.com/Sayi/poi-tl/files/13194903/sub1_fix.docx)
