### ISSUE TITLE
可以动态生成Word文档吗？不依赖于模板数据

### ISSUE THREAD

**Issue by dearMOMO** [Sayi/poi-tl#414]
公司的需求是文字、表格、图片、图表什么的都是后端动态给的数据进行渲染，不是按照模板来的。例如，假如模板上有个位置是生成一个折线图，但是我们这边的数据是动态的，可以生成多个折线图或者饼图这些。大佬，有好的方案吗

**Comment by Sayi** [comment]
数据是动态的是什么意思？你要把数据映射成模版数据就行了吧

**Comment by dearMOMO** [comment]
例如我们要生成一个折线图，但是他的那些样式，是由代码写的，而不是依赖于模板

**Comment by Sayi** [comment]
#415

**Comment by gudqs7** [comment]
> 公司的需求是文字、表格、图片、图表什么的都是后端动态给的数据进行渲染，不是按照模板来的。例如，假如模板上有个位置是生成一个折线图，但是我们这边的数据是动态的，可以生成多个折线图或者饼图这些。大佬，有好的方案吗

@dearMOMO 可以参考嵌套子文档来动态生成非固定数量的图表, 但样式要求使用代码来控制确实是难...  如果不是样式非常多变, 可以试着弄两个图表, 显示一个隐藏另一个的方式... 但局限性很大....    实在不行就找个小树林和产品经理打一架
