### ISSUE TITLE
【图表语法】不通过图表模板，根据数据单独创建

### ISSUE THREAD

**Issue by dearMOMO** [Sayi/poi-tl#415]
http://deepoove.com/poi-tl/apache-poi-guide.html     缺少图表操作的一些示例 例如 (多条)折线图、饼图、(多条)柱状图、其他

**Comment by dearMOMO** [comment]
我们现在的需求就是单独创建图表，而不依赖于模板。太特么蛋疼了

**Comment by Sayi** [comment]
Auto closed.
