### ISSUE TITLE
嵌套功能能否支持一下保留模板格式？

### ISSUE THREAD

**Issue by Kong0305** [Sayi/poi-tl#420]
嵌套功能，也就是{{+var}}标签。在模板中设置好了标签的文字样式，能否将嵌套过来的word的文字也改成设置好的标签的文字样式。

**Comment by Sayi** [comment]
意思是 嵌套文档里面的文字 使用主版本标签{{+var}}的文字样式？

**Comment by Kong0305** [comment]
是的

**Comment by Sayi** [comment]
为啥不在嵌套文档里面设置样式呢？嵌套文档可能不止文字，还有很多图片，全部文字设置成标签样式 不合理。

**Comment by Kong0305** [comment]
需求是这样的：
有个word报告生成的功能，开发或者运维设计好模板就不变了，模板中预留了这块空间用于插入一些说明文字。客户在使用的时候，直接以附件的形式上传一个或者多个word，程序将这些word的内容合并到模板中最终生产一个word报告。因为word报告是有要求的，例如字号、字体、行间距等，因为我们无法控制用户上传的word的内容格式，为了方便统一格式所以需要这个功能。

**Comment by Sayi** [comment]
那可以不用合并的语法，把用户上传的文档读取里面文字，然后用{{text}}文本标签设置样式就可以了。
