### ISSUE TITLE
区块对循环表格第一条数据没有显示出来，前面有的表格是循环成功的

### ISSUE THREAD

**Issue by mianbaoking** [Sayi/poi-tl#421]
![image](https://user-images.githubusercontent.com/36829366/89769068-204bb600-db2f-11ea-908b-944f0c832e18.png)
![image](https://user-images.githubusercontent.com/36829366/89769082-293c8780-db2f-11ea-82d3-7758e5ae3a3d.png)
![image](https://user-images.githubusercontent.com/36829366/89769110-322d5900-db2f-11ea-82df-bdd17aade7c3.png)

**Comment by Sayi** [comment]
@mianbaoking hi，你把代码和模板给我，我来重现下这个问题。
