### ISSUE TITLE
MyDataModel中无setName方法

### ISSUE THREAD

**Issue by hyjunn** [Sayi/poi-tl#422]
![Uploading image.png…]()
public void testRenderObject() throws Exception {
        MyDataModel obj = new MyDataModel();
        obj.setHeader("Deeply love what you love.");
        ### obj.setName("Poi-tl");
        obj.setWord("模板引擎");
        obj.setTime("2019-05-31");

**Comment by Sayi** [comment]
@hyjunn 继承了父类方法。
