### ISSUE TITLE
传入网络上的图片的时候，无法获取图片

### ISSUE THREAD

**Issue by c876483156** [Sayi/poi-tl#424]
传入的文件地址是生成的连接，支持浏览器和手机端下载。这该怎么解决呢？

报错信息：
Server returned HTTP response code: 403 for URL ：图片链接

图片链接是在浏览器上是可以正常下载的。

**Comment by Sayi** [comment]
可以把图片链接发给我试试？如果图片链接不方便公开，可以私信到我邮箱。

**Comment by c876483156** [comment]
您好~已经发送到邮箱了~

**Comment by c876483156** [comment]
您好~
已经发到邮箱咯~

**Comment by Sayi** [comment]
@c876483156  我用你给的链接测试了一下，可以正常使用的。生成的word可以正常展示图片，没有出现你的问题。

**Comment by c876483156** [comment]
哥，源码可以给我看看吗？我直接用这个链接的时候，就会出现403的报错信息

**Comment by Sayi** [comment]
就换成你给的链接就可以了啊：
```java
// 网络图片
put("urlPicture", new PictureRenderData(100, 100, ".png",
    BytePictureUtils.getUrlBufferedImage("替换你的链接")));
```

**Comment by xingzhezhige** [comment]
请教下作者，场景是这样：套打内容包含富文本，要求套打时保留页面富文本样式包括图片，目前采用的方案是，如果是富文本，则先通过富文本内容生成一份word的文档，然后通过DocxRenderPolicy模板嵌套的方式拼接。问题：富文本的样式没什么问题，但是图片无法显示，且套打出来的文件打开提示报错（富文本生成的那份word里面的样式和图片都没问题）。请教下该如何解决？

**Comment by Sayi** [comment]
把富文本生成的文档发出来看看 @xingzhezhige

**Comment by xingzhezhige** [comment]
您好！
&nbsp; 附件分别为word套打的主模板，富文本生成的子模板及套打出来的word文档。
另外咨询下：POIFSFileSystem fs = new POIFSFileSystem();fs.createDocument(is, "WordDocument");这种方式生成的word后缀必须是.doc，如果是.docx的就提示文件损坏，但是子模板需要的是.docx格式的，怎样才能生成.docx的word文件呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sayi/poi-tl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月12日(星期一) 下午3:16
收件人:&nbsp;"Sayi/poi-tl"<poi-tl@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子心"<1109680400@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Sayi/poi-tl] 传入网络上的图片的时候，无法获取图片 (#424)





 
把富文本生成的文档发出来看看 @xingzhezhige

**Comment by Sayi** [comment]
#219
