### ISSUE TITLE
动态表格支持列的合并吗，比如部门和员工，我想把部门相同的合为一个列，有实例吗

### ISSUE THREAD

**Issue by moonzc1** [Sayi/poi-tl#425]

**Comment by Sayi** [comment]
是动态的合并某些列吗？可以把你想要实现的效果描述的更清楚点？

**Comment by moonzc1** [comment]
![捕获](https://user-images.githubusercontent.com/48426642/90617859-c8edca00-e241-11ea-8e85-180db5a532d3.PNG)

**Comment by moonzc1** [comment]
@Sayi
![捕获](https://user-images.githubusercontent.com/48426642/90617986-f0dd2d80-e241-11ea-82d2-a6d6b85a4514.PNG)
相同部门合并，支持吗，是先用list一行行渲染再合并? 还是可以用List<Depart,List<User>>这个样的结构来渲染

**Comment by Sayi** [comment]
目前需要先用list一行行渲染再合并。这块正在想着有什么好的优化方案，你有什么建议也可以提一下。
