### ISSUE TITLE
我想使用poi-tl生成组合图表和圆环图，请问有什么解决方案，我试了引用标签，貌似不支持这两种图表类型

### ISSUE THREAD

**Issue by Alex-lin-yu** [Sayi/poi-tl#426]
我想使用poi-tl生成组合图表和圆环图，请问有什么解决方案，我试了引用标签，貌似不支持这两种图表类型。还请赐教，谢谢！
圆环图：
![image](https://user-images.githubusercontent.com/69912349/90655065-b55b5700-e273-11ea-951b-c9d447311666.png)
组合图表：
![image](https://user-images.githubusercontent.com/69912349/90655158-ca37ea80-e273-11ea-8280-a8aded8da823.png)

**Comment by Alex-lin-yu** [comment]
组合图表即柱状图+折线图的组合图表

**Comment by Sayi** [comment]
@Alex-lin-yu Hi，刚发布了1.8.2版本，使用这个版本并且确保项目中依赖的poi是4.1.2版本
```xml
<dependency>
  <groupId>com.deepoove</groupId>
  <artifactId>poi-tl</artifactId>
  <version>1.8.2</version>
</dependency>
```
可以参考这个单元测试，里面有环形图和组合图表的示例：[ChartReferencePolicyTest.java](https://github.com/Sayi/poi-tl/blob/master/src/test/java/com/deepoove/poi/tl/policy/ref/ChartReferencePolicyTest.java)

**Comment by Alex-lin-yu** [comment]
已验证，可以使用，谢谢老师
