### ISSUE TITLE
动态渲染出来的表格是否支持对某列内容设置行间距？急

### ISSUE THREAD

**Issue by LiJunYi2** [Sayi/poi-tl#430]
你好，我想问下，对于通过继承DynamicTableRenderPolicy来实现对模板里表格的渲染时，是否支持对表格的某列设置行间距样式？

**Comment by Sayi** [comment]
POI是可以设置行间距的，可能是这个：org.apache.poi.xwpf.usermodel.XWPFParagraph.setSpacingBetween(double)

**Comment by LiJunYi2** [comment]
那我应该如何在DynamicTableRenderPolicy中使用，我看了下源码一些接口，没有直接调用设置的地方。麻烦了
