### ISSUE TITLE
请问if语法有对应的else操作么？

### ISSUE THREAD

**Issue by wangjiahao123456** [Sayi/poi-tl#432]
我可以通过增加不通的字段去设置if的显示结果，可是这样太过麻烦，我想问一下，是否存在if,else语法标签
这种标签的显示需要用到if else
![image](https://user-images.githubusercontent.com/40234387/91129125-06d46d80-e6dc-11ea-8f91-cc6a6aa0b650.png)

**Comment by Sayi** [comment]
没有else,可以设计if的条件表达式来满足需求场景。
