### ISSUE TITLE
请问动态表格可以多个使用吗？

### ISSUE THREAD

**Issue by Passion-Logan** [Sayi/poi-tl#434]
作者你好，我现在遇到的具体问题是：我在同一个word中添加了多个不同标签的动态表格，请问可以使用动态策略去渲染吗？我看了http://deepoove.com/poi-tl/#example-table 这个例子，它只能获取一个bind标签的XWPFTable对象进行操控

**Comment by Sayi** [comment]
Hi  可以多次调用bind绑定不同标签到动态表格策略的。

**Comment by Passion-Logan** [comment]
> 嗨，@ Passion-Logan可以多次调用绑定绑定不同标签到动态表格策略的。

@Sayi 好的，谢谢你，我下去试试看，我看到还有一个[HackLoopTableRenderPolicy](http://deepoove.com/poi-tl/#hack-loop-table)插件，这个插件的[示例代码](https://github.com/Sayi/poi-tl/blob/master/src/java/com/deepoove/poi/policy/HackLoopTableRenderPolicyTest.java)地址失效了，能麻烦提供一下新地址么

**Comment by Sayi** [comment]
@Passion-Logan 文档已更新，[HackLoopTableRenderPolicyTest.java](https://github.com/Sayi/poi-tl/blob/master/src/test/java/com/deepoove/poi/tl/policy/HackLoopTableRenderPolicyTest.java)

**Comment by Passion-Logan** [comment]
> @Passion-Logan 文档已更新，[HackLoopTableRenderPolicyTest.java](https://github.com/Sayi/poi-tl/blob/master/src/test/java/com/deepoove/poi/tl/policy/HackLoopTableRenderPolicyTest.java)

好的，谢谢
