### ISSUE TITLE
图片用标签替换的方式失败

### ISSUE THREAD

**Issue by F0nnys** [Sayi/poi-tl#436]
新版word  在替换文字那里已经设置{{img}}了  结果替换失败。
用{{@img}}方式没问题，但格式不满足要求
求大大解答一下~~

**Comment by Sayi** [comment]
错误信息或者日志信息？

**Comment by miRUAcleInjoker** [comment]
> 错误信息或者日志信息？

日志直接跳过了{{img}}的渲染，其他文字的{{}}都是正常的，只有图片没有被替换

**Comment by F0nnys** [comment]
我后面用了一些取巧的方法 做到了其他格式的效果。。 但本质问题没解决-。-

**Comment by miRUAcleInjoker** [comment]
> 我后面用了一些取巧的方法 做到了其他格式的效果。。 但本质问题没解决-。-

请问下怎么投机取巧😂

**Comment by Sayi** [comment]
无法重现。
