### ISSUE TITLE
有没有折线图的示例

### ISSUE THREAD

**Issue by helloworld-wrj** [Sayi/poi-tl#437]
需要实现在折线图中根据实际数据显示折线的数量。

**Comment by Sayi** [comment]
参考这个单元测试：[ChartReferencePolicyTest-1.8.x](https://github.com/Sayi/poi-tl/blob/bugfix1.8.x/src/test/java/com/deepoove/poi/tl/policy/ref/ChartReferencePolicyTest.java)

**Comment by helloworld-wrj** [comment]
那模板中，折线图的渲染的标签在哪输入。

**Comment by helloworld-wrj** [comment]
那模板中折线图的需要渲染的标签要在哪里写入，我用的是office 2016。

**Comment by Sayi** [comment]
文档里面写了很清楚。

**Comment by helloworld-wrj** [comment]
实在找不到（高版本office标签位置在：编辑替换文字-替换文字）。这个位置在哪有
