### ISSUE TITLE
图表标签位置在哪写入

### ISSUE THREAD

**Issue by helloworld-wrj** [Sayi/poi-tl#438]
实标签位置在：图表区格式—​可选文字—​标题（高版本office标签位置在：编辑替换文字-替换文字）。
在offic2016 wps都找了半天都没有找到，谁知道在怎么点击。

**Comment by helloworld-wrj** [comment]
> 实标签位置在：图表区格式—​可选文字—​标题（高版本office标签位置在：编辑替换文字-替换文字）。
> 在offic2016 wps都找了半天都没有找到，谁知道在怎么点击。

**Comment by johnbukaixin** [comment]
这个问题解决了吗？而且图的编辑替换文字-替换文字虽然可以设置但是是不起作用的，实际上对应的是wps的文字说明
