### ISSUE TITLE
兄弟，我从maven引入的poi-tl.1.8.2.jar没有TableRenderData.java，bug快点处理呀，看你昨天代码大改(⊙o⊙)？

### ISSUE THREAD

**Issue by lc11535** [Sayi/poi-tl#439]
![image](https://user-images.githubusercontent.com/18096138/91840162-d748d680-ec82-11ea-88eb-aeee510e7b95.png)
兄弟，我从maven引入的poi-tl.1.8.2.jar没有TableRenderData.java，bug快点处理呀，看你昨天代码大改(⊙o⊙)？
 
TableRenderData
NumberingRenderData 
MyDataModel

这几个类都没有找到(⊙o⊙)？

**Comment by Sayi** [comment]
@lc11535 Hi，

master是1.9.0-SNAPSHOT版本，还未发布。

你可以选择标签v1.8.2查看源码，相关文档指向master的我已经更新成v1.8.2了。
