### ISSUE TITLE
你好，生成表格之后没有边框

### ISSUE THREAD

**Issue by banxingdeyu** [Sayi/poi-tl#441]
这个问题困扰了我两天，在表格里生成表格第一天有边框，第二天再测的时候就没了边框，在表格外测试有边框，我猜测可能是word模板的问题。

**Comment by Sayi** [comment]
边框样式是自动的吧，设置下边框样式（线条、粗细、颜色）就行了。

**Comment by banxingdeyu** [comment]
是使用自动的样式，但是我设置的是正常，也就是所有线都有的样式
但是实际上生成之后的表格，用的是自定义的样式，没有线
我看新的代码里有表格选择线
麻烦问一下，新版本大概什么时候上线呢 @Sayi

**Comment by Sayi** [comment]
新版本暂时没计划哦，你可以重写下MiniTableRenderPolicy，给表格加上边框，然后绑定这个新策略就行了。

**Comment by banxingdeyu** [comment]
谢谢，可以了
