### ISSUE TITLE
builder.buildGrammerRegex(RegexUtils.createGeneral("${", "}"));  比如${p1.1}这个就不行

### ISSUE THREAD

**Issue by clearboy88** [Sayi/poi-tl#446]
比如${p1.1}
要支持.比如 ${p2.1.1},也可以就行了。
需要如何调整呢？

**Comment by Sayi** [comment]
```java
Configure.builder().buildGramer("${", "}").buildGrammerRegex(RegexUtils.createGeneral("${", "}")).build(); 
```
有调用buildGramer设置语法吗？

**Comment by clearboy88** [comment]
感谢这么快回复，有的，按文档说明来的。
这个我再试一下，不行，我再跟。

**Comment by clearboy88** [comment]
v1.8.2

ConfigureBuilder builder = Configure.newBuilder();
builder.buildGramer("${", "}");
builder.addPlugin('@', new PictureRenderPolicy());
builder.buildGrammerRegex(RegexUtils.createGeneral("${", "}"));
XWPFTemplate template = XWPFTemplate.compile("template.docx",builder.build());

word:     ${p1.1}
测试了，不行。

**Comment by clearboy88** [comment]
我要如何才能满足，标签中有点"."

**Comment by Sayi** [comment]
我按照你的代码试了下，我是可以的。
```
Resolve where text: ${p1.1}, and create ElementTemplate 
```

**Comment by Sayi** [comment]
这个点应该和对象前缀冲突吧，解析成p1对象里面的名称为1的属性。

**Comment by clearboy88** [comment]
我没有用到对象的概念，我只是要替换占位符即可。现在有没有解决方案，或者能不能把你测试的demo发我看一下。

**Comment by Sayi** [comment]
只能在对象中使用点来表示。

**Comment by clearboy88** [comment]
好的，明白了，我来看一下文档。
