### ISSUE TITLE
在区块中使用嵌套模板

### ISSUE THREAD

**Issue by QianYC** [Sayi/poi-tl#447]
你好，我想使用嵌套模板来展示一个列表的内容，希望列表为空的时候渲染为空，然而发现单单使用嵌套模板必定会渲染一次。因此想试试区块+嵌套模板的方法来实现上述需求，我尝试了两种模板：

```
{{?internships}}
{{=#this}}
{{/internships}}
```

```
{{?internships}}
{{+internships}}
{{/internships}}
```
均不能实现需求，请问区块可以和嵌套模板一起使用吗？

**Comment by Sayi** [comment]
#403 

当标签对应的值为null时则不会被渲染。

**Comment by QianYC** [comment]
我目前是在逻辑层控制的，如果列表为空就不插入嵌套模板的数据
