### ISSUE TITLE
添加到单系列的线性图报错 ChartSingleSeriesRenderData无法转换成ChartMultiSeriesRenderData？

### ISSUE THREAD

**Issue by lezoycn86** [Sayi/poi-tl#449]
Caused by: java.lang.ClassCastException: com.deepoove.poi.data.ChartSingleSeriesRenderData cannot be cast to com.deepoove.poi.data.ChartMultiSeriesRenderData

**Comment by Sayi** [comment]
你的图表是多系列图表吧？然后用了单系列的数据。

**Comment by lezoycn86** [comment]
您有邮箱吗？我邮箱发您看一下 设置的就是单系列的

**Comment by lezoycn86** [comment]
> 你的图表是多系列图表吧？然后用了单系列的数据。

您有邮箱吗？我邮箱发您看一下 设置的确实是单系列的

**Comment by Sayi** [comment]
你说下你是什么图标？柱形图？

**Comment by lezoycn86** [comment]
> 你说下你是什么图表？柱形图？

这张图是饼状图 改成线形图以后没法导入

**Comment by Sayi** [comment]
饼状图是单系列，线形图是多系列。数据格式不一样。

**Comment by lezoycn86** [comment]
> 饼状图是单系列，线形图是多系列。数据格式不一样

**Comment by lezoycn86** [comment]
> 饼状图是单系列，线形图是多系列。数据格式不一样。
> 
> 文档里写的很清楚，多看看文档~~好的谢谢
