### ISSUE TITLE
DetailTablePolicy中使用SpEL时会报EL1008E的错

### ISSUE THREAD

**Issue by xuzhu007** [Sayi/poi-tl#450]
项目中的单元测试com.deepoove.poi.tl.example.PaymentExample#testPaymentExample方法中用到SpEL时会报EL1008E的错
@Test
    public void testPaymentExample() throws Exception {
        Configure config = Configure.builder().bind("detail_table", new DetailTablePolicy()).useSpringEL().build();
        XWPFTemplate template = XWPFTemplate.compile(resource, config).render(datas);
        template.writeToFile("out_example_payment.docx");
    }

![image](https://user-images.githubusercontent.com/20570417/92671194-345e1f80-f348-11ea-88f1-10870695e941.png)

**Comment by Sayi** [comment]
@xuzhu007 默认el使用了注解，模板标签是detail_table，使用springEL的时候规则是取属性名，你把模板中detail_table换成detailTable就可以了。
