### ISSUE TITLE
TableBuilder.ofWidth(double cmWidth, double[] colCmWidths) 不生效

### ISSUE THREAD

**Issue by pathfindGulf** [Sayi/poi-tl#453]
auto效果不理想，设置的固定表格列宽度不生效。 
`
        List<Apparatus> apparatuses = apparatusMapper.listApparatusByBuoId(businessUtensilOriginal.getId());

        Tables.TableBuilder of = Tables.of().width(14.63f, new double[]{14.63/6, 14.63/6, 14.63/6, 14.63/6, 14.63/6, 14.63/6});
        of.addRow(Rows.of("仪器名称", "型号/出厂编号", "不确定度/准确定度等级/最大允许误差",
                "证书编号", "证书有效期至", "溯源至").center().create());
        for (Apparatus apparatus : apparatuses) {
            of.addRow(Rows.of(Cells.of(apparatus.getName()).center().create(),
                    Cells.of(StrUtil.isNotBlank(apparatus.getModel()) ? apparatus.getModel() + ";" + apparatus.getCode() : "" + apparatus.getCode()).center().create(),
                    Cells.of().addParagraph(WordUtil.str2Special(apparatus.getAccuracyOrError())).center().create(),
                    Cells.of(apparatus.getCertificateNumber()).center().create(),
                    Cells.of(apparatus.getAbolishTime() != null ?
                            apparatus.getAbolishTime().format(DateTimeFormatter.ofPattern("yyyy/MM/dd")) : "/").center().create(),
                    Cells.of(apparatus.getMaxSource()).center().create()
            ).center().create());
        }
        originalVo.setApparatusTable(of.center().create());

        //将表格数据填入模板
//        Configure config = Configure.builder().bind("#apparatus_table", new OriginalRecordUtensilPolicy(tableMerges)).build();
        //保存输出文件
        String fileName = FilePathConstant.FILE_PATH_ORIGINAL_COVER + UUIDUtil.getUUID() + FilePathConstant.FILE_FORMAT_DOCX;
        //渲染其他数据
        WordUtil.writeToLocal(originalVo, TemplatePathBean.TEMPLATE_ORIGINALRECORD, fileName, null);

        //转换为pdf
        String pdfFileName = FilePathConstant.FILE_PATH_ORIGINAL_COVER + UUIDUtil.getUUID() + FilePathConstant.FILE_FORMAT_PDF;
        Document4jUtil.wordToPdf(fileName, pdfFileName);
`

`
    /**
     * 功能描述: 生成word的特殊字符处理
     *
     * @param param: 要转换的字符串
     * @return: com.deepoove.poi.data.ParagraphRenderData  带样式的数据
     * @author: mlk
     * @date: 2020/9/15
     * @throws:
     */
    public static ParagraphRenderData str2Special(String param) {
        Paragraphs.ParagraphBuilder of = Paragraphs.of();

        String[] split = param.split(" ");
        List<Object> value = EnumUtil.getFieldValues(SpecialCharacterEnum.class, "value");
        for (String currData : split) {
            Boolean isMatch = value.contains(currData.split("\\[")[0] + "[");
            if (!isMatch) {
                of.addText(currData);
                continue;
            }
            //斜体
            if (currData.contains(SpecialCharacterEnum.ITALIC.getValue())) {
                String[] strArray = currData.split("i\\[");
                String italicStr = strArray[1].replace("]", "");
                of.addText(strArray[0]).addText(Texts.of(italicStr).italic().create());

                //上标
            } else if (currData.contains(SpecialCharacterEnum.SUB.getValue())) {
                String[] strArray = currData.split("sub\\[");
                String subStr = strArray[1].replace("]", "");
                of.addText(strArray[0]).addText(Texts.of(subStr).sub().create());

                //下标
            } else if (currData.contains(SpecialCharacterEnum.SUP.getValue())) {
                String[] strArray = currData.split("sup\\[");
                String supStr = strArray[1].replace("]", "");
                of.addText(strArray[0]).addText(Texts.of(supStr).sup().create());
            } else {
                log.warn("该特殊字符暂不支持！");
            }
        }
        return of.left().create();
    }
`

![image](https://user-images.githubusercontent.com/41456389/93221209-0c374c00-f7a0-11ea-8f8f-c3848bc4de6f.png)

**Comment by Sayi** [comment]
生成的word是什么样的？ pdf错乱，可能是你使用的pdf组件问题。

**Comment by pathfindGulf** [comment]
![image](https://user-images.githubusercontent.com/41456389/93285549-b6968a00-f807-11ea-98a3-e54647ef0877.png)

**Comment by pathfindGulf** [comment]
word文件表格列宽也是不对

**Comment by pathfindGulf** [comment]
会不会是MiniTableRenderPolicy.Helper.renderRow 改成TableRenderPolicy.Helper.renderRow 的原因。 注掉这行代码，生成的空单元格宽度正常

**Comment by Sayi** [comment]
给个能复现的最小单元测试给我吧

**Comment by pathfindGulf** [comment]
源码中IterableRenderBasicExample.init()方法
`
@BeforeEach
	public void init() {
		// create table
		RowRenderData header = Rows.of("Word处理方案", "是否跨平台", "易用性").textColor("FFFFFF").bgColor("ff9800").center()
			.rowHeight(2.5f).create();
		RowRenderData row0 = Rows.of("Poi-tl", "纯Java组件，跨平台", "简单：模板引擎功能，并对POI进行了一些封装").create();
		RowRenderData row1 = Rows.of("Apache Poi", "纯Java组件，跨平台", "简单，缺少一些功能的封装").create();
		RowRenderData row2 = Rows.of("Freemarker", "XML操作，跨平台", "复杂，需要理解XML结构").create();
		RowRenderData row3 = Rows.of("OpenOffice", "需要安装OpenOffice软件", "复杂，需要了解OpenOffice的API").create();
		RowRenderData row4 = Rows.of("Jacob、winlib", "Windows平台", "复杂，不推荐使用").create();
//        table = Tables.of(header, row0, row1, row2, row3, row4).create();
		RowRenderData row00 = Rows.of("仪器名称", "型号/出厂编号", "不确定度/准确定度等级/最大允许误差",
			"证书编号", "证书有效期至", "溯源至").center().create();
		RowRenderData row01 = Rows.of("多功能校准源", "HG6501;370712249", "DCV:Urel=1.8×10-4 ～1.2×10-2   k=2" +
				"DCI:Urel=5.8×10-4 ～5.8×10-2   k=2" +
				"ACV:Urel=9.2×10-4 ～2.3×10-1   k=2" +
				"ACI:Urel=6.8×10-4 ～5.8×10-1  k=2 ",
			"JZ20200104", "证书有效期至", "西安高压电器研究院").center().create();
		RowRenderData row02 = Rows.of("数字便携式交直流峰值电压表", "PVT0501;4704517", "Urel=1.0×10-3   k=2",
			"GFJGJL2048190001230", "证书有效期至", "中国电子科技集团公司第二十研究所").center().create();
		RowRenderData row03 = Rows.of("数字多用表", "34401AUS36103876", "DCV：Urel=4.6×10-5  ~ 4.6×10-4   k=2" +
				"ACV：Urel=1.0×10-3  ~ 2.7×10-1   k=2" +
				"DCI：Urel=8.1×10-4  ~1.3×10-2   k=2" +
				"ACI:Urel=1.2×10-3  ~3.8×10-3   k=2",
			"MYJL2010003218", "证书有效期至", "西安空间无线电技术研究所航空校准实验室").center().create();
		RowRenderData row04 = Rows.of("函数发生器", "33250AMY40027289", "电压：Urel=1.7%    k=2 " +
				"频率：Urel=5.9×10-8    k=2",
			"MYJL2010003218", "证书有效期至", "西安空间无线电技术研究所航空校准实验室").center().create();
		RowRenderData row05 = Rows.of("精密十进位标准电容箱", "CH-16TKP2067", "±0.03%",
			"校准字第202007008557", "证书有效期至", "中国测试技术研究院").center().create();
		table = Tables.of(row00, row01, row02, row03, row04, row05).create();
		// create numbering
		numbering = Numberings.of("Plug-in grammar, add new grammar by yourself",
			"Supports word text, local pictures, web pictures, table, list, header, footer...",
			"Templates, not just templates, but also style templates").create();
	}
`

**Comment by Sayi** [comment]
有点奇怪，在word文档中看到单元格和列宽其实设置都是正确，但是显示不正确。

不过我用Mac Pages打开是完全正确的，Microsoft Office下可能要花点时间找下问题了。。。

**Comment by Sayi** [comment]
是个bug，原因应该是里面英文拉丁字符太长无法恰当换行导致列宽失效。

master已经修复，随着1.9.0正式版会发布。急着用的话可以看下怎么修复的，自己仿着TableRenderPolicy写个插件。

**Comment by pathfindGulf** [comment]
谢谢，不着急
