### ISSUE TITLE
模板插入子模板问题

### ISSUE THREAD

**Issue by javadoge** [Sayi/poi-tl#455]
![image](https://user-images.githubusercontent.com/5305836/93411089-e9ef1c80-f8cc-11ea-8bd2-58cb84118c39.png)
主模板一部分内容如上图

可以把图中内容单独拆出来作为子模板么？

文档我看就一个DocxRenderData，这个只能传简单的list数据当子模板才可以

请问我上面图中内容想当子模板插入进去支持么？

如果上图列表数据很多，可以插入多次么，在主模板多页展示

求大佬指点一二，万分感谢

**Comment by Sayi** [comment]
用插件。
