### ISSUE TITLE
区块对 包含表格问题

### ISSUE THREAD

**Issue by javadoge** [Sayi/poi-tl#456]
![image](https://user-images.githubusercontent.com/5305836/93417240-22492780-f8da-11ea-95d5-eaafa5b4715a.png)

如上图，区块对包含表格，需要渲染表格，请问这样怎么处理？

.bind("groundResistances", hackLoopTableRenderPolicy)  这样有问题

**Comment by Sayi** [comment]
升级到1.9.0-beta试试，http://deepoove.com/poi-tl/1.9.0-beta/
