### ISSUE TITLE
请教一下，动态表格插件中，怎么使表格中的文本居中对齐（水平和垂直）？

### ISSUE THREAD

**Issue by Nibbbbbbbb** [Sayi/poi-tl#457]
实现了一个自己的策略 extends DynamicTableRenderPolicy 

然后在里面使用了表格居中
`
TableStyle rowStyle = new TableStyle();
rowStyle.setAlign(STJc.CENTER);

RowRenderData build = RowRenderData.build(....);
build.setRowStyle(rowStyle);
`
发现只能水平居中，无法垂直居中，请教一下如何使文本全部水平垂直居中

感激不尽！

**Comment by Sayi** [comment]
要设置CellRenderData里面的style样式。

1.9.0-beta里面有实现。
