### ISSUE TITLE
table 渲染？

### ISSUE THREAD

**Issue by ZJongs** [Sayi/poi-tl#46]
为什么表格数据的渲染，要用 value1;value2    之间要用 ； 分割开？？？ 这种写法好奇怪。如果我的value1的值中含有“；” 就会出问题。感觉不应该这样处理。应该有其他更好的方法。比如用List<Map>

**Comment by Sayi** [comment]
@ZJongs 这的确是个可以优化的点，欢迎pull Request。

**Comment by Sayi** [comment]
1.3.0 版本使用了重新设计的表格数据MiniTableRenderData。
