### ISSUE TITLE
1.9.0-beta ，合并后渲染有问题

### ISSUE THREAD

**Issue by Nibbbbbbbb** [Sayi/poi-tl#460]
poi-tl版本：1.9.0-beta  (1.8.2无此问题)

问题：当把表格中的一行，从N列合并成2列后，再渲染2个字符串进去时会报错：
Dynamic render table error:Number of cells and render data should be the same!

打断点发现此处size=3导致报错，第三个cell的内容是报错信息（没截到图，代码全改回1.8.2版了，不好意思）
![image](https://user-images.githubusercontent.com/21167262/93656601-f5258200-fa5d-11ea-82dc-f99fd22e31b6.png)

测试的渲染策略如下：
`
public class TemplatePolicyTableTestPolicy extends DynamicTableRenderPolicy {

    // 填充数据所在行数
    private int startRow = 10;
    // 总列数
    private int colTotal = 12;
    
    @Override
    public void render(XWPFTable table, Object data)  {

        int nowRow = 1;

        for (int i = 0; i <5; i++) {
            // 插入新行
            insertNewTableRow(table, startRow + nowRow);

            TableTools.mergeCellsHorizonal(table, startRow + nowRow, 0, 5);
            TableTools.mergeCellsHorizonal(table, startRow + nowRow, 1, 5);

            // 渲染一行 1.8.2
            //MiniTableRenderPolicy.Helper.renderRow(table, startRow + nowRow,RowRenderData.build("第一","第二"));

            // 渲染一行 1.9.0-beta
            TableRenderPolicy.Helper.renderRow(table.getRow(startRow + nowRow)
                 , Rows.of("第一","第二").center().create());

            // table.removeRow(startRow);
        }

    }

    /**
     * 插入新行
     *
     * @param table
     * @param row
     */
    private void insertNewTableRow(XWPFTable table, int row) {
        XWPFTableRow insertNewTableRow = table.insertNewTableRow(row);
        for (int j = 0; j < colTotal; j++) {
            insertNewTableRow.createCell();
        }
    }
}
`

[text.docx](https://github.com/Sayi/poi-tl/files/5248948/text.docx)

**Comment by Sayi** [comment]
Hi, 1.9.0-beta作了**更严格的校验**，你给的例子中合并后该行剩下三个单元格所以必须提供三个字符串。

**Comment by Nibbbbbbbb** [comment]
> Hi, 1.9.0-beta作了**更严格的校验**，你给的例子中合并后该行剩下三个单元格所以必须提供三个字符串。

可是如果我再加一个字符串，会报其他的错误，第三个cell的值不是正常的cell，而是一个报错的cell，所以即使我再加一个字符串，他也会错误

**Comment by Sayi** [comment]
![image](https://user-images.githubusercontent.com/1394854/93733900-bf250100-fc09-11ea-8ddd-8a121a9fb552.png)

我这边可以，合并单元格的时候注意，不要把已经合并的单元格再次进行合并。
