### ISSUE TITLE
希望添加一个功能，通过标识符获取位置

### ISSUE THREAD

**Issue by zhouxiaofu** [Sayi/poi-tl#461]
如 getLocation(String... tags)

返回Map<String,TagLocation>
key 为 tag 
value为TagLocation对象

或者返回 List<TagLocation>

TagLocation 属性为
String tag、Integer pageNum、Integer offsetX 、Integer  offsetY

**Comment by imic07** [comment]
可以试下poi操作书签。

**Comment by zhouxiaofu** [comment]
> 可以试下poi操作书签。

对POI不是很熟，查了很多都没找到怎么定位字符串位置的方法，pdf的倒是有看到

**Comment by iehyou** [comment]
docx 是流式文档 没法获取坐标的吧？？ 你要获取坐标位置是要做什么呢？
