### ISSUE TITLE
根据Word模板解析出对应的数据结构

### ISSUE THREAD

**Issue by MACDfree** [Sayi/poi-tl#467]
poi-tl的逻辑是：Word模板+数据=输出
其中Word模板和数据其实是相互独立的，会有Word模板和数据不匹配的情况。
现在想要做的是：根据Word模板解析获取对应的**数据模板**，通过数据模板和自定义的计算规则生成真正需要填充的数据，最后再通过Word模板和数据渲染生成最终的文件。

根据以上思路，请问一下根据Word模板解析获取数据模板是否可行？

**Comment by Sayi** [comment]
可行。

**Comment by diaomina** [comment]
期待实现！

**Comment by MACDfree** [comment]
已在公司内部项目中实现。不过是将poi-tl底层的poi整个替换为了aspose.word（公司买了），降低了上手难度。
