### ISSUE TITLE
jar

### ISSUE THREAD

**Issue by linlinjie** [Sayi/poi-tl#47]

**Comment by linlinjie** [comment]
我在springboot中引入了您的依赖，然后启动后出现了如下错误
Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path
试了一些方法解决不了

**Comment by Sayi** [comment]
这是架包冲突了，你在pom依赖关系里面找到上面两个任意一个架包的父jar包，然后排除掉这个架包。
