### ISSUE TITLE
添加目录没有更新页码？

### ISSUE THREAD

**Issue by lezoycn86** [Sayi/poi-tl#471]
使用TOCRenderPolicy插件，导出打开文件更新域以后目录标题正确，页码错误

**Comment by msansg** [comment]
请问TOCRenderPolicy怎么使用？或者在哪里有例子吗

**Comment by Sayi** [comment]
#131

**Comment by 520lipengtao** [comment]
> 请问TOCRenderPolicy怎么使用？或者在哪里有例子吗
请问下这个插件怎么使用
