### ISSUE TITLE
DocxRenderPolicy模板嵌套，子模板中带有图片时套打出来的文档提示报错，且图片显示不出来

### ISSUE THREAD

**Issue by xingzhezhige** [Sayi/poi-tl#473]
场景是这样：套打内容包含富文本，要求套打时保留页面富文本样式包括图片，目前采用的方案是，如果是富文本，则先通过富文本内容生成一份word的文档，然后通过DocxRenderPolicy模板嵌套的方式拼接。问题：富文本的样式没什么问题，但是图片无法显示，且套打出来的文件打开提示报错（富文本生成的那份word里面的样式和图片都没问题）。请教下该如何解决？

**Comment by Sayi** [comment]
没收到附件。

**Comment by xingzhezhige** [comment]
您看下现在有没有收到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sayi/poi-tl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月12日(星期一) 晚上11:08
收件人:&nbsp;"Sayi/poi-tl"<poi-tl@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子心"<1109680400@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Sayi/poi-tl] DocxRenderPolicy模板嵌套，子模板中带有图片时套打出来的文档提示报错，且图片显示不出来 (#473)





 
没收到附件。

**Comment by xingzhezhige** [comment]
不好意思，之前是在邮箱回复的。
[套打结果.docx](https://github.com/Sayi/poi-tl/files/5368265/default.docx)
[套打子模板.docx](https://github.com/Sayi/poi-tl/files/5368266/default.docx)
[富文本套打模板.docx](https://github.com/Sayi/poi-tl/files/5368267/default.docx)

**Comment by xingzhezhige** [comment]
另外咨询下，POIFSFileSystem fs = new POIFSFileSystem();fs.createDocument(is, "WordDocument");这种方式只能创建.doc类型的文档，可以生成.docx的文档吗？或者XWPFParagraph能不能支持设置富文本文件流？
