### ISSUE TITLE
嵌套循环模板该怎么写

### ISSUE THREAD

**Issue by lovelself** [Sayi/poi-tl#474]
举个例子更好说明这个
现在有这么一个数据
`{
    "num": "001",
    "personList": [
        {
            "name": "张三",
            "num": "001",
            "age": 18,
            "sex": "男",
            "lessonList": [
                {
                    "num": "10001",
                    "name": "语文",
                    "time": 1602662578870
                },
                {
                    "num": "10002",
                    "name": "数学",
                    "time": 1602662578870
                }
            ]
        },
        {
            "name": "王丽",
            "num": "002",
            "age": 39,
            "sex": "女",
            "lessonList": [
                {
                    "num": "10001",
                    "name": "语文",
                    "time": 1602662578870
                },
                {
                    "num": "10003",
                    "name": "英语",
                    "time": 1602662578870
                }
            ]
        }
    ]
}`
其中personList和lessonList的数据时后台动态返回的
现在需要在word中展示成这个样子
![image](https://user-images.githubusercontent.com/28685614/95966086-4e09ef80-0e3d-11eb-8f94-e21de31e03ec.png)

现在只能循环出一个person，没办法循环每一个person中的lessonList，很困扰

**Comment by Sayi** [comment]
文档里面有表格行循环的插件。

**Comment by Sayi** [comment]
很简单，文档里面有表格行循环的插件。
