### ISSUE TITLE
多图表导出报错

### ISSUE THREAD

**Issue by Wanik666** [Sayi/poi-tl#476]
org.apache.poi.openxml4j.exceptions.PartAlreadyExistsException: A part with the name '/word/embeddings/Microsoft_Excel_Worksheet0.xlsx' already exists : Packages shall not contain equivalent part names and package implementers shall neither create nor recognize packages with equivalent part names. [M1.12]

只创建一个ChartMultiSeriesRenderData实例导出没问题，创建多个导出就会报如上错误

**Comment by Wanik666** [comment]
代码类似这样的。
`java`
public void export(ReqMonthlyDTO reqMonthlyDTO, OutputStream outputStream){
    ConfigureBuilder builder = Configure.newBuilder();
    builder.setElMode(Configure.ELMode.SPEL_MODE);
    XWPFTemplate template = XWPFTemplate.compile(exportTemplate + "/模板.docx",builder.build());
    //图表数据1
    ChartMultiSeriesRenderData xsjqChart = new ChartMultiSeriesRenderData();
    xsjqChart.setChartTitle("分类对比图");
    xsjqChart.setCategories(new String[]{'a','b'});
    List<SeriesRenderData> seriesRenderData = new ArrayList<>();
    seriesRenderData.add(new SeriesRenderData("去年同期", xsjqProcess(xsjqLastYearData)));
    seriesRenderData.add(new SeriesRenderData("上月", xsjqProcess(xsjqLastMonthData)));
    seriesRenderData.add(new SeriesRenderData("本月", xsjqProcess(xsjqCurrentData)));
    xsjqChart.setSeriesDatas(seriesRenderData);
    //图表数据2
    ChartMultiSeriesRenderData xsjqDeptChart = new ChartMultiSeriesRenderData();
    xsjqDeptChart.setChartTitle("分类对比图");
    xsjqDeptChart.setCategories(new String[]{'a','b'});
    List<SeriesRenderData> seriesRenderDeptData = new ArrayList<>();
    seriesRenderDeptData.add(new SeriesRenderData("去年同期", xsjqProcess(xsjqLastYearData)));
    seriesRenderDeptData.add(new SeriesRenderData("上月", xsjqProcess(xsjqLastMonthData)));
    seriesRenderDeptData.add(new SeriesRenderData("本月", xsjqProcess(xsjqCurrentData)));
    xsjqDeptChart.setSeriesDatas(seriesRenderData);

    ResMonthlyDTO monthlyDTO = new ResMonthlyDTO();
    monthlyDTO.setXsjqChart(xsjqChart);
    monthlyDTO.setXsjqDeptChart(xsjqDeptChart);

    template.render(monthlyDTO);
    template.write(outputStream);
    template.close();
}

**Comment by Sayi** [comment]
给个简单能复现问题的单测

**Comment by Wanik666** [comment]
`java`

    @Test
    public void exportChart(HttpServletResponse response) {
        try {
            response.addHeader("Content-Disposition", "attachment;filename=xxx.docx");
            response.setContentType("application/octet-stream");
            OutputStream outputStream = response.getOutputStream();
            ConfigureBuilder builder = Configure.builder();

            XWPFTemplate template = XWPFTemplate.compile("D:/test.docx");
            Map<String,Object> map = new HashMap<>();

            ChartMultiSeriesRenderData xsjqChart = new ChartMultiSeriesRenderData();
            xsjqChart.setChartTitle("分类对比图");
            String[] categories = {"抢夺","盗窃汽车","强奸","敲诈勒索","入室盗窃","扒窃"};
            xsjqChart.setCategories(categories);
            List<SeriesRenderData> seriesRenderData = new ArrayList<>();

            seriesRenderData.add(new SeriesRenderData("去年同期", new Integer[] {12,13,1,5,7,9}));
            seriesRenderData.add(new SeriesRenderData("上月", new Integer[] {12,11,1,5,7,9}));
            seriesRenderData.add(new SeriesRenderData("本月", new Integer[] {5,7,1,2,7,7}));
            xsjqChart.setSeriesDatas(seriesRenderData);

            ChartMultiSeriesRenderData xsjqDeptChart = new ChartMultiSeriesRenderData();
            xsjqDeptChart .setChartTitle("各单位分布图");
            xsjqDeptChart .setCategories(new String[]{"白马","新安","青云","南门","北门","后店"});
            List<SeriesRenderData> seriesRenderDeptData = new ArrayList<>();

            seriesRenderDeptData.add(new SeriesRenderData("去年同期", new Integer[] {11,20,15,5,7,9}));
            seriesRenderDeptData.add(new SeriesRenderData("上月", new Integer[] {12,13,1,17,7,9}));
            seriesRenderDeptData.add(new SeriesRenderData("本月", new Integer[] {12,11,17,5,7,9}));
            xsjqDeptChart .setSeriesDatas(seriesRenderDeptData);

            map.put("xsjqChart",xsjqChart);
            map.put("xsjqDeptChart",xsjqDeptChart );

            template.render(map);
            template.write(outputStream);
            template.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

**Comment by Wanik666** [comment]
这是我测试的代码，多图表使用的是可选文字{{xsjqChart}}和{{xsjqDeptChart}}

**Comment by Wanik666** [comment]
![image](https://user-images.githubusercontent.com/52424325/97134370-0877eb80-1788-11eb-8f17-f18c5085e29a.png)

**Comment by begitcn** [comment]
你的模板中的图表 是不是通过excel转成的。删除模板中的图表用word自带的插入一个同类型的即可。

**Comment by Wanik666** [comment]
@begitcn 谢谢，排查后发现确实是这个原因，已经解决了
