### ISSUE TITLE
doc模板里面怎么获取list的index?需要显示序号

### ISSUE THREAD

**Issue by zhouxiaofu** [Sayi/poi-tl#479]
![image](https://user-images.githubusercontent.com/34471928/96948368-13c4e000-1518-11eb-9367-2724779f42e7.png)

![image](https://user-images.githubusercontent.com/34471928/96948410-2dfebe00-1518-11eb-9965-0af519f9b855.png)

生成后没有显示index
试过{{#index}} {{list.index}}都没用

**Comment by Sayi** [comment]
暂时没有这个功能，你可以尝试提交pull request。

**Comment by Sayi** [comment]
暂时没有这个功能，你可以尝试提交pull request。

**Comment by Sayi** [comment]
_index 下个正式版本生效。
