### ISSUE TITLE
假设有一个站点下面集合，每个站点下有很多项，但是在使用{{?experiences}}的时候，只能循环输出站点的名称

### ISSUE THREAD

**Issue by powerlisanwei** [Sayi/poi-tl#481]
假设有一个站点下面集合，每个站点下有很多项，但是在使用{{?experiences}}的时候，只能循环输出站点的名称
然后其实，每个站点下还有一层，包含文字和图片，无法显示和使用，请问如何解决

**Comment by Sayi** [comment]
没明白你说的。

**Comment by powerlisanwei** [comment]
![Uploading image.png…]()

**Comment by powerlisanwei** [comment]
> 
![1603861411(1)](https://user-images.githubusercontent.com/73545236/97394789-6b9b8680-191e-11eb-9651-c62386bb216b.jpg)
如图所示

**Comment by Sayi** [comment]
嵌套循环不会写吗？

**Comment by powerlisanwei** [comment]
每条线路下，只能输出对应的文本信息，但是每个线路每个站点下也有很多对应不用的表格数据，想请问一下有什么参考的案例

**Comment by Sayi** [comment]
循环嵌套下。
