### ISSUE TITLE
无法向word表格中插入数据参考  HackLoopTableRenderPolicy

### ISSUE THREAD

**Issue by yuanlaichengnuozhende** [Sayi/poi-tl#484]
![image](https://user-images.githubusercontent.com/45997994/97661902-9ae1fd00-1ab0-11eb-863c-b28f41db3b5a.png)
![image](https://user-images.githubusercontent.com/45997994/97665494-80ab1d80-1ab6-11eb-8d13-944ae2d70764.png)
![image](https://user-images.githubusercontent.com/45997994/97665476-738e2e80-1ab6-11eb-9575-afd46e2d03cf.png)

@Sayi

**Comment by Sayi** [comment]
自己调试下。
