### ISSUE TITLE
textbox中使用标签占位符不能全部清理

### ISSUE THREAD

**Issue by fofocx** [Sayi/poi-tl#486]
您好，在使用中发现了一处标签占位符没有完全清理的问题，
版本：1.9.0-beta(1.8.x在写入文档时遇到了 #442 问题)
问题重现：在模板文档中添加文本框，并在其中设置标签，比如为文本框增加一段多标签在一行的inline

> {{?volumes}}{{=#this}}{{/volumes}}  {{?journal}}{{?issn}}ISSN：{{=#this}}{{/issn}}{{/journal}}

当写模板后，标签并没有完全被清理掉，留下了如下内容

> 1900  {{?journal}}{{?issn}}ISSN：8848{{/issn}}{{/journal}}

观察代码DocumentProcessor 67-69行使用了

> textboxs.forEach(content -> {
>       content.getXmlObject().set(content.getCTTxbxContent());
> });

赋值解析内容到文本框，但此时占位符仍在，后续处理AbstractIterableProcessor的afterHandler方法虽然将代码run的段落进行了清除处理，但是textbox的xmlObject并未再做赋值，所以word显示内容并没有变，例子中被清除掉的volumes标签对是因为在同一行还有其它标签，处理时又走了DocumentProcessor 67-69行

**Comment by Sayi** [comment]
master已修复。
