### ISSUE TITLE
可以支持样式循环吗

### ISSUE THREAD

**Issue by memorytocode** [Sayi/poi-tl#492]
需求如下：例如我有多个子任务，任务下面有多个列表或者文本，想多个子任务的排版类型都一样，但是子任务是动态的，不清楚有多少。

**Comment by Sayi** [comment]
区块对不满足吗？

**Comment by pigzwy** [comment]
> 区块对不满足吗？

区块对支持集合的序号吗？1.name 2.name 这种

**Comment by Sayi** [comment]
每次只能使用当前Item的数据
