### ISSUE TITLE
关于自定义策略不生效的问题

### ISSUE THREAD

**Issue by dardaplanet** [Sayi/poi-tl#493]
按照付款通知单的demo,使用DetailTablePolicy生成的数据未填充到表格中,经过debug,发现数据已经生成.是不是模板的原因造成.替换成HackLoopTableRenderPolicy策略也不生效.下图是模板(demo中的模板)
![image](https://user-images.githubusercontent.com/32916396/99223803-2c2ad080-2820-11eb-885d-8e377027dc88.png)

**Comment by Sayi** [comment]
看下日志，detail_table是否绑定到具体的策略了。

**Comment by dardaplanet** [comment]
detail_table日志显示Fail introspector the property: detail_table from class entity.PaymentData, Method not found: isDetail_table,这个isDetail_table是什么用的

**Comment by dardaplanet** [comment]
![image](https://user-images.githubusercontent.com/32916396/99326591-60030600-28b3-11eb-8be4-19aa3abbdc0f.png)
策略也绑定了 Start render Template {{detail_table}}, Sign: , policy:DetailTablePolicy

**Comment by Sayi** [comment]
PaymentData类里面没有detail_table属性

**Comment by dardaplanet** [comment]
ok,可以了,通过源码发现@Name可以给属性起别名
