### ISSUE TITLE
可以提供操作图表的demo么?

### ISSUE THREAD

**Issue by changlutong** [Sayi/poi-tl#498]

**Comment by changlutong** [comment]
动物图表那个404了

**Comment by Sayi** [comment]
拼写错误了。。。https://github.com/Sayi/poi-tl/blob/v1.8.2/src/test/java/com/deepoove/poi/tl/example/AnimalExmample.java

**Comment by changlutong** [comment]
非常感谢!!!!,这个动物的word原始模板也可以发一下么?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sayi/poi-tl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 上午10:14
收件人:&nbsp;"Sayi/poi-tl"<poi-tl@noreply.github.com&gt;;
抄送:&nbsp;"花灯初夏"<756335549@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Sayi/poi-tl] 可以提供操作图表的demo么? (#498)





 
拼写错误了。。。https://github.com/Sayi/poi-tl/blob/v1.8.2/src/test/java/com/deepoove/poi/tl/example/AnimalExmample.java
