### ISSUE TITLE
单条同类数据（一个字段）使用区域块渲染等分对齐困难

### ISSUE THREAD

**Issue by oopsRookie** [Sayi/poi-tl#501]
如：
### xxxx名单（居中）
李二狗&emsp;赵铁胆&emsp;赵四
赵四&emsp;李二狗&emsp;李二狗

这样子的数据在等分一行上对齐很难处理。

试过1*1单元格设置33.33%宽度，不过单元格前后有强制换行，所以失败了。
试过文本框，不过不能解析进去。

希望作者对这种样式提供一种支持。
感谢作者的辛苦付出。

**Comment by oopsRookie** [comment]
补：我采用的是区域块 + 模板的方式来渲染数据

**Comment by Sayi** [comment]
什么是等分对齐？

**Comment by oopsRookie** [comment]
> 
> 
> 什么是等分对齐？

比如打印班级人员名单，每行显示3个名字，但人名的长度可能不是一样长的。于是同时<?list>{{name}}</list>这样是对不齐。
所以我尝试了固定宽度的word样式，不过单元格（1*1单元格首尾自动换行），文本框（无法渲染数据）。

**Comment by oopsRookie** [comment]
比如这个[名单示例](http://www.sxyqsz.cn/ewebeditor/uploadfile/20170918/20170918090555770006.png)

**Comment by Sayi** [comment]
单元格首尾自动换行是啥效果？

**Comment by oopsRookie** [comment]
感谢作者，问题在想怎么回复你的过程中解决了，当时想用 \t 来描述，于是网上发现了word中制表符，于是通过设置多个制表符解决了。万分感谢
