### ISSUE TITLE
我有个图片的集合，想一次插入word，不知道有木有支持

### ISSUE THREAD

**Issue by wr-yt** [Sayi/poi-tl#504]

**Comment by Sayi** [comment]
你猜。

**Comment by wr-yt** [comment]
我试了区块对，做了如下实现，图片要如何取出来
<img width="1157" alt="demo" src="https://user-images.githubusercontent.com/32641588/100953963-9943a300-354e-11eb-9a2c-0b493cb819d2.png">
![image](https://user-images.githubusercontent.com/32641588/100954344-58985980-354f-11eb-8846-6582be79709f.png)

**Comment by Sayi** [comment]
{{?pics}}{{@#this}}{{?pics}}
