### ISSUE TITLE
嵌套功能-无法将一个子模板生成的内容使用{{+nested}}的方式嵌入页眉，页脚

### ISSUE THREAD

**Issue by nttd-haohe** [Sayi/poi-tl#506]
业务场景：有大量模板时，页眉页脚内容相同，如果遇到需要修改的情况，需要逐个模板修改页眉页脚，工作量巨大。想用嵌套功能实现。
问题：使用嵌套时，子报表内容在其他位置可以正常显示，但是在页眉页脚中无法正常渲染。生成出来的页眉页脚保留了标签{{+nested}}原样，未被子模板填充。
请问，是否不支持在页眉页脚使用嵌套功能？
是否有其他代替手段？
[输出.docx](https://github.com/Sayi/poi-tl/files/5634602/default.docx)
[页脚模板2.docx](https://github.com/Sayi/poi-tl/files/5634603/2.docx)
[页眉模板2.docx](https://github.com/Sayi/poi-tl/files/5634606/2.docx)
[主模板2.docx](https://github.com/Sayi/poi-tl/files/5634607/2.docx)

**Comment by Sayi** [comment]
不支持。
