### ISSUE TITLE
compile之后的template不能作为单例复用渲染

### ISSUE THREAD

**Issue by yuhaofeng110** [Sayi/poi-tl#508]
@Bean
    public XWPFTemplate xwpfTemplate(){
        InputStream resourceAsStream = null;
        String apktemplatePath = "wordTemplate/apktemplate.docx";
        try{
            resourceAsStream = this.getClass().getClassLoader().getResourceAsStream(apktemplatePath);
        }catch (Exception e){
            ClassPathResource classPathResource = new ClassPathResource(apktemplatePath);
            try {
                resourceAsStream = classPathResource.getInputStream();
            } catch (IOException e1) {
                log.error("word模板读取失败",e);
            }
        }
        HackLoopTableRenderPolicy policy = new HackLoopTableRenderPolicy();
        Configure config = Configure.newBuilder()
                .bind("permInfos", policy).build();
        XWPFTemplate template = XWPFTemplate.compile(resourceAsStream,config);
        return template;
    }
这个只能渲染一次 第二次就报错了

**Comment by Sayi** [comment]
实时操作dom结构，目前无法单例，可以使用`@Scope("prototype")`
