### ISSUE TITLE
长字符串中包含\n不能实现换行

### ISSUE THREAD

**Issue by urhosts** [Sayi/poi-tl#511]
业务需求是动态拼接一字符串，并以换行符进行分割，填充到word表格中的某一个单元格呢
代码如下
`
            for(LkmMaterialBatchs batchsEntity : lists) {
                if(StringUtils.isBlank(codeStr))
                    codeStr = batchsEntity.getCode();
                else {
                    codeStr = codeStr.concat('\n' + batchsEntity.getCode());
                }
`
目前使用\n会输出□，(char)11会输出‘？’，均不能实现换行功能，请问如何解决这个问题

**Comment by Sayi** [comment]
poi-tl的版本号多少？使用最新的试试1.9.0-beta？

**Comment by urhosts** [comment]
1.5

**Comment by Sayi** [comment]
版本太老了，建议使用新版本。
