### ISSUE TITLE
请问这种表格怎么循环处理

### ISSUE THREAD

**Issue by lmh793540604** [Sayi/poi-tl#512]
![1607929660(1)](https://user-images.githubusercontent.com/40755766/102050670-355a8d80-3e1e-11eb-90be-d596b52d88a2.jpg)
请问这种表格循环如何处理，这种情况会导致原价现价循环集合的大小次。

**Comment by Sayi** [comment]
`{{goods}}` 放在循环行上一行：原价现价那一行，或者同一行(1.9.0-beta版本以后)
