### ISSUE TITLE
您好，请问如何设置chart图表标题的样式呢？

### ISSUE THREAD

**Issue by Alex-lin-yu** [Sayi/poi-tl#513]
如题，貌似即使我在模板里设置不显示标题，数据中也不进行填充，生成的word中还是会有空标题显示出来的。

**Comment by Sayi** [comment]
目前没有隐藏图标标题这个选项~~ 😢

**Comment by Sayi** [comment]
下个1.9.0正式版本 支持title为null时隐藏标题。
