### ISSUE TITLE
1.5版本报错

### ISSUE THREAD

**Issue by guohongw** [Sayi/poi-tl#515]
因项目原因引用了1.5.1版本poi-tl  poi使用3.1.7 ;在设置了使用el表达式后渲染会报错org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'appCode' cannot be found on object of type 'java.util.HashMap' - maybe not public or not valid?
,但是在我升级到1.8.0和poi-4.1.1之后就可以正常了 ,按理说低版本也应该正常,毕竟我没有使用一些特殊标签,

**Comment by Sayi** [comment]
这是低版本功能的缺失。
