### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by aaaLf** [Sayi/poi-tl#516]
后续可以支持自定义样式属性的实现嘛，比如TextRenderData里的style支持水平方向对齐

**Comment by Victoryli** [comment]
现在我也遇到这个问题

**Comment by Victoryli** [comment]
水平方向对齐 可以用CellRenderData

`  // 测试CellRenderData
TableStyle rowStyle = new TableStyle();
                rowStyle.setAlign(STJc.CENTER);
                List<CellRenderData> cells = new ArrayList<CellRenderData>();
                CellRenderData cellRenderData1 = new CellRenderData(new TextRenderData("申请\n业务\n类型 "));
                CellRenderData cellRenderData2 = new CellRenderData(new TextRenderData("000000",groupType),rowStyle);
                CellRenderData cellRenderData3 = new CellRenderData(new TextRenderData(serviceNames));
                cells.add(0,cellRenderData1);
                cells.add(1,cellRenderData2);
                cells.add(2,cellRenderData3);
                RowRenderData rowRenderData = new RowRenderData();
                rowRenderData.setCells(cells);

                rowList.add(rowRenderData) ;
 params.put("detail_table", rowList);
`

**Comment by Victoryli** [comment]
水平方向对齐可以用CellRenderData
`  // 测试CellRenderData
                TableStyle rowStyle = new TableStyle();
                rowStyle.setAlign(STJc.CENTER);
                List<CellRenderData> cells = new ArrayList<CellRenderData>();
                CellRenderData cellRenderData1 = new CellRenderData(new TextRenderData("申请\n业务\n类型 ", applyStyle));
                CellRenderData cellRenderData2 = new CellRenderData(new TextRenderData("000000",groupType),rowStyle);
                CellRenderData cellRenderData3 = new CellRenderData(new TextRenderData(serviceNames,style));
                cells.add(0,cellRenderData1);
                cells.add(1,cellRenderData2);
                cells.add(2,cellRenderData3);
                RowRenderData rowRenderData = new RowRenderData();
                rowRenderData.setCells(cells);

                rowList.add(rowRenderData) `

**Comment by Victoryli** [comment]
水平方向对齐可以用CellRenderData

` // 测试cellRenderData
                TableStyle rowStyle = new TableStyle();
                rowStyle.setAlign(STJc.CENTER);
                List<CellRenderData> cells = new ArrayList<CellRenderData>();
                CellRenderData cellRenderData1 = new CellRenderData(new TextRenderData("申请\n业务\n类型 ", applyStyle));
                CellRenderData cellRenderData2 = new CellRenderData(new TextRenderData("000000",groupType),rowStyle);
                CellRenderData cellRenderData3 = new CellRenderData(new TextRenderData(serviceNames,style));
                cells.add(0,cellRenderData1);
                cells.add(1,cellRenderData2);
                cells.add(2,cellRenderData3);
                RowRenderData rowRenderData = new RowRenderData();
                rowRenderData.setCells(cells);`

**Comment by Victoryli** [comment]
水平方向对齐可以用CellRenderData
`
                // 测试cellRenderData
                TableStyle rowStyle = new TableStyle();
                rowStyle.setAlign(STJc.CENTER);
                List<CellRenderData> cells = new ArrayList<CellRenderData>();
                CellRenderData cellRenderData1 = new CellRenderData(new TextRenderData("申请\n业务\n类型 ", applyStyle));
                CellRenderData cellRenderData2 = new CellRenderData(new TextRenderData("000000", groupType), rowStyle);
                CellRenderData cellRenderData3 = new CellRenderData(new TextRenderData(serviceNames, style));
                cells.add(0, cellRenderData1);
                cells.add(1, cellRenderData2);
                cells.add(2, cellRenderData3);
                RowRenderData rowRenderData = new RowRenderData();
                rowRenderData.setCells(cells);`

**Comment by Victoryli** [comment]
`
                // 测试cellRenderData
                TableStyle rowStyle = new TableStyle();
                rowStyle.setAlign(STJc.CENTER);
                List<CellRenderData> cells = new ArrayList<CellRenderData>();
                CellRenderData cellRenderData1 = new CellRenderData(new TextRenderData("申请\n业务\n类型 ", applyStyle));
                CellRenderData cellRenderData2 = new CellRenderData(new TextRenderData("000000", groupType), rowStyle);
                CellRenderData cellRenderData3 = new CellRenderData(new TextRenderData(serviceNames, style));
                cells.add(0, cellRenderData1);
                cells.add(1, cellRenderData2);
                cells.add(2, cellRenderData3);
                RowRenderData rowRenderData = new RowRenderData();
                rowRenderData.setCells(cells);`

**Comment by Victoryli** [comment]
// 测试cellRenderData
                TableStyle rowStyle = new TableStyle();
                rowStyle.setAlign(STJc.CENTER);
                List<CellRenderData> cells = new ArrayList<CellRenderData>();
                CellRenderData cellRenderData1 = new CellRenderData(new TextRenderData("申请\n业务\n类型 ", applyStyle));
                CellRenderData cellRenderData2 = new CellRenderData(new TextRenderData("000000", groupType), rowStyle);
                CellRenderData cellRenderData3 = new CellRenderData(new TextRenderData(serviceNames, style));
                cells.add(0, cellRenderData1);
                cells.add(1, cellRenderData2);
                cells.add(2, cellRenderData3);
                RowRenderData rowRenderData = new RowRenderData();
                rowRenderData.setCells(cells);

**Comment by Sayi** [comment]
1.9.0版本有此功能。

**Comment by aaaLf** [comment]
> 1.9.0版本有此功能。

谢谢解答，请问有没有示例呢，比如实现文字水平居中对齐

**Comment by Sayi** [comment]
自定义插件，或者继承ParagraphRenderPolicy重写下。

**Comment by aaaLf** [comment]
![image](https://user-images.githubusercontent.com/19581648/102752048-e83d6500-43a3-11eb-9c4b-547a73b46f71.png)

ParagraphRenderPolicy 中setContents(List<RenderData> contents)方法虽然写的是接口RenderData，但是实现似乎只实现了
TextRenderData和PictureRenderData，后续会支持所有RenderData嘛

> 自定义插件，或者继承ParagraphRenderPolicy重写下。
