### ISSUE TITLE
区块对中包含区块对，子区块对中含有图表，图表无法渲染

### ISSUE THREAD

**Issue by Edward-Deng** [Sayi/poi-tl#521]
模板如下：
{{?questionAnswerDetailSections}}
{{projectServiceName}}
{{?answerDetailSections}}

{{questionTitle}}
{{#questionTable}}
【这个是多系列图表】

{{/answerDetailSections}}
{{/questionAnswerDetailSections}}
其它渲染正常，到图表就报错了；

我尝试了把图表挪到外面一层，是可以渲染的；

**Comment by Sayi** [comment]
错误信息是什么？是否可以给个最小化的重现demo

**Comment by Edward-Deng** [comment]
麻烦您了，非常感谢您的帮助
测试demo在附件中
报错信息如图




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sayi/poi-tl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 下午2:13
收件人:&nbsp;"Sayi/poi-tl"<poi-tl@noreply.github.com&gt;;
抄送:&nbsp;"只是那风不曾来过"<414647688@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Sayi/poi-tl] 区块对中包含区块对，子区块对中含有图表，图表无法渲染 (#521)





 
错误信息是什么？是否可以给个最小化的重现demo

**Comment by Sayi** [comment]
没收到，要单独发邮件才行。

**Comment by Edward-Deng** [comment]
sayi@163.com这个邮箱被退回了，有其它地址吗？

**Comment by Sayi** [comment]
sayi@apache.org

**Comment by Sayi** [comment]
master已修复，下个版本发布。
