### ISSUE TITLE
HackLoopTableRenderPolicy中引用图片标签中使用区块对标签不生效

### ISSUE THREAD

**Issue by taojunnan** [Sayi/poi-tl#524]
数据源格式：
```
{
  students: [
    {
      id: 1,
      name: 'abc',
      pic: [
        {
           url: PictureRenderData()
        }
      ]
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/18263998/103124608-3fed1080-46c3-11eb-85f5-f16c5333df87.png)
![image](https://user-images.githubusercontent.com/18263998/103124666-6e6aeb80-46c3-11eb-9eb4-fe3bf33d14c3.png)

**Comment by Sayi** [comment]
谁让你在替换文字中使用区块对的，区块对拿到图片前后啊。
