### ISSUE TITLE
区块对中循环内置变量如何使用

### ISSUE THREAD

**Issue by wang-yifu** [Sayi/poi-tl#526]
_is_first、_is_last、_has_next

**Comment by Sayi** [comment]
文档里面有，和普通变量方式一样。

**Comment by Sayi** [comment]
文档里面有，和普通变量方式一样。

**Comment by wang-yifu** [comment]
> 文档里面有，和普通变量方式一样。

![image](https://user-images.githubusercontent.com/40878823/103494077-00b38200-4e70-11eb-8f64-3ef78f6f75fa.png)
![image](https://user-images.githubusercontent.com/40878823/103494095-0c9f4400-4e70-11eb-9f30-e863e4db057c.png)
是使用的问题吗？

**Comment by Irvinghua** [comment]
遍历的元素是个对象，对象有个属性比如name,要在区块对内引用本次迭代的对象该name属性该怎么用呢？
试了{{=#this.name}}   不行 打印不出来

**Comment by Sayi** [comment]
无法重现。
