### ISSUE TITLE
删除末尾的空白页。

### ISSUE THREAD

**Issue by zhaoziming-yh** [Sayi/poi-tl#530]
在生成的word中，末尾有多余的空白页，是在最后，但不是只有一页，这种情况怎么删除掉多余的空白页呢？

**Comment by Sayi** [comment]
空白页怎么出现的？

**Comment by zhaoziming-yh** [comment]
因为当时写入报告的内容是动态的，我不知道几个小标题的内容，因此预留了一些标签，空白就是未put值的标签。

**Comment by Sayi** [comment]
生成好文档之后，获取最后几个段落，删除掉。

**Comment by qqizai** [comment]
我遇到这个问题，生成后，每次都对于一页空白页。
其实多余的空白页是模板没设置好。我之前做的时候，就是特意问了我司的报告组的人，她叫我设置了：页面布局->分隔符->连续；如果还不对那你继续设置一下其他的分隔符来看看效果，总之，我好像弄好了，即模板内板块再嵌套另外一个模板，生成之后，这个内嵌的模板后不会有多余的空白页。

**Comment by Sayi** [comment]
@qqizai 你这个是分隔符导致了换页。

**Comment by zhaoziming-yh** [comment]
最后几个段落的是必须要指定的是吗，然后我生成word后去手动删除掉？

**Comment by qqizai** [comment]
> @qqizai 你这个是分隔符导致了换页。

是的，我这里要的是：内嵌的模板，是循环生成的，所以要换页，但是以前是无论多少条数据，循环后，生成的模板一定会多余页空白页；但是设置的那个之后就不会出现多余的空白页。题主的问题可以参考一下这样设置，但是如果不是翻页的话，可能达不到这种效果了。

**Comment by Sayi** [comment]
不是必须指定的吧，如果用区块对循环就不需要额外预留了。

不是手动删除，使用POI读取文档直接代码删除。

**Comment by zhaoziming-yh** [comment]
嗯嗯，我是需要判断哪些是空的段落还是要指定空段落的数量从末尾开始删除？我一会研究下区块对循环，没用过。

**Comment by zhaoziming-yh** [comment]
使用区块对能完美解决这个问题，🙏
