### ISSUE TITLE
循环输出行之间添加行内容

### ISSUE THREAD

**Issue by urhosts** [Sayi/poi-tl#531]
hi，我又来了，带着问题又来了，目前使用的1.5版本（兼容问题，迫不得已），当前遇到的问题是：
1. 表格内容需要做动态的循环输出，但是每隔几行需要做一个汇总，也就是需要每隔几行需要插入一行数据对上面几行循环输出的内容做个统计总结，同时还涉及到前几行单元格合并的问题，斗胆问一下作者是否有类似的解决方案，感谢！
如下图：
[![wLqT5.md.png](https://s3.jpg.cm/2021/01/14/wLqT5.md.png)](https://imagelol.com/image/wLqT5)
2.还有第二个问题是如上图所示的，2处换行到一下行并有单元格的合并情况下，那个单元格少下面的那条线
希望作者能给提供点改进意见，再次感谢

**Comment by Sayi** [comment]
没啥特别意见啊，文档上表格的示例有的吧。
