### ISSUE TITLE
动态表格单元格列合并问题

### ISSUE THREAD

**Issue by happygis** [Sayi/poi-tl#533]
老师你好，最近在使用该模板引擎导出报告，大大减轻了工作量，谢谢。另外在进行动态表格单元格合并过程中发现一个问题，在进行**列**合并时，可以正常导出word，打开以后也是和预想一致，单元格处于合并状态，但是如果手动在打开的word文档中稍微拖动单元格的边框，刚才合并的单元格立即就被拆分了，不知道是什么原因？

**Comment by Sayi** [comment]
poi-tl是最新版本吗？可以把生成后的word发我邮箱。

**Comment by happygis** [comment]
是1.91最新版本，我马上发

**Comment by happygis** [comment]
你好：
是用的最新的poi-tl版本，1.9.1
<dependency>

  <groupId>com.deepoove</groupId>

  <artifactId>poi-tl</artifactId>

  <version>1.9.1</version>

</dependency>，
另外我发给你的附件中out.docx就是生成后的文档。
谢谢
















在 2021-01-19 10:08:27，"Sayi" <notifications@github.com> 写道：

poi-tl是最新版本吗？可以把生成后的word发我邮箱。

**Comment by Sayi** [comment]
#105

**Comment by happygis** [comment]
感谢这么快的回复，按照你的建议处理一下
