### ISSUE TITLE
批注处理

### ISSUE THREAD

**Issue by CraftsmanHyj** [Sayi/poi-tl#534]
在说明[文档](http://deepoove.com/poi-tl/)中未找到与批注相关的操作，我想对文档中的有关批注做相应的处理，是否支持？
1、查找文档中所有批注
2、识别批注的内容、用户、时间
3、添加批注
4、删除批注

**Comment by Sayi** [comment]
暂不支持。

**Comment by StreetFlaneur** [comment]
请问下，合并文档的时候，{{+content_docx}} 把另外一个有批注的word 合并到模板文件中，使用WPS能正常打开，但是微软office打不开，有解决办法吗？
微信chaozaiai_     欢迎联系

**Comment by Sayi** [comment]
#462 下个版本支持批注。
