### ISSUE TITLE
嵌入模板为空时，导致后面需要渲染的数据渲染失败

### ISSUE THREAD

**Issue by wtNewGit** [Sayi/poi-tl#540]

**Comment by wtNewGit** [comment]
![image](https://user-images.githubusercontent.com/31918717/107141839-678ff380-6966-11eb-896e-abf3c2612e4c.png)

**Comment by wtNewGit** [comment]
发现是在嵌入模板为空时，采用DiscardHandle 这种处理异常数据方式导致，标签未被替换掉导致。

**Comment by Sayi** [comment]
版本号是多少？试试最新版本1.9.1？

**Comment by wtNewGit** [comment]
> 版本号是多少？试试最新版本1.9.1？

是的。

**Comment by wtNewGit** [comment]
> 版本号是多少？试试最新版本1.9.1？

好的。我试试

**Comment by wtNewGit** [comment]
> > 版本号是多少？试试最新版本1.9.1？
> 
> 好的。我试试

试了，是一样的。我自定义了一个 Configure.ValidErrorHandler 类型，将嵌入标签替换掉，变为正常，看源码最后发现是嵌入标签没被替换时，下次循环还会进入导致。

**Comment by wtNewGit** [comment]
> > 版本号是多少？试试最新版本1.9.1？
> 
> 好的。我试试

我的版本是1.9.0

**Comment by Sayi** [comment]
master已修复，下个版本发布。
