### ISSUE TITLE
TOCRenderPolicy使用

### ISSUE THREAD

**Issue by GitHub-Wyatt** [Sayi/poi-tl#541]
TOCRenderPolicy插件可以用了吗，有没有范例

**Comment by GitHub-Wyatt** [comment]
直接文档 {{catalog}}，然后 configureBuilder.bin("catalog", new TOCRenderPolicy())
【目录】两个字得自己写

但是生成的word会提示  【该文档包含的域可能引用了其他文件】如何处理

**Comment by Sayi** [comment]
#131
