### ISSUE TITLE
使用HackLoopTableRenderPolicy插入大量图片时内存消耗较大

### ISSUE THREAD

**Issue by honglong1987** [Sayi/poi-tl#542]
在使用HackLoopTableRenderPolicy在表中插入大量图片时内存消耗较大，能否支持在渲染的过程中按区块输出至文件，避免一次性输出时占用内存过大？

**Comment by draco1023** [comment]
虽然不知道POI本身是不是存在这个问题，但是目前的处理方法都是会将图片数据转成byte[]的方式确实会导致内存爆棚，尤其是图片本身较大时。

**Comment by Sayi** [comment]
1. 检查下图片本身的大小，是否需要提前压缩下
2. `HackLoopTableRenderPolicy` 插件的数据结构是Iterable类型，不要使用List一次性全部加载

**Comment by draco1023** [comment]
问题在于PictureRenderData的提供方式，我试过自定义渲染策略，数据仅使用图片的链接地址或者本地文件路径，在实际渲染的时候再使用流的方式读取图片数据，这样会好很多

**Comment by honglong1987** [comment]
> 1. 检查下图片本身的大小，是否需要提前压缩下
> 2. `HackLoopTableRenderPolicy` 插件的数据结构是Iterable类型，不要使用List一次性全部加载

图片是jpg格式的，每张原始图片是500KB左右；
我提供了自定义的图片渲染策略，在实际渲染的过程中读取图片，但如果表格行数比较大，图片较多时仍然会使用很多内存。

**Comment by Sayi** [comment]
最初设计成byte[]是为了复用InputStream，poitl下个版本的设计是：

> 如果图片不是直接从InputStream获取（如提供链接地址，或图片路径等），则在渲染标签的时候才会读取byte[]数组，这样可以减少不少内存。

**Comment by Sayi** [comment]
页数过多，内容过大等内存问题这是POI的本身机制问题。

https://bz.apache.org/bugzilla/show_bug.cgi?id=50993
https://bz.apache.org/bugzilla/show_bug.cgi?id=61251
