### ISSUE TITLE
你好，能否设置图表的标题样式

### ISSUE THREAD

**Issue by yakun4566** [Sayi/poi-tl#543]
我现在生成的图表的标题不是模板中设定好的样式，字号会变成18，还会自动设置为黑体。

![image](https://user-images.githubusercontent.com/18443998/108980384-94623b80-76c6-11eb-885b-c2112664b0d3.png)

![image](https://user-images.githubusercontent.com/18443998/108980468-a93ecf00-76c6-11eb-9845-a4b95bb7f95e.png)

**Comment by Sayi** [comment]
master已修复，下个版本发布。
