### ISSUE TITLE
是否支持中文字体和西文字体分别设置?

### ISSUE THREAD

**Issue by pansx** [Sayi/poi-tl#549]
需要在表格内分别设置中文和西文的字体,并且因为表格差异极大,只能使用TableRenderData来渲染不同行列数合并的表格,不能使用插件,我尝试过在{{#table}}上设置字体,但是生成的表格内全变成了默认字体...
之后尝试了设置.textFontFamily,但是只能设置中文字体,不能设置西文字体,就算字体中间加个逗号也不行,我也看了TableRenderData里没有设置西文字体的选项,是不是不支持设置西文字体啊...

**Comment by Sayi** [comment]
master已支持，下个版本发布。
