### ISSUE TITLE
请问表格渲染的时候怎么支持换页呢？

### ISSUE THREAD

**Issue by 694551594** [Sayi/poi-tl#550]
表格渲染的时候会从某一行数据开始，换到下一页接着渲染。这样的该怎么处理呢？

**Comment by Sayi** [comment]
没理解。

**Comment by 694551594** [comment]
![image](https://user-images.githubusercontent.com/17873626/110485466-a3b1a200-8126-11eb-8f5e-c17238d21ae0.png)

类似这样的。是同一个数据源，列表表头也是一样的。但是会通过某一规则将数据从某一行开始换到下一页渲染。
