### ISSUE TITLE
目录与EL表达式问题

### ISSUE THREAD

**Issue by lezoycn86** [Sayi/poi-tl#552]
HackLoopTableRenderPolicy policy = new HackLoopTableRenderPolicy();
        //目录更新
        TOCRenderPolicy tocRenderPolicy = new TOCRenderPolicy();
        Configure config = Configure.builder()
                .useSpringEL()
                .bind("catalog", tocRenderPolicy)
                .build();
这样写为啥会报这个错呢？ Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'catalog' cannot be found on object of type 'cn.hutool.core.lang.Dict' - maybe not public?

**Comment by Sayi** [comment]
useSpringEL(false)
