### ISSUE TITLE
生成的png图片 往文档中插入 图片没有插入

### ISSUE THREAD

**Issue by zhoubaishuai** [Sayi/poi-tl#556]
public static PictureRenderData pictureParse(String param, int width, int height, String path) {
        String temTxt = PhantomJsUtil.saveSurfModelUrlToImg(param);
        File file = ImageUtil.base64Decode(temTxt.replace("data:image/png;base64,", ""),
                path);
        return Pictures.ofLocal(file.getAbsolutePath()).size(width,height).create();
    }
  PictureRenderData item = TemplateUtil.pictureParse(Convert.toStr(obj), path);
 itemMap.put(value, item);
![image](https://user-images.githubusercontent.com/58590976/111608793-96767080-8814-11eb-9b25-e21b583f421c.png)
![image](https://user-images.githubusercontent.com/58590976/111608853-a3935f80-8814-11eb-80ef-b4fbcb750731.png)
![image](https://user-images.githubusercontent.com/58590976/111609029-d6d5ee80-8814-11eb-8503-1ade1d2c92f9.png)

**Comment by Sweety-Feel** [comment]
什么原因？
