### ISSUE TITLE
如何在word文档中插入骑缝章，大佬可不可以做个示例

### ISSUE THREAD

**Issue by x522491416** [Sayi/poi-tl#558]
如何在word文档中插入骑缝章，大佬可不可以做个示例

**Comment by Sayi** [comment]
你给个骑缝章的示例给我，我看看什么是骑缝章。。。

**Comment by x522491416** [comment]
https://jingyan.baidu.com/article/e5c39bf510063839d76033f5.html

**Comment by Sayi** [comment]
暂时不支持。
