### ISSUE TITLE
你好，我们在做项目时，客户提出，模板中签名必须使用必须使用一个默认图片，而不是使用{{@签发人}}这种标签的形式展示，请问poi、poitl是否能做到替换这种默认图片？

### ISSUE THREAD

**Issue by liujie1346** [Sayi/poi-tl#559]
![001](https://user-images.githubusercontent.com/27796603/112599515-00ad9780-8e4b-11eb-80d0-b5709c8c8fbb.png)

**Comment by Sayi** [comment]
有的，仔细阅读文档。
