### ISSUE TITLE
如何填充有多行的首行缩进模板

### ISSUE THREAD

**Issue by wgzhao** [Sayi/poi-tl#570]
1. 创建一个word模板文件，对其中一个变量进行格式化，选择“首行缩进”格式
2. 代码里创建一个含有多行内容的字符串，用来填充模板中的变量
3. 期望得到每个换行后的首行都应该缩进，而实际只有第一行带有缩进格式

将docx解压查看xml文件，发现正确的缩行缩进是带有一个`<w:rPr>`的标记，而普通用`\r\n` 换行，则变成了 `&#13;&#10`  符号了。

我们如何应该如何设置要写入的字符串，才能获得正确的缩进格式？

示例代码：

```java
public class DocTest
{
    public static void main(String[] args)
            throws IOException
    {
        String content = "这是一行\r这是另外一行\r这还是一行";
        XWPFTemplate template = XWPFTemplate.compile("test.docx").render(
                new HashMap<String, Object>() {{
                    put("aaa", content);
                }});
        FileOutputStream out = new FileOutputStream("output.docx");
        template.write(out);
        out.flush();
        out.close();
        template.close();
    }
}
```

word 模板见附件
[test.docx](https://github.com/Sayi/poi-tl/files/6303977/test.docx)

上述代码的结果如下图：

<img width="204" alt="image" src="https://user-images.githubusercontent.com/1001616/114559103-f6d6c180-9c9d-11eb-82f5-d3d6f8b7f1d3.png">

期望得到的结果如下：

![image](https://user-images.githubusercontent.com/1001616/114643214-d17e9d80-9d07-11eb-94df-4291762ab85a.png)

**Comment by Sayi** [comment]
使用DocumentRenderData
