### ISSUE TITLE
在做插入表格对象时，会存在文本丢失的情况

### ISSUE THREAD

**Issue by luoysuan** [Sayi/poi-tl#573]
这边有个需求就是根据模板产生对应的word文档，文档内容包括普通的文本对象和表格，在填充表格时，存在丢失数据的情况

**Comment by Sayi** [comment]
没理解你说的场景。

**Comment by luoysuan** [comment]
> 没理解你说的场景。

简单点理解 就是我这边需求要生成word文档 然后文档里面有表格需要填充 但是填充数据的时候发现会存在丢失数据的情况

**Comment by Sayi** [comment]
无法复现。
