### ISSUE TITLE
单体迁移微服务后报错

### ISSUE THREAD

**Issue by 764763903a** [Sayi/poi-tl#575]
poi-tl 版本1.9.0  尝试过1.9.1 依旧报错 
poi版本 4.1.1 尝试升级4.1.2 依旧报错
报错命令：
            Configure config = Configure.builder()
直接跳出当前方法报错，当前方法无法捕捉异常
 Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: DOUGHNUT
 .m.m.a.ExceptionHandlerExceptionResolver Resolved [org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: DOUGHNUT]

求解答

**Comment by 764763903a** [comment]
依赖冲突已经排查过一轮

**Comment by 764763903a** [comment]
this.plugin((ChartTypes)ChartTypes.DOUGHNUT, singleSeriesRenderPolicy);  DOUGHNUT无法转到

**Comment by 764763903a** [comment]
已指定poi-ooxml 为4.1.2  但是包内还是指向4.1.1

**Comment by Sayi** [comment]
你自己项目依赖的先后顺序问题。

**Comment by 764763903a** [comment]
已解决
