### ISSUE TITLE
折线图百分号格式显示为小数

### ISSUE THREAD

**Issue by larryju** [Sayi/poi-tl#582]
ChartMultiSeriesRenderData 通过方法addLineSeries时候传入Double类型的数值，图表折线图正常显示为百分号格式， 而图表下面表格中对应的数据显示为小数。点击编辑数据以后，表格中的数据才自动刷新为百分号格式。

**Comment by Sayi** [comment]
截图描述下？

**Comment by larryju** [comment]
![编辑操作](https://user-images.githubusercontent.com/18693798/117385879-76ac2080-af18-11eb-90af-5e194ae0795a.png)
![点击编辑按钮后](https://user-images.githubusercontent.com/18693798/117385880-77dd4d80-af18-11eb-9a8c-5996274c230c.png)
![模板](https://user-images.githubusercontent.com/18693798/117385882-7875e400-af18-11eb-90bd-ce2d0448e98d.png)
![输出样式](https://user-images.githubusercontent.com/18693798/117385883-790e7a80-af18-11eb-8bab-99577a44143c.png)

**Comment by Sayi** [comment]
给个能复现的最小单元测试给我吧？不好复现出来。

**Comment by larryju** [comment]
[poi-tl-test-demo.zip](https://github.com/Sayi/poi-tl/files/6476383/poi-tl-test-demo.zip)
