### ISSUE TITLE
巨头疼的问题，NoClassDefFoundError: org/apache/poi/POIXMLTypeLoader

### ISSUE THREAD

**Issue by javadoge** [Sayi/poi-tl#586]
两个现有的项目，引入1.9.1版本，都是报这个错误，NoClassDefFoundError: org/apache/poi/POIXMLTypeLoader
问题是这个类是poi-ooxml3.x版本，poitl用的ooxml都是4.x版本了，根本没有这个类，头疼大问题，不知道怎么解决

**Comment by javadoge** [comment]
大佬，4.1.2确实没有这个类啊，org/apache/poi/POIXMLTypeLoader 确实是低版本才有的，如图
![1](https://user-images.githubusercontent.com/5305836/117938286-71483f00-b339-11eb-8ed1-4a0746015e49.png)

3.x版本，如图
![2](https://user-images.githubusercontent.com/5305836/117938405-976ddf00-b339-11eb-956a-b02f366aec4b.png)

**Comment by javadoge** [comment]
> 你说反了，这个类是4.1.2中有的，你的项目依赖了低版本的poi，排除即可。

确实没有啊，如上楼评论截图

**Comment by Sayi** [comment]
项目依赖问题，使用了低版本的poi。

**Comment by javadoge** [comment]
好的
