### ISSUE TITLE
请问SpringEL 内传递的Java代码，是否可以封装为函数使用？

### ISSUE THREAD

**Issue by 1409004379** [Sayi/poi-tl#595]
### Minimal test code to reproduce the issue

```java

```

**Comment by 1409004379** [comment]
1.9.1

**Comment by 1409004379** [comment]
请教

**Comment by Sayi** [comment]
可以，com.deepoove.poi.config.ConfigureBuilder.useSpringEL(Map<String, Method>)。

或者参照SpringEL文档。
