### ISSUE TITLE
三层区块对循环，最里层包含图表，渲染时报错

### ISSUE THREAD

**Issue by fsliang** [Sayi/poi-tl#596]
模板: 其中itemChart是ChartMultiSeriesRenderData，模板里面是多系列图表
{{?array1}}

{{?array2}}

{{?array3}}

{{itemChart}}

{{/array3}}

{{/array2}}

{{/array1}}

**Comment by Sayi** [comment]
我试了下最新版本是可以的，无法重现这个问题。

**Comment by fsliang** [comment]
我用的是1.10.0-beta版本，最里层嵌入文本、表格、图片都没问题，就是图表不行，奇怪了
数据(LevelOneList)：[{"levelTwoList":[{"levelThreeList":[{"name":"111"}]}]}]
模板：
{{?LevelOneList}}
{{?levelTwoList}}
{{?levelThreeList}}
**任意插入一个图表**
{{/levelThreeList}}
{{/levelTwoList}}
{{/LevelOneList}}

**Comment by Sayi** [comment]
可以给个最小的单元测试和模板给我

**Comment by fsliang** [comment]
你好，这个是单元测试和模板

**Comment by Sayi** [comment]
没收到。

**Comment by Sayi** [comment]
已修复，下个月随着1.10.0正式版本发布。
