### ISSUE TITLE
POI版本冲突

### ISSUE THREAD

**Issue by zxf1072329029** [Sayi/poi-tl#598]
easyexcel的poi版本为3.17
poi-tl要求poi版本至少4.1.2
出现版本冲突怎么办

**Comment by Sayi** [comment]
可以使用poi-tl几年前的老版本1.5.1，不过缺少很多新特性。

**Comment by Sayi** [comment]
可以使用poi-tl几年前的老版本1.5.1，不过缺少很多新特性。
