### ISSUE TITLE
关于文本框的问题

### ISSUE THREAD

**Issue by ksyzz** [Sayi/poi-tl#60]
您好，我在使用的时候发现文本框中的内容无法被识别，请问有什么建议吗
![image](https://user-images.githubusercontent.com/26592102/40350178-92d7d2b8-5ddb-11e8-922d-46f487cf27c2.png)

**Comment by Sayi** [comment]
#33 

推荐用table布局，更专业点。

**Comment by ksyzz** [comment]
谢谢！
