### ISSUE TITLE
图片渲染不进去，文件损坏，请大佬指点迷津

### ISSUE THREAD

**Issue by Sweety-Feel** [Sayi/poi-tl#601]
渲染图片导致doc文件打不开了，确定是图片渲染问题，去掉图片渲染就没问题。
renderMap.put("signPersonName",  Pictures.ofUrl("http://deepoove.com/images/icecream.png", PictureType.PNG)
              .size(100, 100).create());

word文档里是：{{@signPersonName}}
跟字体有关系吗？？？

**Comment by Sayi** [comment]
请给个能重现这个问题的最小示例。

**Comment by Sweety-Feel** [comment]
> 请给个能重现这个问题的最小示例。

请大佬先看pom，是包的问题吗？
![image](https://user-images.githubusercontent.com/20548980/120132327-c242a900-c1fc-11eb-805e-73aa51338eda.png)

代码很简单，就是把PictureRenderData放到renderMap里，word文档里是{{@signPersonName}}，但是就渲染不进去。
代码如下
![image](https://user-images.githubusercontent.com/20548980/120132496-05048100-c1fd-11eb-9866-43d4155c263f.png)

![image](https://user-images.githubusercontent.com/20548980/120132543-19487e00-c1fd-11eb-952e-545a3b66d60c.png)

**Comment by Sayi** [comment]
只要poi-tl，其它都去掉。

**Comment by Sweety-Feel** [comment]
> 只要poi-tl，其它都去掉。

不行的，去掉其他的会报错，classNotFound，noSuchMethod等错
之前就是因为只加了poi-tl报错，然后慢慢加上正常的

**Comment by Sweety-Feel** [comment]
这应该是最小示例了，渲染不报错，渲染完文档损坏打不开了
![image](https://user-images.githubusercontent.com/20548980/120134420-a3461600-c200-11eb-8ba4-d282c7c68f65.png)

**Comment by Sayi** [comment]
去掉报错，那一定是你项目依赖有问题。

**Comment by Sayi** [comment]
你搞个只有poi-tl依赖的全新项目试试，如果有问题再来提问。

**Comment by Sweety-Feel** [comment]
> 你搞个只有poi-tl依赖的全新项目试试，如果有问题再来提问。

去掉的话就是这种报错
![image](https://user-images.githubusercontent.com/20548980/120134893-abeb1c00-c201-11eb-9285-c5fdc7d8cc49.png)
![image](https://user-images.githubusercontent.com/20548980/120134899-af7ea300-c201-11eb-92ee-88b338b227ac.png)

**Comment by Sweety-Feel** [comment]
> 你搞个只有poi-tl依赖的全新项目试试，如果有问题再来提问。

感谢大佬，搞定了，是依赖的问题
