### ISSUE TITLE
如何实现图片衬于文字下方？

### ISSUE THREAD

**Issue by yanhelin** [Sayi/poi-tl#610]
poi-tl 1.10.0

**Comment by Sayi** [comment]
引用图片标签？？？

**Comment by yanhelin** [comment]
不是引用图片标签，是使用Pictures.ofStream 创建的图片

**Comment by yanhelin** [comment]
> 引用图片标签？？？

不是引用图片标签，是使用Pictures.ofStream 创建的图片，渲染到模板里面

**Comment by jmap999** [comment]
![image](https://user-images.githubusercontent.com/30304123/123051542-7d451780-d434-11eb-9521-23ba79d5b815.png)
我也遇到这个问题：图片的 “布局选项”，选择“衬于文字下方”。使用区块对时，这个图片不会循环复制。
跟了一下代码，由于对POI不熟悉，可否提供一个思路解决这个问题呢？
![image](https://user-images.githubusercontent.com/30304123/123052284-3c99ce00-d435-11eb-86e8-877a5639edcb.png)

**Comment by wuxinbo** [comment]
可以使用图片替换功能，在图片占位符设置，到时候替换就可以。
