### ISSUE TITLE
内存泄漏 内存中存在大量的SXSSFSheet对象

### ISSUE THREAD

**Issue by wuxinbo** [Sayi/poi-tl#611]
### Issue description
 在生产环境中运行一段时间后，内存无法回收。经使用mat 内存分析工具查看，存在大量<code>org.apache.poi.xssf.streaming.SXSSFSheet</code>，同时在应用中没有使用excel渲染功能，不知道是否是渲染word时产生的对象？还望作者支持下。

### poi-tl version
   <dependency>
                <groupId>com.deepoove</groupId>
                <artifactId>poi-tl</artifactId>
                <version>1.8.1</version>
    </dependency

### Minimal test code to reproduce the issue

```java
 XWPFTemplate template =null;
        try {
            //zip 炸弹
            ZipSecureFile.setMinInflateRatio(-1.0d);
            template=XWPFTemplate.compile(templatePath,configure).render(vars);
            template.writeToFile(outputPath);
        } catch (IOException e) {
            logger.error("render template fail",e);
            return false;
        }finally {
            close(null,null,template);
        }
        return true;
```
close函数代码如下：
```java
/**
     * 关闭流，释放资源
      * @param is
     * @param outputStream
     * @param template
     */
    private void close(InputStream is,OutputStream outputStream,XWPFTemplate template){

        try {
            if (is!=null){
                is.close();
            }
            if (outputStream!=null){
                outputStream.close();
            }if (template!=null){
                template.close();
            }
        } catch (IOException e) {
            logger.error("close fail",e);

        }
    }


```

### 堆内存截图
![image](https://user-images.githubusercontent.com/7484267/122364582-76c62400-cf8c-11eb-9ff3-470a0193d893.png)

**Comment by Sayi** [comment]
word中所有图表的数据都是用excel存储的，你是不是使用了很多图表？

我怎么才能复现这个问题了？

**Comment by wuxinbo** [comment]
经过后来排查，是另一处excel导出导致的，因为导出的数量超过万条，堆内存不够用。和word渲染无关，感谢你
