### ISSUE TITLE
请问对于word中的目录级别是如何设置

### ISSUE THREAD

**Issue by leyung** [Sayi/poi-tl#615]
### Issue description
我查看之前的Issue，发现可以通过paragraphRenderData.setParagraphStyle的属性styleId实现，但是为什么我测试了一下发现没有作用。我想达到的是通过wps或者word打开对于标题的段落是有目录级别（或者标题1、2、3.。。。）
### poi-tl version
1.10.0
### Minimal test code to reproduce the issue

```java
  Map<String, Object> data = new HashMap<>();
  ParagraphRenderData paragraphRenderData = Paragraphs.of(Texts.of("标题1").create()).create();
  paragraphRenderData.setParagraphStyle(ParagraphStyle.builder().withStyleId("2").build());
  DocumentRenderData document = Documents.of()
          .addParagraph(paragraphRenderData)
          .create();
  data.put("title", document);
  Configure config = Configure.builder().bind("title", new DocumentRenderPolicy()).build();
  XWPFTemplate.compile("title.docx", config).render(data)
          .writeToFile("out_example_certificate.docx");
```
### Minimal Docx template file
{{title}}

**Comment by leyung** [comment]
已解决，需要在基础模板使用（引入）到标题1~5的段落样式才能通过styleId实现

**Comment by yun-0001** [comment]
牛逼哦！搞定啦

**Comment by fwk1010** [comment]
你好，请问【需要在基础模板使用（引入）到标题1~5的段落样式】指什么，可能有多级标题，是动态的。不能在文件里写死样式

**Comment by fwk1010** [comment]
@leyung 感谢，理解错了。是可以指定styleId来指定标题样式，可以调整模板word里来设置的对应标题样式。styleId取值参考https://github.com/Sayi/poi-tl/issues/194

**Comment by zlp8013** [comment]
大佬,如何把模板中的标题样式带到生成的目标word中?
![image](https://github.com/Sayi/poi-tl/assets/101457266/2e1a534e-0b38-43c4-99e1-39064e9c215e)

![image](https://github.com/Sayi/poi-tl/assets/101457266/2ad3eeff-a55f-4f92-8825-167144b38c53)

**Comment by fwk1010** [comment]
修改你的doc模板文件里的标题样式 @zlp8013

**Comment by smengcong** [comment]
大佬，可以解释下吗 还是有点没懂 基础模板指的是title.docx吗

**Comment by leyung** [comment]
> 大佬，可以解释下吗 还是有点没懂 基础模板指的是title.docx吗

基础模板就是你的模板文件。在你的word模板文件里面必须使用上1~5的标题（可以通过区块对隐藏），然后在模板里面自行修改每个标题的默认样式。然后通过指定段落的styleId，用这个模板生成的文件就是使用你设置的标题样式了。
