### ISSUE TITLE
word模板导出丢失边框线

### ISSUE THREAD

**Issue by owenwong** [Sayi/poi-tl#618]
### poi-tl version
1.9.0

### Issue description
windows开发环境导出是好的，就是部署到linux服务器上，导出边框线就丢失了。
word模板内容如下图：
![image](https://user-images.githubusercontent.com/31199869/124096274-025faa80-da8d-11eb-9733-27ec1a8328b8.png)
导出后如下图：
![image](https://user-images.githubusercontent.com/31199869/124096478-320eb280-da8d-11eb-9a79-5d65f99276ec.png)

**Comment by Sayi** [comment]
模板中设置下边框线。

**Comment by owenwong** [comment]
> 模板中设置下边框线。

原始模板中已经有边线了，就是在代码中再设置下边线？

**Comment by Sayi** [comment]
就在模板中重新设置下边线和边线大小。

**Comment by owenwong** [comment]
> 就在模板中重新设置下边线和边线大小。

模板重新绘制边线好了
