### ISSUE TITLE
XWPFTemplate装载了一个docx文件时，一直报错，说找不到这个方法

### ISSUE THREAD

**Issue by yuangushi** [Sayi/poi-tl#62]
XWPFTemplate template = XWPFTemplate.compile("src/main/java/template.docx");
![qq 20180524190221](https://user-images.githubusercontent.com/31124203/40481778-031350de-5f85-11e8-9f96-d4fcc186a126.png)

**Comment by yuangushi** [comment]
加一句，用的poi版本是3.10.1，poi-tl版本是1.2.0

**Comment by Sayi** [comment]
升级下poi到3.16

**Comment by Sayi** [comment]
升级poi，再引入dom4j这个包试试

**Comment by yuangushi** [comment]
之前应该是低版本的poi依赖了dom4j，我现在换成3.16版本的，然后在pom里手动dependency了一下dom4j，不再出现这个问题了
