### ISSUE TITLE
循环内置变量_index使用问题

### ISSUE THREAD

**Issue by wang-yifu** [Sayi/poi-tl#621]
### Issue description
按照实例使用_index生成序号失败。
### Minimal test code to reproduce the issue

```java
            List<String> remarkList = new ArrayList<>();
            remarkList.add("代收费包含餐费、校服费和体检费；");
            remarkList.add("上述收费标准自 2021 年 5 月 1 日起正式生效。");
            map.put("remark", remarkList);
```
### Minimal Docx template file
![image](https://user-images.githubusercontent.com/40878823/125264049-1b424880-e336-11eb-90bc-355dfc274c17.png)
![image](https://user-images.githubusercontent.com/40878823/125264093-24331a00-e336-11eb-876a-7aec81e995e8.png)
![image](https://user-images.githubusercontent.com/40878823/125264324-56dd1280-e336-11eb-99c8-df2b8cb7a8b8.png)
![image](https://user-images.githubusercontent.com/40878823/125264350-5cd2f380-e336-11eb-9163-39b8ac45cd34.png)

**Comment by Sayi** [comment]
是不是没有开启springEL？

**Comment by wang-yifu** [comment]
开启springEL后可以显示了，多谢。
