### ISSUE TITLE
关于指定字段不渲染及列表字段渲染的问题

### ISSUE THREAD

**Issue by grallcd** [Sayi/poi-tl#623]
1.实际场景：第一方开发，上传初始模版，第二方导出word（但不是全部字段，只是一些通用字段）修改大致内容，最后用户端根据用户的不同，导出对应用户的word。
问题：当第二方导出word时，有些用户端的字段不用渲染，vo对应的字段值为null，导致word中的占位符直接变成了空，这样就不能在用户端再生成word了。
建议：希望在渲染时可以指定java对象为null的字段不渲染，保留占位符。

2.如果word模版中有列表的的话，java对象不能直接用List<String> 这样的形式存储，中途还需要用Numberings.create()转化一下，这样好像有点不太方便的样子，，，

**Comment by Sayi** [comment]
1. 已经有API了，参见：[处理标签数据类型不合法的错误](http://deepoove.com/poi-tl/#_%E6%A0%87%E7%AD%BE%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B%E4%B8%8D%E5%90%88%E6%B3%95)
2. 目前需要转化的，我会考虑下怎么修改。
