### ISSUE TITLE
模板中创建了柱状图、饼图等单系列图表，如果数据查出为空的情况下生成文件时如何删除图表。

### ISSUE THREAD

**Issue by JieLum** [Sayi/poi-tl#629]
在模板docx里面创建好了柱状图、饼图等，但查询数据后生成文档发现有部分模板因为没有数据填充，导致文档生成后依然保留着模板图表，有没有办法能够在查询到无数据的情况下把模板里的某个单系列图表删除？

**Comment by Sayi** [comment]
图表放到区块对里面去。

**Comment by thirdSunShine** [comment]
> 在模板docx里面创建好了柱状图、饼图等，但查询数据后生成文档发现有部分模板因为没有数据填充，导致文档生成后依然保留着模板图表，有没有办法能够在查询到无数据的情况下把模板里的某个单系列图表删除？

这个问题你解决了 ，作者说的“图表放到区块对里面去。使用区块的if判断语法。” 我咋没明白
