### ISSUE TITLE
关于字符串中包含回车替换后不生效的问题

### ISSUE THREAD

**Issue by ccbyzc** [Sayi/poi-tl#63]
需要替换的是一段带换行的内容，替换后就无换行了，有没有解决办法？揉了下说是可以硬回车，但是看你代码runchar.那块看不太懂，不知道应该在哪里加

**Comment by Sayi** [comment]
\n 表示换行

**Comment by ccbyzc** [comment]
\n没办法换行，我用了另外的方法
							fp.removeRun(ri);
							XWPFRun nn = fp.insertNewRun(ri);
							String[] s=value.split("\n");
							for(int j=0;j<s.length;j++){
								
								nn.setText(s[j]);
								if(j!=(s.length-1)){
									nn.addBreak();
								}
								
							}
                            nn.setFontFamily(tmpstrfontfamily);
                            nn.setFontSize(tmpintfontsize);

**Comment by jackMk** [comment]
确实不生效

**Comment by Sayi** [comment]
可以提供个不生效的test case吗？

**Comment by ccbyzc** [comment]
string s="测试/n换行"

**Comment by Sayi** [comment]
"测试/n换行"  换成  "测试\n换行"吧？
