### ISSUE TITLE
图表无法生成

### ISSUE THREAD

**Issue by wenchengmao** [Sayi/poi-tl#634]
### 想问一下这个图表里面，这个可选文字在哪里呀，我用的word  @2016，windows，找不到这个可选文字，然后图表都没法替换

```java

```

**Comment by shiyun11922** [comment]
在我电脑的office2016版本没有找到这个编辑替换文字选项,最后是在布局属性里面找到的
![office2016编辑图表](https://user-images.githubusercontent.com/17243522/147634396-7e35880e-3091-4f9b-a96c-a39147bf33af.png)
wps的也就找到了.
![wps11 0 1 x编辑图表](https://user-images.githubusercontent.com/17243522/147634554-d8143f82-abdb-4aa7-bc01-21800158e977.png)
