### ISSUE TITLE
是否支持 RenderPolicy.render() 函数中从 Data-Model 中直接取值？

### ISSUE THREAD

**Issue by sjr7** [Sayi/poi-tl#637]
**poi-tl version:** 1.10.0

**问题描述:**   
word 模版如图所示: 
![image](https://user-images.githubusercontent.com/17400895/128976297-2486f54a-b6a1-4109-9861-9180228b5e5b.png)

我们目前在模版中定义了如上面的模版内容，作用是为了无论 desc 变量无论是几个字还是几十个字，**原因描述** 都是可以占满3 行的对齐的。因此我们自定义一个插件，想直接从传入的  map 参数中进行取值，根据官网文档中插件例子写出以下代码:  

传入参数如下: 
````java
 Map<String, Object> map = new HashMap<String, Object>() {
            {
                put("desc", "这里是测试描述");
            }
        };
````

插件代码 : 

```` java

public class CustomerTextBizRenderPolicy implements RenderPolicy {

  @Override
  public void render(ElementTemplate eleTemplate, Object data, XWPFTemplate template) {
    // 由于占位符是 {{desc_______________}} 这种，在执行 renderDataCompute.compute(eleTemplate.getTagName()) 时取到的值一直都是空的 ,  此处是否支持直接获取传入的 map 对象？
  }
}

````

请问针对这种场景是否有好的解决方法 ?

**Comment by Sayi** [comment]
可以直接把map传到CustomerTextBizRenderPolicy这个类里面。
