### ISSUE TITLE
用libreoffice打开poi-tl生成的文档无法显示表格里的合并单元格

### ISSUE THREAD

**Issue by jevislee** [Sayi/poi-tl#638]
### Issue description
用libreoffice打开poi-tl生成的文档无法显示表格里的合并单元格
单元格依然显示为未合并,请问有解决方法吗?

### poi-tl version
1.9.1

### Minimal test code to reproduce the issue

```java

```

**Comment by Sayi** [comment]
生成后的文档发我邮箱。
