### ISSUE TITLE
图片文件无法删除

### ISSUE THREAD

**Issue by taojinjing** [Sayi/poi-tl#64]
模板文件加载外部图片后，图片资源似乎没有被释放，无法删除。代码类似：

XWPFTemplate template = XWPFTemplate.compile(....);
try (FileOutputStream out = new FileOutputStream(file)) {
            .....
            template.render(datas);
            template.write(out);
        } finally {
            if (template != null) {
                template.close();
            }
        }

**Comment by taojinjing** [comment]
用这个接口会有问题：
public PictureRenderData(int width, int height, String path) 
用这个接口是好的：
public PictureRenderData(int width, int height, String path, byte[] data)

**Comment by Sayi** [comment]
1.3.0版本已修复。
