### ISSUE TITLE
SpringEL表达式会占用行，导致Word中有空格

### ISSUE THREAD

**Issue by zhou999264** [Sayi/poi-tl#640]
> 使用SpringEL表达式会出现空白行，有没有好的办法解决  poi-tl版本：1.8.1
![1](https://user-images.githubusercontent.com/17946599/129323665-0402d615-d7ce-42ab-8fb2-a5e271e4bf94.png)
![2](https://user-images.githubusercontent.com/17946599/129323669-381a4cba-be9f-47c6-a5a9-0f16050d1178.png)

**Comment by Sayi** [comment]
@zhou999264 Hi，可以把模板发我邮箱吗？

**Comment by zhou999264** [comment]
可以的，期待您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sayi/poi-tl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sayi/poi-tl] SpringEL表达式会占用行，导致Word中有空格 (#640)





 
@zhou999264 Hi，可以把模板发我邮箱吗？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sayi** [comment]
没收到。sayi90@163.com

**Comment by zhou999264** [comment]
> 没收到。[sayi90@163.com](mailto:sayi90@163.com)

发错邮箱了，已经发送至您的163邮箱。

**Comment by Sayi** [comment]
试了下，我用的最新版本，没有重现你的问题。
![image](https://user-images.githubusercontent.com/1394854/129694695-dbaf48aa-9fc8-43d7-9c63-aed5c904ca3c.png)

**Comment by zhou999264** [comment]
> 试了下，我用的最新版本，没有重现你的问题。
> ![image](https://user-images.githubusercontent.com/1394854/129694695-dbaf48aa-9fc8-43d7-9c63-aed5c904ca3c.png)

我更新一下版本，再试一下吧
