### ISSUE TITLE
表格列循环问题

### ISSUE THREAD

**Issue by javadoge** [Sayi/poi-tl#643]
表格列循环怎么只循环表格中的指定某几行？现在把所有行都循环了

**Comment by javadoge** [comment]
[
https://000000-huan-saas.oss-cn-beijing.aliyuncs.com/upload/20210510/111.png](url)

**Comment by javadoge** [comment]
![2](https://user-images.githubusercontent.com/5305836/130026818-e286f2f4-6407-439c-982b-3729efd80f93.png)
![1](https://user-images.githubusercontent.com/5305836/130026828-5eadc662-69df-4e12-9ec3-50d93fd01914.png)

**Comment by javadoge** [comment]
大佬 有时间可否帮看下 这个问题怎么解决？

**Comment by Sayi** [comment]
当前列都会被循环。
