### ISSUE TITLE
文本字符串替换突然不生效的问题

### ISSUE THREAD

**Issue by Fengjiya** [Sayi/poi-tl#65]
文本字符串不生效：
简单的字符串文本无法替换
前两天还可以正常显示，后来将word中文本周边的文字去掉一些后，文本替换无法生效。

```java
 Map<String, Object> data = new HashMap<String, Object>() {
            {
//                put("BVersion_Severity_Table_Analysis", anaInfo);
//                put("BVersion_Severity_Table_abc", "我为什么一直出不来");
                put("BVersion_Severity_Table_Analysis", new TextRenderData("我为什么一直出不来"));
            }
        };
```

其中，Word文件经过多次编辑并保存，不知道（当然替换的吧标签是没有动的）这个的影响。

**Comment by Sayi** [comment]
Word文件经过多次编辑并保存 这个并不会影响。能影响到的只有标签。

建议你写一个junit的测试用例，这样更方便我来重现你的问题。

**Comment by Fengjiya** [comment]
问题已经解决，但是发现规律了，以下为问题代码：
` List<Map<String, Object>> dataList = GetDataList();  //将模板中所有需要替换的内容做好替换准备
        Map<String, Object> data = new HashMap<>();

        XWPFTemplate template = XWPFTemplate.compile(sdv_report_template);

        //将模板里面的所有标签都替换完毕
        for (int i = 0; i < dataList.size(); i++) {
            data = dataList.get(i);
            template = template.render(data); //将Word里面的内容循环替换
        }
`
按照如上代码，里面所有的文本标签{{XXX}}基本全部失效。

`       XWPFTemplate template = XWPFTemplate.compile(sdv_report_template);

        //将模板里面的所有标签都替换完毕
        for (int i = 0; i < dataList.size(); i++) {
            data.putAll( dataList.get(i));
        }

        template.render(data);`

这样就是OK的，就是template循环调用的时候有问题。

**Comment by Sayi** [comment]
使用问题，所有数据集作为参数，XWPFTemplate.compile调用一次就可以了。

**Comment by Fengjiya** [comment]
这个地方应该还是有些问题的，数据集较少的时候调用正常，多了才出现了问题。
