### ISSUE TITLE
锚点文本如何扩展指向图片

### ISSUE THREAD

**Issue by gaozhenpeng** [Sayi/poi-tl#652]
### Issue description
put("anchor", new HyperlinkTextRenderData("anchortxt", "anchor:appendix1"));
锚点现在是指向一个文本，请问我怎么扩展可以让它指向一张图片？
### poi-tl version
1.10.0
### Minimal test code to reproduce the issue

```java
jdk1.8
```

**Comment by Sayi** [comment]
创作一个图片书签，然后锚点指向它即可。

图片书签可以参考文本书签的写法，参考：BookmarkRenderPolicy。
