### ISSUE TITLE
请问如何循环生成表格

### ISSUE THREAD

**Issue by likedeke** [Sayi/poi-tl#653]
![image](https://user-images.githubusercontent.com/65269574/132192680-9b52f793-8503-48b1-8413-afed4f3c7846.png)
如上图，每个3.1、3.2、3.3...~3.n都代表一个表格，请问如何循环生成？

**Comment by Sayi** [comment]
区块对。

**Comment by likedeke** [comment]
> 区块对。

ok，最后我用的poi原生的。
