### ISSUE TITLE
如和获取表格中设置的列标签

### ISSUE THREAD

**Issue by EdenSun** [Sayi/poi-tl#655]
你好，我想要获取文档中的所有标签，包括表格每一列的标签（如 [column_name1] )

通过调用 XWPFTemplate的getElementTemplates() 只能获取到表格对应的标签（如{{ table_name }}）。是否有办法可以获取每一列设置的标签？

XWPFTemplate template = XWPFTemplate.compile(filePath);
List<MetaTemplate> metaTemplates = template.getElementTemplates();

for(MetaTemplate metaTemplate : metaTemplates) {
	System.out.println(metaTemplate.variable());
}

输出结果为：
{{billLadingNumber}}
{{commodities}}
{{receiverCompany}}
{{shippingAddress}}
{{receiver}}
{{receiverPhone}}
{{deliveryDate}}

其中commodities为表格，希望获取表格的每一列的标签名称

**Comment by Sayi** [comment]
auto closed.
