### ISSUE TITLE
使用雷达图时，用wps能打开，word打不开

### ISSUE THREAD

**Issue by commonStan** [Sayi/poi-tl#657]
[](url)### Issue description

### poi-tl version
1.10.0

### Minimal test code to reproduce the issue
public void export() throws IOException {
        XWPFTemplate template = XWPFTemplate.compile("/Users/mr/Documents/doc/template/test-template.docx").render(
                new HashMap<String, Object>() {{
                    put("chart", Charts.ofRadar("雷达图A", new String[]{"综合", "KDA", "发育", "推进", "生存", "输出"})
                            .addSeries("SPP", new Number[]{42.1, 36.2, 50.9, 52.3, 41.9, 35.4})
                            .create());
        template.writeAndClose(new FileOutputStream("/Users/mr/Documents/doc/template/output1.docx"));
    }
### Minimal Docx template file

**Comment by commonStan** [comment]
https://github.com/commonStan/template/blob/main/test-template.docx

**Comment by Sayi** [comment]
已修复。
