### ISSUE TITLE
Markdown转word时报NoSuchMethodError

### ISSUE THREAD

**Issue by ww920623** [Sayi/poi-tl#658]
Markdown转word时报NoSuchMethodError
使用版本：com.deepoove:poi-tl:1.10.0   
com.deepoove:poi-tl-plugin-markdown:1.0.2
![image](https://user-images.githubusercontent.com/40558028/133360806-5159dc70-7dbf-464e-a4a6-14c0926a302e.png)

**Comment by Sayi** [comment]
master已经修复了，我会在最近发布上线一个版本，可能是1.10.1。

**Comment by Sayi** [comment]
master已经修复了，我会在最近发布上线一个版本，可能是1.10.1。

**Comment by ww920623** [comment]
> master已经修复了，我会在最近发布上线一个版本，可能是1.10.1。

大概什么时候发布版本呀。能不能做一个html写word的呢？
