### ISSUE TITLE
请问使用区块对时怎么样才能不出现空白行

### ISSUE THREAD

**Issue by bonesliu** [Sayi/poi-tl#659]
### Issue description
当section=false时，会多一个空白行
### Minimal Docx template file
第一页内容
---------分页符------------
{{?section}}
第二页内容
{{/section}}
其它内容

**Comment by Sayi** [comment]
![image](https://user-images.githubusercontent.com/1394854/140003873-8b05d916-81bf-4f5b-9d59-eab85b136590.png)

你换行符用错了，“其它内容”这一行和上面是同一行，所以不会删除空行，你换个换行符就没有空行了。
