### ISSUE TITLE
想请教下，表格行循环时，数据模型里字段可能不存在，怎么写模板才能正常展示？

### ISSUE THREAD

**Issue by kola110** [Sayi/poi-tl#669]
### Issue description
使用LoopRowTableRenderPolicy，模板如下：
**{{datas}}  [a]  [b]**  
当传入的对象不包含b，怎么写才能正常渲染？现在是提示EL1008E: Property or field 'b' cannot be found on object of type 'java.util.HashMap' - maybe not public or not valid?

谢谢
### poi-tl version
1.10.1
### Minimal test code to reproduce the issue

```java

```

**Comment by Sayi** [comment]
http://deepoove.com/poi-tl/#_%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86

**Comment by kola110** [comment]
不好意思，看文档已经看到了，来关issue了，感谢回复。
builder.useSpringEL(true);
