### ISSUE TITLE
图片文件不存在，模板标签不会自己删除

### ISSUE THREAD

**Issue by issac21** [Sayi/poi-tl#67]
情景：使用图片模板{{@picture}}, 然后 map.put("picture", new PictureRenderData(570, 380, imgPath));

如果imgPath 文件路径的文件是不存在的，生成出来的文档中{{@picture}}还是存在，如果让它消失或者替换成指定的文字（例如：图片不存在）

当然，可能自己去重写PictureRenderPolicy可以实现，但不知道作者是否有更好的方法

**Comment by Sayi** [comment]
现在没有更好的办法。

让它消失这个功能可以放到源码里，下个版本修改下PictureRenderPolicy，也欢迎Pull Request~

**Comment by Im-cbird** [comment]
@issac21 
这个可以先读取文件流，然后判断一下
if (null == imgBytes) {
	imgData = new PictureRenderData(0, 0, ".jpg", new byte[0]);
       //new byte[0] : 去除标记（参数为null时导出标记仍存在），亲测可用
}
ps: 第一次发言，好激动！！讲真的，这个自定义表格太厉害了，膜拜作者

**Comment by herowzz** [comment]
#98 已修复
