### ISSUE TITLE
word里面的表格数据循环嵌套

### ISSUE THREAD

**Issue by freshbin** [Sayi/poi-tl#670]
请问一下，有人知道怎么实现word里面的表格数据循环嵌套吗？
比如类似下面的数据结构去组装表格，现在是rows可以遍历出每一行的数据，但是list那个集合没办法再遍历每一列的数据
{
	"rows": [{
			"content": "第一行第一列数据",
			"list": [{
					"value": "第一行第二列数据"
				},
				{
					"value": "第一行第三列数据"
				}
			]
		},
		{
			"content": "第二行第一列数据",
			"list": [{
					"value": "第二行第二列数据"
				},
				{
					"value": "第二行第三列数据"
				}
			]
		}
	]
}

**Comment by Sayi** [comment]
自定义插件。
