### ISSUE TITLE
目录后循环模板无法解析

### ISSUE THREAD

**Issue by version2017** [Sayi/poi-tl#673]
### Issue description
使用过程中发现一个比较诡异的问题，翻阅了部分源码加上不断尝试终于解决。从代码上看错误发生在深层次的地方，特此记录分享，看是否能在框架层面解决。
在使用SpringEL表达式标签对渲染word数据时，发现当word中模板代码“{{?test.problems}}...{{/}}”放在目录（固定的模板目录）**之后**时数据未成功渲染，一直循环第一项元素，结果如下图：
![1](https://user-images.githubusercontent.com/25169053/137099498-7a307e52-4eaa-44da-8b75-02f4fc9edbec.jpg)
当word中模板代码“{{?test.problems}}...{{/}}”放在目录（固定的模板目录）**之前**时数据成功渲染，结果如下图：
![2](https://user-images.githubusercontent.com/25169053/137099643-49536205-9871-44d9-b819-be6ccb33f363.jpg)

### Issue reason
IterableProcessor解析那三行模板代码时，会先找到结束标签"{{/}}"，然后在该标签前循环插入"问题{{_index+1}}：{{problem}}"。然后再渲染数据。而当模板代码放到目录之后时，会导致结束标签段落查找错误，插入位置产生异常，继而出现上面的现象。
![3](https://user-images.githubusercontent.com/25169053/137101890-132bcec6-c79e-4733-8d86-5c40ec7a1b5e.jpg)

### Solution
使用“.bind("datalog", new TOCRenderPolicy())”将目录从固定的模板改为动态渲染

### poi-tl version
1.9.1
### word version
专业增强版 2016
### Minimal test code to reproduce the issue

```java
class TestObj{
    private List<ProblemObj> problems
}
class ProblemObj{
    private String problem;
}
```
### Minimal Docx template file  
**注意**：必须是如下的三行格式，因为如果放一行解析时用的是InlineIterableTemplate，而三行用的是IterableTemplate
{{?test.problems}}
问题{{_index+1}}：{{problem}}
{{/}}

**Comment by Sayi** [comment]
这个需要 @version2017 提供下出问题的模板才能解决呢！

**Comment by version2017** [comment]
我的测试代码如下：
```
@Test
public void testNestedBlock() throws Exception {
	class TestObj{
		String name;
		public TestObj(String name) {
			this.name = name;
		}
	}
	class WrapperObj{
		String title = "Hello, poi tl.";
		List<TestObj> testObjs = Arrays.asList(new TestObj("***第一项数据***"), new TestObj("***第二项数据***"),
			new TestObj("***第三项数据***"));
	}
	WrapperObj data = new WrapperObj();

	XWPFTemplate template = XWPFTemplate.compile(resource, builder.build());

	template.render(data);
	template.write(new FileOutputStream("C:\\Users\\roger.wu\\Desktop\\Test\\test.docx"));

	XWPFTemplate renew = XWPFTestSupport.readNewTemplate(template);
        //assertEquals(renew.getElementTemplates().size(), 0);
	renew.close();

}
```

[issue_test.docx](https://github.com/Sayi/poi-tl/files/7623294/issue_test.docx)

**Comment by version2017** [comment]
> 这个需要 @version2017 提供下出问题的模板才能解决呢！

我的测试代码如下：
```
@Test
public void testNestedBlock() throws Exception {
	class TestObj{
		String name;
		public TestObj(String name) {
			this.name = name;
		}
	}
	class WrapperObj{
		String title = "Hello, poi tl.";
		List<TestObj> testObjs = Arrays.asList(new TestObj("***第一项数据***"), new TestObj("***第二项数据***"),
			new TestObj("***第三项数据***"));
	}
	WrapperObj data = new WrapperObj();

	XWPFTemplate template = XWPFTemplate.compile(resource, builder.build());

	template.render(data);
	template.write(new FileOutputStream("C:\\Users\\roger.wu\\Desktop\\Test\\test.docx"));

	XWPFTemplate renew = XWPFTestSupport.readNewTemplate(template);
        //assertEquals(renew.getElementTemplates().size(), 0);
	renew.close();

}
```

[issue_test.docx](https://github.com/Sayi/poi-tl/files/7623359/issue_test.docx)

**Comment by Sayi** [comment]
#914
