### ISSUE TITLE
文档合并 堆内存溢出

### ISSUE THREAD

**Issue by Levan1** [Sayi/poi-tl#677]
版本：1.10.0
关键代码行：
com.deepoove.poi.xwpf.XmlXWPFDocumentMerge.java
public NiceXWPFDocument merge(NiceXWPFDocument source, Iterator<NiceXWPFDocument> mergeIterator, XWPFRun run)
            throws Exception {}

只要合并的第一个docx文件大于130m，必定会内存溢出，看了源码应该可以修复

**Comment by Sayi** [comment]
#329
