### ISSUE TITLE
请问怎么在动态列表的时候设置跨页重复表格头

### ISSUE THREAD

**Issue by duojiuhuitoui** [Sayi/poi-tl#678]
我想问一下怎么在LoopRowTableRenderPolicy插件设置跨页重复表格头

**Comment by Sayi** [comment]
![image](https://user-images.githubusercontent.com/1394854/142802622-2bafbcaa-d1b7-4b4d-965d-e8e29e33abf2.png)

模板中直接选中表格头可重复就可以了。
