### ISSUE TITLE
关于TOCRenderPolicy的使用

### ISSUE THREAD

**Issue by ChesterXi** [Sayi/poi-tl#679]
### Issue description
根据[issue514](https://github.com/Sayi/poi-tl/issues/541)中TOCRenderPolicy的实例，无法自动生成目录。
能否给一个TOCRenderPolicy的完整示例
### poi-tl version
1.10.0
### Minimal test code to reproduce the issue

```java
            Map<String, Object> data = new HashMap<>();
            data.put("title", document);
            Configure config = Configure.builder().bind("title", new DocumentRenderPolicy()).bind("catalog", new TOCRenderPolicy()).build();
            XWPFTemplate.compile("title.docx", config).render(data)
                    .writeToFile("out_example_certificate.docx");
```
### Minimal Docx template file
word文档
![image](https://user-images.githubusercontent.com/42727470/141131726-deba2498-8378-4342-93c7-06ad0f25a72f.png)

**Comment by Sayi** [comment]
#541

**Comment by zhanhui1999** [comment]
你好，请问解决了嘛
