### ISSUE TITLE
Policy的参数希望能支持把datas传入，RULER_REGEX希望能支持自定义

### ISSUE THREAD

**Issue by orxissi** [Sayi/poi-tl#68]
想要能自己定义一套模板例如{{E[a.b.c]}}，E是标记，中括号内容为模板（里面可以自定义一些规则），需要先解析一下再从datas里面取值，自己定义取值的方式
现在想复写XWPFTemplate也没办法复写

**Comment by Sayi** [comment]
目前没有办法做到自定义取值的扩展。

只能fork代码去修改了。
