### ISSUE TITLE
生成的表格office2019跟wps2019不兼容

### ISSUE THREAD

**Issue by sinosofti** [Sayi/poi-tl#680]
### Isue description
如题本人用office2019做的模板生成的表格office2019打开完美但是用wps打开表格就会占满请问有什么解决办法吗

### Minimal Docx template file
![Snipaste_2021-11-11_15-05-44](https://user-images.githubusercontent.com/38282416/141253505-07f52bc0-5826-4bf5-9d16-eb694337677b.png)
)

**Comment by sinosofti** [comment]
![Snipaste_2021-11-11_15-09-16](https://user-images.githubusercontent.com/38282416/141253744-8fe8ff5d-c93c-421e-a9a7-24a674e6e5e2.png)
此图为office2019打开正常的表格

**Comment by sinosofti** [comment]
表格列是动态的自适应能让部分列宽一点也可以

**Comment by Sayi** [comment]
模板中可以限制一下列宽

**Comment by sinosofti** [comment]
就是限制了列宽之后 才有的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月22日(星期一) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sayi/poi-tl] 生成的表格office2019跟wps2019不兼容 (Issue #680)





 
模板中可以限制一下列宽
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sayi** [comment]
表格宽，列宽都限制下，如果还不行，那就是wps的问题了。。。

**Comment by sinosofti** [comment]
限制之后发现wps的表格跟office表格宽是不一样的 然后wps重新设置表格属性 表格宽 才会跟office的表格一致




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月22日(星期一) 下午3:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sayi/poi-tl] 生成的表格office2019跟wps2019不兼容 (Issue #680)





 
表格宽，列宽都限制下，如果还不行，那就是wps的问题了。。。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sayi** [comment]
或者反过来，你的模板直接就用wps调整，比如看下数据填满的情况下调整下模板。

**Comment by sinosofti** [comment]
wps做的表格模板如下&nbsp;






word如下





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sayi/poi-tl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sayi/poi-tl] 生成的表格office2019跟wps2019不兼容 (Issue #680)





 
或者反过来，你的模板直接就用wps调整，比如看下数据填满的情况下调整下模板。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
