### ISSUE TITLE
可以用ListRenderPolicy插件(或者其他插件)动态遍历生成标题吗（不使用占位符生成）

### ISSUE THREAD

**Issue by yun-0001** [Sayi/poi-tl#682]
List<Object> list = new ArrayList<>();
        ParagraphRenderData paragraphRenderData = Paragraphs.of(Texts.of("标题5").create()).create();
        paragraphRenderData.setParagraphStyle(ParagraphStyle.builder().withStyleId("5").build());
        DocumentRenderData document = Documents.of()
                .addParagraph(paragraphRenderData)
                .create();
        list.add(document);
        resMap.put("list", list);
        ListRenderPolicy policy = new ListRenderPolicy();
        Configure config = Configure.builder()
                .bind("list", policy)
                .build();
        XWPFTemplate template = XWPFTemplate.compile("",config).render(resMap);

**Comment by Sayi** [comment]
这个写个插件就行了，很简单。

标题就使用`ParagraphStyle.builder().withStyleId("5").build()`即可。
