### ISSUE TITLE
当使用区块对包含多个标签后，某个标签为空时，出现多余空行能处理掉吗？

### ISSUE THREAD

**Issue by imlzw** [Sayi/poi-tl#683]
当使用区块对包含多个标签后，某个标签为空时，出现多余空行能处理掉吗？
比如如下代码：
{{?list}}
{{name}}
{{@avatar}}
{{/list}}
当list数据中有的项包含avatar图片，有的没有avatar图片，没有avatar图片数据为变成空行，能否把这个空行给去除掉吗？

**Comment by Sayi** [comment]
这个版本试试  #687 这里面的方法，配置下错误处理器。
