### ISSUE TITLE
多系列图表水平轴文本框“文字方向”自动改变

### ISSUE THREAD

**Issue by lanlanfox** [Sayi/poi-tl#684]
### Issue description
多系列图表水平轴文本框“文字方向”自动改变
模版中：
![image](https://user-images.githubusercontent.com/41501540/141808132-a340a444-d997-41aa-8d59-2982f5c825e2.png)

添加数据后：
![image](https://user-images.githubusercontent.com/41501540/141808278-44133a15-ab13-4618-be96-137fb4dfb3d2.png)

### poi-tl version
1.10.0
### Minimal test code to reproduce the issue

```java

```

**Comment by Sayi** [comment]
无法重现。
