### ISSUE TITLE
{{?template}}中间是表格{{/template}} 出现多余的空行

### ISSUE THREAD

**Issue by ouyang2312** [Sayi/poi-tl#687]
一个Word文档上有100多个表，从template1到tempalte100 ，1-100中，给了某些template数据（比如只给了1-10的数据），就渲染这10个template，但是最后渲染出来的文档，10个表格中，每2个表格中间出现的空行可能是1行 可能是2行。也就是说 空行有点随机。

**Comment by Sayi** [comment]
当前版本需要配置下错误处理器：
```java
ConfigureBuilder builder = Configure.builder();
builder.setValidErrorHandler(new ValidErrorHandler() {
    
    @Override
    public void handler(RenderContext<?> context) {
        XWPFRun run = context.getRun();
        BodyContainer bodyContainer = BodyContainerFactory.getBodyContainer(run);
        bodyContainer.clearPlaceholder(run);
    }
});
```

**Comment by ouyang2312** [comment]
好 谢谢 我下午试试


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sayi/poi-tl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 中午11:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sayi/poi-tl] {{?template}}中间是表格{{/template}} 出现多余的空行 (Issue #687)





 
Closed #687.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ouyang2312** [comment]
你好，刚才试了 配置了这个错误处理器，文档还是一样 空行多了几个









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sayi/poi-tl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sayi/poi-tl] {{?template}}中间是表格{{/template}} 出现多余的空行 (Issue #687)





 
当前版本需要配置下错误处理器：
 ConfigureBuilder builder = Configure.builder(); builder.setValidErrorHandler(new ValidErrorHandler() {          @Override     public void handler(RenderContext<?&gt; context) {         XWPFRun run = context.getRun();         BodyContainer bodyContainer = BodyContainerFactory.getBodyContainer(run);         bodyContainer.clearPlaceholder(run);     } });
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sayi** [comment]
poi-tl版本是多少？我这边重现不了，你可以有空把模板和生成的文档发给我邮箱（sayi90 at 163.com)

**Comment by ouyang2312** [comment]
这个模板不能发出去，这是公司的。模板大概就是这样的{{/template1}}
表格（随便弄一个3*4的）
（这行是空行）
{{?template1}}


{{/template2}}
表格（随便弄一个3*4的）
（这行是空行）
{{?template2}}


.... 一直加，弄了100多个，Word页数是27页左右


我只给了template20 template80的数据进去，渲染出来20 和 80的数据，预想结果是
----------中间是Word内容-----------
表格20
（这里空一行）
表格80
（这里空一行）
----------中间是Word内容-----------


实际结果是
----------中间是Word内容-----------
表格20
（这里空一行）
（这里空一行）
（这里空一行）
（这里空一行）
表格80
（这里空一行）
（这里空一行）
----------中间是Word内容-----------


空行多了。


我现在是等渲染完成，再用poi二次处理 把没用的空行删除了。


poi tl 版本是
<dependency&gt;
    <groupId&gt;com.deepoove</groupId&gt;
    <artifactId&gt;poi-tl</artifactId&gt;
    <version&gt;1.8.2</version&gt;
</dependency&gt;








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月22日(星期一) 下午3:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sayi/poi-tl] {{?template}}中间是表格{{/template}} 出现多余的空行 (Issue #687)





 
poi-tl版本是多少？我这边重现不了，你可以有空把模板和生成的文档发给我邮箱（sayi90 at 163.com)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sayi** [comment]
可能是版本太老了，最新版本我重现不了你的问题。

**Comment by ouyang2312** [comment]
好，那我升级一下版本，谢谢了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月22日(星期一) 下午3:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sayi/poi-tl] {{?template}}中间是表格{{/template}} 出现多余的空行 (Issue #687)





 
可能是版本太老了，最新版本我重现不了你的问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
