### ISSUE TITLE
根据一个模板生成多份数据进行合并

### ISSUE THREAD

**Issue by likeflower950** [Sayi/poi-tl#688]
### 
使用 poi-tl 我们可以将一个Map对象根据模板文件，生成一个word文档。但是我现在有一个场景是这样的，比如一个班级有30个学生，每个学生有一份成绩单。我只需要一个模板就可以了，我期望的是传入的参数是 List<Map> 类型， Map是一个学生的数据，List是所有学生的数据，这样在word文档里面重复性的生成一个word，里面包含了30个学生的数据，每个学生占一页

```java

```

**Comment by gudqs7** [comment]
http://deepoove.com/poi-tl/#_%E5%B5%8C%E5%A5%97
@likeflower950 你看看这个可以实现你的需求吗? 我理解ok的
每个学生占一页这个要你自己控制好 模板的内容刚好是一页.

**Comment by Sayi** [comment]
楼上正解，老版本用嵌套就可以了，新版本用区块对循环。
