### ISSUE TITLE
可以增加富文本信息识别功能吗

### ISSUE THREAD

**Issue by lurunfa** [Sayi/poi-tl#69]
最近做的一个功能需求，将存在数据库中的富文本数据导出到word，看能不能在渲染的时候增加此功能

**Comment by Sayi** [comment]
poi-tl提供了一个模板引擎的功能。

你说的问题重点应该在富文本到word的转化吧？

**Comment by lurunfa** [comment]
是的 比如html的标签 和属性转换到word

**Comment by Sayi** [comment]
[自己写个插件](http://deepoove.com/poi-tl/#_%E6%8F%92%E4%BB%B6%E6%9C%BA%E5%88%B6plugin_mechanism)
