### ISSUE TITLE
OOXML: ECMA-376 下载地址 - 详细的 xml 含义解读 (英文)

### ISSUE THREAD

**Issue by gudqs7** [Sayi/poi-tl#693]
### OOXML: ECMA-376 下载地址 - 详细的 xml 含义解读 (英文)

下载页面:
https://www.ecma-international.org/publications-and-standards/standards/ecma-376/

最新一版下载链接:
https://www.ecma-international.org/wp-content/uploads/ecma-376_fourth_edition_december_2012.zip

很详细的文档, 可惜是英文.....

**Comment by Sayi** [comment]
不是Issue，先关闭了。
