### ISSUE TITLE
compile template failed

### ISSUE THREAD

**Issue by LikeASycamore** [Sayi/poi-tl#694]
### 错误描述
idea用插件打包项目后在windows服务器上运行，编译模板时，报“compile template failed”。这个时候是拿到了文件的，所以是模板有问题吗？我试过改文件路径，报错就是单纯的找不到文件而不是编译失败。另外在本地上运行，数据都是成功填充到表格的。恳请大佬们指点

### windows服务器报错信息
![image](https://user-images.githubusercontent.com/38587345/143667739-4d1c4223-de5a-4c73-a634-6f1e177db9d8.png)

### 代码
![image](https://user-images.githubusercontent.com/38587345/143667745-fa958c63-20e7-46fa-a9c7-077f34fdd74b.png)
![image](https://user-images.githubusercontent.com/38587345/143667857-6f3bec08-0bac-4c62-8f48-01e3a9642b7d.png)

### 模板文件路径

![image](https://user-images.githubusercontent.com/38587345/143667748-5f287453-05a6-45cf-bcf7-701d74784852.png)

### 模板：

![image](https://user-images.githubusercontent.com/38587345/143667756-d9a7d43b-44b9-4481-bc72-67c194e913ea.png)

### 本地运行填充后：
![image](https://user-images.githubusercontent.com/38587345/143667761-c0b46adf-7b08-4fad-9cc7-028feec20993.png)

**Comment by Sayi** [comment]
异常栈没贴全？还是就这么点异常？

**Comment by LikeASycamore** [comment]
我把模板文件内容清空，然后文件就成功下载了，应该还是模板内容有问题

**Comment by Sayi** [comment]
可以模板私发到我邮箱里面，我来重现下。

**Comment by Sayi** [comment]
我使用你发给我的模板，在poi-tl  1.10.X版本中没有重现这个问题，可能你使用的版本是旧的吧。

**Comment by LikeASycamore** [comment]
版本的话，是1.9.1，反正重写一次模板就行了
