### ISSUE TITLE
10.0.2 xml-apis版本冲突

### ISSUE THREAD

**Issue by fuzi1996** [Sayi/poi-tl#695]
### Issue description

使用`10.0.2`版本,打包时发现poi-tl引入的`xml-apis`版本出现冲突
![image](https://user-images.githubusercontent.com/21113919/144187648-9adcac8f-9bb7-4d99-8b21-1b1166e30aa3.png)

### poi-tl version

10.0.2

### Minimal test code to reproduce the issue

无

### Minimal Docx template file

![image](https://user-images.githubusercontent.com/21113919/144187780-8a0fa8d8-4f09-4139-90cd-a61185ab54ec.png)

**Comment by Sayi** [comment]
排除一个依赖就行了吧。
