### ISSUE TITLE
关于多个Word文档合并

### ISSUE THREAD

**Issue by taojinjing** [Sayi/poi-tl#70]
看到最新Readme里面加入了：
多个Word文档合并

请问是否有代码的例子，或者UT？谢谢~

**Comment by taojinjing** [comment]
找到了 NiceXWPFDocumentTest.testMerge()

**Comment by Sayi** [comment]
正在调试的一个功能，正式版本还没发布。
StoryExample.testStoryExample  也是个文档合并，循环模板的示例
