### ISSUE TITLE
是否可以像图片标签一样通过在模板内写上{{@var}} （var为图片url），进行插入附件，如：{{#var}}（var为附件地址）

### ISSUE THREAD

**Issue by diaomina** [Sayi/poi-tl#707]
### Issue description
是否可以像图片标签一样通过在模板内写上{{@var}} （var为图片url），进行插入附件，如：{{#var}}（var为附件地址）
### Minimal test code to reproduce the issue

```java

```

**Comment by Sayi** [comment]
你可以试试改下代码。
