### ISSUE TITLE
请教 CTTcPr 代表什么，getActualInsertPosition 返回 -1 引发空指针

### ISSUE THREAD

**Issue by yunfeiSong** [Sayi/poi-tl#710]
int templateColIndex = getTemplateColIndex(tagCell);
            int actualColIndex = getActualInsertPosition(tagCell.getTableRow(), templateColIndex);
            XWPFTableCell firstCell = tagCell.getTableRow().getCell(actualColIndex); 

            private int getActualInsertPosition(XWPFTableRow tableRow, int insertPosition) {
                    int orginalCol = 0;
                    for (int i = 0; i < tableRow.getTableCells().size(); i++) {
                        XWPFTableCell current = tableRow.getCell(i);
                        int intValue = 1;
                        CTTcPr tcPr = current.getCTTc().getTcPr();
                        if (null != tcPr) {
                            CTDecimalNumber gridSpan = tcPr.getGridSpan();
                            if (null != gridSpan) intValue = gridSpan.getVal().intValue();
                        }
                        orginalCol += intValue;
                        if (orginalCol - intValue == insertPosition && intValue == 1) {
                            return i;
                        }
                    }
                    return -1;
                }

**Comment by Sayi** [comment]
可以理解为单元格的样式，自己调试看下原因？？？

**Comment by yunfeiSong** [comment]
再请教下，这个方法是要计算什么，为什么要计算gridSpan，又限制它必须为1呢？

上面第一个问题，调节第二列的宽度，使gridSpan为null就能正常执行。

**Comment by Sayi** [comment]
因为必须处理有单元格合并的情况。
