### ISSUE TITLE
如何读取替换后word文档的页数？

### ISSUE THREAD

**Issue by Xlinlin** [Sayi/poi-tl#711]
是否可以开一个方法，替换后可以获取到word文档的总页数，或者在内部给定一个固定的变量，在替换模板参数的同时替换这个页数的变量？

**Comment by Xlinlin** [comment]
客户有一个需求：
    定制一份word文档，模板参数包含了当前文档的页数，即替换模板参数的同时，也要更新这份文档的总页数。
当前我这边的方案：
    1. 先替换一次模板，在通过poi获取文档总页数，但是获取到的总页数在某些特定条件下不准，于是更换了apose.word，也出现了部分文档页数不准的问题。
    2. 另外网上找到的方案是，替换后生成文件转换成pdf，获取pdf的总页数再进行替换
    以上两种方案都需要不停的对文件进行操作，性能方面会大打折扣，不知道你们是否有可行的方案或升级计划呢？

**Comment by Sayi** [comment]
Word页数可以去寻找APache POI相关的API。
