### ISSUE TITLE
文本框内文本替换出现错乱

### ISSUE THREAD

**Issue by harmydzh** [Sayi/poi-tl#713]
![微信截图_20211220113531](https://user-images.githubusercontent.com/96103266/146708378-9b1e6864-2c20-400d-9eb5-f27e18f8feab.png)
![微信截图_20211220113616](https://user-images.githubusercontent.com/96103266/146708383-a36629b6-0de0-4cbd-9ac5-07d8d104279f.png)

**Comment by Sayi** [comment]
可以给一个能重现这个问题的最小代码和模板吗？

**Comment by harmydzh** [comment]
[D.zip](https://github.com/Sayi/poi-tl/files/7751259/D.zip)

**Comment by harmydzh** [comment]
@Sayi 请查看D.zip 附件，模板也在里面

**Comment by Sayi** [comment]
感谢，已修复，随着下个版本发布。
