### ISSUE TITLE
word创建表格单元格合并问题

### ISSUE THREAD

**Issue by h976353715** [Sayi/poi-tl#715]
### Issue description
合并后只占一个格子，并不是三个
### poi-tl version
1.10.0
### Minimal test code to reproduce the issue
![image](https://user-images.githubusercontent.com/29591786/146895675-da614ee9-9080-4d05-82d3-5fbe1f92b759.png)

```java
![image](https://user-images.githubusercontent.com/29591786/146895544-258d8d55-b159-4912-bc63-7b3d53a1dc1d.png)

```

**Comment by h976353715** [comment]
![image](https://user-images.githubusercontent.com/29591786/146895735-baf0c8ac-8ece-494f-8b70-ff0ffcb429d1.png)

**Comment by h976353715** [comment]
![image](https://user-images.githubusercontent.com/29591786/146896015-f13cc3fb-47c6-4a97-b015-75c5118cb9e3.png)

**Comment by Sayi** [comment]
需要提供一个能复现此问题的最小示例。

**Comment by M-Poplar** [comment]
- [ ] 我也是这个问题，我合并同一行的最后6个单元格，结果变成删除后面的5个单元格

**Comment by gt2ming** [comment]
我也遇到了同样的问题，请问解决了吗？

**Comment by gt2ming** [comment]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/26201976/219564930-5d4d963e-a4a1-44bc-b35a-49dada2d713a.png">

<img width="397" alt="image" src="https://user-images.githubusercontent.com/26201976/219565033-85ce4514-64ea-4882-88d4-5704f6076119.png">
