### ISSUE TITLE
区块对标签会使嵌套标签失效

### ISSUE THREAD

**Issue by cuining-cn** [Sayi/poi-tl#717]
{{?section}}
{{+part}}
{{/section}}
这个中间的嵌套标签不会被解析

**Comment by Sayi** [comment]
#660

**Comment by cuining-cn** [comment]
和#660不是一个问题
{{?section}}
{{+part}}
{{/section}}
这个中间的嵌套标签不会被解析
程序代码不报错
输出的文档里会直接输出 "{{+part}}"的字符串，而不是我引用的子文档

**Comment by cuining-cn** [comment]
另外，如果把
{{?section}}
{{+part}}
{{/section}}

前后的{{?section}}和{{/section}}删掉后
{{+part}}可以正常嵌入子文档

**Comment by Sayi** [comment]
搞错了， 目前不支持。

#403
