### ISSUE TITLE
word中插入.xlsx文件，wps office打开word文件无法显示文件。

### ISSUE THREAD

**Issue by jiedada** [Sayi/poi-tl#721]
**生成的word,使用wps打开无法显示附件。
但是用微软word打卡附件能正常显示。**
**word文档**：[text.docx](https://github.com/Sayi/poi-tl/files/7782505/text.docx)
**wps打开文档截图**：
![image](https://user-images.githubusercontent.com/39790942/147522982-b0f932c2-c1c8-4bce-b284-20c405bb3788.png)
**微软word打开文档截图**：
![image](https://user-images.githubusercontent.com/39790942/147522869-7e5da21f-e653-4d05-bdb3-f9b99a1dda4f.png)

**Comment by Sayi** [comment]
有可能是 #712 解决的问题，待我有时间细看下。

**Comment by jiedada** [comment]
好感谢你的答复，现在有临时的解决方案吗？
我发现：用微软打开word文档，在另存一下，wps打开文档，附件能正常显示

**Comment by jiedada** [comment]
> 有可能是 #712 解决的问题，待我有时间细看下。

好感谢你的答复，现在有临时的解决方案吗？
我发现：用微软打开word文档，在另存一下，wps打开文档，附件能正常显示

**Comment by Sayi** [comment]
主干已修复，随着下个版本发布。

**Comment by yun-0001** [comment]
老哥，下个版本什么时候发布

> 主干已修复，随着下个版本发布。

老哥，下个版本什么时候发布

**Comment by yun-0001** [comment]
> 



> 主干已修复，随着下个版本发布。

老哥，下个版本什么时候发布
