### ISSUE TITLE
根据模板生成多页内容

### ISSUE THREAD

**Issue by coderzhw** [Sayi/poi-tl#722]
![image](https://user-images.githubusercontent.com/10148784/147543904-17dacd12-ce67-4f74-afe3-ca68132513ff.png)
比如上面的模板，我想生成多页，每一页都是这个样式，该如何实现呢？搜了一下并没有搜到

**Comment by Sayi** [comment]
区块对和分页符，参考：https://github.com/Sayi/poi-tl/blob/v1.11.0/poi-tl/src/test/java/com/deepoove/poi/tl/render/IterableRenderBasicExample.java

**Comment by coderzhw** [comment]
> 区块对和分页符，参考：https://github.com/Sayi/poi-tl/blob/v1.11.0/poi-tl/src/test/java/com/deepoove/poi/tl/render/IterableRenderBasicExample.java

已解决，例子很详细，看懂了，多谢了

**Comment by hktk320** [comment]
请问分页符是哪一个啊？

**Comment by leojin0914** [comment]
> 请问分页符是哪一个啊？

word->插入-分页-分页符
