### ISSUE TITLE
word中添加表格,通过实体类进行数据渲染，字段类型是？

### ISSUE THREAD

**Issue by jiedada** [Sayi/poi-tl#723]
当字段类型是：TableRenderData，表格能渲染出来，实体类如下：
![image](https://user-images.githubusercontent.com/39790942/147622401-3a7c7ab7-748b-4c7e-9010-be9197960019.png)
当字段类型是：String[][]二维数组，报解析错误，实体类如下：
![image](https://user-images.githubusercontent.com/39790942/147622469-190e1939-b8da-4431-a062-10d7727b197c.png)
示例可以通过String[][]二维数组创建表格：
![image](https://user-images.githubusercontent.com/39790942/147622540-56ca2d61-8abe-4bc8-bc73-af863c7d8ee5.png)
疑问：String[][]可以创建表格，为什么实体类中字段类型为String[][]，渲染不出表格，报字段类型解析错误？

**Comment by Sayi** [comment]
字段类型目前只能是`TableRenderData `。

**Comment by jiedada** [comment]
> 字段类型目前只能是`TableRenderData `。
谢谢答复
