### ISSUE TITLE
表格渲染后能否像word一样进行 自动调整—>根据内容调整

### ISSUE THREAD

**Issue by qyw10456** [Sayi/poi-tl#727]
你好，当我渲染表格之后，所有的表格都是同样的大小，能否在不手动调整的情况下，进行word一样的功能 自动调整—>根据内容调整，以及我该如何去设置表格中文字的间距
![image](https://user-images.githubusercontent.com/86226719/147730734-985811c8-daf8-4dad-b188-2861cb8062f5.png)

**Comment by Sayi** [comment]
通过设置Cell内段落文字的间距。

自动调整需要计算宽度，目前没有这个计划。
