### ISSUE TITLE
NiceXWPFDocument合并（merge）文档时为什么要重新generate一下

### ISSUE THREAD

**Issue by Im-cbird** [Sayi/poi-tl#73]
https://github.com/Sayi/poi-tl/blob/e0b483d9cd4b8e3cf1609b7d41376abeeecdf7db/src/main/java/com/deepoove/poi/NiceXWPFDocument.java#L444

如题，我看合并时操作的是 **this**.document.body ，此时当前文档结构不是已经改变了吗，直接返回 this 的话会有什么问题

**Comment by Sayi** [comment]
就是因为文档结构已经改变了，所以如果继续使用XWPFDocument的API(使用原先的文档结构的解析结果)的时候会有问题，需要重新解析下文档结构。

**Comment by Im-cbird** [comment]
哦，原来如此，谢啦
