### ISSUE TITLE
使用list渲染嵌套模板报错

### ISSUE THREAD

**Issue by Huochexiansheng** [Sayi/poi-tl#731]
官方文档中使用嵌套标签 JUnit ResumeExample方式，
注入DocxRenderData集合，重复渲染同一个A1模板多次，其中
主模板A1中嵌套有下级模板A2与A3
![image](https://user-images.githubusercontent.com/42929566/149467773-af2ad232-14d7-4666-9634-8b75ec4aa02e.png)

![1642145169(1)](https://user-images.githubusercontent.com/42929566/149468695-e73671d5-8e2c-4789-b5ae-b51cb29965d8.png)

XmlXWPFDocumentMerge 类中报错空指针异常
styleCacheThreadLocal未能获取到值

`Configure config = Configure.builder()
                .addPlugin('%', new LoopRowTableRenderPolicy())
                .build();
        List<SuperviseData> superviseDataList = Lists.newArrayList();
        for (String level1Name : level1Names) {
            superviseParam.setFoodType(level1Name);
            SuperviseData superviseData = initTemplate(superviseTemplateList, a1Template, superviseParam);
            initEndTemp(superviseTemplateList,superviseData);
            superviseDataList.add(superviseData);
        }
        DocxRenderData docxRenderData = Includes.ofLocal(a1Template.getTempPath()).setRenderModel(superviseDataList).create();
        jlData.setJLA1(docxRenderData);
        initEndTemp(superviseTemplateList,jlData);
        XWPFTemplate template = XWPFTemplate.compile(mainTemplate.getTempPath(),config).render(jlData);`

**Comment by Sayi** [comment]
#700  已经解决了，这周会发布新版本。
