### ISSUE TITLE
如何生成树状结构图

### ISSUE THREAD

**Issue by BeamWang** [Sayi/poi-tl#735]
![E9AB97A7-D750-4ABB-ACB1-D453A6A3E280](https://user-images.githubusercontent.com/29188638/150764775-8bc70dc4-93de-40b6-b783-5c147aa2dd01.jpeg)
大佬，我需要在word生成类似上图的树图结构，现在看来只有smart art可实现，我通过配置可选文字的方式绑定数据和插件，但是断点不会进入我编写的插件render方法里，请教是哪里的问题？

**Comment by Sayi** [comment]
不支持形状。
