### ISSUE TITLE
适合android使用吗？

### ISSUE THREAD

**Issue by learder** [Sayi/poi-tl#74]
你好
    poi对安卓支持不够好，XWPFDocument在android使用会报javax里的一个xmlFactory的类找不到！
这个库能解决这个问题吗？

**Comment by Sayi** [comment]
基于POI的，不适合Android端使用。

**Comment by learder** [comment]
好的，谢谢

**Comment by zwc456baby** [comment]
> 好的，谢谢

我找到办法让它支持 Android 了，我写了一篇简书

https://www.jianshu.com/p/60bfb892d42e
