### ISSUE TITLE
图片引用标签在未提供图片源的情况下，模板图片不会清除掉

### ISSUE THREAD

**Issue by CialloAlone** [Sayi/poi-tl#740]
大佬，我想实现一个电子印章的功能，使用了模板中插入图片引用标签的方式，但如果我未提供图片资源，占位用的图片不会自动清除掉,请问如何解决这个问题呢？

**Comment by Sayi** [comment]
引用标签不会清除掉，可以用区块对内放置图片，从而达到不显示图片的目的。

**Comment by CialloAlone** [comment]
> 

我插入的是一个浮动的图片，没办法放到区块对中，我自己写了个RenderPolicy，通过poi API将原图片删除了，也算是解决了这个问题
