### ISSUE TITLE
区块对标签异常

### ISSUE THREAD

**Issue by 1981385824** [Sayi/poi-tl#744]
你好，请教下区块对的异常情况

问题：
模板如下：
![image](https://user-images.githubusercontent.com/37207464/154198450-c04f4358-88b0-42b6-8836-8494494eeba5.png)
结果如下：
![image](https://user-images.githubusercontent.com/37207464/154198603-883973d5-5f06-43be-b89d-1878e7469d96.png)

填充数据格式：
[
{
"proposal": "处置建议详情",
"riskDesc": "风险描述详情"
},
{
"proposal": "处置建议详情",
"riskDesc": "风险描述详情"
},
{
"proposal": "处置建议详情",
"riskDesc": "风险描述详情"
},
{
"proposal": "处置建议详情",
"riskDesc": "风险描述详情"
},
{
"proposal": "处置建议详情",
"riskDesc": "风险描述详情"
},
{
"proposal": "处置建议详情",
"riskDesc": "风险描述详情"
},
{
"proposal": "处置建议详情",
"riskDesc": "风险描述详情"
},
{
"proposal": "处置建议详情",
"riskDesc": "风险描述详情"
},
{
"proposal": "处置建议详情",
"riskDesc": "风险描述详情"
},
{
"proposal": "处置建议详情",
"riskDesc": "风险描述详情"
}
]

共十组数据，{{riskDesc}}结果出现了19次，{{proposal}}出现一次且未替换对应数据

**Comment by 1981385824** [comment]
上述区块对模板中只要存在换行似乎都有该问题

**Comment by Sayi** [comment]
模板发一下

**Comment by 1981385824** [comment]
测试模板
[测试模板.docx](https://github.com/Sayi/poi-tl/files/8152117/default.docx)

**Comment by Sayi** [comment]
无法复现。
