### ISSUE TITLE
关于自定义语法前后缀

### ISSUE THREAD

**Issue by Im-cbird** [Sayi/poi-tl#75]
_目前需求是嵌入不定数量的图片，通过{{+template}}语法实现_

因为项目之前使用freemarker做的，模板大部分做好了，所以自己配置了一下语法前后缀：
```java 
Configure.newBuilder().buildGramer("${", "}").build();
```
以适配freemarker模板。

结果循环数据渲染待嵌入的模板时，发现解析待嵌入的模板时使用的是默认配置：
https://github.com/Sayi/poi-tl/blob/e0b483d9cd4b8e3cf1609b7d41376abeeecdf7db/src/main/java/com/deepoove/poi/policy/DocxRenderPolicy.java#L73
```java
 for (int i = 0; i < dataList.size(); i++) {
                XWPFTemplate temp = XWPFTemplate.compile(docx);
                temp.render(dataList.get(i));
                docs.add(temp.getXWPFDocument());
 }
```
这个地方会解析不到子模板的自定义语法占位符,算是个小bug吧。

可以考虑在此处
https://github.com/Sayi/poi-tl/blob/e0b483d9cd4b8e3cf1609b7d41376abeeecdf7db/src/main/java/com/deepoove/poi/policy/DocxRenderPolicy.java#L50
方法调用时传入主模板配置：
```java
List<NiceXWPFDocument> docMerges = getMergedDocxs((DocxRenderData) data,template.getConfig());
```

**Comment by Sayi** [comment]
的确是BUG，解决办法就是你说的那样传入主模板配置。 👍

**Comment by Im-cbird** [comment]
good！
