### ISSUE TITLE
poi-ooxml-schemas-extra may no longer be needed after poi 5.2.1 release

### ISSUE THREAD

**Issue by pjfanning** [Sayi/poi-tl#752]
### Issue description

I made some changes in POI 5.2.1 (RC1 is announced on POI dev mailing list) that adds the classes and xsbs from poi-ooxml-schemas-extra to poi-ooxml-lite - hopefully, I didn't miss any classes

**Comment by Sayi** [comment]
This is awesome, I will try to use it. 👍

**Comment by Sayi** [comment]
This has been done in the latest version(1.12.0).
