### ISSUE TITLE
animal 示例，循环生成图表，前面图表数据被覆盖

### ISSUE THREAD

**Issue by owensky1** [Sayi/poi-tl#753]
###animal 示例，循环生成图表，前面图标数据被覆盖

### Minimal test code to reproduce the issue

Map<String, Object> elephant = new HashMap<String, Object>() {
            {
                put("name", "大象");
                put("picture", Pictures.ofLocal("lu.png").size(100, 120).create());
                put("chart",
                        Charts.ofMultiSeries("大象生存现状", new String[] { "2018年", "2019年", "2020年" })
                                .addSeries("成年象", new Integer[] { 500, 600, 700 })
                                .addSeries("幼象", new Integer[] { 200, 300, 400 })
                                .addSeries("全部", new Integer[] { 700, 900, 1100 })
                                .create());

            }
        };
        Map<String, Object> giraffe = new HashMap<String, Object>() {
            {
                put("name", "长颈鹿");
                put("picture", Pictures.ofLocal("lu.png").size(100, 120).create());
                put("chart",
                        Charts.ofMultiSeries("长颈鹿生存现状", new String[] { "2018年", "2019年", "2020年" })
                                .addSeries("成年鹿", new Integer[] { 500, 600, 700 })
                                .addSeries("幼鹿", new Integer[] { 200, 300, 500 })
                                .create());

            }
        };
        List<Map<String, Object>> animals = Arrays.asList(elephant, giraffe);

        XWPFTemplate.compile("animal.docx").render(new HashMap<String, Object>() {
            {
                put("animals", animals);
            }
        }).writeToFile("out_example_animal2.docx");
```
### 生成图表之后，右键图表编辑数据或者右键选择数据进行查看数据的时候，前面的图表的数据被后面图表的数据覆盖了

**Comment by owensky1** [comment]
这个poi-tl确实超级好用，不知道作者大神和其他用咱们poi-tl大神遇到我遇到的这个问题了没有，

**Comment by Sayi** [comment]
#751 已修复，下个版本发布。
