### ISSUE TITLE
动态设置图表的横纵坐标标题

### ISSUE THREAD

**Issue by owensky1** [Sayi/poi-tl#755]
![1646374781(1)](https://user-images.githubusercontent.com/8233263/156710415-fcbf1475-08c1-4edd-b052-af7140144121.png)

如上图所示用的ChartMultiSeriesRenderData渲染的数据，想请教一下有没有办法动态设置图表的横纵坐标的标题。

**Comment by owensky1** [comment]
[相似性分析画图.docx](https://github.com/Sayi/poi-tl/files/8220481/default.docx)
您好您好，我是想动态设置这个图表里的轴标题YSLJ-STR-G01-01(με)和YSLJ-STR-G01-02(με)

**Comment by Sayi** [comment]
已支持，将会在下个版本发布。
