### ISSUE TITLE
你通将它做成一个 http 服务就更好了

### ISSUE THREAD

**Issue by runner-mei** [Sayi/poi-tl#756]
你通将它做成一个 http 服务就更好了

同时支持导出 pdf 和 jpg， png 就更好了

**Comment by gkchp** [comment]
你可以用 [JodConverter](https://github.com/sbraconnier/jodconverter) 自己起一个服务，或者用别人现成的 [kkFileView](https://github.com/kekingcn/kkFileView)

**Comment by runner-mei** [comment]
不一样，不是想要一个 doc to pdf 的服务
你有一个 docx 模板功能， 那么我们就可以做一个在线生成工单的服务了

如接口
POST /:模板名/docx 

我调用时，在 post 请求中提供一份数据， 后台将数据和模板生成一个文档，并返回它。

而我让用户写好模板放在指定目录下

**Comment by Sayi** [comment]
下个版本数据模型支持JSON字符串。
