### ISSUE TITLE
请问如何生成散点图？

### ISSUE THREAD

**Issue by zhelgle80** [Sayi/poi-tl#757]
发现没有生成散点图的功能，是还没支持吗？能请教下该怎么才能生成散点图

**Comment by owensky1** [comment]
设置图表格式，生成散点那个设置无线条

**Comment by zhelgle80** [comment]
@owensky1 您能生成散点图吗，能否发个示例我参考一下，谢谢了

**Comment by zhelgle80** [comment]
#758 您能生成散点图吗，能否发个示例我参考一下，谢谢了

**Comment by Sayi** [comment]
下个版本原生支持散点图。

**Comment by zhelgle80** [comment]
作者您好，现在有没有生成示例代码参考下，急需，谢谢了，效果如下图，需要多组数据系列
![image](https://user-images.githubusercontent.com/101047863/157354331-12f80e8c-90d1-45dd-87b6-99bb453ac722.png)

**Comment by Sayi** [comment]
你把你这个效果的doc发给我一下。

**Comment by Sayi** [comment]
需要等下个版本。

**Comment by zhelgle80** [comment]
效果文件发上来了 [ScatterChart_demo.docx](https://github.com/Sayi/poi-tl/files/8212237/ScatterChart_demo.docx)

**Comment by zhelgle80** [comment]
@Sayi 您好，我现在用1.10.3版本，看到您github库现在合并了开发版本里有生成散点图的功能，但是有个问题，我现在生成散点图每个数据系列个数是不固定的，比如A系列有5个，B系列有10个，C系列有20个，D系列2个，但是您的生成代码中每个系列个数必须是一致才可以，这个系列个数必须要一致才可以吗？

**Comment by zhelgle80** [comment]
@Sayi 您好，我现在用1.10.3版本，看到您github库现在合并了这个开发版本里有生成散点图的功能，但是有个问题，我现在生成散点图每个数据系列个数是不固定的，比如A系列有5个，B系列有10个，C系列有20个，D系列2个，但是您的生成代码中每个系列个数必须是一致才可以，这个系列个数必须要一致才可以吗？

**Comment by Sayi** [comment]
这个底层就是要求必须一致吧？

**Comment by zhelgle80** [comment]
@Sayi 哪是否可以一次写入多个纵坐标值与横坐标值，现在的代码只能是写一条纵坐标对应多条横坐标

**Comment by Sayi** [comment]
目前不可以。
