### ISSUE TITLE
设置图表格式，生成散点那个设置无线条

### ISSUE THREAD

**Issue by zhelgle80** [Sayi/poi-tl#758]
您能生成散点图吗，能否发个示例我参考一下，谢谢了

_Originally posted by @owensky1 in https://github.com/Sayi/poi-tl/issues/757#issuecomment-1060081502_

**Comment by zhelgle80** [comment]
> 您能生成散点图吗，能否发个示例我参考一下，谢谢了
> 
> _Originally posted by @owensky1 in [#757 (comment)](https://github.com/Sayi/poi-tl/issues/757#issuecomment-1060081502)_

**Comment by owensky1** [comment]
![image](https://user-images.githubusercontent.com/8233263/156989942-680d77cd-74e0-42b8-800b-a78d78370872.png)

散点和实线代码是一样的，就是设置模板的时候这里线条设置无

**Comment by owensky1** [comment]
你用代码设置图表的横或者纵坐标标题了不，是怎么设置的您知道不，

**Comment by zhelgle80** [comment]
@owensky1 这个标题没设置过，代码里好像只能设置一个标题，我想是不是可以在需要坐标标题位置放一个文本框，然后在文本框里设置标签试试看行不行

**Comment by zhelgle80** [comment]
@owensky1 能加我微信，帮助一下吗？
![image](https://user-images.githubusercontent.com/101047863/156993925-019b2344-fe30-4e70-80b9-11e9f00f90ce.png)
