### ISSUE TITLE
有水印的文件合并失败

### ISSUE THREAD

**Issue by xiongkai3538** [Sayi/poi-tl#760]
![image](https://user-images.githubusercontent.com/65639518/157195630-49a16513-9745-40bc-940b-a70565c89ed4.png)
![image](https://user-images.githubusercontent.com/65639518/157195371-bfb62310-1c3b-47a9-bbe3-4f10758c01f4.png)
![image](https://user-images.githubusercontent.com/65639518/157195454-c466e6c6-c6cd-4b8d-85a8-0e5684a1f339.png)

**Comment by Sayi** [comment]
#391
