### ISSUE TITLE
在使用LoopRowTableRenderPolicy插件时遇到一个bug

### ISSUE THREAD

**Issue by zhelgle80** [Sayi/poi-tl#765]
模板如下：
![image](https://user-images.githubusercontent.com/101047863/159737287-96bee10a-2020-473a-8abb-6768d2b467d9.png)

正确的结果应该是这样子：
![image](https://user-images.githubusercontent.com/101047863/159738375-ff7b4fb9-ae16-449e-a3bb-f974743b744b.png)

模板填充完数据生成结果：
![image](https://user-images.githubusercontent.com/101047863/159737611-5a2c39da-b65a-47c7-924a-a9dd66399306.png)

**Comment by Sayi** [comment]
{{fsd_detail_table}}所在单元格是合并的，放到人数那一个单元格。
