### ISSUE TITLE
普通的text类型可不可以加入一些标签来实现自定义加粗，下划线，倾斜呢

### ISSUE THREAD

**Issue by tr1912** [Sayi/poi-tl#766]
### Issue description
我有一个循环列表的数据要处理，在页面上不能定义多个{{}}来接收，必须是整段的文字写入，但是整段文字中有些文字需要醒目标明，所以需要加粗，或者下划线来展示出来
![image](https://user-images.githubusercontent.com/23535773/160081920-c53bdf8a-a91b-4fe7-ab89-35a59515a59c.png)
![image](https://user-images.githubusercontent.com/23535773/160081959-a88c7395-9b3b-4dce-a481-51a02f0cfe46.png)
希望可以在test里面加入类似html标签，可以实现html的效果比如<u></u> 之类的
这种情况使用不了TextRender
### poi-tl version
1.6.0
### Minimal test code to reproduce the issue

```java

```

**Comment by Sayi** [comment]
使用`ParagraphRenderData`。
