### ISSUE TITLE
怎么使用区块对循环显示word上每页数据？一个循环是一页，两个标签不好放，要么多一页，要么黏在一块了

### ISSUE THREAD

**Issue by zxucooly** [Sayi/poi-tl#767]
怎么使用区块对循环显示word上每页数据？一个循环是一页，两个标签不好放，要么多一页，要么黏在一块了

**Comment by Sayi** [comment]
参照 #722   循环里面放分页符即可，注意处理下最后一个循环的分页符防止空白页。

**Comment by zxucooly** [comment]
**thanks**
