### ISSUE TITLE
期望在表格中一行中的单元格包含多个文本多个样式

### ISSUE THREAD

**Issue by leojin0914** [Sayi/poi-tl#769]
### PaymentExample 期望在表格中一行中的单元格包含多个文本多个样式，求大佬指点，谢谢。

| S数量     | 货物 | 说明 |
| ----------- | ----------- |  ----------- |
| 1     | **书房**+_卧室_       | 表中单元格多个List<<文本>+<样式>> |
| 2   | **厨房**+_卫生间_       | 加粗+下划线等等|

### 在Rows类没找到相应的方法

```java
public class Rows {

    private Rows() {
    }

    public static RowBuilder of() {
        return new RowBuilder();
    }

    public static RowBuilder of(CellRenderData... cell) {
        RowBuilder inst = of();
        if (null != cell) {
            Arrays.stream(cell).forEach(inst::addCell);
        }
        return inst;
    }

    public static RowBuilder of(String... cell) {
        RowBuilder inst = of();
        if (null != cell) {
            Arrays.stream(cell).map(text -> {
                return Cells.of(text).create();
            }).forEach(inst::addCell);
        }
        return inst;
    }

    public static RowBuilder of(TextRenderData... cell) {
        RowBuilder inst = of();
        if (null != cell) {
            Arrays.stream(cell).map(text -> {
                return Cells.of(text).create();
            }).forEach(inst::addCell);
        }
        return inst;
    }

```
###

**Comment by Sayi** [comment]
`Cells`构造`CellRenderData`中，通过ParagraphRenderData去解决。

**Comment by leojin0914** [comment]
1. 构建数据

`package com.deepoove.poi.tl.example;

import com.deepoove.poi.XWPFTemplate;
import com.deepoove.poi.config.Configure;
import com.deepoove.poi.data.*;
import com.deepoove.poi.data.style.Style;
import org.apache.poi.xwpf.usermodel.UnderlinePatterns;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@DisplayName("Example for Table")
public class PaymentExample2 {

    String resource = "src/test/resources/payment/payment2.docx";
    PaymentData datas = new PaymentData();

    @BeforeEach
    public void init() {

        DetailData detailTable = new DetailData();
        RowRenderData good = Rows.of("4", "墙纸", "书房+卧室", "1500", "/", "400", "1600").center().create();

		CellRenderData[] cellRenderData = new CellRenderData[6] ;

		List<ParagraphRenderData> paragraphRenderDatas = new ArrayList<>();

		ParagraphRenderData paragraphRenderData = new ParagraphRenderData();
		List<RenderData> renderData = new ArrayList<>();

		TextRenderData textRenderData1 = new TextRenderData();
		textRenderData1.setText("1");
		Style style1 = new Style();
		style1.setBold(true);
		textRenderData1.setStyle(style1);
		renderData.add(textRenderData1);

		TextRenderData textRenderData2 = new TextRenderData();
		textRenderData2.setText(" 2");
		Style style2 = new Style();
		style2.setUnderlinePatterns(UnderlinePatterns.DASH);
		textRenderData2.setStyle(style2);
		renderData.add(textRenderData2);

		paragraphRenderData.setContents(renderData);
		boolean add = paragraphRenderDatas.add(paragraphRenderData);

		cellRenderData[0] = new CellRenderData();
		cellRenderData[0].setParagraphs(paragraphRenderDatas);

		cellRenderData[1] = new CellRenderData();
		cellRenderData[1].setParagraphs(paragraphRenderDatas);

		cellRenderData[2] = new CellRenderData();
		cellRenderData[2].setParagraphs(paragraphRenderDatas);

		cellRenderData[3] = new CellRenderData();
		cellRenderData[3].setParagraphs(paragraphRenderDatas);

		cellRenderData[4] = new CellRenderData();
		cellRenderData[4].setParagraphs(paragraphRenderDatas);


		RowRenderData rowRenderData = Rows.of(cellRenderData).center().create();
		List<RowRenderData> goods = Arrays.asList(rowRenderData,rowRenderData);
        detailTable.setGoods(goods);
        datas.setDetailTable(detailTable);
    }

    @Test
    public void testPaymentExample() throws Exception {
        Configure config = Configure.builder().bind("detail_table", new DetailTablePolicy2()).build();
        XWPFTemplate template = XWPFTemplate.compile(resource, config).render(datas);
        template.writeToFile("target/out_example_payment2.docx");
    }

}
`

2. 定义渲染策略


`package com.deepoove.poi.tl.example;

import com.deepoove.poi.data.RowRenderData;
import com.deepoove.poi.policy.DynamicTableRenderPolicy;
import com.deepoove.poi.policy.TableRenderPolicy;
import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;

import java.util.List;

/**
 * 付款通知书 明细表格的自定义渲染策略<br/>
 * 1. 填充货品数据 <br/>
 * @author Sayi
 * @version 
 */
public class DetailTablePolicy2 extends DynamicTableRenderPolicy {

    // 货品填充数据所在行数
    int goodsStartRow = 2;

    @Override
    public void render(XWPFTable table, Object data) throws Exception {
        if (null == data) return;
        DetailData detailData = (DetailData) data;


        List<RowRenderData> goods = detailData.getGoods();
        if (null != goods) {
            table.removeRow(goodsStartRow);
            for (int i = 0; i < goods.size(); i++) {
                XWPFTableRow insertNewTableRow = table.insertNewTableRow(goodsStartRow);
                for (int j = 0; j < 6; j++) insertNewTableRow.createCell();
                TableRenderPolicy.Helper.renderRow(table.getRow(goodsStartRow), goods.get(i));
            }
        }
    }

}
`

3. 模板附件

[payment2.docx](https://github.com/Sayi/poi-tl/files/8402025/payment2.docx)

4. thx @Sayi
