### ISSUE TITLE
请问如何实现在同一份word中循环一段模板

### ISSUE THREAD

**Issue by 253936563** [Sayi/poi-tl#77]
你好，我想在同一份word模板中实现类似文档模板{{+var}}的功能。就比如word模板中有{#list}{name},{sex},{idCard}{/list},然后循环生成list，能否给一个例子看一下

**Comment by Sayi** [comment]
由于word文档结构的特性，所以在一模板中并不好实现循环。

目前推荐用{{+var}}

**Comment by 253936563** [comment]
就是说必须要有两份word吗

**Comment by Sayi** [comment]
是的。

**Comment by 253936563** [comment]
好的 麻烦你了
