### ISSUE TITLE
使用手册中关于区块对生成简历的模板代码404

### ISSUE THREAD

**Issue by wangwangwangBoy** [Sayi/poi-tl#772]
hi,http://deepoove.com/poi-tl/#example-resume 使用手册中关于简历生成的这块，模板链接点进去是404；
https://github.com/Sayi/poi-tl/tree/master/poi-tl/src/test/java/com/deepoove/poi/tl/render/IterableRenderResumeExample.java
![image](https://user-images.githubusercontent.com/46279672/161011353-c40527d1-e3e9-4be8-9480-b74671edda80.png)

**Comment by Sayi** [comment]
已修复，谢谢。
