### ISSUE TITLE
在区对块中使用嵌套模版失效

### ISSUE THREAD

**Issue by hubStarzy** [Sayi/poi-tl#777]
> 这种模版无法正确渲染
{{?produces}}
{{+nested}}
{{/produces}}

**Comment by Sayi** [comment]
不支持哦。

**Comment by hubStarzy** [comment]
> 

 感谢你的回复，仔细回顾了一下已经关闭的issues发现有不少人使用区块对内嵌套模型，不知道后续会支持么？ @Sayi

**Comment by Sayi** [comment]
嵌套方案需要改造下，才能支持这个功能，需要时间。
