### ISSUE TITLE
是否支持表格中插入word

### ISSUE THREAD

**Issue by xiongkai3538** [Sayi/poi-tl#782]
![image](https://user-images.githubusercontent.com/65639518/165712025-c390b48f-b8b3-4063-897f-fbb460218a21.png)
![image](https://user-images.githubusercontent.com/65639518/165716635-38de568e-45cf-48fc-8358-e6ea8e587562.png)
![image](https://user-images.githubusercontent.com/65639518/165716734-5a3fbc58-b36b-44f4-b049-416119d9f14f.png)

**Comment by Sayi** [comment]
应该不支持，没试过这个场景。

**Comment by xiongkai3538** [comment]
好的，动态word嵌入是否支持？

**Comment by xiongkai3538** [comment]
好的，动态word嵌入是否支持？
