### ISSUE TITLE
使用poi-tl 1.11.1版本生成图片之后启用编辑图片消失

### ISSUE THREAD

**Issue by wangluhanlu** [Sayi/poi-tl#787]
### Minimal test code to reproduce the issue

```java

```
### Minimal Docx template file
![image](https://user-images.githubusercontent.com/39073425/168584461-727f9886-df4b-4298-bd5b-30ebecb9b699.png)
![image](https://user-images.githubusercontent.com/39073425/168584541-487446f6-be9b-4e96-b023-a3fe9136fd85.png)
[surveymodel.docx](https://github.com/Sayi/poi-tl/files/8699677/surveymodel.docx)
附件为word模板
![image](https://user-images.githubusercontent.com/39073425/168584784-ffa618cf-cdf1-4673-a56e-c86a09e94d57.png)

**Comment by Sayi** [comment]
请提供一下最小的单元测试。
