### ISSUE TITLE
特殊标签这么替换不了

### ISSUE THREAD

**Issue by tanyp588** [Sayi/poi-tl#789]
![图片](https://user-images.githubusercontent.com/53160979/169258434-9081b602-322c-4160-b04f-b5258a63fc3f.png)
左边标红的标签一个都替换不了

**Comment by tanyp588** [comment]
![图片](https://user-images.githubusercontent.com/53160979/169259291-bec75f24-c1ba-4d13-a7cc-0dc664ef382d.png)
这是读取标签的日志

**Comment by Sayi** [comment]
模板发一下

**Comment by tanyp588** [comment]
你好！

        模板在附件里面，还有个字符串里面有上下标的那种字符这么自动还原到word里面，就是比如：题干里面有这种




***@***.***
 
发件人： Sayi
发送时间： 2022-05-24 00:19
收件人： Sayi/poi-tl
抄送： tanyp588; Author
主题： Re: [Sayi/poi-tl] 特殊标签这么替换不了 (Issue #789)
模板发一下

**Comment by Sayi** [comment]
没收到附件，你直接发我邮箱。

**Comment by tanyp588** [comment]
***@***.***
 
发件人： Sayi
发送时间： 2022-05-24 10:05
收件人： Sayi/poi-tl
抄送： tanyp588; Author
主题： Re: [Sayi/poi-tl] 特殊标签这么替换不了 (Issue #789)
没收到附件，你直接发我邮箱。

**Comment by Sayi** [comment]
无法复现。
