### ISSUE TITLE
图片渲染异常问题

### ISSUE THREAD

**Issue by javadoge** [Sayi/poi-tl#793]
版本10.x
渲染图片方式：{{@firstOwnerSignUrl}}

代码：checkInfo.setFirstOwnerSignUrl(Pictures.ofLocal("https://xxx.oss-cn-beijing.aliyuncs.com//upload//20220522//15a6e24fe792e4137bdaf0a631ca3d71.png").size(120, 120).create());

报错：{{@firstOwnerSignUrl}} error: Illegal char <:> at index 5: https:\xxx.oss-cn-beijing.aliyuncs.com\

发现图片//自动变为了\ ，请问这怎么处理呢？

**Comment by Sayi** [comment]
Pictures.ofUrl
