### ISSUE TITLE
LoopRowTableRenderPolicy 和区块对一起使用的渲染顺序问题

### ISSUE THREAD

**Issue by qyw10456** [Sayi/poi-tl#798]
当在区块对里渲染表格时会出现这种情况
![image](https://user-images.githubusercontent.com/86226719/170912765-c9b0e6ee-9cc7-46d3-b735-555dbf3fc849.png)
这是我的模板
![image](https://user-images.githubusercontent.com/86226719/170912903-5d076db9-4686-4bb8-90af-ce215e5f07ee.png)

**Comment by qyw10456** [comment]
表格是通过LoopRowTableRenderPolicy渲染的

**Comment by Dato001** [comment]
你用这个的话LoopRowTableRenderPolicy标签应该是在table里面去设置吧。

**Comment by Dato001** [comment]
不过我猜你是想通过普通的渲染表格方式来渲染你这个东西。大概思路有几个：

- 用区块来代替表格循坏，当然这可能需要数据结构吻合还可能出现表格只会把数据显示在一行。不会循坏增加行数。
- 第二种是动态表格代理http://deepoove.com/poi-tl/1.10.x/#plugin-dynamic-table 作者这里也写的很清楚，可以仿造试一下。
- 第三种如果实在不行，可以进行切割，用子模板来实现，然后再合并到主模板。http://deepoove.com/poi-tl/1.10.x/#_%E5%B5%8C%E5%A5%97

过程不是很重要，作者提供的这个东西不完善可以提出来，但是也需要自己想别的方法来实现。这是开发的基础性问题。

**Comment by Sayi** [comment]
@qyw10456 无法重现你的问题，我这边没有问题。
