### ISSUE TITLE
表格行循环渲染，一行对应多张图片问题

### ISSUE THREAD

**Issue by javadoge** [Sayi/poi-tl#799]
![微信图片_20220531144239](https://user-images.githubusercontent.com/5305836/171109164-443a14a4-d152-4c23-98c0-b8c82d5ddbd3.png)

大佬，请教渲染表格数据的时候，如果一条数据包含多张照片，这个照片怎么循环渲染出来呢？

**Comment by javadoge** [comment]
求救，这种怎么处理呢，试了多种方式都不行
这个list里面对应的图片字段为：
private List<PictureRenderData> evidenceImgs;

**Comment by javadoge** [comment]
[?evidenceImgs][=#this][/evidenceImgs]   怎么把这个this对象显示为图片呢？

**Comment by Sayi** [comment]
[?evidenceImgs][@#this][/evidenceImgs]
