### ISSUE TITLE
使用Micsoft office 2007 打开out.docx(word) 报错

### ISSUE THREAD

**Issue by jixiaa** [Sayi/poi-tl#8]
An error has occurred. See error log for more details.
java.lang.NullPointerException

1.唯独只有这个名字的out.docx就报错。
2.使用高版本的Micsoft Office 能打开不报错。

**Comment by Sayi** [comment]
@jixiaa 
告知一下poi-tl的版本号和低版本的Micsoft Office版本号

1.可以尝试下模板文件是否能用低版本office打开

**Comment by jixiaa** [comment]
1. 凡是案例中有【put("changeLog", new TableRenderData(new ArrayList<RenderData>(){{
				add(new TextRenderData("d0d0d0", ""));
				add(new TextRenderData("d0d0d0", "introduce"));
			}},new ArrayList<Object>(){{
				add("1;add new # gramer");
				add("2;support insert table");
				add("3;support more style");
			}}, "no datas", 10600));】代码的地方。导出的word都打不开。
2.micsoft offfice 2007 (12.0.6768.5000) sp3 MS0 
3.poi 版本V0.0.5 、V0.0.4 (只用了这两个版本)

**Comment by Sayi** [comment]
@jixiaa 
修改了表格的一些代码逻辑，poi-tl再升级到1.0.1-Beta1试试。我试了下在`Microsoft office word 2007 (12.0.4518.1014) MSO`是可以打开的。
```
<dependency>
    <groupId>com.deepoove</groupId>
    <artifactId>poi-tl</artifactId>
    <version>1.0.1-Beta1</version>
</dependency>
```

**Comment by jixiaa** [comment]
@Sayi 

1. 按照上面的操作。还是打不开。
2.感谢你的辛勤付出。

**Comment by xingya771** [comment]
@Sayi
@jixiaa 
我也遇到过相似的问题，代码中只要有插入表格的操作就会导致在低版本（Microsoft office word 2007 (12.0.4518.1014) MSO）中打不开，在wps中显示不完整。经测试，注释掉SimpleTableRenderPolicy.java中86行-87行的
`CTTblWidth width = table.getCTTbl().addNewTblPr().addNewTblW();
			width.setW(BigInteger.valueOf(tableData.getWidth()));`
后可正常插入表格并在低版本word中正常打开

**Comment by Sayi** [comment]
@xingya771 
的确是格式的问题，这个问题当时做了修复。你说的86-87行好像是旧代码。
[SimpleTableRenderPolicy.java master最新代码，参见102行-112行](https://github.com/Sayi/poi-tl/blob/master/src/main/java/com/deepoove/poi/policy/SimpleTableRenderPolicy.java)

1.确认下你现在使用的是最新代码？
2.或者使用最新依赖包试试是否还有此问题？
```
<dependency>
    <groupId>com.deepoove</groupId>
    <artifactId>poi-tl</artifactId>
    <version>1.0.1-Beta1</version>
</dependency>
```

**Comment by xingya771** [comment]
@Sayi 采用最新代码后问题解决，感谢。
