### ISSUE TITLE
导出的docx使用Libreoffice转换pdf有错误

### ISSUE THREAD

**Issue by LeeSons** [Sayi/poi-tl#800]
### Issue description
导出的docx文件好像缺点什么信息，使用Libreoffice打开会乱。看之前有人提交过issue，现在应该是还没解决，因为我也遇到了同样的问题，业务上需要在线预览生成的word，我们采用的是用Libreoffice转成pdf之后直接预览pdf，但是转换的时候会出现错误，用wps打开重新保存后就变正常了。所以我怀疑是不是生成文档的时候缺少点头信息之类的东西？
### poi-tl version
1.12.0

**Comment by Sayi** [comment]
无法复现。
