### ISSUE TITLE
table循环[]使用外部数据{{xxx}}

### ISSUE THREAD

**Issue by Dato001** [Sayi/poi-tl#801]
类似现在有一种情况  当使用LoopRowTableRenderPolicy去处理表格时，中间不能再用{{xxx}}来获取最外层的值了？？？

**Comment by Dato001** [comment]
感觉既然已经区分了表格里面的值是用[]这个去识别，那应该{{}}默认是最外层拿到va呀。

**Comment by Sayi** [comment]
动态新增的单元格没有再次解析{{}}标签，已有单元格会正常处理。

**Comment by Sayi** [comment]
#807

**Comment by Sayi** [comment]
引入作用域可能能解决这个问题。

**Comment by Sdky** [comment]
请问这个可以怎么解决呢？
