### ISSUE TITLE
LoopRowTableRenderPolicy表格渲染问题

### ISSUE THREAD

**Issue by qyw10456** [Sayi/poi-tl#802]
当表格头有跨行跨列之后
![image](https://user-images.githubusercontent.com/86226719/172091719-d36cccfe-0907-4daf-98a7-ba9236828696.png)
上面是模板，下面是生成后的效果
![image](https://user-images.githubusercontent.com/86226719/172091842-056e312e-6ebd-45a4-b1b8-4a41f3878b37.png)

**Comment by Dato001** [comment]
http://deepoove.com/poi-tl/#hack-loop-table

**Comment by qyw10456** [comment]
> http://deepoove.com/poi-tl/#hack-loop-table

![image](https://user-images.githubusercontent.com/86226719/173732865-89f2d8bc-bfd9-4d69-823a-186181acfff1.png)
没截清楚，是表格头有一格拆分了，如果不拆分的话生成是没有问题的

**Comment by Dato001** [comment]
如果希望模板标签和循环行在同一行而不是在上一行，可以使用 new LoopRowTableRenderPolicy(true) 来构造插件。

文档写的很清楚了。如果希望是在同一行开始循坏的话。初始化给个true入参就可以了

**Comment by qyw10456** [comment]
> 可以的，那个入参是onSameLine. 那你就要把你的{{checkPointPositions}}放入到数据的那一行，这样才会从数据那行开始循坏呀。 ![image](https://user-images.githubusercontent.com/59041476/173779810-9758e88b-248c-4d3a-a9b2-c3e2d9c65f0e.png)

好的，太感谢了，非常完美

**Comment by qyw10456** [comment]
> 可以的，那个入参是onSameLine。那你就接你的{Pointsitions}}检查到数据的那一行，这样呀从数据那行开始循坏。 ![图片](https://user-images.githubusercontent.com/59041476/173779810-9758e88b-248c-4d3a-a9b2-c3e2d9c65f0e.png)

这个还有一个问题 https://github.com/Sayi/poi-tl/issues/798 有时间帮我看看吗
