### ISSUE TITLE
关于在linux 批量生成word为jpg 时 字体出现变化

### ISSUE THREAD

**Issue by suiquantong** [Sayi/poi-tl#805]
因为生成文件耗费的io 比较大，想通过定时任务进行批量生 但是在生成过程中，发现 在windows 服务器 单个生成，或者批量都是正常的 ，但是用linux 服务进行批量生成时 出现了 字体变化，导致行距变大，从而导致生成的word 无法在一张纸上展示开的问题

**Comment by Sayi** [comment]
和poi无关。

**Comment by suiquantong** [comment]
已接受到你的信息或文件
