### ISSUE TITLE
列合并存在异常

### ISSUE THREAD

**Issue by wangqd93** [Sayi/poi-tl#81]
调用  NiceXWPFDocument.mergeCellsHorizonal(1,2,6) 会出现越界异常。
方法中 rowTable.getCtRow().removeTc(colIndex）认为存在问题，
合并之后单元格会变少，如果继续循环移除会出现越界。

**Comment by wangqd93** [comment]
mergeCellsHorizonal(table,i * 1 + 1,2,6) 换成调用后 NiceXWPFDocument.mergeCellsHorizonal(table,i * 1 + 1,2,6)  会出现越界

`class DetailTablePolicy extends DynamicTableRenderPolicy {
    @Override
    public void render(XWPFTable table, Object data) {
        for (int i = 0; i < 2; i++) {

            XWPFTableRow xwpfTableRow0 = table.insertNewTableRow(i * 4 + 1);

            xwpfTableRow0.addNewTableCell().setText(String.valueOf(i + 1));
            xwpfTableRow0.addNewTableCell().setText("标题");
            xwpfTableRow0.addNewTableCell().setText("标题标题标题标题吧");
            xwpfTableRow0.addNewTableCell().setText("1");
            xwpfTableRow0.addNewTableCell().setText("2");
            xwpfTableRow0.addNewTableCell().setText("3");

            XWPFTableRow xwpfTableRow1 = table.insertNewTableRow(i * 4 + 2);
            xwpfTableRow1.createCell();
            xwpfTableRow1.createCell().setText("发布时间");
            xwpfTableRow1.createCell().setText("2016-06-02");
            xwpfTableRow1.createCell().setText("原告");
            xwpfTableRow1.createCell().setText("原告公司");
            xwpfTableRow1.createCell().setText("被告");
            xwpfTableRow1.createCell().setText("被告公司");


            XWPFTableRow xwpfTableRow2 = table.insertNewTableRow(i * 4 + 3);
            xwpfTableRow2.createCell();
            xwpfTableRow2.createCell().setText("程序");
            xwpfTableRow2.createCell().setText("一审");
            xwpfTableRow2.createCell().setText("法院层级");
            xwpfTableRow2.createCell().setText("人民法院");
            xwpfTableRow2.createCell().setText("类型");
            xwpfTableRow2.createCell().setText("劳动合同");


            XWPFTableRow xwpfTableRow3 = table.insertNewTableRow(i * 4 + 4);
            xwpfTableRow3.createCell();
            xwpfTableRow3.createCell().setText("URL");
            xwpfTableRow3.createCell();
            xwpfTableRow3.createCell();
            xwpfTableRow3.createCell();
            xwpfTableRow3.createCell();

            mergeCellsHorizonal(table,i * 4 + 1,2,6);
            mergeCellsHorizonal(table, i * 4 + 4, 2, 6);
            NiceXWPFDocument.mergeCellsVertically(table, 0, i * 4 + 1, i * 4 + 4);

        }
    }


    public void mergeCellsHorizonal(XWPFTable table, int row, int fromCol, int toCol) {
        if (toCol <= fromCol) {
            return;
        }
        XWPFTableCell cell = table.getRow(row).getCell(fromCol);
        CTTcPr tcPr = cell.getCTTc().getTcPr();
        if (null == tcPr) {
            tcPr = cell.getCTTc().addNewTcPr();
        }
        XWPFTableRow rowTable = table.getRow(row);
        for(int colIndex = toCol; colIndex >=fromCol + 1; colIndex --){
            rowTable.removeCell(colIndex);
        }

        for (int i = 0 ; i < toCol - fromCol -1 ; i ++){
            rowTable.getCtRow().removeTc(fromCol + 1);
        }
        spanCellsAcrossRow(table, row, fromCol, toCol - fromCol + 1);
    }


    private static void spanCellsAcrossRow(XWPFTable table, int rowNum, int colNum,
                              int span) {
        XWPFTableCell cell = table.getRow(rowNum).getCell(colNum);
        cell.getCTTc().getTcPr().addNewGridSpan();
        cell.getCTTc().getTcPr().getGridSpan()
                .setVal(BigInteger.valueOf((long) span));
    }
}
`

**Comment by Sayi** [comment]
每一次合并都是在上一次合并后的表格中进行的。

**Comment by wangqd93** [comment]
那应该如何调用NiceXWPFDocument的mergeCellsHorizonal方法合并列

**Comment by Sayi** [comment]
每次合并自己计算好边界。
