### ISSUE TITLE
关于散点图

### ISSUE THREAD

**Issue by licongcai** [Sayi/poi-tl#815]
有散点图的代码示例吗

**Comment by Gingigo** [comment]
`    private ChartSingleSeriesRenderData createSingleSeriesScatterChart() {
        return Charts.ofSingleSeries("ChartTitle", new String[] { "1", "3", "4", "6", "9", "2", "4" })
                .series("Y值", new Integer[] { 12, 4, 9, 2, 10, 5, 7 })
    private ChartMultiSeriesRenderData createMultiSeriesScatterChart() {
        return Charts.ofMultiSeries("ChartTitle", new String[] { "1", "3", "4", "6", "9", "2", "4" })
                .addSeries("A", new Integer[] { 12, 4, 9, 2, 10, 5, 7 })
                .addSeries("B", new Integer[] { 2, 6, 3, 6, 2, 6, 9 })
                .create();
    }`

**Comment by licongcai** [comment]
> ` private ChartSingleSeriesRenderData createSingleSeriesScatterChart() { return Charts.ofSingleSeries("ChartTitle", new String[] { "1", "3", "4", "6", "9", "2", "4" }) .series("Y值", new Integer[] { 12, 4, 9, 2, 10, 5, 7 }) private ChartMultiSeriesRenderData createMultiSeriesScatterChart() { return Charts.ofMultiSeries("ChartTitle", new String[] { "1", "3", "4", "6", "9", "2", "4" }) .addSeries("A", new Integer[] { 12, 4, 9, 2, 10, 5, 7 }) .addSeries("B", new Integer[] { 2, 6, 3, 6, 2, 6, 9 }) .create(); }`
能说说怎么设置每个点的显示名称吗？

**Comment by licongcai** [comment]
能说说怎么设置每个点的显示名称吗？ @Gingigo
