### ISSUE TITLE
表格生成时，可以设置头部是垂直的吗？另外有qq群吗？

### ISSUE THREAD

**Issue by ZJongs** [Sayi/poi-tl#82]
表格生成时，可以设置头部是垂直的吗？另外有qq群吗？

**Comment by Sayi** [comment]
去研究下Apache POI

**Comment by ZJongs** [comment]
@Sayi 现在是用poi实现了。想看看这里有没有实现。前人留下的。维护起来很吃力。所以想看看poi-tl有没有实现。
