### ISSUE TITLE
使用嵌套标签，当嵌套模板中既有表格又有文字时，主模板的{{+nested}}被替换后，发现主模板平白无故多了几个新的字体样式，比如Heading、Normalda2babca

### ISSUE THREAD

**Issue by Danst-bjtu** [Sayi/poi-tl#822]
### Issue description
使用嵌套标签，当嵌套模板中既有表格又有文字时，主模板的{{+nested}}被替换后，发现主模板平白无故多了几个新的字体样式，比如heading 2a5552bda、Normalda2babca
### poi-tl version
4.1.2
### Minimal test code to reproduce the issue

```java
1.8
```

**Comment by Sayi** [comment]
样式是合并进来的。

可以做的更好一点：可以比较下样式，如果主模板已存在，则无需合并。

**Comment by Sayi** [comment]
#823  也可以参考下这个PR。

**Comment by Danst-bjtu** [comment]
感谢回复，问题已经解决，用的是POI的模板样式迁移方法，由于我设计的模板文档样式都是基于word、wps文档的标题样式或正文样式，所以完全可以在合并后为主文档赋予这些样式，这样合并后就不会产生新的样式了，其中template.docx中包含标题1、标题2、正文等样式
            template = new XWPFDocument(new FileInputStream("src/main/java/com/poi/springbootpoi/template/template.docx"));
            wordStyles = template.getStyle();
            XWPFStyles newStyles = document.createStyles();
            newStyles.setStyles(wordStyles);

**Comment by Sayi** [comment]
#823
