### ISSUE TITLE
wps模板里面SpEl表达式中的插入对勾符号，在读取的时候没有读成了空格

### ISSUE THREAD

**Issue by sxaulibo** [Sayi/poi-tl#827]
{{exist ? '是          否' : '是          否'}}
<img width="582" alt="image" src="https://user-images.githubusercontent.com/61260653/182019559-6deae962-9222-4118-92ee-5e8da3d1bb40.png">

在最新版本1.12.0调试看读取的时候这个符号读取不到，放在表达式外面的静态模板内容导出数据不受影响还是存在的
niceDocumentRead.read(this);

**Comment by Sayi** [comment]
你这个用区块对的if来实现即可，这样可以完美保留对勾符号。
