### ISSUE TITLE
表格图标没有数据时，怎么能删掉，替换显示成文本“无数据”这种

### ISSUE THREAD

**Issue by thirdSunShine** [Sayi/poi-tl#831]
现在的情况是某个块如果没数据的话，该块原始的模板还是会显示。希望是没有数据的时候模板不显示，然后该位置显示一个“暂无数据”替代

**Comment by cuitzh** [comment]
加一个变量判断

**Comment by thirdSunShine** [comment]
> 加一个变量判断

啥意思 没明白

**Comment by cuitzh** [comment]
![image](https://user-images.githubusercontent.com/25560862/183034985-85280aab-179a-4e7d-969a-3b83e2a24867.png)
showContent参数是bool变量

**Comment by cuitzh** [comment]
> > 加一个变量判断
> 
> 啥意思 没明白

http://deepoove.com/poi-tl/#_%E5%8C%BA%E5%9D%97%E5%AF%B9
文档说的很清楚了
