### ISSUE TITLE
关于单元格内循环时使用内置变量的问题

### ISSUE THREAD

**Issue by cuitzh** [Sayi/poi-tl#832]
### poi-tl version
1.12.0
### 想实现的功能
在表格单元格内循环集合时根据索引设置值颜色
![image](https://user-images.githubusercontent.com/25560862/183049312-020b857d-de88-4a8c-af6d-8b76cf9e13ea.png)
### 数据源
```json
{
    "list": [
        {
            "value0": "aaa"
        },
        {
            "strList": [
                "x",
                "y",
                "z"
            ]
        }
    ]
}
```
### 模板
![image](https://user-images.githubusercontent.com/25560862/183049868-5e6bbb7a-f717-4733-87b7-6361afdb6477.png)

### 问题
请问是否可以以这种方式设置文本颜色？

**Comment by Sayi** [comment]
不可以，标签的样式是唯一的。

**Comment by cuitzh** [comment]
> 不可以，标签的样式是唯一的。

ok
