### ISSUE TITLE
如何对表格文字设置自动换行、文字大小自适应？

### ISSUE THREAD

**Issue by YanceTimor** [Sayi/poi-tl#839]

**Comment by cuitzh** [comment]
模板里面，表格设置为固定列宽，文本不就自动换行了？

**Comment by YanceTimor** [comment]
![image](https://user-images.githubusercontent.com/15117654/184547119-13010089-d0aa-4ca4-8c20-2940b41135ef.png)
没啥用

**Comment by YanceTimor** [comment]
> 

有没有啥地方可以讨论讨论的啊

**Comment by cuitzh** [comment]
4

**Comment by huanlirui** [comment]
请问解决了吗？
