### ISSUE TITLE
是否支持复选框？

### ISSUE THREAD

**Issue by bingqingwu** [Sayi/poi-tl#843]
### Issue description
多个复选框，可以控制选中几个，不选中几个
### Minimal test code to reproduce the issue

```java

```

**Comment by Sayi** [comment]
#119 #276

**Comment by catlvsuger** [comment]
根据#276提示写了个简单的复选框实现，供参考：

**Comment by Strong-Gavin** [comment]
> 根据#276提示写了个简单的复选框实现，供参考： 1、插入单个复选框： @slf4j public class SingleCheckBoxPolicy implements RenderPolicy {
> 
> ```
> @Override
> public void render(ElementTemplate eleTemplate, Object data, XWPFTemplate xwpfTemplate) {
>     Boolean onOrOff = false;
>     if (null != data) {
>         onOrOff = (Boolean) data;
>     }
>     RunTemplate runTemplate = (RunTemplate)eleTemplate;
>     XWPFRun run = runTemplate.getRun();
>     OfficeConvertUtil.insertFormField(run,"FORMCHECKBOX", onOrOff);
> }
> ```
> 
> }
> 
> ```
> public static void insertFormField(XWPFRun run, String type, Boolean onOrOff) {
>     run.setText("", 0);
>     run.getCTR().addNewFldChar().setFldCharType(STFldCharType.BEGIN);
>     CTFFCheckBox checkbox = run.getCTR().getFldCharArray(0).addNewFfData().addNewCheckBox();
>     CTOnOff onOff = CTOnOff.Factory.newInstance();
>     onOff.setVal(onOrOff ? STOnOff.ON : STOnOff.OFF);
>     checkbox.setChecked(onOff);
>     run.getCTR().addNewInstrText().setStringValue(type);
>     run.getCTR().addNewFldChar().setFldCharType(STFldCharType.END);
> }
> ```
> 
> 2 批量插入复选框 -- 列 @slf4j public class MultipleCellCheckBoxPolicy implements RenderPolicy {
> 
> ```
> private String prefix;
> private String suffix;
> private boolean onSameLine;
> 
> public MultipleCellCheckBoxPolicy() {
>     this(false);
> }
> public MultipleCellCheckBoxPolicy(boolean onSameLine) {
>     this("[", "]", onSameLine);
> }
> 
> public MultipleCellCheckBoxPolicy(String prefix, String suffix, boolean onSameLine) {
>     this.prefix = prefix;
>     this.suffix = suffix;
>     this.onSameLine = onSameLine;
> }
> 
> @Override
> public void render(ElementTemplate eleTemplate, Object data, XWPFTemplate template) {
>     log.info("MultipleCellCheckBoxPolicy");
>     RunTemplate runTemplate = (RunTemplate) eleTemplate;
>     XWPFRun run = runTemplate.getRun();
>     try {
>         if (!TableTools.isInsideTable(run)) {
>             throw new IllegalStateException(
>                     "The template tag " + runTemplate.getSource() + " must be inside a table");
>         }
>         XWPFTableCell tagCell = (XWPFTableCell) ((XWPFParagraph) run.getParent()).getBody();
>         XWPFTableRow tableRow = tagCell.getTableRow();
>         XWPFTable table = tableRow.getTable();
>         run.setText("", 0);
>         int rowIndex = TableUtil.getRowIndex(tableRow);
>         int templateRowIndex =  onSameLine ? rowIndex : (rowIndex + 1);
>         int templateColIndex = TableUtil.getColIndex(tagCell);
> 
>         //data List， Map ， 按顺序赋值 将 [1] 替换成 checkBox ， 找到 []
>         //列赋值，获取根据所有行遍历
>         int rowSize = table.getRows().size();
>         if (data instanceof Map) {
>             Map map = (Map) data;
>             TemplateResolver resolver = new TemplateResolver(template.getConfig().copy(prefix, suffix));
>             for (int i = templateRowIndex; i < rowSize; i++) {
>                 XWPFTableRow row = table.getRow(i);
>                 XWPFTableCell templateCell = row.getCell(templateColIndex);
>                 if (TableUtil.parseCheckBox(template, map, resolver, templateCell, prefix, suffix)) {
>                     break;
>                 }
>             }
>         }
>     } catch (Exception e) {
>         throw new RenderException("HackLoopTable for " + eleTemplate + "error: " + e.getMessage(), e);
>     }
> }
> ```
> 
> } 3 批量插入复选框 -- 行 public class MultipleRowCheckBoxPolicy implements RenderPolicy {
> 
> ```
> private String prefix;
> private String suffix;
> private boolean onSameCol;
> 
> public MultipleRowCheckBoxPolicy() {
>     this(false);
> }
> 
> public MultipleRowCheckBoxPolicy(boolean onSameCol) {
>     this("[", "]", onSameCol);
> }
> 
> public MultipleRowCheckBoxPolicy(String prefix, String suffix, boolean onSameCol) {
>     this.prefix = prefix;
>     this.suffix = suffix;
>     this.onSameCol = onSameCol;
> }
> 
> @Override
> public void render(ElementTemplate eleTemplate, Object data, XWPFTemplate template) {
>     RunTemplate runTemplate = (RunTemplate) eleTemplate;
>     XWPFRun run = runTemplate.getRun();
>     try {
>         if (!TableTools.isInsideTable(run)) {
>             throw new IllegalStateException(
>                     "The template tag " + runTemplate.getSource() + " must be inside a table");
>         }
>         XWPFTableCell tagCell = (XWPFTableCell) ((XWPFParagraph) run.getParent()).getBody();
>         XWPFTableRow tableRow = tagCell.getTableRow();
>         run.setText("", 0);
>         //1.获取实际下标 templateColIndex
>         int colIndex = TableUtil.getColIndex(tagCell);
>         int templateColIndex =  onSameCol ? colIndex : (colIndex + 1);
>         //data List， Map ， 按顺序赋值 将 [1] 替换成 checkBox ， 找到 []
>         if (data instanceof Map) {
>             Map map = (Map) data;
>             Configure configure = template.getConfig().copy(prefix, suffix);
>             TemplateResolver resolver = new TemplateResolver(configure);
>             List<XWPFTableCell> tableCells = tableRow.getTableCells();
>             //2. 从实际列下标开始解析
>             for (int i = templateColIndex; i < tableCells.size(); i++) {
>                 XWPFTableCell templateCell = tableCells.get(i);
>                 if (TableUtil.parseCheckBox(template, map, resolver, templateCell, prefix, suffix)) {
>                     break;
>                 }
>             }
>         }
>     } catch (Exception e) {
>         throw new RenderException("HackLoopTable for " + eleTemplate + "error: " + e.getMessage(), e);
>     }
> }
> ```
> 
> }
> 
> 根据数据解析复选框 /** * 解析复选框 -- 结束解析返回true * @param template * @param map * @param resolver * @param templateCell * @return */ public static boolean parseCheckBox(XWPFTemplate template, Map map, TemplateResolver resolver, XWPFTableCell templateCell, String prefix, String suffix) { if (templateCell == null){ return true; } List templates = resolver.resolveBodyElements(templateCell.getBodyElements()); if (CollUtil.isNotEmpty(templates)) { for (MetaTemplate metaTemplate : templates) { String s = metaTemplate.toString(); if (!s.contains(prefix) || !s.contains(suffix)) { break; } String key = s.replace(prefix, "").replace(suffix, "").trim(); Object root; if (map.containsKey(key)) { root = map.get(key); } else { root = false; } SingleCheckBoxPolicy singleCheckBoxPolicy = new SingleCheckBoxPolicy(); singleCheckBoxPolicy.render((ElementTemplate) metaTemplate, root, template); } }else { return true; } return false; }
> 
> ```
> 多行插入模板格式：
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/39261781/261931147-dfc5a9d5-ac0b-4b6f-a5b5-5eb2a51ea5de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzI5NjUsIm5iZiI6MTcwNjA3MjY2NSwicGF0aCI6Ii8zOTI2MTc4MS8yNjE5MzExNDctZGZjNWE5ZDUtYWMwYi00YjZmLWE1YjUtNWViMmE1MWVhNWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA1MDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOWQ5YmJhYjJiYjZhN2FlYjhkNjk5YzE5ZmIyNTgxZTM3NzVmNWM2ODI1YWYxZmE3MmNmYjUzN2MzMjZjMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fLxIg37UsWeZhaIkJ5r3KVs3BF58O3J6bvxADrwvIRQ) 效果： ![image](https://private-user-images.githubusercontent.com/39261781/261931240-bc9b1caa-b9a2-4d39-9406-4e5281c0836c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzI5NjUsIm5iZiI6MTcwNjA3MjY2NSwicGF0aCI6Ii8zOTI2MTc4MS8yNjE5MzEyNDAtYmM5YjFjYWEtYjlhMi00ZDM5LTk0MDYtNGU1MjgxYzA4MzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA1MDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjODE2MzE3NmVmNjJkOWFhYjA3ZDExMzFjYTBkOTdhMjY5MjVkMDZmMDRhYjMwMTUxYjRmMDQ4ODVhOTQyMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lhJQm6yLAo8gOyOGJjg4-PGp_co__iqSVH85Sjqbr0w) 组装示例： if (StringUtils.isNotBlank(taxMode)) { Map<String, Object> box = new HashMap<>(); if (CommonConstant.ONE.equals(taxMode)) { box.put("2", true); } else if (CommonConstant.TWO.equals(taxMode)) { box.put("1", true); } else if (CommonConstant.ZERO.equals(taxMode)) { box.put("3", true); } map.put("box", box); } MultipleRowCheckBoxPolicy rowCheckBoxPolicy = new MultipleRowCheckBoxPolicy(true); Configure config = Configure.builder().bind("box", rowCheckBoxPolicy).build(); XWPFTemplate.compile(inputPath, config).render(map).writeToFile(outputPath);
> 
> ![image](https://private-user-images.githubusercontent.com/39261781/261933229-86a4c61e-f7ad-435b-a90d-d60a79b37f19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzI5NjUsIm5iZiI6MTcwNjA3MjY2NSwicGF0aCI6Ii8zOTI2MTc4MS8yNjE5MzMyMjktODZhNGM2MWUtZjdhZC00MzViLWE5MGQtZDYwYTc5YjM3ZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA1MDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5OWI1ODhjMGZlMGY2MDNkZWJiYjcyMWJlZDg3ZTA5YTIxNDk0MjJiMzU0MzkxYzQzN2QwYzNkMmJhMWYzY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iPNOMZAmoHTPnfmn0Qf5-mLf5jKTwOn95UW5-tZWYfY) ![image](https://private-user-images.githubusercontent.com/39261781/261933721-fba7e91a-0b04-46cc-b195-10a345b26bde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzI5NjUsIm5iZiI6MTcwNjA3MjY2NSwicGF0aCI6Ii8zOTI2MTc4MS8yNjE5MzM3MjEtZmJhN2U5MWEtMGIwNC00NmNjLWIxOTUtMTBhMzQ1YjI2YmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA1MDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ODNjMzNiZDNlYjEwZDI0ZGJiYmI0ODA5NGIzMmQzNjljOThlZjMxYjcxYjFkNjY0MTkzZGE4MDIyN2Y5MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SFpBGg5A_mE5VyUhXyMfQy5fH-sUgcEch6YIvkIilZM)

您好，参考你的代码，请问是不是少了TableUtil的部分代码，获取实际下标部分代码没有

**Comment by catlvsuger** [comment]
/**
     * 获取单元格所在行下标
     *
     * @param row
     * @return
     */
    public static int getRowIndex(XWPFTableRow row) {
        List<XWPFTableRow> rows = row.getTable().getRows();
        return rows.indexOf(row);
    }

**Comment by catlvsuger** [comment]
/**
     * 获取列下标
     *
     * @param cell
     * @return
     */
    public static int getColIndex(XWPFTableCell cell) {
        XWPFTableRow row = cell.getTableRow();
        List<XWPFTableCell> cells = row.getTableCells();
        for (int i = 0; i < cells.size(); i++) {
            if (cells.get(i) == cell) {
                return i;
            }
        }
        return -1;
    }

**Comment by Strong-Gavin** [comment]
> ```
> /**
>  * 获取列下标
>  *
>  * @param cell
>  * @return
>  */
> public static int getColIndex(XWPFTableCell cell) {
>     XWPFTableRow row = cell.getTableRow();
>     List<XWPFTableCell> cells = row.getTableCells();
>     return cells.indexOf(cell);
> }
> ```

好的 感谢

**Comment by Strong-Gavin** [comment]
@catlvsuger 请问参考您的代码，未生效，是需要模版中所有的复选框在独立的表格单元格吗，我目前的单元格是这样的
![image](https://github.com/Sayi/poi-tl/assets/17334234/b8227cf8-1a2e-4cd6-a7fc-152ce5b4ed90)
代码是这样的，但是最后生成没有生成

![image](https://github.com/Sayi/poi-tl/assets/17334234/af7875d0-e6f5-442e-b172-68111290277f)

**Comment by Strong-Gavin** [comment]
@catlvsuger 已解决，构造传入true,同列可以了
