### ISSUE TITLE
关于生成Word多级列表的问题

### ISSUE THREAD

**Issue by eimsteim** [Sayi/poi-tl#844]
### 我想在生成Word文档时，能够自动生成带格式的多级列表，例如：
1 xxxx
1.1 xxxx
1.1.1 xxxxx

目前官方的列表example中似乎都没有涉及到这种模式，然后我自己想尝试使用
```java
Numberings.of(NumberingFormat.DECIMAL).addItem(NumberingRenderData)
```
的方式来实现NumberingRenderData的嵌套，但是addItem方法似乎又不支持传入NumberingRenderData类型的参数……

请问有什么办法可以解决这个问题吗？

### poi-tl version
```xml
<dependency>
    <groupId>com.deepoove</groupId>
    <artifactId>poi-tl</artifactId>
    <version>1.12.0</version>
</dependency>
```

**Comment by Sayi** [comment]
ParagraphRenderData 实现了多级列表。

**Comment by eimsteim** [comment]
我仔细看了下ParagraphRenderPolicy，这是渲染一个段落的规则，可以包含不同样式文本，图片等，但是并没有说怎么实现多级列表……大佬可否给点具体的思路或者demo？

**Comment by Sayi** [comment]
参考下这个：https://github.com/Sayi/poi-tl/blob/master/poi-tl/src/test/java/com/deepoove/poi/tl/policy/DocumentRenderPolicyTest.java

**Comment by eimsteim** [comment]
> 参考下这个：https://github.com/Sayi/poi-tl/blob/master/poi-tl/src/test/java/com/deepoove/poi/tl/policy/DocumentRenderPolicyTest.java

确实可以用，多谢指导！
