### ISSUE TITLE
动态生成表格的demo似乎有点小问题

### ISSUE THREAD

**Issue by gzocs** [Sayi/poi-tl#849]
### Issue description
[动态生成表格的demo](http://deepoove.com/poi-tl/#plugin-dynamic-table)
按照demo上面的写法，在本机上运行之后，没有生成“货物明细”表
原来的写法：
代码：
![image](https://user-images.githubusercontent.com/40254500/187823200-a1fbb054-87ae-4173-ac6b-1d00c717bb9d.png)
模板：
![image](https://user-images.githubusercontent.com/40254500/187823785-e468d86f-1c98-4bd2-bdab-5199906d3513.png)

导出来的文档中“货物明细”的数据没有渲染出来，通过debug发现DetailTablePolicy下的render方法拿不到数据；
后来将**{{detail_table}}** 改为 **{{detailTable}}**，与PaymentData类属性保持一致是可以渲染的，一开始以为会按java的驼峰自动将detail_table自动转化为detailTable，后来经过与同事讨论之后才发现这个问题。不知道是不是之前也有人有类似的经历？
### poi-tl version
1.12.0
### Minimal test code to reproduce the issue

```java
Configure config = Configure.builder().bind("detailTable", new DetailTablePolicy()).build();
        XWPFTemplate template = XWPFTemplate.compile(new ClassPathResource("word/payment.docx").getInputStream(), config).render(datas);
        template.writeToFile("F:\\out_example_payment.docx");
```
### Minimal Docx template file
成功导出后：
![image](https://user-images.githubusercontent.com/40254500/187824656-46d1e969-cb3e-4c1a-a525-ff1856bcd720.png)

**Comment by Sayi** [comment]
没有问题，用了注解重命名。

```java
@Name("detail_table")
private DetailData detailTable;
```

**Comment by gzocs** [comment]
> 没有问题，用了注解重命名。
> 
> ```java
> @Name("detail_table")
> private DetailData detailTable;
> ```

IC，我把这个注解忽略了，这样应该是没问题，多谢解惑 :P
