### ISSUE TITLE
生成的文档wps打开正常，office打开，页数显示不全

### ISSUE THREAD

**Issue by SupHook** [Sayi/poi-tl#850]
wps打开在表格上面插入一个分页符后，office可以显示全了
尝试在模板中，表格上方插入一个分页符，生成后文件，office仍然显示不全，这是删除分页符，office又可以显示全了

**Comment by SupHook** [comment]
这是模板文件：
[template.docx](https://github.com/Sayi/poi-tl/files/9468873/template.docx)

**Comment by Sayi** [comment]
能提供最小化代码的单元测试吗？

**Comment by SupHook** [comment]
已经解决了，问题出现原因是创建表格时调用的API是：
Tables.ofWidth(14.55f, new double[4]).center().create();
每次在word打开时，都会在表格这地方无法显示
最后更换成
Tables.create(rowdata)
