### ISSUE TITLE
表格行循环内无法使用Spring EL表达式

### ISSUE THREAD

**Issue by KevinMcblack** [Sayi/poi-tl#852]
### Issue description
表格行循环内无法使用Spring EL表达式
循环行内使用标签 []，但此时无法再使用EL表达式，试过几种{{[xxx]==null}}等写法均不行

### Minimal test code to reproduce the issue

```java

```
### Minimal Docx template file

![image](https://user-images.githubusercontent.com/35475472/189014065-83f3b992-b061-4571-b05e-e35998b9545a.png)

**Comment by show1999** [comment]
我也在想这个问题，你解决了吗兄弟

**Comment by show1999** [comment]
我是因为没打开springEL表达式。。。
