### ISSUE TITLE
如何在区块对中实现使用自定义表格插件可以创建出不同行列的表格

### ISSUE THREAD

**Issue by long-sdk** [Sayi/poi-tl#853]
使用1.7.3版本。模板如下{{?list}}{{table}}{{/list}}   table是表格插件，循环list区块对，里面的每个table行列是不一样的，但是Configure只能build一次table,请问如何实现区块对中对于表格插件可以创建出不同的行列表格。测试代码如下：
public class DynamicTableRenderPolicy extends AbstractRenderPolicy<Object>{

    private int row;
    private int col;

    public DynamicTableRenderPolicy(){}

    public DynamicTableRenderPolicy(int row,int col){
        this.row = row;
        this.col = col;
    }

    @Override
    protected void afterRender(RenderContext<Object> context) {
        // 清空标签
        clearPlaceholder(context, true);
    }

    @Override
    public void doRender(RenderContext<Object> renderContext) throws Exception {
        XWPFRun run = renderContext.getRun();
        // 当前位置的容器
        BodyContainer bodyContainer = BodyContainerFactory.getBodyContainer(run);
        // 定义行列
//        int row = 9, col = 3;
        // 当前位置插入表格
        XWPFTable table = bodyContainer.insertNewTable(run, row, col);

        // 定义表格宽度、边框和样式
        TableTools.widthTable(table, MiniTableRenderData.WIDTH_A4_FULL, col);
        TableTools.borderTable(table, 4);

        TableTools.mergeCellsHorizonal(table, 0, 0, 1); //水平合并
        //同一列单元格合并某几行
// 合并第3列的第一行到第九行的单元格
        TableTools.mergeCellsVertically(table, 0, 1, 6); //垂直合并
        TableTools.mergeCellsVertically(table, 0, 7, 8);
    }

    public static void main(String[] args) throws IOException {

        Map<String,Object> map = new HashMap<>();

        ConfigureBuilder builder = Configure.newBuilder();
        builder.bind("table", new DynamicTableRenderPolicy(9,3));  //这只有一次导致创建表格每次都是9行3列
        List<Map<String,Object>> list = new ArrayList<>();
        Map<String,Object> map1 = new HashMap<>();
        Map<String,Object> map2 = new HashedMap();
        list.add(map1);
        list.add(map2);
        map.put("list",list);
        String templateFilepath = "C:\\Users\\Administrator\\Desktop\\temp\\template.docx";  
        String resultFilepath = "C:\\Users\\Administrator\\Desktop\\temp\\result.docx";
        XWPFTemplate.compile(templateFilepath, builder.build()).render(map).writeToFile(resultFilepath);

    }
}

**Comment by Sayi** [comment]
数据总不一样吧，根据数据来区分？

**Comment by long-sdk** [comment]
数据已经区分过了，关键是区块对里有多少个表格在写代码时是不确定的只能循环，而且每个表格的行列有多少个写代码时也是不知道的，只能根据size函数来动态计算

**Comment by Sayi** [comment]
所以能确定的是数据啊，根据数据来构建不同的表格。

**Comment by long-sdk** [comment]
{{?list}}{{table}}{{/list}}   这个里面的table有多少个是动态的，  不能在报告模板里写死{{table1}}{{table2}}{{table3}},所以我在这里使用区块对循环画表格
