### ISSUE TITLE
poi-tl支持区块+表格嵌套吗？

### ISSUE THREAD

**Issue by WFL-Tian** [Sayi/poi-tl#854]
我在做数据库文档生成器，数据库表和字段是两个不同对象，构造的数据结构为表对象，表对象中有表字段对象，所以返回的数据类型为一个表集合，这种后台要怎么构造对象，word模板中需要怎么写变量呢？（也就是我的一个对象中嵌套了一个list集合），使用的版本：Version 1.9.1，我现在的后端代码是这样的
DDocumentTableField 表信息
`public class DDocumentTableField {

    private String number;
    /**
     * 表名
     */
    private String tableName;
    /**
     * 表标注
     */
    private String tableComment;

    /**
     * 表信息
     */
    private List<DDocumentField> fieldList;
}`

DDocumentField表信息
`public class DDocumentField {

    /**
     * 序号
     */
    private String number;
    /**
     * 字段名称
     */
    private String comment;
    /**
     * 字段代码
     */
    private String field;
    /**
     * 字段类型
     */
    private String type;
    /**
     * 长度
     */
    private String length;
    /**
     * 是否为空
     */
    private String isNull;
    /**
     * 约束条件
     */
    private String constraint;
    /**
     * 备注
     */
    private String remarks;
}`

java代码
`Map<String,Object> params = new HashMap<>();
        params.put("projectBackground",projectBackground);
        // 数据库表数据
        params.put("tableFieldList",tableFieldList);

        HackLoopTableRenderPolicy policy = new HackLoopTableRenderPolicy();
        Configure config = Configure.builder()
                .bind("tableFieldList", policy)
                .build();

        XWPFTemplate template = XWPFTemplate.compile(templatePath, config).render(params);
        try {
            FileOutputStream out = new FileOutputStream(savePath);
            template.write(out);
            out.flush();
            out.close();
            template.close();
        } catch (Exception e) {
            e.printStackTrace();
        }`

word模板
![image](https://user-images.githubusercontent.com/24720561/189877052-6a0a508a-290c-4a93-a2b0-94fb119ad373.png)

**Comment by Sayi** [comment]
可以嵌套的，肉眼看起来好像没有什么问题，执行的时候看下日志中的ERROR信息。

**Comment by WFL-Tian** [comment]
已经解决，指定fieldList的策略为HackLoopTableRenderPolicy
这么写就对了：
`        HackLoopTableRenderPolicy policy = new HackLoopTableRenderPolicy();
        Configure config = Configure.newBuilder()
                .bind("tableFieldList", policy)
                .bind("fieldList", policy)
                .build();
        XWPFTemplate template = XWPFTemplate.compile(templatePath, config).render(params);`
