### ISSUE TITLE
请问如何插入一个目录？

### ISSUE THREAD

**Issue by grover572** [Sayi/poi-tl#858]
插入目录并且可根据标题更新目录的页码，请问这样的要怎么实现呢

**Comment by grover572** [comment]
已解决 https://github.com/Sayi/poi-tl/issues/541
实测 office打开word会提示更新域，但是WPS并不会，WPS需要在目录的地方右键手动更新域；

**Comment by AndyTalk** [comment]
@grover572  请问有具体的demo案例么？

**Comment by grover572** [comment]
https://github.com/Sayi/poi-tl/issues/541 用这个办法就可以的 直接引入TOCRenderPolicy插件即可
![image](https://user-images.githubusercontent.com/57468373/210970154-36b62c43-ee10-480b-8a60-e4d266dcaf0f.png)

**Comment by AndyTalk** [comment]
> #541 用这个办法就可以的 直接引入TOCRenderPolicy插件即可 ![image](https://user-images.githubusercontent.com/57468373/210970154-36b62c43-ee10-480b-8a60-e4d266dcaf0f.png)
好的，我试下 。谢谢啦
