### ISSUE TITLE
word里面的excel纵向合并单元格失败

### ISSUE THREAD

**Issue by 200T** [Sayi/poi-tl#859]
合并后文档
![image](https://user-images.githubusercontent.com/40780625/190956892-e4f9ffae-7582-4511-8369-15de0ccec65c.png)
拖拽线后
![aa27643f3f7798640ca8cb550a38ba3](https://user-images.githubusercontent.com/40780625/190956996-65fbb711-4bc3-4322-9b01-2e20dc5ace7d.jpg)
会变成这样
![image](https://user-images.githubusercontent.com/40780625/190957040-abd7bf5b-2ae6-480d-89d2-76191cb64e2a.png)
这是代码
String filePath = "D:\\poi-tl\\tableTest.docx";
        String targetPath =  "D:\\poi-tl\\tableTest2.docx";

        // 表头
        RowRenderData tableHead = Rows.of("姓名", "性别", "地址", "微信公众号").center().bgColor("4472c4").create();
        // 第一行
        RowRenderData row1 = Rows.create("张三", "男", "广东深圳", "liziba_98");
        // 第二行
        RowRenderData row2 = Rows.create("李四", "男", "广东深圳", "liziba_98");
        // 合并第一行和第二行的第二列与第三列
        MergeCellRule rule = MergeCellRule.builder().map(MergeCellRule.Grid.of(1, 1), MergeCellRule.Grid.of(2, 1))
                .map(MergeCellRule.Grid.of(1, 2), MergeCellRule.Grid.of(2, 2)).build();

        XWPFTemplate template = XWPFTemplate.compile(filePath).render(
                new HashMap<String, Object>() {
                    {
                        put("table", Tables.of(tableHead, row1, row2).mergeRule(rule).center().create());
                    }
                });
        template.writeAndClose(new FileOutputStream(targetPath));
影响：转pdf时，隐藏的区域会显示出来
版本：1.8和1.11都试过

**Comment by Sayi** [comment]
最新版无法重现。

**Comment by Sayi** [comment]
最新版无法重现。
