### ISSUE TITLE
扩展了word表格嵌套图片的RenderPolicy

### ISSUE THREAD

**Issue by aofavx** [Sayi/poi-tl#86]
我需要在word的表格中嵌套图片和文字，但直接实现RenderPolicy的方法不行。你RenderAPI中做了是否是DocxRenderPolicy的判断。
现在继承了 DocxRenderPolicy 方法。增加了word嵌套图片的扩展，能提交到你的代码么

**Comment by Sayi** [comment]
你可以提交个Pull Request。

**Comment by Sayi** [comment]
#106
