### ISSUE TITLE
请教，使用组合图表渲染时，如何自定义图表两边的坐标和刻度

### ISSUE THREAD

**Issue by hdlmx** [Sayi/poi-tl#860]
### Issue description
例如途中，我想在左侧显示的是柱状图的数量，右侧显示的是占比
![image](https://user-images.githubusercontent.com/13895242/191148368-9fee7d3f-9975-4c6a-8be3-42190db66964.png)

### Minimal test code to reproduce the issue

```java

```

**Comment by Fourteen-579** [comment]
请问你现在有结果了吗？

**Comment by Sayi** [comment]
Auto closed.
