### ISSUE TITLE
请教，word中生成table的行高设置问题

### ISSUE THREAD

**Issue by Techmile** [Sayi/poi-tl#862]
### 如图所示，RowRenderData中设置的height属性，似乎是作用在表格的外框线上，如果表中的文本设置的行高是3，那么该属性只能在大于行高的情况下生效。我想问的是有没有办法调整表格中文本的行高，而不是外部框线的高度
![image](https://user-images.githubusercontent.com/17844251/191481655-a8744e46-9c3f-4e99-9b5e-30c833c020d0.png)
![image](https://user-images.githubusercontent.com/17844251/191481851-6259a113-891d-4743-89f0-d781042fb8c6.png)

### Minimal test code to reproduce the issue

```
RowRenderData[] rowRenderDataArray = new RowRenderData[this.tableData.length];
//设置表头
 rowRenderDataArray[0] = BuildRow.buildDefaultHeader().build(tableData[0]);
//设置表内容
for (int j = 1; j < tableData.length; j++) {
       rowRenderDataArray[j] = BuildRow.buildDefaultContent().build(tableData[j]);
 }
Tables.create(rowRenderDataArray)
```

**Comment by Sayi** [comment]
调整表格内段落行距即可。
