### ISSUE TITLE
TextRenderData可以设置字体大小为五号吗？

### ISSUE THREAD

**Issue by ufo-21** [Sayi/poi-tl#865]

**Comment by humphreygao** [comment]
Texts.of("XXX").fontSize(10.5).create()

**Comment by yuanay** [comment]
> Texts.of("XXX").fontSize(10.5).create()

你好，很抱歉是我弄错了，我是想设置表格的字体大小
RowRenderData row0 = Rows.of("姓名", "学历").textFontSize(10.5).create();
但是textFontSize()只支持int类型

**Comment by humphreygao** [comment]
> > Texts.of("XXX").fontSize(10.5).create()
> 
> 你好，很抱歉是我弄错了，我是想设置表格的字体大小 RowRenderData row0 = Rows.of("姓名", "学历").textFontSize(10.5).create(); 但是textFontSize()只支持int类型
基于我提示的Texts.of("XXX").fontSize(10.5).create()
```java
RowRenderData tableHeaderRow = Rows.of(
                        Texts.of("列名1").fontSize(10.5).create(),
                        Texts.of("列名2").fontSize(10.5).create(),
                        Texts.of("列名3).fontSize(10.5).create()
            )
            .create();
```
不就好了

**Comment by yuanay** [comment]
> > > Texts.of("XXX").fontSize(10.5).create()
> > 
> > 
> > 你好，很抱歉是我弄错了，我是想设置表格的字体大小 RowRenderData row0 = Rows.of("姓名", "学历").textFontSize(10.5).create(); 但是textFontSize()只支持int类型
> 
> 基于我提示的Texts.of("XXX").fontSize(10.5).create()
> 
> ```java
> RowRenderData tableHeaderRow = Rows.of(
>                         Texts.of("列名1").fontSize(10.5).create(),
>                         Texts.of("列名2").fontSize(10.5).create(),
>                         Texts.of("列名3").fontSize(10.5).create()
>             )
>             .create();
> ```
> 
> 不就好了

感谢！
