### ISSUE TITLE
表格列循环，第一列空白

### ISSUE THREAD

**Issue by ufo-21** [Sayi/poi-tl#871]
模板：
![image](https://user-images.githubusercontent.com/62231340/195022694-89fe3f01-25b0-4bc6-b534-24d97ff95957.png)
代码：
LoopColumnTableRenderPolicy columnPolicy = new LoopColumnTableRenderPolicy();
Configure config = Configure.builder().bind("goods", policy).build();
XWPFTemplate template = XWPFTemplate.compile(resource, config).render(
  new HashMap<String, Object>() {{
      put("goods", goods);
    }}
);
![image](https://user-images.githubusercontent.com/62231340/195023362-d1fce9d7-24d1-49c7-9cac-dd15d71aa48f.png)
请教各位大佬，如何得到我想要的效果

**Comment by Sayi** [comment]
可以提供个最简单的testcase来复现这个问题吗？

**Comment by ufo-21** [comment]
> 可以提供个最简单的testcase来复现这个问题吗？

已经用其他方法实现了，谢谢
