### ISSUE TITLE
[Word] Merge multilevel list with nested document

### ISSUE THREAD

**Issue by RepublicOfGitHub** [Sayi/poi-tl#872]
### Issue description
I have a problem about it. The parent document has multilevel list and I need it merged with nested document.
![image](https://user-images.githubusercontent.com/73865861/195317112-ef5ed191-27b1-427d-97ea-bdfe4e53d9a9.png)
The multilevel list (number) should be dynamic because there are only some parts in document need it.
When I insert as normal nested document (the word "bar"), it likes below
![image](https://user-images.githubusercontent.com/73865861/195318298-a73dff06-db27-4c21-a186-b67af5856039.png)
Expected behave
![image](https://user-images.githubusercontent.com/73865861/195318548-9681fe1b-003c-40f2-945c-70c0c78f4b5a.png)
@Sayi Please help me :<
Is it possible? Any idea is appreciate!
P/S: The previous multilevel list number cannot be controlled, and the sub-document must have dynamic multilevel list. Sometimes I use WPS Office, it behaves like I need. But I need it works in Microsoft Word.
### poi-tl version
<artifactId>poi-tl</artifactId>
 <version>1.12.0</version>
 
 <maven.compiler.target>17</maven.compiler.target>
(poi-tl version 1.12.0, Java 17)
### Minimal test code to reproduce the issue
```java
import com.deepoove.poi.XWPFTemplate;
import com.deepoove.poi.data.Includes;

import java.io.IOException;
import java.util.*;

public class App2 {
    public static void main(String[] args) throws IOException {
        class AddrModel {
            private String addr;
            public AddrModel(String addr) {
                this.addr = addr;
            }
        }

        List<AddrModel> subData = new ArrayList<>();
        subData.add(new AddrModel("bar"));
        XWPFTemplate.compile(App.class.getClassLoader().getResourceAsStream("template.docx")).render(new HashMap<String, Object>() {{
            put("nested", Includes.ofStream(getClass().getClassLoader().getResourceAsStream("sub.docx")).setRenderModel(subData).create());
        }}).writeToFile("/tmp/aa_out_template.docx");

    }
}
```
### Minimal Docx template file
[template.docx](https://github.com/Sayi/poi-tl/files/9764047/template.docx)
[sub.docx](https://github.com/Sayi/poi-tl/files/9764054/sub.docx)
Input: "template.docx" file and "sub.docx" file I put directly in "resources" folder
Output: /tmp/aa_out_template.docx
![image](https://user-images.githubusercontent.com/73865861/195322189-6e3e41c1-7e24-4086-9ec1-63e9eb639a0d.png)

**Comment by Sayi** [comment]
Can you use section to do this?

Section can preserve the list level.

**Comment by RepublicOfGitHub** [comment]
> Can you use section to do this?
> 
> Section can preserve the list level.

Thanks, I will try it now

**Comment by RepublicOfGitHub** [comment]
> Can you use section to do this?
> 
> Section can preserve the list level.

@Sayi 
I tried it, but it didn't work 😥
![ảnh](https://user-images.githubusercontent.com/73865861/196044939-8a680ab9-7ee9-43fa-9a80-4fb039c44bb5.png)
I also tried to add list level to sub-document but it still didn't work.
![ảnh](https://user-images.githubusercontent.com/73865861/196044994-c98226a3-cfef-41b8-ae0e-84ee4e562208.png)
P/S: The previous multilevel list number cannot be controlled, and the sub-document must have dynamic multilevel list.

**Comment by Sayi** [comment]
I still think section is the best choice.
See the demo: [NumberingContinueTest](https://github.com/Sayi/poi-tl/blob/master/poi-tl/src/test/java/com/deepoove/poi/tl/render/NumberingContinueTest.java)

**Comment by RepublicOfGitHub** [comment]
> I still think section is the best choice. See the demo: [NumberingContinueTest](https://github.com/Sayi/poi-tl/blob/master/poi-tl/src/test/java/com/deepoove/poi/tl/render/NumberingContinueTest.java)

Using this method, my problem becomes similar with #403 
So I have to find another way to solve it (bad hard coding :<).
