### ISSUE TITLE
有没有对填写的设置的标签做验证的方法？

### ISSUE THREAD

**Issue by MulderLiu** [Sayi/poi-tl#876]
### Issue description
如果模版中标签多写了一个空格 比如{{myname}}写成了{{my name}} 想要给个错误提示出来说标签写错了，要怎么处理？ 有上面方法吗？ 

### poi-tl version 1.12.0

**Comment by Sayi** [comment]
可以XWPFTemplate编译后，渲染前对所有标签进行校验和处理，参考这段代码：
```java
new LogProcessor().process(template.getElementTemplates());
```
