### ISSUE TITLE
[Feature Request] Allow to access root model in {? } blocks

### ISSUE THREAD

**Issue by mojo2012** [Sayi/poi-tl#877]
Hi,

I have the following scenario:

`builder.useSpringEL(false)` 

Model:
```
{
    "entries: {
        "main": "mainEntry",
        "secondary": "useless"
    },
    "customer": {}
}
```

Template:
```
{{? customer}}
    {{entries.main}}
}}
```

The goal is to only show the `entries.main` if the `customers` are set. But it seems that within the customers block there is no way to access outside data. 
Is there a simple way to inject the parent into the `?` block?

I was debugging a bit and found the `SpELRenderDataCompute` which I think I could change to return the root model in case the template is a `?` block. The `#this` element would still allow to access the block's internal object. I think this would be much more clean anyway. Although it poses one question: what would happen with nested blocks.

One way would be to have a `#parent` or a `#root` element as well.

**Comment by mojo2012** [comment]
I added support for `#root` (which should be available in SpEL I guess) by injecting my own `CustomSpELRenderDataCompute` that fetches the initial root context object from a threadlocal variable. It's a quick and dirty hack to get access to the root object without having to massively refactor everything to be able to inject it properly.

It looks like this in the template: `{{=#root.start.streetName}}`

But it would be nice if this was supproted out of the box!

**Comment by mojo2012** [comment]
Initially I created the config object at start but I refactored it to always create a new config to set the datacompute every time, already prepopulated with the root context object. This is much nicer and safer, and gets rid of the threadlocal.

**Comment by Sayi** [comment]
Can you provide a pull request? This really has a great feature.

**Comment by Sayi** [comment]
#589

**Comment by mojo2012** [comment]
He sorry, I actually totally forgot about this. I will post my code here when I find some time.
