### ISSUE TITLE
建议批注的接口添加如下功能

### ISSUE THREAD

**Issue by beimengyeyu** [Sayi/poi-tl#881]
目前的批注接口已经很完美了，可以适配绝大部分场景。但是如下场景没办法满足，

我有一段文本 “你好的” 需要在给 “你好” 和 “好的”分别添加批注，目前提供的接口貌似没办法实现这个（如果可以实现请教一下如何实现）

因此建议批注可以添加类似于 可以选择 start-end的文字进行批注的功能

**Comment by Sayi** [comment]
“选择 start-end的文字进行批注的功能”  这种不好制作模板吧？有什么建议吗

**Comment by beimengyeyu** [comment]
> “选择 start-end的文字进行批注的功能” 这种不好制作模板吧？有什么建议吗

感谢您的回复。我理解：
目前在构造CommentRenderData的时候使用addText()添加的要批注文本，可否提供一些别的途径选择批注文本的形式，把选择批注文本的这个过程独立出来，比如start-end的这种形式，当然start-end 不一定是整数，可能就是word上面可以唯一标记一个元素位置的坐标（我以前也没研究过，看看作者有没有好的想法或者思路）。

PS：上述需求我通过自定义插件实现了，再次感谢您的项目提供了这么简介易用的API以及良好的可读性的代码。

**Comment by hunfwj** [comment]
> 

我最近遇到了类似的需要选取start-end的需求。

我通过在DocumentRenderPolicy增加CustomCommentRenderPolicy策略， 该策略只负责在文档中添加comment内容， 但是不处理批注和内容的关联。

关联的方式采用了， 批注的getInitials设定一个唯一值对应起来。

然后我抽象了CustomCommentRangeRenderPolicy， 该策略从文档的comments中找到对应的批注， 并在当前位置根据开始还是结束的标记位 插入insertNewCommentRangeStart 或者 insertNewCommentRangeEnd。 

不知道这个方式能不能作为通用的策略置入的开源库。

PS： 以上部分参考您的Comment RenderPolicy， 感谢您的开源代码。
