### ISSUE TITLE
使用altChunk时，异常

### ISSUE THREAD

**Issue by clxy** [Sayi/poi-tl#882]
### Issue description
使用altChunk时，抛出异常
org.apache.xmlbeans.XmlException
xml-fragment没有对应的</xml-fragment>

### poi-tl version
1.12.0

### Minimal test code to reproduce the issue

```java

```
### Minimal Docx template file

调查了下，似乎是
在使用altChunk时，xml是这样的
```xml
  <w:p><w:p><w:r /></w:p><w:altChunk r:id="chunk1" /></w:p>
```

在
XmlXWPFDocumentMerge#truncatedOverlapWP
该方法中有如下置换

```java
xmlText = xmlText.replaceAll("<w:p><w:p>", "<w:p>")
```

会导致 <w:p> 这个tag的缺失
```xml
  <w:p><w:r /></w:p><w:altChunk r:id="chunk1" /></w:p>
```

**Comment by Sayi** [comment]
换了一种字符串替换算法，应该会彻底解决此类问题。
