### ISSUE TITLE
wps创建的模板文件运行插入图片和表格的时候报错

### ISSUE THREAD

**Issue by zackzergzeng** [Sayi/poi-tl#886]
[test模板-复杂的副本2.docx](https://github.com/Sayi/poi-tl/files/9867544/test.-.2.docx)
![image](https://user-images.githubusercontent.com/42129897/197974208-d980972c-0799-4a23-b939-d1c0c24287b8.png)

**Comment by Sayi** [comment]
没有设置页边距，无法计算出页面宽度，从而无法计算表格的百分比宽度。

如果固定页面宽度的话，你的表格宽度可以不用百分比。

**Comment by zackzergzeng** [comment]
我没有刻意的设置页面和表格的宽度，而且word创建文件没有这个问题，所以我需要设置一个固定页面宽度吗？

**Comment by zackzergzeng** [comment]
或者说，如果我在模板上设置了页面距就没有问题了对吧

**Comment by zackzergzeng** [comment]
设置了页面宽度就解决了，感谢。
（但是感觉需要优化下提示，这个报错我没法知道是页面宽度有问题……）

**Comment by Sayi** [comment]
代码处理了下空指针，这个只会在表格设置百分比或者图片设置FIT自适应时，并且无法计算页面宽度时候才会出现。
