### ISSUE TITLE
合并文档后样式过多，是否能够合并样式

### ISSUE THREAD

**Issue by charlieDJ** [Sayi/poi-tl#891]
多个文档是同一个模板生成的，模板内有样式。合并文档后，样式没有合并，这个细节能够优化吗？

版本是1.12.0

[报告模板_03.docx](https://github.com/Sayi/poi-tl/files/9920074/_03.docx)

**Comment by Sayi** [comment]
#823 参见这个PR，可以控制是否合并样式。

**Comment by Danst-bjtu** [comment]
> #823 参见这个PR，可以控制是否合并样式。

我下载了1.10.4版本的jar包，发现PR的代码没有出现在jar包相应文件中，请问我怎么才能应用这个PR的代码呢？

**Comment by Sayi** [comment]
还没有发布新版本。

[#822](https://github.com/Sayi/poi-tl/issues/822#issuecomment-1217512560) 也可以参见这个问题，最后重设下样式。

**Comment by Danst-bjtu** [comment]
> 还没有发布新版本。
> 
> [#822](https://github.com/Sayi/poi-tl/issues/822#issuecomment-1217512560) 也可以参见这个问题，最后重设下样式。

这个就是我目前使用的方式，但是https://github.com/Sayi/poi-tl/pull/823这种方式是每次在合并到主模板是就合并样式，而我目前使用的方式是在所有文档合并完之后在将样式统一合并，主要怕目前这种最后统一合并的方式会对文档创建效率产生影响，因为越往后面样式堆积越多，内存应该也会越占越多吧？时间上不知道会不会造成影响。而https://github.com/Sayi/poi-tl/pull/823这种似乎就不用考虑这种样式堆积问题，因为每次合并后都不会产生新的样式。

**Comment by Danst-bjtu** [comment]
> 还没有发布新版本。
> 
> [#822](https://github.com/Sayi/poi-tl/issues/822#issuecomment-1217512560) 也可以参见这个问题，最后重设下样式。

这个就是我目前采用的方式。一个是每次合并就合并样式了，这样就不会有新的样式产生，也就不会造成样式堆积；而采用另一种先合并所有文档，最后在对样式做合并，会造成产生文档创建过程中样式不断变多，占用内存不断增大，这会不会也是影响导出效率变慢的因素之一呢？

**Comment by Sayi** [comment]
@Danst-bjtu 如果主模板和子模板样式一致，那不合并样式才是最佳的选择。

**Comment by Danst-bjtu** [comment]
> @Danst-bjtu 如果主模板和子模板样式一致，那不合并样式才是最佳的选择。

https://github.com/Sayi/poi-tl/issues/822#issue-1313344316 ， 因为使用的是嵌套标签，就算嵌套模板中的样式与主模板样式一致，也会带进来新样式
![image](https://user-images.githubusercontent.com/77576766/201822829-4c3b297d-e695-493f-9f73-c302566e8661.png)
这个样式虽然影响可能不大，但是还是被合并了好
