### ISSUE TITLE
对子模版渲染数据后，再将子模版嵌套到主模版中报错

### ISSUE THREAD

**Issue by MRgenial** [Sayi/poi-tl#892]
`@Test
    public void test2() throws IOException {
        List<Map<String,Object>> outList = new ArrayList<>();

        Map<String,Object> map1 = new HashMap<>();
        map1.put("dataCenterName","测试1");
        map1.put("dataResult","{{+dataOne}}");
        Map<String,Object> map2 = new HashMap<>();
        map2.put("dataCenterName","测试2");
        map2.put("dataResult","{{+dataTwo}}");
        outList.add(map1);
        outList.add(map2);
        Map<String,Object> map = new HashMap<>();
        map.put("dataCenter",outList);
        Resource resource = new ClassPathResource("template/TestTemplate.docx");
        InputStream inputStream=resource.getInputStream();
        XWPFTemplate parentTemplate = XWPFTemplate.compile(inputStream).render(map);

        //处理子模版
        Resource resourceChild = new ClassPathResource("template/ScenariosTemplate.docx");
        InputStream inputStreamChild=resourceChild.getInputStream();
        Map<String,Object> clearMap = new HashMap<>();
        //设置区块对为false
        clearMap.put("truncation",false);
        //渲染子模版，将子模版区块对中的内容删除掉
        XWPFTemplate renderChild = XWPFTemplate.compile(inputStreamChild).render(clearMap);
        //将渲染后的子模版转为输入流
        InputStream inputStream2 = PoitlIOUtils.docToInputStream(renderChild.getXWPFDocument().generate());
        //将输入流生成为渲染数据
        DocxRenderData docxRenderData = Includes.ofStream(inputStream2).create();
        //将两个子模版渲染到主模版的嵌套中
        Map<String,Object> childMap = new HashMap<>();
        childMap.put("dataOne",docxRenderData);
        childMap.put("dataTwo",docxRenderData);
        //得到最终结果
        XWPFTemplate result = XWPFTemplate.compile(parentTemplate.getXWPFDocument().generate()).render(childMap);

        //>>>>>>>>>>>>>写入文件流（省略）>>>>>>>>>>>>>>>>>
    }`
<img width="1490" alt="iShot2022-11-03 10 29 10" src="https://user-images.githubusercontent.com/49973336/199637277-478c4fe6-b899-4270-8552-b200bc6359b9.png">

**Comment by Sayi** [comment]
可以提供个能复现的最小单元测试吗？

**Comment by Sayi** [comment]
这个应该已经彻底在master解决了。
