### ISSUE TITLE
怎么设置中西文不同字体

### ISSUE THREAD

**Issue by ai-sauce** [Sayi/poi-tl#893]
怎么设置中西文不同字体

**Comment by ai-sauce** [comment]
一段话总中西文结合，怎么设置中文一个字体西文一个字体

**Comment by Sayi** [comment]
Style里面有两个设置项，分别是中文字体和西文字体。

**Comment by ai-sauce** [comment]
那个版本，我没看到有

**Comment by ai-sauce** [comment]
使用TextRenderData给文字设置格式，Style设置文件样式，setFontFamily设置中文样式，setWesternFontFamily设置西文样式
