### ISSUE TITLE
图表如何实现底部坐标轴多列（界面上多行）数据显示？

### ISSUE THREAD

**Issue by MungJI** [Sayi/poi-tl#895]
图表进行编辑数据，如图能选择排名列和姓名列，到图表上就显示第一行为姓名，姓名下为排名，这要怎么实现？

![编辑数据](https://user-images.githubusercontent.com/45352612/200756290-ee65625f-2389-4ca5-b13e-28412576f359.jpg)
![界面](https://user-images.githubusercontent.com/45352612/200756310-b1a4ea33-7f4c-4611-9236-00fc00fc3c9c.jpg)

原创建chart对象只能传一个数组（orgNameRank为姓名字符串），显示不了两行效果
代码如下：
ChartMultiSeriesRenderData chart = Charts
                    .ofComboSeries(chartTitle, orgNameRank)
                    .addBarSeries("得分", scoreArray)
                    .addLineSeries("平均分", new Double[]{avg, avg, avg, avg, avg, avg, avg, avg, avg})
                    .addLineSeries("标准分", new Double[]{weightD, weightD, weightD, weightD, weightD, weightD, weightD, weightD, weightD})
                    .create();

**Comment by Sayi** [comment]
当前不支持。
