### ISSUE TITLE
1.12版本XWPFTemplate.create创建文件没有布局

### ISSUE THREAD

**Issue by 15542688830** [Sayi/poi-tl#897]
DocumentRenderData data = Documents.of().create();
data.add  XXXX各种
XWPFTemplate template = XWPFTemplate.create(data);

正常创建文件 文件解压打开后没有相关布局的配置文件导致错误

![0658b24eb927224d244fc0ebf5b9aa1](https://user-images.githubusercontent.com/29878065/201640482-720a0dde-b679-46c0-95c2-e3d94f72c4b7.png)

麻烦问下可能是什么导致的

我怀疑包冲突导致  还请大佬解惑

或者如何在创建文件的时候加入布局也可以

**Comment by Sayi** [comment]
代码创建默认都是没有布局的，设置布局应该也比较复杂，建议用空模板实现你的逻辑。

**Comment by Sayi** [comment]
这种情况建议自己创建文档。
