### ISSUE TITLE
实现了一个虚假的目录插件，是否可以收录

### ISSUE THREAD

**Issue by bajie-git** [Sayi/poi-tl#899]
poi在目录这块一直没有太好的解决办法尤其是页码问题，现有的目录插件是更新域的方式实现的 

最近实现了一个虚假的目录，他没有页码但是其他功能是正常的例如跳转，效果图
![image](https://user-images.githubusercontent.com/63085735/202597621-aa1338a5-da34-4f0f-aa1c-663fd5de4438.png)

这个插件和原始的页码插件各有特点所以，可以的话我会提交一个pr  大家一起完善他

**Comment by Sayi** [comment]
Great Job!  欢迎提交PR。

**Comment by Sayi** [comment]
#901
