### ISSUE TITLE
请问如何使用区块对循环生成多级列表？

### ISSUE THREAD

**Issue by Danst-bjtu** [Sayi/poi-tl#904]
NumberingRenderData可以创建多级列表，但是推荐使用区块对：区块对的循环功能可以很好的循环列表，并且保持有序列表编号有序。
请问使用区块对循环生成多级列表有示例代码吗？

**Comment by baizizai1118** [comment]
List<Test> sample;
public class Test{
  private String test1;
  private String test2;
}

renderData.put("name",sample)

{{?name}}//循环sample集合
  {{test1}}//对象中的属性名
  {{test2}}
{{/name}}

**Comment by Sayi** [comment]
http://deepoove.com/poi-tl/#example-swagger
