### ISSUE TITLE
可以动态插入附件吗？

### ISSUE THREAD

**Issue by solomanwang** [Sayi/poi-tl#906]
### Minimal test code to reproduce the issue

```java

```

**Comment by hzauitdog** [comment]
这个插入附件的功能只能插入word和excel。我们项目有个需求要插入pdf,dwg等各种附件，我是修改了一小部分源码，附件对象，用的是另外一个库杂交出来的，并且只能用wps打开。希望大佬能完善这个导出附件的功能

**Comment by hzauitdog** [comment]
<dependcy>
<groupId>com.groupdocs</groupId>
<artifactId>groupdocs-merger</artifactId>
<version>20.7</version>

**Comment by solomanwang** [comment]
> 这个插入附件的功能只能插入word和excel。我们项目有个需求要插入pdf,dwg等各种附件，我是修改了一小部分源码，附件对象，用的是另外一个库杂交出来的，并且只能用wps打开。希望大佬能完善这个导出附件的功能

可以把word文件和pdf打在同一个目录里面用链接的形式打开

**Comment by Sayi** [comment]
#733
