### ISSUE TITLE
可否将EmbeddedPictures分类保存？

### ISSUE THREAD

**Issue by Nondirectional** [Sayi/poi-tl#909]
NiceXWPFDocument::readRun将文档中的所有Picture都存入到了allPicture中，但是我在使用中遇到了有业务需要区分header和footer的Picture做处理，因为他们需要分别建header和footer的RelationShip，所以readParagrphs和readTables的操作我还需要再做一次。

有没有可能把allPictures分成headerPictures、footerPictures、documentPictures

**Comment by Sayi** [comment]
暂时没有计划。
