### ISSUE TITLE
合并文档如果word版本不同会出现合并后的文件打不开的情况。

### ISSUE THREAD

**Issue by jerycn** [Sayi/poi-tl#91]
合并文档如果word版本不同，或文档中存在一些图片，或某些版本的docx文件，会出现合并后的文件打不开的情况。
具体情况很多种，但出现的几率还挺大的。

**Comment by Sayi** [comment]
没有验证过不同版本文档之间的合并，也不建议不同版本文档合并，未知问题可能比较多。
