### ISSUE TITLE
表格循环列一直空指针异常

### ISSUE THREAD

**Issue by baobaozhou** [Sayi/poi-tl#910]
[模板.docx](https://github.com/Sayi/poi-tl/files/10139163/default.docx)
### Issue description
在word表格中需要使用表格循环列生成报错，即使指定了表格宽度及数据存在的情况

### Minimal test code to reproduce the issue
LoopColumnTableRenderPolicy lie = new LoopColumnTableRenderPolicy();
 Configure config = Configure.builder()
                .bind("analystList", lie)
                .build();
 InputStream inputStream = new ClassPathResource("templates/模板.docx").getInputStream();
 XWPFTemplate template = XWPFTemplate.compile(inputStream, config);
 Map<String, Object> data = new HashMap<>();
 List<Object> objects = new ArrayList<>(2);
 data.put("analystList", objects);
  for (int i = 0; i < 2; i++) {
            HashMap<Object, Object> map = new HashMap<>();
            map.put("time", "2020年12月2日13时41分");
            map.put("name", "氧气含量");
            map.put("data", "100ML/平方");
            map.put("people", "张三");
            objects.add(map);
        }
 template.render(data);
```java

```
### Minimal Docx template file

**Comment by show1999** [comment]
可以参考poi-tl文档的这部分[DynamicTableRenderPolicy](http://deepoove.com/poi-tl/#plugin-dynamic-table)，自定义个插件策略，我之前有写过 可以实现。

**Comment by Sayi** [comment]
目前的循环列不能合并单元格。

**Comment by zhouliuhuo** [comment]
> 可以参考poi-tl文档的这部分[DynamicTableRenderPolicy](http://deepoove.com/poi-tl/#plugin-dynamic-table)，自定义个插件策略，我之前有写过 可以实现。

使用文档里的DetailTablePolicy例子，为什么我新生成出来的表格没有边框？
insertNewTableRow.createCell();这样的插入方式效果是未知的。
还是我缺少什么设置吗？

**Comment by lifan970507** [comment]
> 目前的循环列不能合并单元格。

循环列的前一列也不能出现合并单元格吗，会报同样的错误
![image](https://github.com/Sayi/poi-tl/assets/42936726/b121f1b9-d291-4876-ae15-c893823c7798)
