### ISSUE TITLE
区块对中增加动态表格，模板如果有目录动态表格会失效

### ISSUE THREAD

**Issue by bajie-git** [Sayi/poi-tl#914]
# 模板文件
![image](https://user-images.githubusercontent.com/63085735/207584928-2e79c6e3-3312-4824-aff5-e62c281febcf.png)

#  代码
```java
@Test
    public void test() throws Exception {
        FileInputStream oriWordInput = new FileInputStream("D:/temp/RiskReportTest1.docx");
        FileOutputStream tarWordOutput = new FileOutputStream("D:/temp/RiskReportTest1-ok.docx");

        List<Good> goods = new ArrayList<>();

        for (int i = 0; i < 50; i++) {
            Good good = new Good();
            good.setA("a" + i);
            good.setB("b" + i);
            good.setC("c" + i);
            good.setD("d" + i);
            goods.add(good);
        }

        Configure config = Configure.builder()
                .bind("detailListVo", new DetailTablePolicy())
                .build();

        XWPFTemplate template = XWPFTemplate.compile(oriWordInput, config).render(
                new HashMap<String, Object>() {{
                    put("goods", goods);
                }});

        template.write(tarWordOutput);
    }


public class DetailTablePolicy extends DynamicTableRenderPolicy {

  @Override
  public void render(XWPFTable table, Object data) throws Exception {
    if (null == data) return;
  }
}
```

# 效果
## 模板中有目录
![image](https://user-images.githubusercontent.com/63085735/207585852-5c281146-dd1a-4976-9d59-539679936a80.png)

**Comment by bajie-git** [comment]
## 模板中无目录
![image](https://user-images.githubusercontent.com/63085735/207592200-735f9cd9-a840-413d-830c-921c50a7536c.png)

**Comment by bajie-git** [comment]
发现和动态表格插件无关，只要区块对中包含了表格，并且模板中有目录，区块对循环就不会循环表格

**Comment by bajie-git** [comment]
调试发现，插入目录后bodyElements集合最后会多一个元素，导致insertNewParagraph方法无法准确的在指定游标前面插入段落
![image](https://user-images.githubusercontent.com/63085735/207771241-96140cb6-c6c5-41c0-8553-d8dc7574dd0c.png)

**Comment by Sayi** [comment]
模版发一下？

**Comment by bajie-git** [comment]
我不知道改怎么回复文件

**Comment by bajie-git** [comment]
[RiskReportTest1.docx](https://github.com/Sayi/poi-tl/files/10235676/RiskReportTest1.docx)


> 模版发一下？

**Comment by bajie-git** [comment]
更新一下解决办法，我没有修改源代码  我在区块对标签的前后各加了一个空行来解决计数错误的问题，像这样:
{{?goods}}
空行

空行
{{/goods}}

**Comment by Sayi** [comment]
已修复，下个版本发布。

**Comment by Danst-bjtu** [comment]
我也遇到类似问题，在有目录情况下，区块对一直提示找不到匹配尾标签，可是我都已经写上了
比如：
<?a>
content
<?b>
content
</b>
</a>
会提示我找不到<?b>的尾标签，我仿照上面的解决方法，在<a>标签的上下加空行的方式也可以解决，两者应该属于统一问题

**Comment by Danst-bjtu** [comment]
我也遇到类似问题，在有目录情况下，区块对一直提示找不到匹配尾标签，可是我都已经写上了
比如：
{{?a}}
content
{{?b}}
content
{{/b}}
{{/a}}
会提示我找不到{{?b}}的尾标签，我仿照上面的解决方法，在{{a}}标签的上下加空行的方式也可以解决，两者应该属于统一问题

**Comment by zlp8013** [comment]
您好,我想问一下,您是怎么生成目录的

**Comment by bajie-git** [comment]
> 您好,我想问一下,您是怎么生成目录的

非常复杂且麻烦，，自己写了个目录生成得方法（参考poi自带得目录生成），但生成后没有页码，然后把这个没有页码得word用libreoffice7.4转成pdf，此时页码会被更新出来（原因未知）。最后在读取pdf中得页码回更到word中。

这个方案太麻烦了而且坑也很多，我修改了很多版本才稳定下来，我建议你还是使用aspost 永久授权也不贵

**Comment by Danst-bjtu** [comment]
> 您好,我想问一下,您是怎么生成目录的

我用的Spire，不开源

**Comment by zlp8013** [comment]
> > 您好,我想问一下,您是怎么生成目录的
> 
> 我用的Spire，不开源

这个确实好用,但是收费

**Comment by bajie-git** [comment]
我当时调研了大量得开源方案，我认为开源方案里面几乎没有一个好的解决方案；建议还是使用付费版，不然你会发现你调研得时间换算成工资足够购买一个付费版了

**Comment by zlp8013** [comment]
> 

是的,大佬，我还有一个小问题，就是如果标签没有值的话（也就是赋的值为空），那么其前面的文本也不显示，这个怎么实现？
![image](https://github.com/Sayi/poi-tl/assets/101457266/d12a2bab-08ba-40e1-a8fa-924165c57021)
 比如说，如果{{b}}，或者{{c}}没有值的话，那么其前面的文本：Test1和Test2不显示
