### ISSUE TITLE
你好，我咨询一下为什么word渲染的时候表格和非表格换行符格式不一样

### ISSUE THREAD

**Issue by beimengyeyu** [Sayi/poi-tl#915]
如图，第一张图是非标格下面的形式，第二张是在表格下面的形式

![image](https://user-images.githubusercontent.com/107797432/207758612-9cd88f95-036f-40de-9d88-37161e6e3d3d.png)

![image](https://user-images.githubusercontent.com/107797432/207758694-3e8d2ab7-6da3-4c1b-96db-6439a721c43c.png)

**Comment by Sayi** [comment]
表格内同一个段落内不支持第一种换行形式。

如果要求表格表现为第一种换行，需要用多个段落即可。
