### ISSUE TITLE
表格在导出后，数据没有正确的展示出来

### ISSUE THREAD

**Issue by MulderLiu** [Sayi/poi-tl#918]
请问 ，导出的模板中有一个表格，但是导出后，数据没有正常的展示，变成了第二张图的样子。感觉是吧数据，标记全部都打印出来了，我们检查了一下导出的数据也没有什么特别的地方，都是普通字符串数据（第三张图）模板在下面附件中。可能是哪里问题？
![f4679c07d313cba7b1c62a448fc3e65](https://user-images.githubusercontent.com/11418478/209625881-1a70ecd0-987d-4ec1-93c1-3193399d89bc.png)

![746752d34296270172526ae2727d866](https://user-images.githubusercontent.com/11418478/209625935-d7c9c77f-5aa5-4224-9822-e24a47e44f74.png)

### Minimal Docx template file
[输出 - 副本.docx](https://github.com/Sayi/poi-tl/files/10306570/-.docx)

**Comment by Sayi** [comment]
标签要绑定策略。

**Comment by MulderLiu** [comment]
好的 我再试试
