### ISSUE TITLE
office word 开启“保存新文档的预览图片”选项，运行会报错

### ISSUE THREAD

**Issue by zackzergzeng** [Sayi/poi-tl#919]
在office word的偏好设置里勾选如图所示选项
<img width="400" alt="企业微信截图_9f17aff1-c400-40a0-9031-c34317a562ca" src="https://user-images.githubusercontent.com/42129897/209772956-5c511bd4-56a5-4b23-8b64-99af6241964a.png">

就会报如下错误
```
Zip bomb detected! The file would exceed the max. ratio of compressed file size to the size of the expanded data.
This may indicate that the file is used to inflate memory usage and thus could pose a security risk.
You can adjust this limit via ZipSecureFile.setMinInflateRatio() if you need to work with files which exceed this limit.
Uncompressed size: 106496, Raw/compressed size: 499, ratio: 0.004686
Limits: MIN_INFLATE_RATIO: 0.010000, Entry: docProps/thumbnail.emf
```
看起来是因为缩略图使用的格式是emf无法被读取，这个有什么解决方案吗？
poi-tl版本为1.10.4

**Comment by Sayi** [comment]
`ZipSecureFile.setMinInflateRatio(-1.0d);` 可以忽略这个检查，看看是否能解决问题？

**Comment by zackzergzeng** [comment]
> `ZipSecureFile.setMinInflateRatio(-1.0d);` 可以忽略这个检查，看看是否能解决问题？

这个ZipSecureFile是从哪里引入？我试下

**Comment by zackzergzeng** [comment]
> `ZipSecureFile.setMinInflateRatio(-1.0d);` 可以忽略这个检查，看看是否能解决问题？

可以，`import org.apache.poi.openxml4j.util.ZipSecureFile;`后使用这个方法就可以了
