### ISSUE TITLE
List

### ISSUE THREAD

**Issue by huwenjia** [Sayi/poi-tl#92]
ListDataRenderPolicy里面怎么加docxRenderData 类型的数据？

**Comment by huwenjia** [comment]
我是指类似的功能，因为我也是用测试包测试 ，里面可以放文本，可以放picture,那么能放word么，相当一个标签对应多个资源，资源有文本，有图片，也有word，我试了下文本和图片是可以，但如何加入word呢

**Comment by Sayi** [comment]
你可以改造ListDataRenderPolicy。

**Comment by huwenjia** [comment]
改造了一下，但word一加进来就什么都没替换
