### ISSUE TITLE
Tables.ofPercentWidth(String percent, int[] colWidthsPercent)方法生成表格时异常

### ISSUE THREAD

**Issue by zhuggy** [Sayi/poi-tl#922]
### Issue description
Tables.ofPercentWidth(String percent, int[] colWidthsPercent)方法生成表格时，各列挤在一堆了
### poi-tl version
1.12.0
### Minimal test code to reproduce the issue

```java
Tables.ofPercentWidth(StrUtil.isEmpty(bWidth) ? "9000" : bWidth,new int[]{8,35,25,20,12}).border(borderStyle).center()
                    .create();
```
### Minimal Docx template file
![1672730261677](https://user-images.githubusercontent.com/121851568/210314077-7f2566c6-4cf4-46ae-947e-6b0dc179da54.jpg)

**Comment by Sayi** [comment]
模版可以发一下吗？

**Comment by zhuggy** [comment]
应该不是模板的问题，我换成使用Tables.ofPercentWidth("9000" )时能正常生成word表格，就是每列宽度不是我想要的

**Comment by Sayi** [comment]
第一个参数格式是百分比：XX%，才会以百分比计算各列宽度。

如果第一个参数非百分比，比如9000，则以该值为固定宽度，均分各列。

**Comment by zhuggy** [comment]
好的，谢谢
