### ISSUE TITLE
数据模型-mode能否支持key为 x.y.z

### ISSUE THREAD

**Issue by dhuaqiao** [Sayi/poi-tl#924]
### Issue description
如果模型数据定义为map
map.put("x.y.z","XYZ");
在渲染的时候会被当成对象进行处理了
### poi-tl version
1.12.0
### Minimal test code to reproduce the issue
![image](https://user-images.githubusercontent.com/7965431/211445260-9079d8f8-c3de-463d-961e-4d0fcb5035d9.png)

```
### Minimal Docx template file

**Comment by Sayi** [comment]
不支持直接使用，如果希望这种格式，可以扩展：[如何计算标签值](http://deepoove.com/poi-tl/#_%E8%AE%A1%E7%AE%97%E6%A0%87%E7%AD%BE%E5%80%BC)

**Comment by dhuaqiao** [comment]
谢谢
