### ISSUE TITLE
区块对标签值为Boolean渲染后出现空行的问题

### ISSUE THREAD

**Issue by cuitzh** [Sayi/poi-tl#928]
### Issue description
docx模板中，区块对标签值为Boolean，并且开始标签和结束标签跨页时，渲染后出现了空行，而开始标签和结束标签在同一页时不会出现此问题。
### poi-tl version
1.12.1
### Minimal test code to reproduce the issue

```java
@Test
void testRender() {
    Map<String, Object> model = new LinkedHashMap<>();
    model.put("show1", false);

    ConfigureBuilder configureBuilder = Configure.builder();
    configureBuilder.useSpringEL(false);

    File template = new File("test.docx");
    try (XWPFTemplate render = XWPFTemplate.compile(template, configureBuilder.build())) {
        render.render(model);
        render.write(Files.newOutputStream(Paths.get("a.docx")));
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
}
```

### Minimal Docx template file

[test.docx](https://github.com/Sayi/poi-tl/files/10420474/test.docx)

<img width="456" alt="image" src="https://user-images.githubusercontent.com/25560862/212549445-9f8f5499-a260-4321-9b47-46af1a8de552.png">

**Comment by Sayi** [comment]
#920 是一个已知问题，下个版本会解决。
