### ISSUE TITLE
在使用文档嵌套时，子文档中存在如下格式时，嵌套失败

### ISSUE THREAD

**Issue by MRgenial** [Sayi/poi-tl#931]
![1675221506400](https://user-images.githubusercontent.com/49973336/215937533-43d4d3a4-bf2f-4fa3-b8c5-0fbb26acb016.jpg)
<img width="1606" alt="image" src="https://user-images.githubusercontent.com/49973336/215937619-747b0967-288e-41dc-8b08-b0a9f0a7b552.png">
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/49973336/215937660-42f71d74-ee0a-47c9-890d-53438a3663f1.png">

**Comment by Sayi** [comment]
先使用最新版本1.12.1或者1.10.5试试。
