### ISSUE TITLE
示例代码中，输出流的关闭是不是不太合适

### ISSUE THREAD

**Issue by mateJay** [Sayi/poi-tl#932]
### Issue description
看到示例代码中，流的关闭是不是应该放在finally里面

### Minimal test code to reproduce the issue

response.setContentType("application/octet-stream");
response.setHeader("Content-disposition","attachment;filename=\""+"out_template.docx"+"\"");

// HttpServletResponse response
OutputStream out = response.getOutputStream();
BufferedOutputStream bos = new BufferedOutputStream(out);
template.write(bos);
bos.flush();
out.flush();
PoitlIOUtils.closeQuietlyMulti(template, bos, out);  // 是不是需要放在finally里面，或者所有的流都放在try里面

**Comment by Sayi** [comment]
可以提供一个示例吗？这将会非常棒。

**Comment by mateJay** [comment]
http://deepoove.com/poi-tl/#_output%E8%BE%93%E5%87%BA 这是官网提供的示例代码，存在前面提到的流关闭问题。

个人看法放在try里面会不会更好一点
```
try  (XWPFTemplate template = getXXXTemplate();
         OutputStream out = response.getOutputStream();
         BufferedOutputStream bos = new BufferedOutputStream(out)) {


         template.write(bos);
         bos.flush();
         out.flush();
        }
```
