### ISSUE TITLE
模板导出 不规则表头  如何设置？数据根据行 循环写入导出 

### ISSUE THREAD

**Issue by Joey-zy1024** [Sayi/poi-tl#938]
![Uploading image.png…]()

想请问下各位大佬 表头是这种格式的 如果 写入表格数据  动态表格失效 
固定表头的话 第二行又有数据需要写入 
怎么解决？？？

**Comment by Sayi** [comment]
图片裂了。

**Comment by Joey-zy1024** [comment]
![81d76d7b8a9e413ff1ec5cc5bd4747f](https://user-images.githubusercontent.com/38678002/218746202-9916c05e-a322-4dca-b471-06eba1034821.png)

**Comment by Joey-zy1024** [comment]
首行是说明文字  第一行 有三个 属性  下面分别是属性下的类别 实际上 数据在第三行 输出 怎么搞 谢谢大佬解惑！！！

**Comment by Sayi** [comment]
行循环插件  应用到第三行 不行吗？

**Comment by zhujinghuic** [comment]
> 行循环插件 应用到第三行 不行吗？

你好，我想问下，动态表头这种是不是只能写代码方式处理，用springEl遍历集合的写法能行吗？
