### ISSUE TITLE
渲染顺序的问题

### ISSUE THREAD

**Issue by cstg-xun** [Sayi/poi-tl#939]
### Issue description
自定义Policy和第三方Policy如何确保渲染顺序的问题 我使用了第三方Pol-tl-ext中的htmlRenderPolicy和自定义的Policy 执行结果是htmlRenderPolicy的数据在文档的最上方 当我单独执行多个自定义Policy或者多个第三方Policy的时候就不会出现顺序乱的结果
### poi-tl version
1.12.1
### Minimal test code to reproduce the issue

```java

```

**Comment by Sayi** [comment]
#933 重复Issue
