### ISSUE TITLE
请不要把logback日志级别设置的那么高

### ISSUE THREAD

**Issue by funyule** [Sayi/poi-tl#94]
jar包中的logback-test.xml直接覆盖了原本业务系统里的日志配置文件

**Comment by funyule** [comment]
- Logback tries to find a file called **logback-test.xml** in the classpath.
- 
- If no such file is found, logback tries to find a file called logback.groovy in the classpath.
- 
- If no such file is found, it checks for the file logback.xml in the classpath..
- 
- If no such file is found, service-provider loading facility (introduced in JDK 1.6) is used to resolve the implementation of com.qos.logback.classic.spi.Configurator interface by looking up the file META-INF\services\ch.qos.logback.classic.spi.Configurator in the class path. Its contents should specify the fully qualified class name of the desired Configurator implementation.
- 
- If none of the above succeeds, logback configures itself automatically using the BasicConfigurator which will cause logging output to be directed to the console.

**Comment by Sayi** [comment]
#90
