### ISSUE TITLE
使用插件时，无法设置单个cell的样式

### ISSUE THREAD

**Issue by zhouliuhuo** [Sayi/poi-tl#943]
比如使用 LoopRowTableRenderPolicy 处理表格，没有办法使用 RowRenderData 来对每一个cell单独设置样式

**Comment by fwk1010** [comment]
可以的。XWPFTableRow和XWPFTableCell都可以设置样式，比如cell.getCTTc().addNewTcPr().addNewShd().setFill("000000");

**Comment by Sayi** [comment]
LoopRowTableRenderPolicy和RowRenderData是两件事，没有关系。
