### ISSUE TITLE
区块内无法访问区块外的变量

### ISSUE THREAD

**Issue by yelv123** [Sayi/poi-tl#949]
### Minimal test code to reproduce the issue

其中  {{metaInfo.showYear.1}}-{{metaInfo.showYear.8}}  不是 competitiveAssayList 内的参数
### Minimal Docx template file
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/20295470/224248540-e8f93155-1d25-4c9b-b13b-d2226ae75f15.png">

**Comment by Sayi** [comment]
#807 #589
