### ISSUE TITLE
请教下，集合中带有集合图片的写法有吗？

### ISSUE THREAD

**Issue by yulonglyw** [Sayi/poi-tl#953]
![image](https://user-images.githubusercontent.com/39002453/224974435-5768c383-8887-4c6c-a051-5215533d723e.png)

或者给下思路，谢谢了。

**Comment by yygscode** [comment]
渲染两次，第一次把图片标签渲染进去，第二次就把图片渲染进去

**Comment by Sayi** [comment]
用区块对。
