### ISSUE TITLE
模板标签保留问题

### ISSUE THREAD

**Issue by huangxuyongwin** [Sayi/poi-tl#955]
在render渲染之后，没有数据渲染的标签怎么能继续保留在生成的文档里面，而不是不见了

**Comment by ouyang2312** [comment]
这个简单  比如 {{name}} 你定义一个对象name属性 设置值为 "{{name}}" 这样子这次渲染就会是这个标签了，然后你下次渲染name的时候 就改成 name = "xx" 就正常渲染了

**Comment by huangxuyongwin** [comment]
Thanks for your mail!Soon I will reply.

**Comment by huangxuyongwin** [comment]
Thanks for your mail!Soon I will reply.

**Comment by twricu** [comment]
> 可以实现Configure.ValidErrorHandler接口，实现类ClearHandler就是删除占位符`bodyContainer.clearPlaceholder(run);`

这个老哥说的对，在文档的[8.7.2. 标签数据类型不合法](http://deepoove.com/poi-tl/#_%E6%A0%87%E7%AD%BE%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B%E4%B8%8D%E5%90%88%E6%B3%95)里面写了

**Comment by huangxuyongwin** [comment]
Thanks for your mail!Soon I will reply.
