### ISSUE TITLE
[请教]一段重复文字中，部分加粗怎么做

### ISSUE THREAD

**Issue by zhouliuhuo** [Sayi/poi-tl#956]
类似于这样的句子，这个加粗怎么实现比较好呢？
![image](https://user-images.githubusercontent.com/30459157/225528665-22713df7-3acd-4956-9aa1-b4fb663cfede.png)

**Comment by Sayi** [comment]
可能你需要多个标签；或者使用区块对，区块对的集合数据是拥有不同样式的TextRenderData，还可以考虑使用ParagraphRenderPolicy插件。
