### ISSUE TITLE
区块对中支持嵌套么

### ISSUE THREAD

**Issue by prettyhe** [Sayi/poi-tl#957]
比如循环一堆表格出来，但这些表格的样式不完全一样，可以抽象为A、B两个模板，是否可以使用区块对循环遍历出来，遍历对象使用嵌套再次渲染。类似这样
```
{{?auditList}}
{{+=#this}}
{{/auditList}}
```
auditList=Arrays.asList(Includes.ofLocal("A.docx").setRenderModel(dataA).create(),Includes.ofLocal("B.docx").setRenderModel(dataB).create())
测下来会报错
![image](https://user-images.githubusercontent.com/5018836/226287730-930d9728-38c4-4aeb-bcb8-24f5ed552b66.png)

**Comment by wangjiahao123456** [comment]
大哥，请问你最后怎么弄得？

**Comment by Sayi** [comment]
#403

**Comment by prettyhe** [comment]
使用了笨办法，没有使用嵌套。
在模板里把两个样式都写出来，通过控制区块对的条件来决定哪一个样式显示哪一个样式隐藏，例如：
{{?list}}
// 条件判断1，满足时使用样式1
{{?contition1}}
{{dataA}}
{{dataB}}
....
{{/contition1}}

// 条件判断2，满足时使用样式2
{{?contition2}}
{{dataB}}
{{dataA}}
....
{{/contition2}}

{{/list}}

list是个数组，数组里每个对象的参数决定是满足contition1还是contition2，从而达到使用对应的样式的效果
