### ISSUE TITLE
能支持word模板导出段落两端对齐吗

### ISSUE THREAD

**Issue by 807592732** [Sayi/poi-tl#958]
### Minimal test code to reproduce the issue

```java

```

**Comment by white-cwy-dove** [comment]
兄弟 有实现的方法吗

**Comment by VVFtang** [comment]
使用自定义段落样式即可，如：
```
// 两端对齐
ParagraphStyle style = ParagraphStyle.builder().withAlign(ParagraphAlignment.BOTH);

**Comment by zlp8013** [comment]
> 使用自定义段落样式即可，如：
> 
> ```
> // 两端对齐
> ParagraphStyle style = ParagraphStyle.builder().withAlign(ParagraphAlignment.BOTH).build();;
> ```

有没有什么办法设置文本的复杂样式

**Comment by Sayi** [comment]
> > 使用自定义段落样式即可，如：
> > ```
> > // 两端对齐
> > ParagraphStyle style = ParagraphStyle.builder().withAlign(ParagraphAlignment.BOTH).build();;
> > ```
> 
> 有没有什么办法设置文本的复杂样式

复写文本插件。
