### ISSUE TITLE
能否不要把logback-test.xml打包进去

### ISSUE THREAD

**Issue by herowzz** [Sayi/poi-tl#96]
spring boot项目logback优先级优先加载了poi-tl中的logback-test文件，导致本身项目中的logback文件没法加载了
第三方应用没必要将日志配置也打包进去，建议删去

**Comment by herowzz** [comment]
[见Logback官方文档](https://logback.qos.ch/manual/configuration.html)

> Let us begin by discussing the initialization steps that logback follows to try to configure itself:
> 
> Logback tries to find a file called logback-test.xml in the classpath.
> 
> If no such file is found, logback tries to find a file called logback.groovy in the classpath.
> 
> If no such file is found, it checks for the file logback.xml in the classpath..
> 
> If no such file is found, service-provider loading facility (introduced in JDK 1.6) is used to resolve the implementation of com.qos.logback.classic.spi.Configurator interface by looking up the file META-INF\services\ch.qos.logback.classic.spi.Configurator in the class path. Its contents should specify the fully qualified class name of the desired Configurator implementation.
> 
> If none of the above succeeds, logback configures itself automatically using the BasicConfigurator which will cause logging output to be directed to the console.

logback-test.xml 的加载顺序，优先级是最高的

**Comment by Sayi** [comment]
poi-tl 1.3.1版本已修复，你升级下试试。

**Comment by herowzz** [comment]
升级后，该问题已解决，3ks
