### ISSUE TITLE
请教一下 表格样式设置了无边框还有一层虚框 是否可以通过代码清除这个虚框

### ISSUE THREAD

**Issue by white-cwy-dove** [Sayi/poi-tl#961]
### Minimal test code to reproduce the issue

```java

```

**Comment by white-cwy-dove** [comment]
![1680144068473](https://user-images.githubusercontent.com/49520296/228714342-61e1d22e-a5a7-4d35-9870-db4f86b5a3b6.png)

**Comment by white-cwy-dove** [comment]
![1680144517902](https://user-images.githubusercontent.com/49520296/228715460-32bb4b03-f7c7-46a3-bd25-9fdd421fada6.png)
这层虚框是否可以用代码去处理

**Comment by Sayi** [comment]
这是word显示的样子（可能和主题有关），底层已经去除了边框。
