### ISSUE TITLE
怎么调图片的自动换行样式

### ISSUE THREAD

**Issue by Wu-Z-J** [Sayi/poi-tl#964]
![WX20230404-113245](https://user-images.githubusercontent.com/75168110/229681404-7cf7b798-2560-44f8-8109-626218044ab4.png)

**Comment by zlp8013** [comment]
> ![WX20230404-113245](https://user-images.githubusercontent.com/75168110/229681404-7cf7b798-2560-44f8-8109-626218044ab4.png)

解决了吗

**Comment by Sayi** [comment]
目前只能使用引用图片标签。
