### ISSUE TITLE
请教下，有没有支持Excel 模板的开源工具呢？

### ISSUE THREAD

**Issue by ppgogo** [Sayi/poi-tl#967]
Poi-tl 解决了我很大问题哈，先前这种word模板生成，都是自己来手写替换，只能支持简单的文本/表格场景。
在实际业务中，还有一种需求，就是利用Excel 模板来生成复杂的报表，
比如有多个sheet页面，一个sheet页面内有多组表格（横向表格，纵向表格），
不知道大家有没有看到比较好用的，类似这个poi-tl的工具包？

感谢大家:)

**Comment by lxl97312** [comment]
有的 阿里巴巴的easyexcle

**Comment by entropy-cloud** [comment]
可以使用Nop平台中的NopReport引擎，它支持使用Excel作为报表模板设计器生成中国式报表。https://github.com/entropy-cloud/nop-entropy/blob/master/docs/user-guide/report.md。视频演示说明 https://www.bilibili.com/video/BV1Sa4y1K7tD/。另外Word模板也可以使用Nop平台中的NopWordTemplate，它不需要在Java代码中做复杂的结构准备，可以将所有报表相关逻辑都写在报表模板内部。 https://github.com/entropy-cloud/nop-entropy/blob/master/docs/dev-guide/report/word-template.md
