### ISSUE TITLE
word 转pdf

### ISSUE THREAD

**Issue by Raycheng2016** [Sayi/poi-tl#970]
### Minimal test code to reproduce the issue

```java

```

**Comment by Raycheng2016** [comment]
poi  word转pdf格式错乱。poi-tl有没有相关功能

**Comment by cuitz** [comment]
> poi word转pdf格式错乱。poi-tl有没有相关功能

word转pdf免费开源的没有好的方案，用libreoffice转吧，效果不错

**Comment by roc97** [comment]
> poi word转pdf格式错乱。poi-tl有没有相关功能
可以用这个试试
`<dependency>
            <groupId>cn.wisewe</groupId>
            <artifactId>docx4j-wisewe-convert</artifactId>
            <version>1.7.0.RELEASE</version>
        </dependency>`

**Comment by 759427794** [comment]
收费的Aspose.Words不错

**Comment by cuitz** [comment]
> 收费的Aspose.Words不错
这个收费的费用不低，一般小公司用不起，用PJ版还有法律风险，目前最成熟的开源方案应该还是基于libreoffice的。

**Comment by cuitz** [comment]
> 收费的Aspose.Words不错
这个收费的费用不低，一般小公司用不起，用PJ版还有法律风险，目前最成熟的开源方案应该还是基于libreoffice的。

**Comment by Sayi** [comment]
#287
