### ISSUE TITLE
同一行打多个表格行循环标签，填充时多个标签之间的数据相互影响

### ISSUE THREAD

**Issue by lzhquiet** [Sayi/poi-tl#971]
请教一个问题：目前表格行循环标签我看是只支持同一行打一个标签，如果更复杂点，想要同一行打多个表格行循环的标签，有没有什么现有的插件或者实现思路呢？目前通过插件LoopRowTableRenderPolicy同一行打多个标签的时候，填充时多个标签之间的数据会相互影响，出现重复、互相覆盖的问题

**Comment by wangjiahao123456** [comment]
老哥你最后怎么就解决的？

**Comment by Sayi** [comment]
只支持同一行打一个标签
