### ISSUE TITLE
文件输出到网络流时报错

### ISSUE THREAD

**Issue by wzj760130613** [Sayi/poi-tl#978]
### Issue description
按照官网给定的写法，导到网络流时报错，但是输出到本地时可以，请问是否遇到过类似的问题？
![image](https://user-images.githubusercontent.com/11485223/234236525-c964ca6d-8044-4d96-b16c-3ad99b550e66.png)

报错信息如下：
org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /docProps/core.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.ZipPackagePropertiesMarshaller@69ec4d08. Enable logging via Log4j 2 for more details.
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:598)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1490)
	at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:227)
	at com.deepoove.poi.XWPFTemplate.write(XWPFTemplate.java:235)

### poi-tl version
      1.12.1
### Minimal test code to reproduce the issue

```java
XWPFTemplate template = XWPFTemplate.compile("E:\\template\\template.docx",configBuilder.build()).render(paramMap);

            // 导出到本地文件可以正常
            // template.writeAndClose(new FileOutputStream("E:\\template\\output.docx"));

            response.setContentType("application/octet-stream");
            response.setHeader("Content-disposition","attachment;filename=\""+"out_template.docx"+"\"");

            // HttpServletResponse response
            OutputStream out = response.getOutputStream();
            BufferedOutputStream bos = new BufferedOutputStream(out);
            template.write(bos);
            bos.flush();
            out.flush();
            PoitlIOUtils.closeQuietlyMulti(template, bos, out);
```

**Comment by somanei** [comment]
哥们怎么样了? 我也遇到了这个问题,我的版本是1.10.5

**Comment by wzj760130613** [comment]
我后来改成生成一份文件在服务器端，不直接输出到网络流客，下载的时候读取本地这份。



---原始邮件---
发件人: "Katherina ***@***.***&gt;
发送时间: 2023年6月3日(周六) 下午3:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Sayi/poi-tl] 文件输出到网络流时报错 (Issue #978)




 
哥们怎么样了? 我也遇到了这个问题,我的版本是1.10.5

**Comment by somanei** [comment]
![image](https://github.com/Sayi/poi-tl/assets/54315950/f9660465-7e4b-4923-9cae-3e0be8420e24)
那个问题我找到了poi里面讲需要在外面包一层BufferedOutputStream
