### ISSUE TITLE
【求助】怎么在自定义表格使用PictureRenderData的时候设置图片的具体在第几个字符的位置呢

### ISSUE THREAD

**Issue by TheThao223739** [Sayi/poi-tl#981]
![image](https://user-images.githubusercontent.com/82553862/234823807-75fbe4c6-5add-4445-b948-5c2a9c8c954c.png)

**Comment by TheThao223739** [comment]
大佬，如何在自定义表格时，处理富文本中的图片和文字呢

**Comment by Sayi** [comment]
ParagraphRenderData根据添加顺序展示富文本。
