### ISSUE TITLE
如何设置纸张大小

### ISSUE THREAD

**Issue by peibokai** [Sayi/poi-tl#983]
### Minimal test code to reproduce the issue
我用poi设置了A4纸张大小，但是通过字符串填充后，又变成了默认的

![image](https://user-images.githubusercontent.com/58499785/235049097-658503ca-9df7-479c-aaec-c91f0a1c45e7.png)
![image](https://user-images.githubusercontent.com/58499785/235049117-e8daee4b-8ca6-46a3-9a5b-2eee1a553691.png)

**Comment by Sayi** [comment]
设置的方法好像没有问题，需要可复现的单元测试。
