### ISSUE TITLE
Why is the version of poi-tl-plugin-markup in the poi-tl v1.12.1 tag 1.0.4-SNAPSHOT?

### ISSUE THREAD

**Issue by jinsenianhua-ai** [Sayi/poi-tl#984]
Hello,
Why is the version of poi-tl-plugin-markup in the poi-tl v1.12.1 tag 1.0.4-SNAPSHOT? Can you push an official version of poi tl plugin markup?I am currently unable to download this version from the Maven central repository.
![20230515-143314(WeLinkPC)](https://github.com/Sayi/poi-tl/assets/43307372/eb9c5ab5-ff23-47cd-8acc-567190194991)

**Comment by jinsenianhua-ai** [comment]
So I need to use POI-TL v1.12.1 and plugin 1.0.3?

**Comment by Sayi** [comment]
That's it.

**Comment by jinsenianhua-ai** [comment]
@Sayi  If I use poi-tl v1.12.1 and poi-tl-plugin-markup v1.0.3, we need to introduce poi-tl v1.12.1 and poi-tl v1.11.1. As a result, the open source software used is not unified. Can we release the official version of the later version? Otherwise, we may not be able to use the open source software.
