### ISSUE TITLE
表格一个单元格插入多张图片

### ISSUE THREAD

**Issue by 13232411221** [Sayi/poi-tl#986]
表格一个单元格插入多张图片的时候, 怎么设置可以让图片不换行? 
现有效果: 
![image](https://github.com/Sayi/poi-tl/assets/29544751/088de94b-e0cb-4571-a37a-ca14b5329ef9)
期望效果:
![image](https://github.com/Sayi/poi-tl/assets/29544751/6a46afca-7981-4f05-b403-ba3556087c05)

**Comment by fwk1010** [comment]
可以设置样式

**Comment by Sayi** [comment]
同一个段落中插入。
