### ISSUE TITLE
继承DynamicTableRenderPolicy生成动态表格无法取消缩进

### ISSUE THREAD

**Issue by cxhello** [Sayi/poi-tl#990]
### Issue description

继承DynamicTableRenderPolicy生成动态表格无法取消缩进，以及如何复用表头样式

### poi-tl version

1.12.1

### Minimal test code to reproduce the issue

```java
    public static void renderRow(XWPFTable table, List<RowRenderData> dataList) throws Exception {
        int size = dataList.get(0).getCells().size();
        for (int i = dataList.size() - 1; i>= 0; i--) {
            XWPFTableRow insertNewTableRow = table.insertNewTableRow(startRow);
            for (int j = 0; j < size; j++) {
                insertNewTableRow.createCell();
            }
            // 单行渲染
            XWPFTableRow row = table.getRow(startRow);
            TableRenderPolicy.Helper.renderRow(row, dataList.get(i), STYLE);
            List<XWPFTableCell> tableCells = row.getTableCells();
            for (XWPFTableCell cell : tableCells) {
                // 获取单元格的段落对象
                XWPFParagraph paragraph = cell.getParagraphArray(0);
                // 让文本内容自适应单元格高度
                paragraph.setSpacingLineRule(LineSpacingRule.AUTO);
                paragraph.setSpacingBetween(15, LineSpacingRule.EXACT);
                // 取消首行缩进
                paragraph.setIndentationFirstLine(0);
            }
        }
    }
```
### Minimal Docx template file

![image](https://github.com/Sayi/poi-tl/assets/49056040/2b12c073-d320-417c-8caf-b692ac70cf3d)

**Comment by RedStone365** [comment]
这个好像不是缩进，前面默认加了个tab，难受。

**Comment by RedStone365** [comment]
`paragraphStyle.setIndentLeftChars(-1D);`
解决了，你那个也设置-1试试，不行就-4。

**Comment by cxhello** [comment]
> `paragraphStyle.setIndentFirstLineChars(-0.01D);`

如何获取paragraphStyle

**Comment by doublevgp** [comment]
所以 如何获取paragraphStyle，我使用的是poi-tl 1.6.0，也出现了动态渲染表格，首行缩进改不掉

**Comment by RowanJie** [comment]
我是这样解决的：
  List<XWPFParagraph> paragraphs = cell.getParagraphs();
                paragraphs.forEach(x-> x.setIndentationFirstLine(0));

**Comment by RowanJie** [comment]
这样就能解决了
List<XWPFParagraph> paragraphs = cell.getParagraphs();
                paragraphs.forEach(x-> x.setIndentationFirstLine(0));

**Comment by cxhello** [comment]
> 这样就能解决了 List paragraphs = cell.getParagraphs(); paragraphs.forEach(x-> x.setIndentationFirstLine(0));

好的，感谢，回头我试下。

**Comment by ncman** [comment]
我按上楼的方法试了，paragraphStyle.setIndentFirstLineChars(-0.01D); ，但是还是不能取消首行缩进，这个怎么解决啊。
