### ISSUE TITLE
使用 Markdown 导出 Word 的时候，无序列表的符号 “●” 变成特殊的符号。

### ISSUE THREAD

**Issue by jiamliang** [Sayi/poi-tl#994]
### Issue description
使用 markdown 插件将 Markdown 文本导出到 Word 的时候，Markdown 中的无序列表，导到 Word 中，显示的无序列表符号不是期待的 “●”  而是其他的特殊符号。
### poi-tl version
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.2.3</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.2.3</version>
		</dependency>
		<dependency>
			<groupId>com.deepoove</groupId>
			<artifactId>poi-tl</artifactId>
			<version>1.12.1</version>
		</dependency>
		<dependency>
			<groupId>com.deepoove</groupId>
			<artifactId>poi-tl-plugin-markdown</artifactId>
			<version>1.0.3</version>
		</dependency>

### Minimal test code to reproduce the issue

```java
        MarkdownRenderData code = new MarkdownRenderData();
        byte[] bytes = Files.readAllBytes(Paths.get("C:\\Users\\username\\Desktop\\README.md"));
        String mkdn = new String(bytes);
        code.setMarkdown(mkdn);

        MarkdownStyle style = MarkdownStyle.newStyle();
        style.setShowHeaderNumber(true);
        code.setStyle(style);

        Map<String, Object> data1 = new HashMap<>();
        data1.put("md", code);

        Configure config1 = Configure.builder().bind("md", new MarkdownRenderPolicy()).build();
        XWPFTemplate.compile("C:\\Users\\username\\Desktop\\markdown_template.docx", config1)
                .render(data1)
                .writeToFile("C:\\Users\\username\\Desktop\\markdown.docx");
```
### Minimal Docx template file
markdown 文件和 word 模版均为 github 中的文件。

输出的截图如下：
![image](https://github.com/Sayi/poi-tl/assets/1405049/1e93af67-f02f-4908-beab-cdf7edcc074c)

请问如何将无序列表的符号调整为默认的圆点“●”
谢谢！

**Comment by jiamliang** [comment]
我觉得应该是这里： https://github.com/Sayi/poi-tl/blob/e7ed117d0219d9912e3ff588fdfe8dea7b17f373/poi-tl/src/main/java/com/deepoove/poi/data/NumberingFormat.java#L30
   public static final NumberingFormat BULLET = new NumberingFormat(NumFormat.BULLET, "●");
输出 "●" 的时候，Word 里面对无序列表的符号字体设置为 wingdings 字体导致的。

**Comment by devswork** [comment]
我也遇到这个问题了

**Comment by jiamliang** [comment]
https://github.com/Sayi/poi-tl/blob/e7ed117d0219d9912e3ff588fdfe8dea7b17f373/poi-tl/src/main/java/com/deepoove/poi/data/NumberingFormat.java#L30

在 Word 里面无序列表的符号默认是 wingdings 字体，按照这个字体去显示这个圆点 “●” 就是图上的那个符号。
修改方法：
1. 修改 Word 的无序列表符号的字体，设置成非 wingdings 系列字体就可以了；
2. 修改这个代码，将这个圆点 “●”  替换为小写字母 “l”。小写字母 l 在 wingdings 字体里面就是这个圆点 “●”。
3. Markdown 插件支持对 NumberingFormat 指定样式“Style”， 用户可以根据需要自己去设置 Word 输出的列表的样式（Style）

**Comment by devswork** [comment]
> https://github.com/Sayi/poi-tl/blob/e7ed117d0219d9912e3ff588fdfe8dea7b17f373/poi-tl/src/main/java/com/deepoove/poi/data/NumberingFormat.java#L30
> 
> 在 Word 里面无序列表的符号默认是 wingdings 字体，按照这个字体去显示这个圆点 “●” 就是图上的那个符号。 修改方法：
> 
> 1. 修改 Word 的无序列表符号的字体，设置成非 wingdings 系列字体就可以了；
> 2. 修改这个代码，将这个圆点 “●”  替换为小写字母 “l”。小写字母 l 在 wingdings 字体里面就是这个圆点 “●”。
> 3. Markdown 插件支持对 NumberingFormat 指定样式“Style”， 用户可以根据需要自己去设置 Word 输出的列表的样式（Style）

感谢，不过我是 java bean 依据 docx 生成，目前改为用 区块对 来解决了，可以自定义列表前面的符号（任意字符），更加方便，而且只需要用 List<String> 就可以了。
