### ISSUE TITLE
class XWPFTemplateTest chart

### ISSUE THREAD

**Issue by g2plus** [Sayi/poi-tl#995]
I run your code，and in this, I found you wrote  the following code
datas.put("chart1",
			Charts.ofMultiSeries("易用性", new String[] { "代码量", "维护量" })
				.addSeries("poi-tl", new Double[] { 10.0, 5.0 })
				.addSeries("freemark", new Double[] { 90.0, 70.0 })
				.create());

and in the template file src/test/resources/template/template.docx, I did find any tag related to it, please have a check on this.

**Comment by Sayi** [comment]
reference_chart.docx
