### ISSUE TITLE
升级后缺失方法

### ISSUE THREAD

**Issue by Tiz-liu** [Sayi/poi-tl#999]
您好，当我从org.apache.poi:ooxml-schemas:1.4升级到org.apache.poi:poi-ooxml-full:5.2.3，发现isSetRFonts() ，getRFonts()，getSzCs()等方法不见了，请问有什么好的解决方法嘛？
![image](https://github.com/Sayi/poi-tl/assets/72006474/b3c4268c-b03d-4425-88db-796fe0e380b7)

**Comment by Sayi** [comment]
新版本丢弃了这些方法，替换方法为：sizeOfRFontsArray
